### ISSUE TITLE
Use jszip instead of adm-zip to zip error reports

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1000]
https://github.com/cthackers/adm-zip/issues/289 is seem to be unmaintained and it has many issues with macOS Catalina that were fixed but never got published on npm.

We should replace it with https://github.com/Stuk/jszip which seem to be maintained

**Comment by pantharshit00** [comment]
Maybe I can take this setup the development environment again. I already have it partially setup.

**Comment by timsuchanek** [comment]
https://github.com/Stuk/jszip is unmaintained as well. We need to find a proper Zip library first.

**Comment by pantharshit00** [comment]
We can use https://github.com/archiverjs/node-archiver. I tested it on MacOS Catalina(10.15.2) and it is working fine.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/22195362/71469578-a2c97480-27ef-11ea-84e3-334ad7c1ce60.png">
