### ISSUE TITLE
starterkit -> javascript -> graphql + auth -> postgres -> prisma2 dev

### ISSUE THREAD

**Issue by tmfprlt1234** [prisma/prisma2#1001]
<Anything that helps us reproduce the error goes here>

**Error dump**
Cannot destructure property `dmmf` of 'undefined' or 'null'.

**Stacktrace**
TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at connect (/usr/local/lib/node_modules/prisma2/build/photon-worker.js:44:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by janpio** [comment]
Where exactly do you get this error message - in your console or Prisma Studio?

**Comment by pantharshit00** [comment]
I think this might be a duplicate of https://github.com/prisma/prisma2/issues/999

**Comment by tmfprlt1234** [comment]
> Where exactly do you get this error message - in your console or Prisma Studio?

i got this message in terminal and localhost:5555

**Comment by pantharshit00** [comment]
Yup, this is indeed a duplicate of #999. Thanks for reporting this though.

Going to close this now
