### ISSUE TITLE
Updates to schema.prisma in dev mode require for the studio to work

### ISSUE THREAD

**Issue by 2color** [prisma/prisma2#1006]
## Problem

While initialising a new project with the JavaScript GraphQL starter script I encountered a problem with migrations.
When a new field is added, the CLI automatically runs the migration and re-generates the client library, however, the studio throws an error when the browser is reloaded. 

In the following example, I added a `facebook` field and reloaded the browser. 

![Screen Shot 2019-11-27 at 12 45 57 pm](https://user-images.githubusercontent.com/1992255/69720999-2bcb8e00-1114-11ea-9b36-6ba1c3dbd1a7.png)

## Suggested Solution 
The problem is solved by stoping `prisma dev` and running it again. Perhaps it makes sense to automatically reload the studio?

**Comment by timsuchanek** [comment]
Thanks for reporting @2color and you report this in the perfect timing. We'll release a patch for this within the next 30 min :)
I'll notify you here in the issue and close it once we've released it.

**Comment by timsuchanek** [comment]
The patch is out! https://github.com/prisma/prisma2/releases/tag/2.0.0-preview017.1

**Comment by 2color** [comment]
@timsuchanek Can you link to the commit with the fix? I'm curious to see how it was resolved
