### ISSUE TITLE
Blocked postinstall script on install causes problems

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma2#1012]
When activating the npm config: `ignore-scripts` like so: `npm config set ignore-scripts true` it causes problems when installing prisma2, since it cannot load the appropriate engine(I believe)

**Comment by pantharshit00** [comment]
Yes, it will not execute the post-install hook that downloads the binaries. 

So, in that case, I think we can have a cli command `prisma2 download-binaries` that would download and we can refer to this in another cli command if they detect that they can't find the binaries.

**Comment by janpio** [comment]
An interesting question is where we actually do this detection... because my obvious idea was the postinstall script - which is of course not executed in the first place. Maybe we can detect that it did not run on installation (or that the engines are missing), and then refer to that command to solve it.

**Comment by pantharshit00** [comment]
> Maybe we can detect that it did not run on installation (or that the engines are missing), and then refer to that command to solve it.

Yup, that is what I was referring in my comment.

**Comment by divyenduz** [comment]
@BjoernRave I am very curious to know your use case of disabling npm scripts? Can you please share more on that? :)

**Comment by BjoernRave** [comment]
@divyenduz I saw a talk of a guy talking about the security problems with the way we develop apps nowadays and that with the postinstall script, library authors are able to execute basically anything they want on your machine.

**Comment by schickling** [comment]
> So, in that case, I think we can have a cli command prisma2 download-binaries that would download and we can refer to this in another cli command if they detect that they can't find the binaries.

Aren't all needed binaries downloaded anyway when running `prisma2 generate`?

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest version of `prisma2`.
You can try it out with `npm i -g prisma2`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
