### ISSUE TITLE
`--port` is not working on the prisma2 studio

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1014]
`prisma2 studio` command says that we can pass `--port` option to change the port it is running on but the flag currently doesn't affect the port number.

![image](https://user-images.githubusercontent.com/22195362/69820141-7c331080-1226-11ea-815b-34f6d999ba15.png)

**Comment by Errorname** [comment]
I just made a PR that should fix this issue: https://github.com/prisma/lift/pull/255
