### ISSUE TITLE
ManyToMany pivot table

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#1017]
Hello, just a follow up on that https://github.com/prisma/prisma2/issues/201

When have you planned to tackle this thing?

Thanks

**Comment by pantharshit00** [comment]
Sorry this got lost. We will tackle this now.

**Comment by yovanoc** [comment]
Ahah no worries, it's just to know but thanks

**Comment by pantharshit00** [comment]
Adding context to this issue as it is not very descriptive:

We need to remove some upcoming feature code from lift.prisma.io Many to Many section as it is a bit misleading to new users(even though we have added coming soon but it is not very visible).

**Comment by janpio** [comment]
Internal Note: Use square brackets.

**Comment by nikolasburk** [comment]
@yovanoc can you please clarify what this issue is about exactly? Is it about adjusting a code snippet 
 on the Lift website or is it about the actual implementation of many-to-many pivot tables in Prisma 2? 🙂

**Comment by yovanoc** [comment]
I think is the implementation.

![image](https://user-images.githubusercontent.com/7302317/70988861-dce59880-20c2-11ea-9299-82ee2cb2e517.png)

Because when we try that, the generate and/or lifts commands doesn't want to

**Comment by janpio** [comment]
#201 was about a missing square bracket, which seems to have been fixed both in your schema and on the website.

If you are still getting errors @yovanoc, please provide some information what is actually happening so we can investigate. Please also post your schema as text, so we can easier recreate what is happening to you instead of having to type the text from your image.

**Comment by yovanoc** [comment]
You just have to put these 3 models that come from your lift frontpage... I think is not implemented at all.

`prisma2 generate`:

```sh
Error: Schema parsing
thread 'main' panicked at 'Unable to resolve scalar field 'user'', src/libcore/option.rs:1190:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: prisma_models::index::IndexTemplate::build::{{closure}}
  11: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  12: prisma_models::index::IndexTemplate::build
  13: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  14: prisma_models::model::ModelTemplate::build
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  16: prisma_models::internal_data_model::InternalDataModelTemplate::build
  17: prisma::cli::CliCommand::execute
  18: <std::future::GenFuture<T> as core::future::future::Future>::poll
  19: tokio::runtime::global::with_thread_pool
  20: tokio::runtime::global::with_state
  21: tokio::runtime::spawner::Spawner::enter
  22: tokio::runtime::time::variant::with_default
  23: std::thread::local::LocalKey<T>::with
  24: prisma::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error Command failed with exit code 1.
```

**Comment by pantharshit00** [comment]
Closing in favour of #1177
