### ISSUE TITLE
Can't I link many field in one Model to the other one ?

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#1024]
for Example 
```
model EventGroup {
  eventGroupId       String   @default(cuid()) @id
  eventGroupName     String
  eventGroupAdminCreator Admin    @relation(references: [adminId])
  lastUpdateAdmin    Admin    @relation(references: [adminId])
}

```
EventGroupAdminCreator and lastUpdateAdmin link to the same 
when I do this , in the process of  prisma2 lift save , it always show error 

![image](https://user-images.githubusercontent.com/16795429/69873116-085a3c00-12ea-11ea-849a-d4dfbe2fa8fb.png)

**Comment by pantharshit00** [comment]
Right now you will need to create backrelations like so:
```
model EventGroup {
  eventGroupId           String @default(cuid()) @id
  eventGroupName         String
  eventGroupAdminCreator Admin  @relation(references: [adminId], name: "AdminCreatorEventGroup")
  lastUpdateAdmin        Admin  @relation(references: [adminId], name: "LastUpdateGroupAdmin")
}

model Admin {
  adminId           String       @default(cuid()) @id
  name              String
  lastUpdatedEvents EventGroup[] @relation(references: [adminId], name: "AdminCreatorEventGroup")
  eventGroups       EventGroup[] @relation(references: [adminId], name: "LastUpdateGroupAdmin")
}
```

Also, can you please tell me which version of Prisma 2 you are using. I wasn't able to reproduce the error. Instead, I got a warning when I tried to deploy the model without backrelations:
![image](https://user-images.githubusercontent.com/22195362/69966711-f58b7580-153c-11ea-8320-ff3d75b4aeb2.png)


We are also trying to improve the backrelation syntax, you can check the proposal for that here: https://github.com/prisma/specs/issues/339

**Comment by justicejoe** [comment]
@pantharshit00  Ok thanks for your reply, btw my prisma2 version installed in project is 2.0.0-preview013.3 and global version is 2.0.0-preview015

**Comment by pantharshit00** [comment]
> Ok thanks for your reply, btw my prisma2 version installed in project is 2.0.0-preview013.3 and global version is 2.0.0-preview015

Thanks for the info. That explains why you got an outdated error message.

**Comment by justicejoe** [comment]
but now I upgrade it to the lastest one already alongside with nexus prisma

**Comment by pantharshit00** [comment]
Are you still getting the issue in the latest one? If not, feel free to close this issue

**Comment by justicejoe** [comment]
still got this error 
![image](https://user-images.githubusercontent.com/16795429/70129882-1b865680-16b2-11ea-8186-dd04bba4d079.png)

model Event {
  eventId           String         @default(cuid()) @id
  eventNameTH       String?
  eventNameEN       String?
  createDate        DateTime       @default(now())
  eventDate         DateTime?
  bookableDateStart DateTime?
  bookableDateEnd   DateTime?
  priceStart        Int?
  priceEnd          Int?
  organizer         String?
  latitude          Float?
  longtitude        Float?
  location          String?
  keyword           String?
  eventAdminCreator Admin          @relation(references: [adminId], name: "eventAdminCreator")
  raceType          String?
  linkUrl           String?
  coverPhotoUrl     String?
  youtubeUrl        String?
  eventGroup        EventGroup?    @relation(references: [eventGroupId])
  descriptionTH     String?
  descriptionEN     String?
  comment           Comment[]
  lastUpdateTime    DateTime?      @updatedAt
  lastUpdateAdmin   Admin?         @relation(references: [adminId], name: "lastUpdateAdmin")
  followBy          User[]
  eventScore        Float?
  distance          DistanceType[]
}


model Admin {
  adminId         String       @default(cuid()) @id
  email           String
  password        String
  firstName       String
  lastName        String
  createDate      DateTime     @default(now())
  event           Event[]      @relation(references: [adminId], name: "eventAdminCreator")
  eventLastUpdate Event[]      @relation(references: [adminId], name: "lastUpdateAdmin")
  eventGroup      EventGroup[]
  comment         Comment[]
}

@pantharshit00

**Comment by justicejoe** [comment]
Ok now I know, this lift save will be successful if I use global version prisma2@2.0.0-preview015
If I use the version prisma2@2.0.0-preview017.2 to run lift save . it shows error as I mentioned.

@pantharshit00

**Comment by pantharshit00** [comment]
I was able to successfully migrate this in 17.2. I think there was a breaking change in between. So can you please try migrating this on a fresh database. Also, delete your migrations folder inside prisma folder.

**Comment by justicejoe** [comment]
Ok after i change all of my prisma2 version to 17.2 and create new db and delete migration folder 

i try to migrate this model below using prisma2 lift save 

generator photon {
  provider = "photonjs"
}



datasource db {
  provider = "postgresql"
  url      = "postgresql://test:example@localhost:777/db2?schema=db2"
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
}

model User {
  id              String   @default(cuid()) @id
  email           String   @unique
  password        String
  posts           Post[]
  name            String?
  firstName       String?
  lastName        String?
  createDate      DateTime @default(now())
  profileImageUrl String?
  eventFollow     Event[]
}

model Event {
  eventId               String         @default(cuid()) @id
  eventNameTH           String?
  eventNameEN           String?
  eventNameTH_lowerCase String?
  eventNameEN_lowerCase String?
  slug                  String?
  createDate            DateTime       @default(now())
  eventDate             DateTime?
  bookableDateStart     DateTime?
  bookableDateEnd       DateTime?
  priceStart            Int?
  priceEnd              Int?
  organizer             String?
  latitude              Float?
  longtitude            Float?
  location              String?
  keyword               String?
  locationTextShowTH    String?
  locationTextShowEn    String?
  eventAdminCreator     Admin?         @relation(references: [adminId], name: "eventAdminCreator")
  raceType              String?
  linkUrl               String?
  coverPhotoUrl         String?
  coverPhotoUrl_resize  String?
  youtubeUrl            String?
  eventGroup            EventGroup?    @relation(references: [eventGroupId])
  descriptionTH         String?
  descriptionEN         String?
  comment               Comment[]
  lastUpdateTime        DateTime?      @updatedAt
  lastUpdateAdmin       Admin?         @relation(references: [adminId], name: "lastUpdateAdmin")
  followBy              User[]
  eventScore            Float?
  distance              DistanceType[]
}



model EventGroup {
  eventGroupId              String   @default(cuid()) @id
  eventGroupName            String
  createTime                DateTime @default(now())
  slug                      String?
  event                     Event[]
  eventGroupImageUrl        String
  eventGroupImageUrl_resize String
  eventGroupAdminCreator    Admin    @relation(references: [adminId], name: "eventGroupAdminCreator")
  lastUpdateTime            DateTime @updatedAt
  lastUpdateAdmin           Admin    @relation(references: [adminId], name: "eventGroupAdminLastUpdate")
}

model Comment {
  commentId    String         @default(cuid()) @id
  comment      String
  createTime   DateTime       @default(now())
  user         User           @relation(references: [id])
  event        Event          @relation(references: [eventId])
  approve      Boolean
  photo        CommentPhoto[]
  commentScore Float
  approveBy    Admin          @relation(references: [adminId])
  approveTime  DateTime
}

model CommentPhoto {
  commentPhotoId String  @default(cuid()) @id
  imageUrl       String
  comment        Comment @relation(references: [commentId])
}


model DistanceType {
  distanceTypeId String @default(cuid()) @id
  distance       Float
  event          Event  @relation(references: [eventId])
}

model Admin {
  adminId              String       @default(cuid()) @id
  email                String?
  password             String?
  firstName            String?
  lastName             String?
  createDate           DateTime     @default(now())
  event                Event[]      @relation(references: [eventId], name: "eventAdminCreator")
  eventLastUpdate      Event[]      @relation(references: [eventId], name: "lastUpdateAdmin")
  eventGroup           EventGroup[] @relation(references: [eventGroupId], name: "eventGroupAdminCreator")
  eventGroupLastUpdate EventGroup[] @relation(references: [eventGroupId], name: "eventGroupAdminLastUpdate")
  comment              Comment[]
}

and here is my error

![image](https://user-images.githubusercontent.com/16795429/70249435-f6c3d900-17ae-11ea-986d-6448c736a2f4.png)

@pantharshit00

**Comment by pantharshit00** [comment]
I am able to successfully migrate this.

Here is the migration readme:
# Migration `20191206002256-init`

This migration has been generated by Harshit Pant at 12/6/2019, 12:22:56 AM.
You can check out the [state of the schema](./schema.prisma) after the migration.

## Database Steps

```sql
CREATE TABLE "public"."Post" (
  "content" text   ,
  "createdAt" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  "id" text NOT NULL  ,
  "published" boolean NOT NULL DEFAULT true ,
  "title" text NOT NULL DEFAULT '' ,
  "updatedAt" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  PRIMARY KEY ("id")
);

CREATE TABLE "public"."User" (
  "createDate" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  "email" text NOT NULL DEFAULT '' ,
  "firstName" text   ,
  "id" text NOT NULL  ,
  "lastName" text   ,
  "name" text   ,
  "password" text NOT NULL DEFAULT '' ,
  "profileImageUrl" text   ,
  PRIMARY KEY ("id")
);

CREATE TABLE "public"."Event" (
  "bookableDateEnd" timestamp(3)   ,
  "bookableDateStart" timestamp(3)   ,
  "coverPhotoUrl" text   ,
  "coverPhotoUrl_resize" text   ,
  "createDate" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  "descriptionEN" text   ,
  "descriptionTH" text   ,
  "eventDate" timestamp(3)   ,
  "eventId" text NOT NULL  ,
  "eventNameEN" text   ,
  "eventNameEN_lowerCase" text   ,
  "eventNameTH" text   ,
  "eventNameTH_lowerCase" text   ,
  "eventScore" Decimal(65,30)   ,
  "keyword" text   ,
  "lastUpdateTime" timestamp(3)   ,
  "latitude" Decimal(65,30)   ,
  "linkUrl" text   ,
  "location" text   ,
  "locationTextShowEn" text   ,
  "locationTextShowTH" text   ,
  "longtitude" Decimal(65,30)   ,
  "organizer" text   ,
  "priceEnd" integer   ,
  "priceStart" integer   ,
  "raceType" text   ,
  "slug" text   ,
  "youtubeUrl" text   ,
  PRIMARY KEY ("eventId")
);

CREATE TABLE "public"."EventGroup" (
  "createTime" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  "eventGroupId" text NOT NULL  ,
  "eventGroupImageUrl" text NOT NULL DEFAULT '' ,
  "eventGroupImageUrl_resize" text NOT NULL DEFAULT '' ,
  "eventGroupName" text NOT NULL DEFAULT '' ,
  "lastUpdateTime" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  "slug" text   ,
  PRIMARY KEY ("eventGroupId")
);

CREATE TABLE "public"."Comment" (
  "approve" boolean NOT NULL DEFAULT false ,
  "approveTime" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  "comment" text NOT NULL DEFAULT '' ,
  "commentId" text NOT NULL  ,
  "commentScore" Decimal(65,30) NOT NULL DEFAULT 0 ,
  "createTime" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  PRIMARY KEY ("commentId")
);

CREATE TABLE "public"."CommentPhoto" (
  "commentPhotoId" text NOT NULL  ,
  "imageUrl" text NOT NULL DEFAULT '' ,
  PRIMARY KEY ("commentPhotoId")
);

CREATE TABLE "public"."DistanceType" (
  "distance" Decimal(65,30) NOT NULL DEFAULT 0 ,
  "distanceTypeId" text NOT NULL  ,
  PRIMARY KEY ("distanceTypeId")
);

CREATE TABLE "public"."Admin" (
  "adminId" text NOT NULL  ,
  "createDate" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,
  "email" text   ,
  "firstName" text   ,
  "lastName" text   ,
  "password" text   ,
  PRIMARY KEY ("adminId")
);

CREATE TABLE "public"."_EventToUser" (
  "A" text NOT NULL  REFERENCES "public"."Event"("eventId") ON DELETE CASCADE,
  "B" text NOT NULL  REFERENCES "public"."User"("id") ON DELETE CASCADE
);

ALTER TABLE "public"."Post" ADD COLUMN "author" text   REFERENCES "public"."User"("id") ON DELETE SET NULL;

ALTER TABLE "public"."Event" ADD COLUMN "eventAdminCreator" text   REFERENCES "public"."Admin"("adminId") ON DELETE SET NULL,
ADD COLUMN "eventGroup" text   REFERENCES "public"."EventGroup"("eventGroupId") ON DELETE SET NULL,
ADD COLUMN "lastUpdateAdmin" text   REFERENCES "public"."Admin"("adminId") ON DELETE SET NULL;

ALTER TABLE "public"."EventGroup" ADD COLUMN "eventGroupAdminCreator" text NOT NULL  REFERENCES "public"."Admin"("adminId") ON DELETE RESTRICT,
ADD COLUMN "lastUpdateAdmin" text NOT NULL  REFERENCES "public"."Admin"("adminId") ON DELETE RESTRICT;

ALTER TABLE "public"."Comment" ADD COLUMN "approveBy" text NOT NULL  REFERENCES "public"."Admin"("adminId") ON DELETE RESTRICT,
ADD COLUMN "event" text NOT NULL  REFERENCES "public"."Event"("eventId") ON DELETE RESTRICT,
ADD COLUMN "user" text NOT NULL  REFERENCES "public"."User"("id") ON DELETE RESTRICT;

ALTER TABLE "public"."CommentPhoto" ADD COLUMN "comment" text NOT NULL  REFERENCES "public"."Comment"("commentId") ON DELETE RESTRICT;

ALTER TABLE "public"."DistanceType" ADD COLUMN "event" text NOT NULL  REFERENCES "public"."Event"("eventId") ON DELETE RESTRICT;

CREATE UNIQUE INDEX "User.email" ON "public"."User"("email")

CREATE UNIQUE INDEX "_EventToUser_AB_unique" ON "public"."_EventToUser"("A","B")
```

## Changes

```diff
diff --git datamodel.mdl datamodel.mdl
migration ..20191206002256-init
--- datamodel.dml
+++ datamodel.dml
@@ -1,0 +1,120 @@
+datasource db {
+  provider = "postgresql"
+  url      = "***"
+}
+
+generator photon {
+  provider = "photonjs"
+}
+
+model Post {
+  id        String   @default(cuid()) @id
+  createdAt DateTime @default(now())
+  updatedAt DateTime @updatedAt
+  published Boolean  @default(true)
+  title     String
+  content   String?
+  author    User?
+}
+
+model User {
+  id              String   @default(cuid()) @id
+  email           String   @unique
+  password        String
+  posts           Post[]
+  name            String?
+  firstName       String?
+  lastName        String?
+  createDate      DateTime @default(now())
+  profileImageUrl String?
+  eventFollow     Event[]
+}
+
+model Event {
+  eventId               String         @default(cuid()) @id
+  eventNameTH           String?
+  eventNameEN           String?
+  eventNameTH_lowerCase String?
+  eventNameEN_lowerCase String?
+  slug                  String?
+  createDate            DateTime       @default(now())
+  eventDate             DateTime?
+  bookableDateStart     DateTime?
+  bookableDateEnd       DateTime?
+  priceStart            Int?
+  priceEnd              Int?
+  organizer             String?
+  latitude              Float?
+  longtitude            Float?
+  location              String?
+  keyword               String?
+  locationTextShowTH    String?
+  locationTextShowEn    String?
+  eventAdminCreator     Admin?         @relation(references: [adminId], name: "eventAdminCreator")
+  raceType              String?
+  linkUrl               String?
+  coverPhotoUrl         String?
+  coverPhotoUrl_resize  String?
+  youtubeUrl            String?
+  eventGroup            EventGroup?    @relation(references: [eventGroupId])
+  descriptionTH         String?
+  descriptionEN         String?
+  comment               Comment[]
+  lastUpdateTime        DateTime?      @updatedAt
+  lastUpdateAdmin       Admin?         @relation(references: [adminId], name: "lastUpdateAdmin")
+  followBy              User[]
+  eventScore            Float?
+  distance              DistanceType[]
+}
+
+model EventGroup {
+  eventGroupId              String   @default(cuid()) @id
+  eventGroupName            String
+  createTime                DateTime @default(now())
+  slug                      String?
+  event                     Event[]
+  eventGroupImageUrl        String
+  eventGroupImageUrl_resize String
+  eventGroupAdminCreator    Admin    @relation(references: [adminId], name: "eventGroupAdminCreator")
+  lastUpdateTime            DateTime @updatedAt
+  lastUpdateAdmin           Admin    @relation(references: [adminId], name: "eventGroupAdminLastUpdate")
+}
+
+model Comment {
+  commentId    String         @default(cuid()) @id
+  comment      String
+  createTime   DateTime       @default(now())
+  user         User           @relation(references: [id])
+  event        Event          @relation(references: [eventId])
+  approve      Boolean
+  photo        CommentPhoto[]
+  commentScore Float
+  approveBy    Admin          @relation(references: [adminId])
+  approveTime  DateTime
+}
+
+model CommentPhoto {
+  commentPhotoId String  @default(cuid()) @id
+  imageUrl       String
+  comment        Comment @relation(references: [commentId])
+}
+
+model DistanceType {
+  distanceTypeId String @default(cuid()) @id
+  distance       Float
+  event          Event  @relation(references: [eventId])
+}
+
+model Admin {
+  adminId              String       @default(cuid()) @id
+  email                String?
+  password             String?
+  firstName            String?
+  lastName             String?
+  createDate           DateTime     @default(now())
+  event                Event[]      @relation(references: [eventId], name: "eventAdminCreator")
+  eventLastUpdate      Event[]      @relation(references: [eventId], name: "lastUpdateAdmin")
+  eventGroup           EventGroup[] @relation(references: [eventGroupId], name: "eventGroupAdminCreator")
+  eventGroupLastUpdate EventGroup[] @relation(references: [eventGroupId], name: "eventGroupAdminLastUpdate")
+  comment              Comment[]
+}
```

## Photon Usage

You can use a specific Photon built for this migration (20191206002256-init)
in your `before` or `after` migration script like this:

```ts
import Photon from '@generated/photon/20191206002256-init'

const photon = new Photon()

async function main() {
  const result = await photon.users()
  console.dir(result, { depth: null })
}

main()

```


##### Can you please make sure that the cli that you are using is on latest version? Run prisma2 -v

**Comment by justicejoe** [comment]
this is my package.json

{
  "name": "graphql-auth",
  "version": "1.0.0",
  "dependencies": {
    "@babel/cli": "^7.7.4",
    "@google-cloud/storage": "^4.1.3",
    "@prisma/photon": "2.0.0-preview017.2",
    "@types/ws": "^6.0.3",
    "bcrypt": "3.0.6",
    "config": "^3.2.4",
    "cors": "^2.8.5",
    "dayjs": "^1.8.17",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "file-type": "^12.4.0",
    "graphql": "^14.5.8",
    "graphql-shield": "5.7.3",
    "graphql-yoga": "1.18.3",
    "jsonwebtoken": "8.5.1",
    "mime-types": "^2.1.25",
    "multer": "^1.4.2",
    "nexus": "0.12.0-rc.5",
    "nexus-prisma": "0.6.1",
    "ts-node": "^8.5.2",
    "typescript": "^3.7.2",
    "uuid": "^3.3.3"
  },
  "scripts": {
    "build": "babel src --out-dir build",
    "start": "nodemon --exec babel-node src/index.js",
    "start:prod": "node build/index.js",
    "seed": "node prisma/seed.js",
    "postinstall": "prisma2 generate"
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/node": "^7.7.0",
    "@babel/preset-env": "^7.7.1",
    "prisma2": "2.0.0-preview017.2"
  }
}


and I always make sure to use npx prisma2 to use the latest version of prisma2 command 

@pantharshit00

**Comment by pantharshit00** [comment]
Can you please paste output of `npx prisma2 -v` here? It might be reading a older version from the npm cache.

**Comment by divyenduz** [comment]
"Error parsing the migration steps". This error happens when the internal representation of lift (the migration engine) has a breaking change. 

Since, we are in preview, although we try to contain the surface area of breaking changes, this one is acceptable. 

The workaround is to remove your migrations and the migration table and start from scratch wrt migration. Does that make sense? 

I am closing this one, if the problem persists for you, please comment here or reach out to me in our slack: https://slack.prisma.io.
