### ISSUE TITLE
after update from version  2.0.0-preview013.3 to  2.0.0-preview017.2 there is a query error

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#1025]
all DateTime Type query using graphql return as null and also come with error 

```
"errors": [
    {
      "message": "Expected a value of type \"DateTime\" but received: {}",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "events",
        2,
        "eventDate"
      ]
    },
    {

**Comment by justicejoe** [comment]
I don't know why I got this error , i think the data is already correct and in the DateTime format.

   {
      "message": "Expected a value of type \"DateTime\" but received: \"2019-11-28T13:28:46.054Z\"",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "events",
        16,
        "createDate"
      ]
    },
    {
      "message": "Expected a value of type \"DateTime\" but received: \"2019-11-29T09:52:50.342Z\"",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "events",
        17,
        "createDate"
      ]
    },
    {
      "message": "Expected a value of type \"DateTime\" but received: \"2019-11-29T12:34:19.191Z\"",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "events",
        18,
        "createDate"
      ]
    },
    {
      "message": "Expected a value of type \"DateTime\" but received: \"2019-11-29T12:39:45.160Z\"",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "events",
        19,
        "createDate"
      ]
    },
    {
      "message": "Expected a value of type \"DateTime\" but received: \"2019-11-29T15:04:36.427Z\"",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "events",
        20,
        "createDate"
      ]
    }
  ]
}

**Comment by justicejoe** [comment]
Is there a problem with nexus, or nexus-prisma ?

**Comment by pantharshit00** [comment]
We had a breaking change in preview015 where we started mapping dates to the javascript date type: https://github.com/prisma/prisma2/releases/tag/2.0.0-preview015

So you need to pass a Date object instead of a string now.

**Comment by justicejoe** [comment]
@pantharshit00 Thanks for your answer, Do you have the detail about which parts of code I need to change in order to get it work ? both insert and read.   Now the already add info's date keep inside postgres can not be query at all

**Comment by pantharshit00** [comment]
Can you please share code that you have for this resolver?

You will need to pass a javascript date object wherever you will update the dates.

**Comment by justicejoe** [comment]
here is the one
@pantharshit00 

export const Event = objectType({
    name: "Event",
    definition(t) {
        t.id("eventId")
        t.string("eventNameTH", { nullable: true })
        t.model.eventNameEN()
        t.field("createDate", {
            type: DateTime,
            nullable: true,
        })
        t.field("eventDate", {
            type: DateTime,
            nullable: true,
        })
        t.field("bookableDateStart", {
            type: DateTime,
            nullable: true,
        })
        t.model.bookableDateEnd()
        t.int("priceStart", { nullable: true })
        t.int("priceEnd", { nullable: true })
        t.string("organizer", { nullable: true })
        t.float("latitude", { nullable: true })
        t.float("longtitude", { nullable: true })
        t.string("location", { nullable: true })
        t.string("keyword", { nullable: true })
        t.model.locationTextShowEn()
        t.model.locationTextShowTH()
        t.field("eventAdminCreator", {
            type: Admin,
            list: [false],
            resolve: (parent, args, ctx) => {
                return ctx.photon.admins.findMany({
                    where: {
                        event: {
                            some: {
                                eventId: parent.eventId
                            }
                        }
                    }
                })
            },
        })
        t.string("raceType", { nullable: true })
        t.string("linkUrl", { nullable: true })
        t.string("coverPhotoUrl", { nullable: true })
        t.model.coverPhotoUrl_resize()
        t.string("youtubeUrl", { nullable: true })
        t.field("eventGroup", {
            type: EventGroup,
            nullable: true,
        })
        t.string("descriptionTH", { nullable: true })
        t.model.descriptionEN()
        t.field("comment", {
            type: Comment,
            list: [false],
            nullable: true,
        })
        t.field("lastUpdateTime", {
            type: DateTime,
            nullable: true,
        })
        t.field("lastUpdateAdmin", {
            type: Admin,
            list: [false],
            resolve: (parent, args, ctx) => {
                return ctx.photon.admins.findMany({
                    where: {
                        event: {
                            some: {
                                eventId: parent.eventId
                            }
                        }
                    }
                })
            },
        })
        t.field("followBy", {
            type: User,
            list: [true],
            nullable: true,
        })
        //t.model.followBy()
        t.float("eventScore", { nullable: true })
        t.field("distance", {
            type: DistanceType,
            list: [false],
            resolve: (parent, args, ctx) => {
                return ctx.photon.distanceTypes.findMany({
                    where: {
                        event: { eventId: parent.eventId }
                    }
                })
            },
        })

    }
})

**Comment by pantharshit00** [comment]
Can you please share code for the `DateTime` type that you are using? Also, I will recommend you to use t.model syntax in place of t.<type> to define your fields as they come with root resolvers and are adhered to your schema.

**Comment by justicejoe** [comment]
@pantharshit00  
u mean this one ?

export const DateTime = scalarType({
    name: "DateTime",

});

**Comment by pantharshit00** [comment]
Yes, so how can you please try changing this to :
```
export const DateTime = scalarType({
name: "DateTime",
serialize: t => new Date(t)
});
```

**Comment by divyenduz** [comment]
Closing this one because of lack of activity. @justicejoe In case your issue still exists, please feel free to add a comment here and tag me. I would be happy to reopen this one.
