### ISSUE TITLE
Connect to Heroku SSL problem

### ISSUE THREAD

**Issue by lasharela** [prisma/prisma2#1027]
I'm trying to connect to Heroku Database `prisma2 init`, blank template.

everything is filed correctly but I'm getting an error:

```
 ERROR  self signed certificate
```

**Comment by williamluke4** [comment]
Pretty sure this is related to #884

**Comment by williamluke4** [comment]
Try this
> Adding `sslaccept=accept_invalid_certs` to your datasource url should work for now

_Originally posted by @williamluke4 in https://github.com/prisma/prisma2/issues/884#issuecomment-551697427_

**Comment by lasharela** [comment]
> Try this
> 
> > Adding `sslaccept=accept_invalid_certs` to your datasource url should work for now
> 
> _Originally posted by @williamluke4 in [#884 (comment)](https://github.com/prisma/prisma2/issues/884#issuecomment-551697427)_

Yes, I'm connecting to local DB and then `sslaccept=accept_invalid_certs` is helping

**Comment by pantharshit00** [comment]
I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/884
