### ISSUE TITLE
PRISMA_QUERY_ENGINE_BINARY being ignored

### ISSUE THREAD

**Issue by LongLiveCHIEF** [prisma/prisma2#1034]
I'm compiling my own binaries via [Dockerfile](https://github.com/LongLiveCHIEF/prisma2/blob/574dc3de29cbe2f7dff8aa81e47f429909ed0e77/docker/Dockerfile), and setting the binaries on a custom path of `/prisma-engine/binaries/<binary_name>`.

However, when I run `prisma lift` or `prisma generate` commands, I get a node `ENOENT` error because it's trying to spawn the binary from `/usr/local/lib/node_modules` instead of the path I've provided to the explicit binary.

Just to be sure it wasn't a naming problem (see comment https://github.com/prisma/prisma2/issues/938#issuecomment-554780269), i named the binary with the same resolved name for my native platform.

```
$ echo $PRISMA_QUERY_ENGINE_BINARY
/prisma-engine/binaries/query-engine-linux-glibc-libssl1.1.0
$ prisma lift up --preview
Error: Get config Error: Command failed with exit code 2 (ENOENT): /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 clie --get_config /tmp/d02f6653-7b90-478f-9cf4-98ce4d8b3ba8
spawn /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 ENOENT
```

**Comment by pantharshit00** [comment]
Moving to prisma2 repository as this is related to the cli

**Comment by janpio** [comment]
That bug also seems to apply for the `MIGRATION` env var: https://github.com/prisma/prisma2/issues/343#issuecomment-559856520

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.

**Comment by pantharshit00** [comment]
@LongLiveCHIEF Here is the commit which fixed the issue: https://github.com/prisma/prisma2/commit/93d33ffc595bbb9204f34f8bc313460a73cf3766
