### ISSUE TITLE
Current Prisma2 limitations. 

### ISSUE THREAD

**Issue by Ericnr** [prisma/prisma2#1035]
I can't wait to try out Prisma2 in a new project, but there's a few things I'd like to know if it's supported or not. Is there link where I can see if certain features have been implemented?. Things like JSON field, check constraint, aggregates, etc. Much appreciated!

**Comment by pantharshit00** [comment]
Hi,

We list some of the limitations here: https://github.com/prisma/prisma2/blob/master/docs/limitations.md

You can look into the issue for other limitations.

Unfortunately, the things that you have mentioned are also work in progress 😅.

You can check the specs repository on what is coming: https://github.com/prisma/specs

**Comment by Ericnr** [comment]
Cool, tyvm! I don't see JSON fields or check constraint in  the specs, I hope they'll be added.

**Comment by pantharshit00** [comment]
JSON fields are part of the native type. We will not only support JSON type but all other database types in the future: https://github.com/prisma/specs/tree/master/schema#type-definitions-provided-by-connectors. JSON will just another postgres type.

I opened a new spec issue for check constraints though: https://github.com/prisma/specs/issues/344

**Comment by yovanoc** [comment]
Hey, I'm working with protobuf, and I get a Long type for `uint64` and there is no way actually to save more than an Int in prisma?
![image](https://user-images.githubusercontent.com/7302317/70039372-1cd45800-15ba-11ea-8bb8-8de2c78d2d31.png)

**Comment by pantharshit00** [comment]
Longs are also part of type declarations as described by @matthewmueller here: https://github.com/prisma/photonjs/issues/170#issuecomment-517369338

That is a long ongoing work that will remove many limitations. It still requires much product and implementation work so it is taking time.

**Comment by Ericnr** [comment]
Question answered!
