### ISSUE TITLE
1:N and M:N relationship on same foreign key

### ISSUE THREAD

**Issue by seanemmer** [prisma/prisma2#1036]
I am trying to create two fields in one Model that both relate to the same field in another Model.  I am prompted to disambiguate the relationship, but when I add a @relation directive to one field the remaining field throws an error:

`Error validating model "User": Automatic related field generation would cause a naming conflict. Please add an explicit opposite relation field.`

```groovy
model User {
  id              String     @default(cuid()) @id
  accounts       Account[] @relation(name: "UserAccounts")
  currentAccount Account
}

model Account {
  id        String     @default(cuid()) @id
  name      String
  users     User[] @relation(name: "UserAccounts")
}
```

**Comment by mavilein** [comment]
The problem is in the field `User.currentAccount`. This would fix it:
```groovy
model User {
  id              String     @default(cuid()) @id
  accounts       Account[] @relation("UserAccounts")
  currentAccount Account @relation("CurrentAccount")
}

model Account {
  id        String     @default(cuid()) @id
  name      String
  users     User[] @relation("UserAccounts")
  currentAccountOf User @relation("CurrentAccount")
}
```

**Comment by pearlyplan** [comment]
Thanks!  Unfortunately this solution requires me to create a second field on the Account model (currentAccountOf).

The desired schema is for both `user.accounts` and `user.currentAccount` to relate to account.users, where user.currentAccount is a 1:N relationship and is a selection from user.accounts, which is a M:N relationship.

**Comment by seanemmer** [comment]
Thanks! Unfortunately this solution requires me to create a second field on the Account model (currentAccountOf).

The desired schema is for both user.accounts and user.currentAccount to relate to account.users, where user.currentAccount is a 1:N relationship and is a selection from user.accounts, which is a M:N relationship.

**Comment by mavilein** [comment]
Ah i see. This is not possible. You have to implement this yourself in your application layer.

**Comment by seanemmer** [comment]
Understood, thanks for clarifying
