### ISSUE TITLE
t.model.something()   of nexus-prisma not working when it represent other model

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#1041]
![image](https://user-images.githubusercontent.com/16795429/70138295-8e97c900-16c2-11ea-9174-423edf8d0194.png)

![image](https://user-images.githubusercontent.com/16795429/70138818-aa4f9f00-16c3-11ea-8668-3ba2e698cd04.png)

when I use t.model.event()    to represent other model.  I can not query with something like this

![image](https://user-images.githubusercontent.com/16795429/70139171-75901780-16c4-11ea-959a-8190561e7de0.png)

It will alway show error as above

but the normal query not include relation work normally

![image](https://user-images.githubusercontent.com/16795429/70139326-d28bcd80-16c4-11ea-9e51-c1962dd68eda.png)

this is my admin objectModel

![image](https://user-images.githubusercontent.com/16795429/70139412-04049900-16c5-11ea-812e-8699db62f7a2.png)

**Comment by pantharshit00** [comment]
Hi,

I have moved your issue over here since it is related to nexus-prisma: https://github.com/prisma-labs/nexus-prisma/issues/553

**Comment by pantharshit00** [comment]
Locking this, continue the conversation over at https://github.com/prisma-labs/nexus-prisma/issues/553
