### ISSUE TITLE
Include connection query feature with Photon (important when migrating from Prisma 1)

### ISSUE THREAD

**Issue by reinvanimschoot** [prisma/prisma2#1042]
Hi guys!

I have a project that is nearly complete and entirely written with Prisma 1 as an integral part of the stack.

The last few days I have been going back and forth whether or not to bite the bullet and rewrite the project in Prisma2 or at least start the process of migrating. 

But one thing that is really making me hesitant of migrating to Prisma 2 is the fact it currently lacks any kind of connection queries. 

As seen in the docs of [Prisma 1](https://www.prisma.io/docs/reference/prisma-api/queries-ahwee4zaey#connection-queries
):

```
The Prisma API offers two kinds of queries:
- Object queries: Fetch single or multiple nodes of a certain object type
- Connection queries: Expose advanced features like aggregations and Relay compliant connections enabling a powerful pagination model
```

This is an incredibly powerful feature to get access to out of the box since it provides so much value.

I make heavy use of the connection queries and the prospect of heaving to replicate all of this myself is making me weary of actually making the jump to Prisma2.

I have heard that this behaviour would become the responsibility of nexus-prisma but that would require the adoption of nexus, which is not always possible nor desirable.

It would be great if Photon itself could provide a connection query out of the box, just as is the case with Prisma1:

Prisma 1:

`ctx.db.query.commentsConnection( ... )`

so Prisma 2 would be:

`ctx.photon.commentsConnection( ... )`

Thanks for all the hard work!

**Comment by pantharshit00** [comment]
Hi,

Instead of connections, you can use `findMany` query to get paginated data(`ctx.photon.users.findMany({ //options })`. It is not fully relay spec compatible but you can use it create your paginable api. 

In the future, we may add meta responses in that as well. Spec here for that: https://github.com/prisma/specs/tree/master/photonjs#experimental-meta-response

**Comment by reinvanimschoot** [comment]
The problem is that if you have a full-fledged API that heavily relies on edges/connections, page info but also cursors etc., it becomes quite a burden to migrate to Prisma 2. Suddenly, you have to implement that whole layer yourself. And then it becomes the tedious matter of trying to see what Prisma 2 offers out of the box and what you have to add.

For example, the pageInfo idea you linked has `hasNext` and `hasPrev` but no cursors. So you are left with something that more or less resembles Prisma 1's approach but has a different naming scheme and is missing certain aspects of it.

I know Prisma 2 prides itself on being database and API tech-agnostic but Prisma 1 very much leaned into the GraphQL approach and I can't imagine I am the only that made use of that. So I'd wager I'm not the only one that would love to see a more fleshed out migration path.

So I would say either you do provide the same approach as Prisma 1 did, consciously leaning into the GraphQL approach which might be against the core idea of Prisma 2. 

Or you provide a well thought out migration guide that covers all aspects of migrating a Relay-compliant API built on Prisma 1 to Prisma 2.

Right now, I feel like you're doing a disservice to the people that bought into Prisma 1. Prisma as a company always moved fast, going from Graphcool to Prisma 1 to Prisma 2 in a relatively short timespan, often drastically changing the approach along the way. So please do not leave the people that have supported you for a long time out in the cold.

**Comment by soqt** [comment]
I feel the same way, you guys moved way too fast, even Prisma 1 has tons of bugs and now Prisma 2 is out and not backward compatible. Personally, relay connection is the main reason why I like to use Prisma 1, it is not wise to remove relay completely from Prisma 2. Hope this can be implemented as soon as possible in Prisma 2.

**Comment by steebchen** [comment]
I agree that Prisma should build pageInfo (which is the last component needed for having relay-style connections) in its core. It shouldn't be too hard to implement and makes PhotonJS and all other clients built on top of Prisma super easy to work with.

**Comment by nikolasburk** [comment]
Thanks a lot for sharing your thoughts here everyone 👋

It is definitely true that the current versions of Prisma 2 and `nexus-prisma` don't provide good support for Relay-style pagination, and as @reinvanimschoot mentioned, you're pretty much left implementing the whole layer yourself if you want that feature today. 

Eventually, the implementation of Relay-pagination will become _seamless_ using `nexus-prisma`, and it will supported out-of-the-box. We are aware that this is a really important feature for the majority of users that are currently running Prisma 1 setups! We're currently discussing internally whether that is something that we can deliver for the [Photon.js launch in Q1](https://www.prisma.io/blog/state-of-prisma-2-december-rcrwcqyu655e/) and I will submit an update here once we have this figured out.

**Comment by steebchen** [comment]
In my opinion, this should be a _core_ feature in the query engine so that _all_ things on top of Prisma can make use of it. That means PhotonJS (which implies nexus), but also Photon Go and probably other tools in the future.

**Comment by divyenduz** [comment]
Thanks everyone for the valuable discussion. @nikolasburk's answer is our current stance on this topic. 

We do acknowledge that Photon + "relay API helpers" is a feature request and we want to consider that separately. This issue tracks that https://github.com/prisma/photonjs/issues/321

@ctrlplusb also wrote a nice helper to make this possible https://github.com/prisma/photonjs/issues/321#issuecomment-574593136

Let us use the other issue to track this feature. In the meantime, I am closing this one.

**Comment by nikolasburk** [comment]
Also just want to quickly highlight @ctrlplusb's work here who wrote a helper to support Relay Cursor Connection Specification type querying: https://gist.github.com/ctrlplusb/17b5a1bd1736b5ba547bb15b3dd5be29 🚀
