### ISSUE TITLE
nexus prisma deletemany  Error

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#1044]
![image](https://user-images.githubusercontent.com/16795429/70150305-67e68c00-16dc-11ea-9e35-c17e361b2852.png)

this is the error

from this query 

![image](https://user-images.githubusercontent.com/16795429/70150356-78970200-16dc-11ea-9c7c-ab9c2045c99c.png)

**Comment by pantharshit00** [comment]
Can you please share your code? I tried on a user model and the query is working fine.

![image](https://user-images.githubusercontent.com/22195362/70244019-aee68700-1799-11ea-9dbf-fc1ec1299961.png)


Maybe share your datamodel as well.

Also, maybe issue is more relevant in the https://github.com/prisma-labs/nexus-prisma repository

**Comment by justicejoe** [comment]
Here is my model

generator photon {
  provider = "photonjs"
}



datasource db {
  provider = "postgresql"
  url      = "postgresql://test:example@localhost:777/mydb?schema=my_db"
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
}

model User {
  id              String   @default(cuid()) @id
  email           String   @unique
  password        String
  posts           Post[]
  name            String?
  firstName       String?
  lastName        String?
  createDate      DateTime @default(now())
  profileImageUrl String?
  eventFollow     Event[]
}

model Event {
  eventId               String         @default(cuid()) @id
  eventNameTH           String?
  eventNameEN           String?
  eventNameTH_lowerCase String?
  eventNameEN_lowerCase String?
  slug                  String?
  createDate            DateTime       @default(now())
  eventDate             DateTime?
  bookableDateStart     DateTime?
  bookableDateEnd       DateTime?
  priceStart            Int?
  priceEnd              Int?
  organizer             String?
  latitude              Float?
  longtitude            Float?
  location              String?
  keyword               String?
  locationTextShowTH    String?
  locationTextShowEn    String?
  eventAdminCreator     Admin?         @relation(references: [adminId], name: "eventAdminCreator")
  raceType              String?
  linkUrl               String?
  coverPhotoUrl         String?
  coverPhotoUrl_resize  String?
  youtubeUrl            String?
  eventGroup            EventGroup?    @relation(references: [eventGroupId])
  descriptionTH         String?
  descriptionEN         String?
  comment               Comment[]
  lastUpdateTime        DateTime?      @updatedAt
  lastUpdateAdmin       Admin?         @relation(references: [adminId], name: "lastUpdateAdmin")
  followBy              User[]
  eventScore            Float?
  distance              DistanceType[]
}



model EventGroup {
  eventGroupId              String   @default(cuid()) @id
  eventGroupName            String
  createTime                DateTime @default(now())
  slug                      String?
  event                     Event[]
  eventGroupImageUrl        String
  eventGroupImageUrl_resize String
  eventGroupAdminCreator    Admin    @relation(references: [adminId], name: "eventGroupAdminCreator")
  lastUpdateTime            DateTime @updatedAt
  lastUpdateAdmin           Admin    @relation(references: [adminId], name: "eventGroupAdminLastUpdate")
}

model Comment {
  commentId    String         @default(cuid()) @id
  comment      String
  createTime   DateTime       @default(now())
  user         User           @relation(references: [id])
  event        Event          @relation(references: [eventId])
  approve      Boolean
  photo        CommentPhoto[]
  commentScore Float
  approveBy    Admin          @relation(references: [adminId])
  approveTime  DateTime
}

model CommentPhoto {
  commentPhotoId String  @default(cuid()) @id
  imageUrl       String
  comment        Comment @relation(references: [commentId])
}


model DistanceType {
  distanceTypeId String @default(cuid()) @id
  distance       Float
  event          Event  @relation(references: [eventId])
}

model Admin {
  adminId              String       @default(cuid()) @id
  email                String?
  password             String?
  firstName            String?
  lastName             String?
  createDate           DateTime     @default(now())
  event                Event[]      @relation(references: [eventId], name: "eventAdminCreator")
  eventLastUpdate      Event[]      @relation(references: [eventId], name: "lastUpdateAdmin")
  eventGroup           EventGroup[] @relation(references: [eventGroupId], name: "eventGroupAdminCreator")
  eventGroupLastUpdate EventGroup[] @relation(references: [eventGroupId], name: "eventGroupAdminLastUpdate")
  comment              Comment[]
}


@pantharshit00

**Comment by pantharshit00** [comment]
Hey @justicejoe 

Sorry for the late response here but it seems like you have shared model for some other project with me. 

The type in the screenshot that you have shared is `Event` but in this datamodel, there is no Event type. Maybe you can share the git repository of this project with me. That I can test out the full server implementation without guessing or assuming certain implementation details.
