### ISSUE TITLE
Newcomers are confused about individual naming of Prisma 2 tools

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1048]
With Prisma 2, we decided to make different pieces of Prisma available as _standalone tools with individual names_, concretely we decided to name them as follows:

- Photon (Database access)
- Lift (Migrations)
- Studio (GUI-based workflows)

Together these tools form the _Prisma Framework_.

While these individual names make it clear that the tools can be used standalone and overall feel more lightweight, they are adding mental overhead for newcomers who are just getting started with Prisma. It's not always easy to understand which part does what. 

We'd like to hear some opinions on the naming strategies of using the individual names versus using more descriptive names, such as:

- Prisma Query (Database access)
- Prisma Migrate (Migrations)
- Prisma Admin (GUI-based workflows)

If you're a Prisma newcomer or can reflect on the first times you've used Prisma, we'd like to hear from you whether the current non-descriptive names were a source of confusion and a descriptive naming strategy might be clearer?

**Comment by ctrlplusb** [comment]
I quite like Lift and Studio - they feel very appropriate for their roles. Photon maybe not so much - it's cool name, but perhaps an opportunity for a rename there.

Personally, I am not overly bothered by the names. I actually have a package called [Easy Peasy](https://easy-peasy.now.sh) - so I am probably the last person who is allowed to criticise product names! 

That all being said perhaps the confusion has less to do with the names, but is rather a signal that the opening docs/blogs/etc aren't doing enough to prime readers with clear enough understandings for each role. 

Taking a look at the [readme landing for the GitHub repo](https://github.com/prisma/prisma2#what-is-the-prisma-framework);

Personally, I am not a big fan of leading with an image. For myself it feels like an increase in cognitive load as I have to try and breakdown what the image is trying to convey without knowing anything about the product. The image also contains vague labels such as "develop" which could lead to assumptions.  We need to move readers away from assumptions. 😊

I would flip the image with the bullet point list below it, and then consider expanding the list to provide slightly more detail about the role of each of the tools. We want to remaining concise enough not to overload the reader, but still be able to describe each tool with enough clarity that the user feels sufficiently confident about the role of each. Easier said than done? 😛

Hopefully then displaying the image below the breakdown will make the image a lot easier to digest and then aid to cement the readers understanding of what they have just read.

Of course this is all my opinion, and perhaps others may have very different perspectives. 😀

**Comment by CaptainChemist** [comment]
I really like the idea of appending the prefix Prisma to whatever names you decide on. I think that solves the main point of confusion that I had when I was originally reading about Prisma 2. You could even have some graphic that shows how each of those 3 tools are pie pieces that together form the full circle which is Prisma 2.

I think that one potential issue with the Prisma Query name is that the word query is already kind of confusingly used in the GraphQL community and I’d hate to add to the confusion. What I mean is that you have queries and mutations *but* the name of the umbrella group that refers to queries *or* mutations is *also* query. You can see this, for example if you run a graphQL playground request and look at the POST request- the body has a field called query that will contain the query or mutation that was sent off. Maybe you could call it the Prisma Query Engine to make it clear that you aren’t talking about the actual gql document itself? 

I generally agree with @ctrlplusb ’s critique that adding 3 short bullet points describing each service before the image would be useful. I’m definitely more of a visual learner though so I find a picture to be immensely helpful at framing a longer, multi-paragraph discussion, so I hope that you keep an image before any dense technical paragraphs.

I could be off base with these points but hopefully this is helpful!

**Comment by jlengstorf** [comment]
I'm always a fan of naming things with what they do.

I think it's critical that these tools are linked by a brand. When I first saw Photon, Lift, and Studio, I didn't know if these were officially supported Prisma projects, OSS projects Prisma was using, or something else. (Same for e.g. Yoga, too.)

I think it makes a lot of sense to bundle these tools and encourage people to use only what they need, but also I think it's important to send a clear signal about which projects are official/maintained and which are OSS/likely to fade away.

I have a lot of love for Prisma, but there's a trail of packages with clever names in the company's wake and I have very little idea what most of them do or whether they're actively maintained by Prisma or whether they're recommended for use in new projects.

I would strongly encourage y'all to use naming that A) includes the Prisma brand, and B) tells us what the thing does.

What is a "lift"? I have no idea. I've looked at the product page before, but I can't remember what it does and the name isn't helping me fill in the gaps.

"Prisma Migrate" (I'm just choosing one; can't remember if that's the actual thing that Lift does) makes it pretty clear that A) Prisma officially maintains this product and B) it migrates things.

**Comment by nikolasburk** [comment]
Thank you all so much for sharing your thoughts on this delicate topic! 🙏 

After many conversations we've had, we finally concluded that we'd like to go with the "simpler" naming model and renamed Photon.js to Prisma Client JS for Lift to Prisma Migrate. This has taken effect with [today's release](https://github.com/prisma/prisma2/releases/tag/2.0.0-preview020), I'm therefore closing this issue.
