### ISSUE TITLE
Inconsistent engine files names

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1049]
In `preview017.2` the engines are inconsistently named:
![image](https://user-images.githubusercontent.com/183673/70172757-acb8f580-16d1-11ea-9fa8-226102567eed.png)

**Comment by janpio** [comment]
This is still the case in current `alpha`:

```
λ prisma2 -v
prisma2@2.0.0-alpha.402, binary version: f9dc134bb45be197241dd04b0c11073fc5917ed7
```

**Comment by divyenduz** [comment]
![image](https://user-images.githubusercontent.com/746482/72075379-ea71f500-32f3-11ea-8da1-09f326584fc4.png)

@janpio  This is the latest state, good enough?

**Comment by janpio** [comment]
Please check the unpacked state.

**Comment by pantharshit00** [comment]
They are still inconsistent:
![image](https://user-images.githubusercontent.com/22195362/72204772-80974e00-34a1-11ea-8de9-7e4e48128f9f.png)

Tested with `alpha.520`

**Comment by janpio** [comment]
Internal note: Please also check if the naming on other platforms is consistent and makes sense when looking into this.

**Comment by pantharshit00** [comment]
Naming is also inconsistent on other platforms:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/22195362/72811417-a5e84100-3c85-11ea-9186-7d286edfd9cd.png">

**Comment by janpio** [comment]
Ah, in the same way even - thanks for confirming @pantharshit00.

**Comment by divyenduz** [comment]
Note: Spec is to be adjusted, if needed.
