### ISSUE TITLE
Lift and dev, popup to create a new database missing

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1051]
```
divyendusingh [footybot]$ prisma2 --version
prisma2@2.0.0-preview017.2, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293
```

To reproduce: 

1. Create a schema file with a DB url where the database does not exist

2. Run lift save or dev
```
divyendusingh [footybot]$ prisma2 lift save --name init
Error: Could not connect to database: Starting a mysql pool with 13 connections.
[2019-12-05T09:38:10Z ERROR migration_engine] Database 'footyboy-dev1' does not exist.
```

**Comment by divyenduz** [comment]
I can still observe this for MySQL on both alpha and the latest preview

![image](https://user-images.githubusercontent.com/746482/70440770-329ebd00-1a93-11ea-8767-e77ed7417bd8.png)

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
