### ISSUE TITLE
Could not install prisma2 using volta

### ISSUE THREAD

**Issue by mjyoung** [prisma/prisma2#1054]
I'm using [volta.sh](volta.sh) as my Node version manager. 

Installing prisma works via:
```sh
volta install prisma
```

However, when trying to install prisma2 via:
```sh
volta install prisma2 --verbose
```

I get the following error:
```
[verbose] Using npm@6.12.1 from default configuration
[verbose] Running command: `"npm" "view" "--json" "prisma2@latest"`
[verbose] [parsed package metadata (single)]
NpmViewData { name: "prisma2", version: Version { major: 2, minor: 0, patch: 0, pre: [AlphaNumeric("preview017"), Numeric(2)], build: [] }, dist: RawDistInfo { shasum: "a5f741fda24f13a060b570dc591d52c456277dae", tarball: "https://registry.npmjs.org/prisma2/-/prisma2-2.0.0-preview017.2.tgz" }, dist_tags: RawPackageDistTags { latest: Version { major: 2, minor: 0, patch: 0, pre: [AlphaNumeric("preview017"), Numeric(2)], build: [] }, beta: None } }
[verbose] Found prisma2 latest version (2.0.0-preview017.2) from https://registry.npmjs.org/prisma2/-/prisma2-2.0.0-preview017.2.tgz
[verbose] prisma2@2.0.0-preview017.2 has already been fetched, skipping download
[verbose] No 'engines.node' found for prisma2@2.0.0-preview017.2, using latest
[verbose] Found latest node version (13.3.0) from https://nodejs.org/dist/index.json
[verbose] Installing dependencies with command: "npm" "install" "--only=production" "--loglevel=warn" "--no-update-notifier" "--no-audit"
[verbose] [install stderr]
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

Any tips on how to deal with this? `prisma2` is the first package that I haven't been able to globally install using `volta`

**Comment by pantharshit00** [comment]
Looks like volta is trying to devDependencies as well. We use pnpm(https://pnpm.js.org/) in development to create a workspace environment. So we have some devDependencies have workspace protocol:
![image](https://user-images.githubusercontent.com/22195362/70305531-a5f1c600-182a-11ea-80d4-7dff7eb9b57b.png)

But I think we can change in the package.json file that we release. So I am marking this as a bug.

**Comment by pantharshit00** [comment]
Update: I think this is actually a bug in our cli pipeline. The workspace url should be replaced by the actual package version by pnpm.

https://pnpm.js.org/en/workspaces#publishing-workspace-packages

**Comment by timsuchanek** [comment]
@mjyoung thanks for reporting, @pantharshit00 thanks for the comment!

The problem doesn't lie in our ci pipeline, but both tools `volta` and `pnpm` don't behave in this case as they should.

I filed issues in both and added a fix to the pnpm problem.

https://github.com/pnpm/pnpm/issues/2202
https://github.com/volta-cli/volta/issues/622

As soon as the first of these two is fixed, we can close this issue.

**Comment by timsuchanek** [comment]
And the winner of our race is `pnpm` 🎉 

This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by mjyoung** [comment]
It worked! Although I had to `volta install prisma2@2.0.0-alpha.447`.

If I do `volta install prisma2@alpha` I get:
```
volta install prisma2@alpha --verbose
error: Could not parse version "alpha"

Please verify the intended version.
[verbose] Error cause: the given version requirement is invalid
Error details written to /Users/michaelyoung/.volta/log/volta-error-2019-12-11_11_09_52.763.log
[verbose] No custom hooks found
```

Anyway, specifying the exact version worked perfectly. Thank you so much for taking care of this so quickly.
