### ISSUE TITLE
Document multiple default(now()) restrictions

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#1062]
Based on: https://github.com/prisma/prisma2/issues/457

Apparently this is difficult to fix in Rust-land and is part of a larger refactor that we won't get to for MVPhoton, so we'll need to document this and perhaps offer a temporary error in `prisma-fmt`.

**Comment by nikolasburk** [comment]
Documented via: https://github.com/prisma/prisma2/pull/1164
