### ISSUE TITLE
[Introspection]  Error: Schema parsing

### ISSUE THREAD

**Issue by williamluke4** [prisma/prisma2#1067]
## Context
Currently, I'm using `prisma1` this was an attempt to introspect the DB  to upgrade to `prisma2`
- Postgresql 10.11 (Local/Docker)
- Ubuntu 19.04
- `prisma2@2.0.0-preview018`

## Command Run 
`prisma2 introspect`
## Error
```
Error: Schema parsing
error: Unexpected token. Expected one of: End of block ("}"), field declaration.
  -->  schema.prisma:10
   | 
 9 |   version                                                                       Int
10 |   _AccommVoucherToAccommVouchers_AccommVoucherTo_AccommVoucherToAccommVoucher_A _AccommVoucherToAccommVoucher[]      @relation("AccommVoucherTo_AccommVoucherToAccommVoucher_A", references: [A], onDelete: CASCADE)
   |   ^ Unexpected token.
11 |   _AccommVoucherToAccommVouchers_AccommVoucherTo_AccommVoucherToAccommVoucher_B _AccommVoucherToAccommVoucher[]      @relation("AccommVoucherTo_AccommVoucherToAccommVoucher_B", references: [B], onDelete: CASCADE)
   | 
    at Object.<anonymous> (/home/will/.nvm/versions/node/v11.15.0/lib/node_modules/prisma2/build/index.js:73435:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/will/.nvm/versions/node/v11.15.0/lib/node_modules/prisma2/build/index.js:73330:65)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by janpio** [comment]
Oh oh @williamluke4, can you maybe share your sql Schema or the relevant part of it so we can reproduce this? Thanks.

**Comment by williamluke4** [comment]
@janpio I just sent you the psql schema backup on Slack

**Comment by janpio** [comment]
Thanks, posted it internally to https://github.com/prisma/prisma2-private/issues/15 for @pantharshit00

**Comment by pantharshit00** [comment]
Some fields in your schema contains `_` at the beginning which currently is not supported.

**Comment by janpio** [comment]
Can you help @williamluke4 to fix his schema via Slack maybe @pantharshit00, please? It would be great to know if this indeed fixes his problems.

**Comment by pantharshit00** [comment]
It does indeed fixes it, I tried on a smaller model. But doing it on those many fields is tiring. We surely need to fix this on the introspection level itself because Prisma 1 heavily uses fields with `_` and I believe the schema the @williamluke4 shared is also bootstrapped by Prisma 1.

**Comment by williamluke4** [comment]
@pantharshit00 Yep that is correct, this is a `prisma1` project

**Comment by janpio** [comment]
Ok, the real solution here then is to support fields with non-alphanumeric characters. We will work on that as soon as possible. If this does not happen, we will adapt the Introspection in a way that the @map is added automatically to the schema.

**Comment by williamluke4** [comment]
@janpio Just tested this out using prisma2@**2.0.0-alpha.488** as prisma/prisma-engine#331 has been merged. But much to my dismay there is another issue. 
### Steps to Reproduce

1.  Use the prisma1 schema found here [prisma/prisma2-private#15](https://github.com/prisma/prisma2-private/issues/15)
2. Deploy it to a postgres db
3. Run `prisma2 introspect`


```
### Thoughts
In the log, it says `Table ChatRoomFromTrip not found` and indeed `ChatRoomFromTrip` is not in the database but `_ChatRoomFromTrip` is present. I would assume that the `_` has been removed at some point during the introspection?

### Log
```
Jan 06 18:59:45.426 DEBUG Introspect{url=UrlInput { url: "postgresql://prisma:prisma@localhost:5434/prisma?schema=API%24production" }}: sql_introspection_connector::calculate_datamodel: Found no corresponding foreign key    
Jan 06 18:59:45.426 DEBUG Introspect{url=UrlInput { url: "postgresql://prisma:prisma@localhost:5434/prisma?schema=API%24production" }}: sql_introspection_connector::calculate_datamodel: Handling column Column { name: "A", tpe: ColumnType { raw: "varchar", family: String, arity: Required }, default: None, auto_increment: false }    
Jan 06 18:59:45.426 DEBUG Introspect{url=UrlInput { url: "postgresql://prisma:prisma@localhost:5434/prisma?schema=API%24production" }}: sql_introspection_connector::calculate_datamodel: Calculating field type for 'A'    
Jan 06 18:59:45.426 DEBUG Introspect{url=UrlInput { url: "postgresql://prisma:prisma@localhost:5434/prisma?schema=API%24production" }}: sql_introspection_connector::calculate_datamodel: Found corresponding foreign key    
Jan 06 18:59:45.426 DEBUG Introspect{url=UrlInput { url: "postgresql://prisma:prisma@localhost:5434/prisma?schema=API%24production" }}: sql_introspection_connector::calculate_datamodel: Handling column Column { name: "B", tpe: ColumnType { raw: "varchar", family: String, arity: Required }, default: None, auto_increment: false }    
Jan 06 18:59:45.426 DEBUG Introspect{url=UrlInput { url: "postgresql://prisma:prisma@localhost:5434/prisma?schema=API%24production" }}: sql_introspection_connector::calculate_datamodel: Calculating field type for 'B'    
Jan 06 18:59:45.426 DEBUG Introspect{url=UrlInput { url: "postgresql://prisma:prisma@localhost:5434/prisma?schema=API%24production" }}: sql_introspection_connector::calculate_datamodel: Found corresponding foreign key    

{"message":"[src/libcore/result.rs:1165:5] called `Result::unwrap()` on an `Err` value: \"Table ChatRoomFromTrip not found\"","backtrace":"stack backtrace:\n   0: user_facing_errors::UnknownError::new_in_panic_hook\n   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   2: std::panicking::rust_panic_with_hook\n             at src/libstd/panicking.rs:468\n   3: std::panicking::continue_panic_fmt\n             at src/libstd/panicking.rs:373\n   4: rust_begin_unwind\n             at src/libstd/panicking.rs:302\n   5: core::panicking::panic_fmt\n             at src/libcore/panicking.rs:139\n   6: core::result::unwrap_failed\n             at src/libcore/result.rs:1165\n   7: sql_schema_describer::SqlSchema::table_bang\n   8: sql_introspection_connector::calculate_datamodel::calculate_model\n   9: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  10: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  11: tokio::runtime::enter::Enter::block_on\n  12: std::thread::local::LocalKey<T>::with\n  13: std::thread::local::LocalKey<T>::with\n  14: tokio::runtime::spawner::Spawner::enter\n  15: tokio::runtime::time::variant::with_default\n  16: std::thread::local::LocalKey<T>::with\n  17: <introspection_engine::rpc::RpcImpl as introspection_engine::rpc::rpc_impl_Rpc::gen_server::Rpc>::introspect\n  18: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call\n  19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll\n  20: futures::future::chain::Chain<A,B,C>::poll\n  21: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  22: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  23: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  24: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll\n  26: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll\n  27: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll\n  28: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  29: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll\n  30: futures::task_impl::Spawn<T>::poll_future_notify\n  31: std::panicking::try::do_call\n  32: __rust_maybe_catch_panic\n             at src/libpanic_unwind/lib.rs:78\n  33: tokio_threadpool::task::Task::run\n  34: tokio_threadpool::worker::Worker::run_task\n  35: tokio_threadpool::worker::Worker::run\n  36: tokio_reactor::with_default\n  37: tokio::runtime::threadpool::builder::Builder::build::{{closure}}\n  38: std::thread::local::LocalKey<T>::with\n  39: std::sys_common::backtrace::__rust_begin_short_backtrace\n  40: std::panicking::try::do_call\n  41: __rust_maybe_catch_panic\n             at src/libpanic_unwind/lib.rs:78\n  42: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  43: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942\n  44: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942\n      std::sys_common::thread::start_thread\n             at src/libstd/sys_common/thread.rs:13\n      std::sys::unix::thread::Thread::new::thread_start\n             at src/libstd/sys/unix/thread.rs:79\n  45: start_thread\n  46: __clone\n"}
```

**Comment by janpio** [comment]
Please create a new issue @williamluke4, as your original issue here has indeed been fixed. We will gladly look into your new problem then. Thanks.
