### ISSUE TITLE
Prisma 2 init with SQLite works but throws an error

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1085]
To reproduce: 

1. Run `prisma2 init`
1. Blank project -> SQLite -> TS/JS -> Just the Prisma schema

![image](https://user-images.githubusercontent.com/746482/70429905-e4c98b00-1a79-11ea-8353-c82a08b3f527.png)

Note that the command actually works i.e. prints out the blank project schema.

**Comment by pantharshit00** [comment]
This is still a problem in preview 18.1.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
