### ISSUE TITLE
Introspection panics on an empty database

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1087]
To reproduce, create a database (MySQL) on a server, try to introspect that in the init workflow. This makes init flow with new database not possible. 

![image](https://user-images.githubusercontent.com/746482/70446827-f9b81580-1a9d-11ea-9387-87f4f41399ea.png)

**Comment by janpio** [comment]
Did you supply the database in the form?

**Comment by divyenduz** [comment]
Yes

**Comment by pantharshit00** [comment]
It also happens with a non-empty database but with a different stack trace:
![image](https://user-images.githubusercontent.com/22195362/70459953-479f3e80-1adb-11ea-8944-dffe83b52fc4.png)

**Comment by do4gr** [comment]
This should be fixed by now.
