### ISSUE TITLE
Enable SQLite introspection in `prisma2 init`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1089]
Since this is now available on an engine level, this should also be available in the `init` flow of the CLI. Note that you can already use `prisma2 introspect url="file:dev.db"` to introspect an existing SQLite DB.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
