### ISSUE TITLE
CLI is not writing SSL option to the URL

### ISSUE THREAD

**Issue by bobsingor** [prisma/prisma2#109]
I tried connecting to my postgres DB on Heroku.

I am running: 
`prisma2 init`

Enter all the database information and check the box 'ssl enabled'

Then it says: ✔ Connected to database

Then in the next step: Select the schema you want to introspect
I am selecting a news schema and click "Introspect"

After this the initialization process stops.

When I run 

`prisma2 introspect`

I get the following error: 

`Error: no pg_hba.conf entry for host "82.81.221.43", user "xxx", database "xxx", SSL off`

Even though I checked the box SSL enabled.

**Comment by pantharshit00** [comment]
I was able to use to init flow and it introspected the Heroku postgres correctly.

However, I was unable to use the introspect command as right now there seems to be no way to enable SSL in the URL.

So can you please try the init flow again with the latest version of the prisma cli.

**Comment by cullophid** [comment]
I have a similar issue when trying to connect to a postgres db on render.com
I can run `prisma2 init` (requires ssl)
but after that `prisma2 lift` hangs indefinitely and `prisma2 introspect` returns:
Error: SSL/TLS required.

I have tried this on v 0.0.114 and 0.0.122.

schema.prisma:
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://reports_user:<PASSWORD>@postgres.render.com/reports?schema=public"
}

```

**Comment by pantharshit00** [comment]
Ref: https://github.com/prisma/prisma2/issues/134

This issue can now serve as a bug report for the CLI.

**Comment by timsuchanek** [comment]
Fixed in latest version.
