### ISSUE TITLE
Introspection improvement idea: Add native types as comments in generated Prisma schema

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1091]
The mapping from native DB types to Prisma types is very rough at the moment, i.e. we only have String, Int, Float, Boolean and DateTime as Prisma types. This means we're loosing a lot of type information in that mapping. 

While we don't support native DB types yet, we could still add the information which native DB type a certain field in the Prisma schema maps to as comments.

**Comment by janpio** [comment]
(Related: If you have a (or many!) good schema for testing these, please let me know via Slack please.)

**Comment by janpio** [comment]
Note from @do4gr: Everything is a string now. Will crash on writes when using the Query Engine (probably also on read).

**Comment by do4gr** [comment]
This is now implemented. Unsupported types will be commented out. They will be shown with the type information we get from the database.
