### ISSUE TITLE
Introspection panic on a non empty database

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1092]
Similar to #1087 

To reproduce, create a database (PostgreSQL), try to introspect that in the init workflow. 

![image](https://user-images.githubusercontent.com/22195362/70460823-35be9b00-1add-11ea-9a48-1303c6cfef70.png)

**Comment by janpio** [comment]
Can you please confirm this is still a problem with current `alpha` @pantharshit00?

**Comment by pantharshit00** [comment]
It works now in alpha. It was a bit slower but it works now.
