### ISSUE TITLE
Introspection documentation could mention `--url`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1094]
Currently https://github.com/prisma/prisma2/blob/master/docs/introspection.md does not mention the `--url` parameter that can be used to supply a connection string directly instead of needing a filled out `schema.prisma` file. 

Especially for users with an existing database (P1 users or similar), this can be a quick way to see what a Prisma schema file could look like.

**Comment by nikolasburk** [comment]
Added via https://github.com/prisma/prisma2/pull/1317
