### ISSUE TITLE
prisma init fails: Each model must have exactly one id criteria.

### ISSUE THREAD

**Issue by PeterDraex** [prisma/prisma2#1100]
I'm trying to generate prisma schema out of my MySQL schema.

Steps to reproduce:
1. Run `prisma2 init eshop-test`
2. Select *Blank project*
3. Select *MySQL*
4. Enter database details
Host: localhost
Port: 3306
Username: root
Password: (left empty)
Database name: (provided)
5. Long error is shown, which points to the following problems.

### 1. Database name is ignored

I think the first, but minor, problem is that even though I have provided database name, I'm asked again to select the database out of a list. This worked correctly in preview016.2.

### 2. Table without primary key: Error validating model

```
Schema parsing
error: Error validating model "alert_names": Each model must have 
exactly one id criteria. Either mark a single field with `@id` or add a multi field 
id criterion with `@@id([])` to the model..
  -->  schema.prisma:26
   |
25 |
26 | model alert_names {
27 |   key  String
   |
```

This is what the table looks like:
![image](https://user-images.githubusercontent.com/18402223/70535908-27649380-1b5e-11ea-919d-1288a460e6e6.png)

After checking, I discovered, that this table doesn't have a primary key. When I've added primary key, the problem with this table disappeard. 
I assume that this is desired behavior, but I think this deserves a clearer error message with instruction to add a primary key. 

### 3. Table with tinyint primary key fails: Error validating model
```
error: Error validating model "articles": Invalid ID field. ID field must be one of: Int @i
d or Int @id @default(`Integer`) for Int fields or String @id or String @id @default(`cuid(
)`|`uuid()`|`String`) for String fields..
  -->  schema.prisma:33
   |
32 |   created DateTime
33 |   id      Boolean  @id
34 | }
   |
```
This what the table looks like: 
![image](https://user-images.githubusercontent.com/18402223/70536904-e4a3bb00-1b5f-11ea-88b5-3d7ae1f715b5.png)

**Comment by pantharshit00** [comment]
Yes, I can confirm all of these.

> Table without primary key: Error validating model

Yes, this is known. More information here: https://github.com/prisma/prisma2/issues/1083


>  Table with tinyint primary key fails: Error validating model

This will supported once we have support for native database types. See #446 


So I would only keep this issue open for `#1`. If you have some time, please open a new issue just mentioning `#1`. That will save people from going over all of the other parts of this and we can close this one then.

**Comment by PeterDraex** [comment]
> please open a new issue just mentioning `#1`. That will save people from going over all of the other parts of this and we can close this one then.

Done. #1120

**Comment by pantharshit00** [comment]
Awesome. Thanks @PeterDraex 

Closing in favour of #1120

**Comment by janpio** [comment]
> This will supported once we have support for native database types. See #446

Small correction here: 
This has nothing to do with database types - we just have a bug that small tinyint fields are wrongly introspected as Boolean: https://github.com/prisma/prisma2/issues/1123
