### ISSUE TITLE
Invalid photon provider results in a silent error

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#1102]
When specifying an invalid value as a provider, it results in a silent failure:

```
generator photon {
	provider = "blubb"
}
```

<img width="430" alt="image" src="https://user-images.githubusercontent.com/5013932/70546411-88e12e00-1b6f-11ea-88b8-49f119dc19ed.png">

Verbose logging prints the error, but it should return without verbose logging with a non-zero exit code.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/5013932/70546477-a57d6600-1b6f-11ea-8464-3e02e2d832a2.png">

**Comment by divyenduz** [comment]
Candidate because low hanging

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
