### ISSUE TITLE
[Introspection] "created_at timestamp with time zone not null default now()" doesn't work

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#1104]
Many postgres schemas have something like:

```sql
    CREATE TABLE note(
        id serial PRIMARY KEY,
        created_at TIMESTAMP WITH TIME ZONE not null DEFAULT now()
    );
```

or

```sql
    CREATE TABLE note(
        note_id serial PRIMARY KEY,
        created_at TIMESTAMP WITH TIME ZONE not null DEFAULT CURRENT_TIMESTAMP
    );
```

I've talked to @do4gr and he says we handle this wrong:

```rust
let default = col.get("column_default").and_then(|param_value| {
    param_value
        .to_string()
        .map(|x| x.replace("\'", "").replace("::text", ""))
});
```

**Comment by janpio** [comment]
Can you provide an example what currently happens with tables like this @matthewmueller? Does it throw an error? Is the inferred model incorrect?

**Comment by pantharshit00** [comment]
Right now we just don't have a default value for such fields:
![image](https://user-images.githubusercontent.com/22195362/70997022-171e5c80-20fa-11ea-87d2-dc85bd0d0f23.png)

**Comment by janpio** [comment]
Next steps:
- Research what variants exist
- Create a table that has some/all of them
- Then see how this is introspected
- If something is wrong, fix it

**Comment by janpio** [comment]
Related to https://github.com/prisma/prisma2/issues/487

**Comment by danilofuchs** [comment]
Just in case another example is needed for testing, I created a simple schema in MySQL:
```sql
CREATE TABLE Todo (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  description VARCHAR(255),
  completedAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
```
The output schema.prisma:
```graphql
model Todo {
  completedAt DateTime?
  createdAt   DateTime
  description String?
  id          Int       @default(autoincrement()) @id
  updatedAt   DateTime
}
```
`@default` decorators are not being set to createdAt and updatedAt fields.

**Comment by janpio** [comment]
This should be fixed in the current `alpha` version now.

Can you try and confirm this behaves as expected @matthewmueller and @danilofuchs? Thanks.

**Comment by danilofuchs** [comment]
Yes, indeed!
OLD:
```prisma
model Todo {
  completedAt DateTime?
  createdAt   DateTime
  description String?
  id          Int       @default(autoincrement()) @id
  updatedAt   DateTime
}
```
**NEW:**
```prisma
model Todo {
  completedAt DateTime?
  createdAt   DateTime  @default(now())
  description String
  id          Int       @default(autoincrement()) @id
  updatedAt   DateTime  @default(now())
}
```
