### ISSUE TITLE
[Introspection] Use @map for problematic ENUM values

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1105]
- `Unexpected token. Expected one of: End of block ('}'), enum field declaration.`

--- 

sakila schema

```
"error: Unexpected token. Expected one of: End of block ('}'), enum field declaration.
  -->  schema.prisma:180
   | 
179 |   G
180 |   NC-17
   |     ^ Unexpected token.
181 |   PG
   | "
```

**Comment by danielweil** [comment]
This correctly creates the ENUM in the DB, but the Javascript object generated ignores the mapped name. Can someone look into this?
