### ISSUE TITLE
[Introspection] dot (and other non-[a-z0-9] characters) in field name

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1106]
e.g. Vanilla schema

**Comment by do4gr** [comment]
Let's define some of the terms a little bit more: 

Invalid character -> everything that does not match the regex `_a-zA-Z0-9`
Invalid at start of identifier -> everything that does not match the regex `a-zA-Z`

### Replacement strategy: 

Everything invalid before the first character valid for start of the the identifier gets dropped. 
Everything invalid after the first character valid for the start of the identifier gets replaced with `_`.

**Comment by janpio** [comment]
fixed via #1139
