### ISSUE TITLE
[Introspection] posts are turned into postses

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma2#1109]
This Postgres Schema
```sql
        create table if not exists users (
          id serial primary key not null,
          email text not null unique
        );
        create table if not exists posts (
          id serial primary key not null,
          user_id int not null references users (id) on update cascade,
          title text not null
        );
        insert into users ("email") values ('ada@prisma.io');
        insert into users ("email") values ('ema@prisma.io');
        insert into posts ("user_id", "title") values (1, 'A');
        insert into posts ("user_id", "title") values (1, 'B');
        insert into posts ("user_id", "title") values (2, 'C');
```

Is introspected as
```prisma
model posts {
  id      Int    @id @sequence(name: "posts_id_seq", allocationSize: 1, initialValue: 1)
  title   String
  user_id users
}

model users {
  email   String  @unique
  id      Int     @id @sequence(name: "users_id_seq", allocationSize: 1, initialValue: 1)
  postses posts[]
}
```

I would expect the `posts` field to still be called `posts` instead of `postses`.

**Comment by sorenbs** [comment]
@do4gr - can you please list the current rules for deciding field names during introspection. Do we have a spec?

**Comment by janpio** [comment]
@sorenbs See https://www.notion.so/prismaio/Naming-d0eb13ac0cbf4e2994e84728bc780c38#4d4fa8b0f3c64763a617962b69698db8

**Comment by sorenbs** [comment]
DECISION: We want to remove all pluralization from all aspects of Prisma.

We will launch Prisma Client without pluralization. In the future we might find a better way to introduce some convenience around this.

In this particular case, we will remove the second step of the current 3-step process for constructing back-relation names:

![image](https://user-images.githubusercontent.com/281337/74365788-0d9a3380-4dcf-11ea-96dd-6090b9f69d0b.png)
