### ISSUE TITLE
[Introspection] Remove @default from scalar lists

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1110]
- `Error parsing attribute "@default": Cannot set a default value on list field.` 
- `default-on-list` 
- `@default on a list type field (which is not supported)` 

---

Postgres, basic-blog:

```
Error: Schema parsing error: Error parsing attribute "@default": Cannot set a default value on list field..
  -->  schema.prisma:25
   | 
24 |   id      Int      @id @sequence(name: "posts_id_seq", allocationSize: 1, initialValue: 1)
25 |   tags    String[] @default("{}[]") @scalarList(strategy: EMBEDDED)
26 |   title   String
   | 
```

**Comment by BrenoMazieiro** [comment]
Is there any news about this feature?

**Comment by janpio** [comment]
What feature? This is a bug report about Introspection getting things wrong for @default of scalar lists - which is not possible. If you mean _that_ feature, it is being tracked at https://github.com/prisma/prisma/issues/8330

**Comment by BrenoMazieiro** [comment]
Thanks @janpio! "that" one it is! =)
