### ISSUE TITLE
[Introspection] ID = (Scalar, RelationField)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1112]
mix of https://github.com/prisma/prisma-engine/issues/253 and https://github.com/prisma/prisma-engine/issues/252

**Comment by mavilein** [comment]
@do4gr will check whether the guardrail is in place

**Comment by janpio** [comment]
Best next step: Create a SQL schema that has this problem: A compound Primary Key, where one of the columns, is also a Foreign Key (e.g. `id` + `user_id`)

**Comment by janpio** [comment]
Turns out we have a _lot_ of these in the Introspection CI schemas:
https://github.com/prisma/prisma2/issues/1681

**Comment by do4gr** [comment]
Closed via https://github.com/prisma/prisma-engines/pull/578
