### ISSUE TITLE
[Introspection] PrismaModels should be able to handle relation field as Id

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1115]
- `Invalid ID field. ID field must be one of: Int @id or Int @id @default(`Integer`) for Int fields or String @id or String @id @default(`cuid()`|`uuid()`|`String`) for String fields.`
- `format-of-id-on-relation`
- `@id field is model (which is not supported)`

--- 

```
error: Error validating model "atTopicSettings": Invalid ID field. ID field must be one of: Int @id or Int @id @default(`Integer`) for Int fields or String @id or String @id @default(`cuid()`|`uuid()`|`String`) for String fields..
  -->  schema.prisma:249
   | 
248 | model atTopicSettings {
249 |   akID                       AttributeKeys @id
250 |   akTopicAllowMultipleValues Boolean       @default(true)
   | 
```

Lined 249 is the problem

**Comment by bstro** [comment]
I am curious where this landed; is there any support for this functionality in `2.0.0-preview019` ?

**Comment by do4gr** [comment]
At the moment the functionality is not fully implemented. 

When Prisma spots a relation on a Primary key field during introspection it will currently ignore this relation. This is mentioned above as a guardrail to allow users to continue using the parts of their SQL schema that Prisma already has support for.

**Comment by janpio** [comment]
Please open a new issue about this @do4gr with a clean description, that also mentions our current guardrail. The bug and error message this issue was about is indeed fixed and this issue should be closed.

**Comment by janpio** [comment]
This should output a comment "next" to the field that is modified via the temporary guardrail.

**Comment by do4gr** [comment]
Closed via https://github.com/prisma/prisma-engines/pull/578
