### ISSUE TITLE
[Introspection] Flag to print schema file by ignoring errors

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1116]
Feature request based on this discussion: 
![image](https://user-images.githubusercontent.com/746482/70069170-a3585c00-15f1-11ea-890c-adf7ce3bc046.png)

Related issue: https://github.com/prisma/prisma-engine/issues/231

**Comment by janpio** [comment]
Will probably be built on https://github.com/prisma/prisma2/issues/1138 and https://github.com/prisma/prisma2/issues/1150. We need a better way to give the user an optimal experience, even if validation fails.

**Comment by janpio** [comment]
https://github.com/prisma/prisma2/issues/1138#issuecomment-587469465
