### ISSUE TITLE
[Introspection] Schema parser should collect all errors before failing

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1117]
Schema parser fails fast in some scenarios. See [these](https://www.notion.so/prismaio/shopware-da730f7228294f108ba65d22677659fe) introspection notes for example. 

It should collect all parsing errors and report them together. 

This might need some spec work.

**Comment by pantharshit00** [comment]
Using both candidate and product labels so that we can discuss exactly where this belongs.

**Comment by janpio** [comment]
The linked Notion page doesn't explain anything to me @divyenduz. Can you elaborate please?

**Comment by divyenduz** [comment]
Maybe similar to this: https://github.com/prisma/prisma2/issues/1097

**Comment by janpio** [comment]
Duplicate of https://github.com/prisma/prisma2/issues/1097
