### ISSUE TITLE
Report Introspection errors to Error Reporting Backend

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1124]
When an Introspection fails, we want to ask the user to report this to our Error Reporting Backend, similar to Migration Engine errors in Lift. 

This probably requires https://github.com/prisma/prisma-engine/issues/282 to be implemented.

**Comment by janpio** [comment]
From feedback from @do4gr it seems "Introspection" can actually fail in 4 levels:

1. introspection
2. validation
3. query engine schema generation
4. query engine runtime errors

As far as the CLI can differentiate these (e.g. because they are caused by different RPC calls), we should make sure we clearly include this information in the error package that is reported to the backend.

**Comment by janpio** [comment]
There could an advanced version, where we somehow ask the user for the original SQL schema export (instead of just what we get via https://github.com/prisma/prisma-engine/issues/282) as this might be different because of bugs in the describer. This could work by the user putting it in a specific location, being asked for it interactively in the CLI (where they then can paste it) or similar.

This is currently not part of this issue.

**Comment by timsuchanek** [comment]
Done in latest preview. The SQL Schema reporting is tracked separately.
