### ISSUE TITLE
DB Connection URL at Runtime

### ISSUE THREAD

**Issue by Keithcat767** [prisma/prisma2#1125]
Hello! 

I am working with Prisma2 and am loving it so far. I was trying to get it up and running on Platform.sh, however, the DB credentials for it are not available to me during the build hook, when the deploy process allows me to write to the filesystem. I was wondering if there is a way to have my generated Photon.js use an ENV variable or set a new DB connection URL at runtime, rather than when generate is run. Thanks for the help!

**Comment by pantharshit00** [comment]
Hello @Keithcat767 

You can set the datasource in the photon constructor itself.

For example, if you datasource is defined as following:
```prisma
datasource db {
  provider = "postgresql"
  url      = "postgresql://......"
}
```

You can set it like so in the photon constructor like so:
```js
const photon = new Photon({
  datasources: {
    db: "postgresql://....."
  }
})
```

**Comment by Keithcat767** [comment]
Hey @pantharshit00,

Awesome, this is exactly what I needed. Thanks!
