### ISSUE TITLE
Running `init hello-prisma` results in error due to React in cmd/power shell

### ISSUE THREAD

**Issue by joshuarobs** [prisma/prisma2#1130]
As soon as I enter a single letter in the 'Host' field, I get this error:

![!psh01](https://user-images.githubusercontent.com/52946881/70718404-41f86180-1d44-11ea-91d0-2ac7297bc171.png)

After I get the error, I obviously can't proceed on and have to exit with Control + C.

Full error:
````The above error occurred in one of your React components:
    in Unknown
    in div (created by Box)
    in Box
    in span (created by Color)
    in Color
    in Unknown (created by Step1PostgresCredentials)
    in div (created by Box)
    in Box (created by BorderBox)
    in div (created by Box)
    in Box (created by BorderBox)
    in BorderBox (created by Step1PostgresCredentials)
    in div (created by Box)
    in Box (created by Step1PostgresCredentials)
    in Step1PostgresCredentials
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
````

I got this error in WebStorm's terminal (command prompt, using Windows 10), and I also get it in PowerShell.

What's the cause of this? I find myself being unable to even do a hello world

**Comment by janpio** [comment]
What version of Prisma2 are you using? (`prisma2 -v` should tell you) If it is not `preview018.2` you might want to update to that and try again. If it still not works, please report back and we will investigate further.

**Comment by joshuarobs** [comment]
@janpio Updating to the latest version of prisma2 helped, thanks!

**Comment by janpio** [comment]
Yay 🚀
