### ISSUE TITLE
Do not print credentials into an introspected schema file

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1133]
For security, as printing them by default might make our users commit it into version control by mistake: 

Potential solutions: 

1. https://github.com/prisma/prisma2/issues/24
2. Render a warning after introspection/init flows to prompt the user (with a backing docs page)
3. Something else

**Comment by timsuchanek** [comment]
This is not relevant anymore, as the introspection by default reuses the current schema file. If that file already uses env vars, it will also reuse env vars.
