### ISSUE TITLE
ENV Variables with SQLite

### ISSUE THREAD

**Issue by jlarmstrongiv** [prisma/prisma2#1142]
I was trying out how the .env settings worked with schema.prisma.  

Setting the url of a sqlite database dynamically using an env variable does not work.
```
datasource sqlite {
  provider = "sqlite"
  url      = env("SQLITE_FILE")
  enabled  = true
}
```
That schema throws an error
```
Error:
Invalid `photon.()` invocation in /Users/jlarmst/Downloads/boombox/prisma/seed.js:5:36



undefined target="exit" timestamp="2019-12-14T22:53:34.018Z" fields={"message":"1"}
    at PhotonFetcher.<anonymous> (/Users/jlarmst/Downloads/boombox/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jlarmst/Downloads/boombox/node_modules/@prisma/photon/index.js:6:65)
(node:2244) UnhandledPromiseRejectionWarning: Error: undefined target="exit" timestamp="2019-12-14T22:53:34.018Z" fields={"message":"1"}
    at NodeEngine.engineReady (/Users/jlarmst/Downloads/boombox/node_modules/@prisma/photon/runtime/index.js:3533:23)
    at async /Users/jlarmst/Downloads/boombox/node_modules/@prisma/photon/runtime/index.js:3456:21
(node:2244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

However, defining two sqlite datasources with the enabled property set in the .env does work.  
```
datasource sqlite {
  provider = "sqlite"
  url      = "file:dev2.db"
  enabled  = env("SQLITE_ENABLED")
}
```
Note that the env has to be a boolean, or it crashes.  The [documentation](https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#using-environment-variables) shows setting the enabled env to the same url variable.  
```
Error

Error: Schema parsing
error: Expected a boolean value, but failed while parsing "file:./dev2.db": fail
ed to parse bool.
  -->  schema.prisma:8
   |
 7 |   url      = "file:dev.db"
 8 |   enabled  = env("SQLITE_URL")
 9 | }
   |
    at Object.<anonymous> (/Users/jlarmst/env/lib/node_modules/prisma2/build/ind
ex.js:74991:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jlarmst/env/lib/node_modules/prisma2/build/index.js:7488
6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by pantharshit00** [comment]
Can you please try this on alpha(`npm install -g prisma2@alpha`)? We recently have changed some behaviour regarding this: https://github.com/prisma/prisma-engine/pull/285

**Comment by jlarmstrongiv** [comment]
I tried installing the alpha, but I received incompatibility errors.

**Comment by jlarmstrongiv** [comment]
Installed the correct alphas:
prisma2 --version
prisma2@2.0.0-alpha.453, binary version: 7edae2b0fa48187478076e6515fce1968bc11096

Still received the errror
```
Error: Get config error: Expected a boolean value, but failed while parsing "file:dev2.db": failed to parse bool.
  -->  schema.prisma:10
   |
 9 |   url      = env("FILE")
10 |   enabled  = env("FILE")
11 | }
   |
```

**Comment by webnoob** [comment]
I can confirm that you need a bool value for enabled or it complains (on windows prisma preview 18.2)

My config:

```
datasource db {
  provider = "sqlite"
  url = env("SQLITE_URL")
  enabled = env("SQLITE_ENABLED")
}
```

That being said, I also get `Error: Cannot read property 'enabled' of undefined`

**Comment by pantharshit00** [comment]
Ok, docs do look off here. We either need to fix the docs or change the behaviour to match the docs.

**Comment by seawatts** [comment]
I am still getting the error from the original post. If I try to use `env("DATABASE_URL")` I get the same error.

```
Invalid `photon.()` invocation in /Users/jlarmst/Downloads/boombox/prisma/seed.js:5:36
```

**Comment by pantharshit00** [comment]
@seawatts I think you are running into https://github.com/prisma/photonjs/issues/318

Please make sure that the env variable that you are using is not empty.

**Comment by seawatts** [comment]
@pantharshit00 thanks you are right. Seems like it would be good to have better error logging there.

**Comment by janpio** [comment]
Please reconfirm @pantharshit00

**Comment by pantharshit00** [comment]
Yes, it is indeed fixed in preview019

**Comment by webnoob** [comment]
@pantharshit00 Can you just confirm what is fixed please? Will this now work:
```
datasource db {
  provider = "sqlite"
  url = env("SQLITE_URL")
  enabled = env("SQLITE_URL")
}
```
as the docs originally said?

**Comment by pantharshit00** [comment]
Yes, this should work now in preview019 :) . It will error in preview18.2 but the behaviour got fixed by this PR in the engine: https://github.com/prisma/prisma-engine/pull/285 and it is now available.

**Comment by webnoob** [comment]
Excellent, thanks for all your hard work.
