### ISSUE TITLE
Include with select does not work for findOne

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma2#1167]
When querying a DB with findOne and include like below, it does not work if I add select. I mean either select works or include works. Both do not work together.

**THIS DOES NOT WORK:**
```
const userObj = await db.userAuthentications.findOne({
        where: {
            username: username
        },
        select: {
            id: true,
            username: true,
            local: true,
            status: true,
            emails: true,
            metadata: true,
            password: true,
            mobiles: true
        },
        include: {
            emails: true,
            mobiles: true
        }
    });
```

It is not able to find all the properties within userObj in this case.

**THIS WORKS:**

```
const userObj = await db.userAuthentications.findOne({
        where: {
            username: username
        },
        include: {
            emails: true,
            mobiles: true
        }
    });
```

**THIS WORKS:**
```
const userObj = await db.userAuthentications.findOne({
        where: {
            username: username
        },
        select: {
            id: true,
            username: true,
            local: true,
            status: true,
            emails: true,
            metadata: true,
            password: true,
            mobiles: true
        }
    });
```

**Comment by yovanoc** [comment]
![image](https://user-images.githubusercontent.com/7302317/70989699-5b8f0580-20c4-11ea-8e9c-97f98a43501b.png)

It's written in the doc, that's a non-sense to have select and include together

**Comment by tvvignesh** [comment]
@yovanoc Thanks. @divyenduz clarified the same in slack. So, if I am to include a related schema, how do I select only the fields I require?

Also wondering, if both cannot be used together, why is there a need for include API at all? I mean, can't select do the job of include as well?

**Comment by yovanoc** [comment]
Yes, include is a shortcut for default fields + what you want to load. But you can only use select if you want. And in your case yeah, I think you just want to use select.

**Comment by tvvignesh** [comment]
@yovanoc In my case, I wanted to do both:
Select id, username, status, metadata, password from the main table and emails, mobiles from related tables. Would this usecase be satisfied? Cause from what I want, I don't want all columns from main table. But using include would get me all columns as I understand.

**Comment by yovanoc** [comment]
You already said that is it working, simply as that

![image](https://user-images.githubusercontent.com/7302317/70995317-8f702800-20d0-11ea-8662-a0b4769dcd81.png)

**Comment by tvvignesh** [comment]
@yovanoc Oh. Sorry for that. When I did that I did not get emails and mobiles field. It just runs. Does not return emails and mobiles fields. In other cases, the query itself fails.

**Comment by tvvignesh** [comment]
@yovanoc Let me verify once again on my end. Don't want to cause unnecessary confusion. Thanks a lot for your help.

**Comment by tvvignesh** [comment]
@yovanoc My bad. It does work with select alone. Will close this issue. Thanks.

**Comment by Kara-ipssi** [comment]
@tvvignesh  hello, 
you can do it like this :
`onst userObj = await db.userAuthentications.findOne({
        where: {
            username: username
        },
        select: {
            id: true,
            username: true,
            local: true,
            status: true,
            emails: true,
            metadata: true,
            password: true,
            mobiles: true,
            emails:{
                  id:true,
                  etc...
             }
        }
    });`
