### ISSUE TITLE
SDK's getGenerators resolves to a wrong version of the query-engine binary if `version` is omitted

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#1180]
The SDK's `getGenerators` function is used to generate Photon. It accepts an optional parameter called `version` which dictates which version of the query-engine binary would be used (read: downloaded) during Photon generation.

However, if `version` is omitted, then `getGenerator` defaults to downloading the `latest` query-engine binary. I believe it should download the binary pinned to the version of the photon generator in use.

The `version` param should either be required, or it should behave like an optional parameter, and resolve to the correct generator version.

The consequence of this is that binary pinning is rendered useless, and so breaking changes spread to any consumers(Studio & Prisma Labs as of now) without even updating the SDK. (issues like this: https://github.com/prisma/studio/issues/316)

Note that `prisma2 generate` is unaffected because it happens to always provide this `version` parameter.

Currently, the way to get around this is to manually always supply this `version` parameter (aka resolve it myself), but this should be handled inside the SDK IMO.

**Comment by Weakky** [comment]
Had a discussion with @timsuchanek. It seems like passing the `version` doesn't even fix the problem. Some work is definitely needed on sdk's side

**Comment by timsuchanek** [comment]
Fixed in latest version.
