### ISSUE TITLE
CLI init always reports that dependencies are installed via npm

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1191]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/22195362/71186300-ffcea300-22a2-11ea-8984-92c9284ef213.png">

CLI init always reports that it has installed the dependencies via npm even though if it has used yarn and created a yarn.lock file.
<img width="144" alt="image" src="https://user-images.githubusercontent.com/22195362/71186357-170d9080-22a3-11ea-8825-3a64489ac9d1.png">

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
