### ISSUE TITLE
`prisma dev` errors for postgres

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#12]
![image](https://user-images.githubusercontent.com/1567498/59600082-7fb35f00-9100-11e9-8f91-8c630eb6c6b0.png)

**Comment by mavilein** [comment]
This is not actionable right now.
The bug description by @schickling does not show the datasource configuration. Hence no reproduction is possible.
The description by @matthewmueller uses provider postgres with a file url. This should have been rejected at some point. The proper source validation is not implemented yet.

**Comment by liamdanielduffy** [comment]
@mavilein @schickling @timsuchanek 

Reproduction here: https://github.com/liamdanielduffy/prisma2-postgres-issue-repro

Steps are:
1) Make sure the docker image for postgres is available locally with `docker pull postgres`
2) In the root of the directory, run `yarn setup-db` or `npm run setup-db`
3) In the root of the directory, run `prisma2 dev`

**Comment by mavilein** [comment]
So the error indicates that the schema param is missing in the connection URL. E.g. this URL is not enough as of now:
> postgresql://postgres:password@localhost:5432/db

It would be have to be something like this:
> postgresql://postgres:password@localhost:5432/db?schema=my_schema

We could make this parameter optional and default to the public schema in this case. Does that change sound good?

**Comment by schickling** [comment]
Yes, I think that‘s a great suggestion @mavilein. 

@nikolasburk please make sure we also cover this accordingly in our docs.

**Comment by mavilein** [comment]
This got fixed in: https://github.com/prisma/prisma/commit/818accd4a177faadabdd2a501b0ae5d1dc92daf4
Will be available through tomorrows release.
