### ISSUE TITLE
[Introspection] Unexpected walls of text in `prisma2 introspect`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1200]
`prisma2 introspect --url="mysql://prisma:qd58rcCywPRS4Stk@mysql127-divy.cg7tbvsdqlrs.eu-central-1.rds.amazonaws.com:3306/Bench4" > foo.txt`

![image](https://user-images.githubusercontent.com/183673/71282579-2f42e580-235f-11ea-8c2e-d961a59a9d9e.png)

See a readable version in this file:
[error.log](https://github.com/prisma/prisma2/files/3989686/error.log)

```
λ prisma2 -v
prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038
```

**Comment by do4gr** [comment]
I tried with the current version and this does not happen anymore. Those are also debug statements, so are you sure you did not have a log level set via env var? 
```
$ prisma2 -v
prisma2@2.0.0-alpha.654, binary version: 1399c21167cd527e70f9a468a91efa077fa2c71d
```

**Comment by janpio** [comment]
I do not think so, but great we are rid of this. I also could not reproduce this any more, but had unrelated trouble: https://github.com/prisma/prisma2/issues/1452
