### ISSUE TITLE
prisma2 introspection failed -windows

### ISSUE THREAD

**Issue by rakeshrana15** [prisma/prisma2#1203]
encountered prisma2 introspection failed error with mysql db on windows.

Schema parsing
error: Error validating model "profile": Each model must have exactly one id criteria. Either mark a single field with @id or add a multi field id criterion with @@id([]) to the model.
--> schema.prisma:18
![prisma2 introspection failed](https://user-images.githubusercontent.com/20044916/71303315-1842d880-23dd-11ea-9332-735f6e67bfb7.png)

**Comment by janpio** [comment]
Thanks for reporting this issue @rakeshrana15.

Can you share the SQL schema of the database you were introspecting? (If you can not share it publicly, please see our instructions at https://github.com/prisma/prisma2/issues/757)

**Comment by rakeshrana15** [comment]
error is due to primary key not defined. We should handle this with a proper message rather than exception. 

Thanks for quick response.

**Comment by janpio** [comment]
Exactly, having your SQL schema would help us to build a proper mechanism that helps the user. I reopened this issue because of that and will close it when this solution is in place.

**Comment by divyenduz** [comment]
@rakeshrana15 : Would you be up for sharing your schema at `schemas@prisma.io`, if yes, please do. Note that we do sign an NDA if needed. 

I would close this issue though as we have a tracking issue for this here: https://github.com/prisma/prisma2/issues/1083 🙏
