### ISSUE TITLE
`Del`/`Entf` (DE) key does not work in `MySQL database credentials`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1210]
In the `MySQL database credentials` form of `prisma2 init` the `Entf` key of my German keyboard does not work, instead of removing the character right to the curser nothing happens.

**Comment by pantharshit00** [comment]
Can you please confirm this? I don't have a german keyboard. I am guessing that you are referring to the delete key. 

I can confirm though that delete key from my keyboard doesn't work I need to be sure they are the same.

**Comment by janpio** [comment]
As mentioned in the title, `Entf` and `Del` are the same key in theory. In practice I assume they are the same one, but do not know enough about keyboard layouts and key codes to be sure.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
