### ISSUE TITLE
automatic index generation is not implemented

### ISSUE THREAD

**Issue by smartnet-club** [prisma/prisma2#1214]
prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038

schema:
```
model Email {
  id        Int  @id
  address   String
}
```

generated:
```
export declare type EmailCreateWithoutContactInput = {
    id: number;
    address: string;
};

```

**id** parameter is **required** 

in version prisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7:
```
export declare type EmailCreateWithoutContactInput = {
    address: string;
};

```

**Comment by Hydrophonix** [comment]
automatic index generation for id Int was removed in last build.
https://github.com/prisma/prisma2/releases/tag/2.0.0-preview019

**Comment by pantharshit00** [comment]
Yes, you will need to add `@id @default(autoincrement())` in order to get sequences for your integer id fields.
