### ISSUE TITLE
running prisma2 dev in background

### ISSUE THREAD

**Issue by crimson-med** [prisma/prisma2#1215]
Hello working with prisma i found it very tedious to have the need of three commands in three terminals for launching my app:

```
docker-compose up
prisma2 dev
yarn dev
```

I am trying to run the command `prisma2 dev` in the background I have tried the following with no success:

```
prisma2 dev &
```

```
(prisma2 dev) &
```

This last one almost throws it to the background but then prisma2 hijacks the location

![Dec-23-2019 19-19-09](https://user-images.githubusercontent.com/28290546/71355158-2f3e2200-25b9-11ea-8423-90929c608a7d.gif)

How could I run it in background mode so that the window doesn't get hijacked and I can create a proper script for launching all needed commands.

**Comment by pantharshit00** [comment]
I can confirm this behaviour. I think it is not expected. 

For now, you can use `nohup` to write the output to a file instead of stdout as a workaround:
```sh
nohup prisma2 dev &
```

**Comment by crimson-med** [comment]
@pantharshit00 I have now created a shell script which handles prisma and yarn with pm2. But this still makes it difficult to read logs easily.

**Comment by pantharshit00** [comment]
Yes, I agree. We need to fix this behaviour.

**Comment by janpio** [comment]
Internal Note: Dropping from current sprint, and picking up later.

**Comment by timsuchanek** [comment]
As we removed the `prisma2 dev` command, I'm closing this.
