### ISSUE TITLE
`init`: Blank Project → Postgres → up/down flicker

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#1219]
**Steps to Reproduce**

`Prisma 2 Version: 2.0.0-preview019`

1. Setup

```
mkdir demo && cd demo
yarn init -y
yarn add prisma2
yarn prisma2 init
```

2. Select "Blank Project"
3. Select "PostgresSQL"
4. Use the up / down arrows

You'll notice a flicker. It appears we're logging something here.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
