### ISSUE TITLE
`init`: Blank Project → Postgres → typed out schema → broken url string

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#1222]
**Steps to Reproduce**

`Prisma 2 Version: 2.0.0-preview019`

1. Setup

```
mkdir demo && cd demo
yarn init -y
yarn add prisma2
yarn prisma2 init
```

2. Select "Blank Project"
3. Select "PostgresSQL"
4. Type out "postgresql://m@localhost:5432/prisma-demo?schema=public"
5. Select "Create new PostgreSQL schema"
6. Type "public"
7. Select "Typescript"
8. Select "Just the Prisma Schema"

You'll see a prisma schema with the following:

```prisma
datasource db {
  provider = "postgresql"
  url      = "postgresql://m@localhost:5432/prisma-demo?schema=public&s=&sc=&sch=&sche=&schem="
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

Notice the `postgresql://m@localhost:5432/prisma-demo?schema=public&s=&sc=&sch=&sche=&schem=`

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
