### ISSUE TITLE
Supporting Scalar Lists in Postgres

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma2#1236]
In reference to https://github.com/prisma/prisma2/issues/169

Noticed that Postgres does not currently have scalar lists support. Thought I would create an issue here for the same.

**Comment by pantharshit00** [comment]
Postgres does support them. It is just a bug in the extension that you are reporting. Lift successfully migrates the database.

See: https://github.com/prisma/vscode/issues/38
