### ISSUE TITLE
Just the schema option from the CLI init is creating an invalid schema

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1237]
Exact Steps:
1. prisma2 init
2. Blank Project
3. Sqlite
4. Select both photon and lift
5. Typescript
6. Just the schema

It is generating the following schema:
```prisma
datasource db {
  provider = "sqlite"
  url      = "sqlite://"
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

This schema has multiple problem:
1. SQLite uses the file protocol not the `sqlite://` protocol
2. `@id @unique` are not allowed together in preview019

**Comment by divyenduz** [comment]
Incorrect schema is fixed now https://github.com/prisma/prisma2/issues/1294
