### ISSUE TITLE
Unable to use DateTime along with nexus object

### ISSUE THREAD

**Issue by RobRuizR** [prisma/prisma2#1239]
I've got a model similar to this:

```prisma
model Person {
  name        String
  birthday    Datetime
}
```

I'm trying to create a Nexus object for it: 

```ts
export const Person = objectType({
  name: 'Person',
  definition(t) {
    t.model.name()
    t.model.birthday()  // Getting an error here
  },
})
```

This is the error I'm getting: 
> Property 'type' is missing in type '{}' but required in type '{ type: "ERROR: No subset types are available. Please make sure that one of your GraphQL type is a subset of your t.model('<ModelName>')"; }'

I'm using a PostgreSQL database with the graphql-auth prisma2 starter.

How can I fix this?

**Comment by PhilippSpo** [comment]
@RobRuizR Maybe you have a type in `Datetime` -> `DateTime`? Or just try to regenerate nexus/prisma2. Hope it helps 🤗.

**Comment by pantharshit00** [comment]
Yes, it is spelled as `DateTime`. `Datetime` is not recognised by our schema:
![image](https://user-images.githubusercontent.com/22195362/71980894-3581fe80-3247-11ea-9edb-25afef7f19fb.png)


I think you didn't deploy your schema after this update as the parser would also refuse to deploy this schema:
![image](https://user-images.githubusercontent.com/22195362/71980951-4e8aaf80-3247-11ea-9990-2994648c8afd.png)


So please fix this typo to get rid of the error :)
