### ISSUE TITLE
Questions with Prisma2 relations

### ISSUE THREAD

**Issue by Albert-Gao** [prisma/prisma2#1244]
```javascript
datasource db {
  provider = "postgresql"
  url      = "postgresql://AlbertGao@localhost:5432/teamingCloud"
  default  = true
}

generator photon {
  provider = "photonjs"
}

model User {
  id          String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  // 1:n
  selfOwnedCompany         Company[] @relation(name: "_UserToOwnedCompanies", references: [id, id])

  // m:n
  joinedCompanies       Company[] @relation(name: "_UserToJoinedCompanies", references: [id, id]) 
  joinedProjects           Project[] @relation(name: "_UserToJoinedProjects", references: [id, id])
}

model Company {
  id        String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  // 1:n
  creator   User @relation(name: "_UserToOwnedCompanies", references: [id, id])
  projects     Project[] @relation(name: "_CompanyToProjects", references: [id, id])

  // m:n
  users     User[] @relation(name: "_UserToJoinedCompanies", references: [id, id])
}

model Project {
  id          String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  // 1:n
  company     Company @relation(name: "_CompanyToProjects", references: [id, id]) 

  // m:n
  users User[] @relation(name: "_UserToJoinedProjects", references: [id, id])
}
```

So, what's happening here:

## model User
1. A user can create multiple companies (1:n)
1. A user can join multiple companies (m:n)
1. A user can join multiple projects (m:n)

## model Company
1. A company can have one creator(create the company) (1:n)
1. A company can have multiple projects (1:n)
1. A company can have multiple users (join the company) (m:n)

## model Project
1. A project can belong to only 1 company (1:n)
1. A project can have multiple users (join the project) (m:n)

## Error when running `prisma2 dev`
```bash
AlbertGao@Albert-LottoNZ-Laptop now % DEBUG=* prisma2 dev
  download Skipping download as /Users/AlbertGao/.nvm/versions/node/v13.2.0/lib/node_modules/prisma2/download-done exists +0ms
  engineCommands getConfig, override prismaPath = undefined +0ms
  getos { platform: 'darwin', libssl: undefined } +0ms
Error: Error: Get config SyntaxError: Unexpected token P in JSON at position 0
    at Object.<anonymous> (/Users/AlbertGao/.nvm/versions/node/v13.2.0/lib/node_modules/prisma2/build/index.js:73808:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/AlbertGao/.nvm/versions/node/v13.2.0/lib/node_modules/prisma2/build/index.js:73659:58)
AlbertGao@Albert-LottoNZ-Laptop now % 
```

## Questions:
1. ~How to fix the error~
1. Anything I did wrong here? Did I decalre the relations with a non-Prisma2 way?
1. The `m:n relation`. For example. `User.joinedCompanies` and has a `Company.users`, they both have a `@relation(name: "_UserToJoinedCompanies", references: [id, id])`, the 2 `id` here, which one is which?
1. Ideally, I want to have a `UserToCompany` table, and have an extra `isCreator` field to determine if it is a create-company record or a join-company record, how to do that?

**Comment by Albert-Gao** [comment]
The error is here: `at Object.<anonymous> (/Users/AlbertGao/.nvm/versions/node/v13.2.0/lib/node_modules/prisma2/build/index.js:73810:19)`

in the `getConfig()`. there is one line: `return JSON.parse(result.stdout);`

It causes problem in this case because the vaiue of `result.stdout` in this case is not a JSON strinf but a string: `Please wait until the 'prisma query-engine' download completes!`

**Comment by matthewmueller** [comment]
Thanks for posting this @Albert-Gao,  you're doing it correctly, though it surely feels wrong 😅

**2. Anything I did wrong here? Did I decalre the relations with a non-Prisma2 way?**

The fact that you're asking this question, means we have some work to do. Ideally, you could declare your relations like this:

```prisma
model User {
  id String @id @default(cuid())

  // 1:n
  ownedCompanies Company[]

  // m:n
  joinedCompanies Company[]
  joinedProjects  Project[]
}

model Company {
  id String @id @default(cuid())

  // 1:n
  creator  User
  projects Project[]

  // m:n
  users User[]
}

model Project {
  id String @id @default(cuid())

  // 1:n
  company Company[]

  // m:n
  users User[]
}
```

This is not currently possible, our IDE support does a nice job of pointing this out:

<img width="666" alt="Screen Shot 2019-12-30 at 3 47 40 PM" src="https://user-images.githubusercontent.com/170299/71586827-ca844980-2b1b-11ea-910f-af53f892cf6d.png">
<img width="665" alt="Screen Shot 2019-12-30 at 3 47 45 PM" src="https://user-images.githubusercontent.com/170299/71586829-ca844980-2b1b-11ea-8aa9-3d1f5d611463.png">

Quick solutions that come to my mind:

- fix it so back-relations don't need to be disambiguated
- remove back-relations
- require join tables

@mavilein @sorenbs anything we can do here to clean this up?

**3. The m:n relation [...]**

Agreed, `[id, id]` is not ideal and related to the questions above.

**4. ideally i can have `UserToCompany` [...]**

Explicit join tables should be possible soon. @mavilein @sorenbs do we know when?

**Comment by TeamingCloud** [comment]
Thanks :) That means the doc is doing a great job :D

The only question is, `_UserToOwnedCompanies` is not being created:

![image](https://user-images.githubusercontent.com/58796091/71607199-3f09c780-2bb2-11ea-87a2-6bc8458b43c3.png)

Is this right?

**Comment by Albert-Gao** [comment]
Thanks :) That means the doc is doing a great job :D

The only question is, `_UserToOwnedCompanies` is not being created:

![image](https://user-images.githubusercontent.com/58796091/71607199-3f09c780-2bb2-11ea-87a2-6bc8458b43c3.png)

Is this right?

**Comment by pantharshit00** [comment]
> 1. Error: Get config SyntaxError: Unexpected token P in JSON

Yes, I have seen this. It occurs when the binary is partially downloaded. See https://github.com/prisma/prisma2/issues/1232#issuecomment-569090211

@Albert-Gao Can you please paste the schema after you have made the changes so that we can review. I guess the above one is outdated now.

**Comment by Albert-Gao** [comment]
I send my schema to the schema@prisma.io haha

I didn't make many changes as I am working on the FE part, just added the missing part of my schema, 

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DB_URL")

  default  = true
}

generator photon {
  provider = "photonjs"
}

model User {
  id          String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  nickName        String
  email           String    @unique
  isEmailVerified Boolean   @default(false)
  password        String
  googleId        String    @default("")

  // 1:n
  ownedCompanies         Company[] @relation(name: "_UserToOwnedCompanies", references: [id, id])

  // m:n
  joinedCompanies       Company[] @relation(name: "_UserToJoinedCompanies", references: [id, id]) 
  joinedProjects        Project[] @relation(name: "_UserToJoinedProjects", references: [id, id])
}

model Company {
  id        String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  name      String
  description      String   @default("")
  logoUrl      String   @default("")

  // 1:n
  creator   User @relation(name: "_UserToOwnedCompanies", references: [id, id])
  projects     Project[] @relation(name: "_CompanyToProjects", references: [id, id])

  // m:n
  users     User[] @relation(name: "_UserToJoinedCompanies", references: [id, id])
}

model Project {
  id          String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  name      String
  description      String   @default("")
  logoUrl      String   @default("")

  // 1:n
  company     Company @relation(name: "_CompanyToProjects", references: [id, id]) 

  // m:n
  users User[] @relation(name: "_UserToJoinedProjects", references: [id, id])
}
```

Still, the `_UserToOwnedCompanies ` is not there after initialization, haven't play around it to see what happens at runtime.

**Comment by pantharshit00** [comment]
First of all `references:[id, id]` is incorrect. You cannot refer to the same field twice. Replace it with `references: [id]`

> Still, the _UserToOwnedCompanies is not thereafter initialization, haven't play around it to see what happens at runtime.

This is expected. This related is 1:m relation or one to many relations. It doesn't require a join table. It is maintained using a column in the` side of the relation where many rows can refer to a single row and it is aggregated using those row while querying. Join tables are created only when the relation is m:n ie Many to Many in where either side can refer to each other multiple times. In that case, we can't create a column to either side to track the relation because a column can't store more than one value very efficiently, so we use a join table.

**Comment by pantharshit00** [comment]
I am closing this now, feel free to comment if you feel this is not resolved.
