### ISSUE TITLE
CLI tries to download npm packages using `npm add`

### ISSUE THREAD

**Issue by thecodeah** [prisma/prisma2#1247]
https://github.com/prisma/prisma2/blob/34f5e82d201fc5ceaad6041bf670838161188f1b/cli/sdk/src/predefinedGeneratorResolvers.ts#L88-L90

It tries to download packages using `npm add` even though npm packages are installed using `npm install`

**Comment by timsuchanek** [comment]
`npm add` is an alias for `npm install` https://docs.npmjs.com/cli/install, did this still break for you?

**Comment by janpio** [comment]
@pantharshit00 Did you confirm that this breaks something?

**Comment by pantharshit00** [comment]
My bad here. I wasn't aware that `npm add` was an alias to `npm install` and I have yarn installed on my machine so I didn't encounter it.

We can close this.
