### ISSUE TITLE
 The current connector does not support lists of primitive types

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [prisma/prisma2#1251]
Hello! this is my schema, im using prisma2@alpha version:

```
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photonjs"
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean @default(true)
  title     String
  content   String?
  author    User?
  dataType String
  materialType String
  imaginaryPartX Float[]   
  imaginaryPartY Float[]  
  dfImaginaryPartX Float[] 
  dfImaginaryPartY Float[] 
  dfRealPartX Float[]   
  dfRealPartY Float[]  
}

model User {
  id       String  @default(cuid()) @id
  email    String  @unique
  password String
  name     String?
  posts    Post[]
}
```

 and is given me this error:

> Field "imaginaryPartX" in model "Post" can't be a list. The current connector does not support lists of primitive types.

**Comment by GolfredoPerezFernandez** [comment]
help please

**Comment by pantharshit00** [comment]
Hello,

We have dropped support for scalar list(for example `String[]` or `Float[]`) for the connectors that don't support it.
The only connector that supports scalar lists is postgres so please use that now or change those to a relation and manually resolve them.

You can follow this upgrade guide: https://github.com/prisma/prisma2/blob/master/docs/upgrade-guides/upgrading-to-preview019.md

**Comment by virajshitole** [comment]
i am also getting this error

**Comment by lebonMIA** [comment]
I don't know if it's the right place to post but I'm also facing this error.
I  understand that scalar list are only available on supported connectors (I'm using sqlite).
Right, but scalar list is a pretty common requirement in a database model so how should we deal with this problem ? The documentation does not say much about it, (implicitly says "migrate to a supported connector".)

**Comment by DestroyerXyz** [comment]
> You can follow this upgrade guide: [prisma/prisma2@`master`/docs/upgrade-guides/upgrading-to-preview019.md](https://github.com/prisma/prisma2/blob/master/docs/upgrade-guides/upgrading-to-preview019.md?rgh-link-date=2020-01-06T13%3A18%3A18Z)

For anyone here in the future, a working link to this file: https://github.com/prisma/prisma/blob/ba74c81fdbc9e6405946fdc6f9d42d103d008dc2/docs/upgrade-guides/upgrading-to-preview019.md

**Comment by joshbedo** [comment]
so whats the solutions for this?

**Comment by janpio** [comment]
Use a recent version of Prisma, and it should work as documented.
If it does not, please open a new discussion or bug report issue and provide all the information the template asks for.

**Comment by chad-vanmark** [comment]
Getting this same error in version 5.17.0

model Product {
  productId         String @id
  categories        String[]
  imageUrl          String
  thumbnailUrl    String
  previousHash   String
  hash                 String
}

**Comment by akshayparkad** [comment]
same issue in prisma 5.19.1

**Comment by Nepmine** [comment]
> Use a recent version of Prisma, and it should work as documented. If it does not, please open a new discussion or bug report issue and provide all the information the template asks for.

Not working in the current version [6.5.0]
