### ISSUE TITLE
Cannot do an `in` query when the field is an Enum

### ISSUE THREAD

**Issue by abhiaiyer91** [prisma/prisma2#1254]
I have a data model that looks like this:

```
enum PermissionName {
    CONTRIBUTOR
    OWNER
}

model Doc {
    id           String            @default(uuid()) @id
    name         PermissionName
}
```

I'm trying to query this like so:

```
const doc = await photon.doc.findMany({
      where: {
        name: {
          in: ["OWNER", "CONTRIBUTOR"],
        }
      },
    })
```

The generated client does not have filter options for PermissionNameFilter.

**Comment by malekjaroslav** [comment]
Duplicate: https://github.com/prisma/photonjs/issues/361

**Comment by pantharshit00** [comment]
Closing as a duplicate of prisma/photonjs#361. Thanks for reporting though 🙏
