### ISSUE TITLE
[Introspection] Duplicate back relation on multi-field relation

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1264]
```
mysql_127/Basketball_men_stderr.log,"error: Error validating model 'series_post': Wrongly named relation detected. The fields `tmIDLoser` and `year` in model `series_post` both use the same relation name. Please provide different relation names for them through `@relation(<name>).",unknown-pattern
```

Internal note: https://github.com/prisma/introspection-engine-output/blob/master/mysql_127/Basketball_men_stderr.log#L58-L62

**Comment by pantharshit00** [comment]
I am unsure how I can triage this. I can't find the related schema.

**Comment by divyenduz** [comment]
Do you have access to this "internal note" repo? If no, I will provide you the schema in DM. This is confirmed via the introspection analysis though.

**Comment by janpio** [comment]
No need to spend time on this for you @pantharshit00

**Comment by janpio** [comment]
I could not find current occurrences of this any more, so it was probably solved. @do4gr?
