### ISSUE TITLE
Prisma in Cluster

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#1267]
Hello, since prisma alpha 480 I can't use Prisma2 in a clustered server.

![image](https://user-images.githubusercontent.com/7302317/71720908-85b22880-2e23-11ea-80e7-d05ff976eb06.png)

**Comment by janpio** [comment]
Ping @tomhoule

**Comment by yovanoc** [comment]
Oh, I have the same issue in plain "normal" project too, is not related to clutering.

**Comment by yovanoc** [comment]
Nevermind. My domain has just changed his registrar
