### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by lglie** [prisma/prisma2#1270]
init error:
![image](https://user-images.githubusercontent.com/931410/71773879-0ac24c80-2fa0-11ea-896c-8414b77135fe.png)

**Comment by sachaw** [comment]
Same Issue, OS Windows 10, have tried a clean install

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/1232#issuecomment-569090211
