### ISSUE TITLE
Can't go to database connection after connecting to database

### ISSUE THREAD

**Issue by huv1k** [prisma/prisma2#1275]
In CLI it's not possible to go back to connection step in `init` flow to change the name of a database or other information provided.

![](https://i.imgur.com/RHY54jL.gif)

**Version:** `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a03`

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #723
