### ISSUE TITLE
Error reporting zip and MacOS catalina

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1279]
The error reports that we upload as a part of the `prisma2` CLI are not working on MacOS catalina. An attempt to unzip them yields: 

![image](https://user-images.githubusercontent.com/746482/71820061-3b80af80-308e-11ea-9892-4e3c2549197f.png)

**Comment by pantharshit00** [comment]
Closing as duplicate of #1000

**Comment by divyenduz** [comment]
@pantharshit00 thanks, marking the duplicate as a candidate, you missed that bit :)
