### ISSUE TITLE
Init quits after introspecting - Postres

### ISSUE THREAD

**Issue by timmushen** [prisma/prisma2#128]
prisma2@0.0.122

Using primsa2 init, the prompt quits after the introspection step. This occurred while creating a new schema and connecting to a current.  

I believe the next step is to select a boilerplate? This may have been removed?

**Comment by nikolasburk** [comment]
Hey @timmushen, thanks a lot for opening this issue. If I understand correctly, this is a duplicate of #73 so I'll close this one in favor of that issue.

Please let me know if that's not the case and we'll reopen this one 🙂

**Comment by timmushen** [comment]
👍 Yup 😄 

Missed that one reviewing before I submitted.
