### ISSUE TITLE
Certificate identity files are required in both prisma folder and in the folder from which lift is executed

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1286]
My folder structure is the following:
```
.
├── prisma
│   ├── migrations
│   │   ├── 20200107210356-init
│   │   └── lift.lock
│   └── schema.prisma
├── server-cert.pem
└── client-identity.p12
```

my connection string is `postgresql://postgres:<REDACTED>@<REDACTED>:5432/postgres?schema=public&sslmode=require&sslcert=server-ca.pem&sslidentity=client-identity.p12&sslpassword=<REDACTED>`

Now when I execute prisma2 lift save it ran into the following I/O error:
![image](https://user-images.githubusercontent.com/22195362/71907811-cb0f8680-3192-11ea-8546-f4b856f0dc12.png)

Which is unexpected as the file is in the directory according to the path. 

Now as a temporary workaround you can copy the `server-cert.pem` and `client-identity.p12` to prisma folder and run all prisma command from that directory or maintain two copies of keys one in root and one in prisma folder.

I will like the cli to resolve paths relative to cwd and not to `prisma` folder.

**Comment by pantharshit00** [comment]
Not opening it in the lift repo as it also affects photon.

Photon also requires them to be in the prisma folder otherwise it throws our infamous Undefined target="exit" error:
![image](https://user-images.githubusercontent.com/22195362/71908477-1aa28200-3194-11ea-8f6d-1198675da2b8.png)

**Comment by divyenduz** [comment]
@pantharshit00 Since #357 is fixed, can you please try this again and see what the actual error is with Photon on this? Thanks.

**Comment by pantharshit00** [comment]
It is totally unrelated to #357. It is about resolution of ssl identity files by our engine.

**Comment by divyenduz** [comment]
Yes, can you please list the actual error message from photon?

**Comment by pantharshit00** [comment]
Actual error from photon:
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/22195362/72204598-ebe02080-349f-11ea-937c-2213ea99157d.png">


```
(node:93965) UnhandledPromiseRejectionWarning: Error: undefined timestamp="2001-01-11T12:56:15.185Z" target="mobc" fields={"message":"mobc failed to connect: IoError(Os { code: 2, kind: NotFound, message: \"No such file or directory\" })","log.target":"mobc","log.module_path":"mobc","log.file":"/root/.cargo/registry/src/github.com-1ecc6299db9ec823/mobc-0.3.2/src/lib.rs","log.line":455}
    at NodeEngine.engineReady (/Users/harshit/code/reproductions/issue-1228/node_modules/@prisma/photon/runtime/index.js:3545:23)
    at async /Users/harshit/code/reproductions/issue-1228/node_modules/@prisma/photon/runtime/index.js:3468:21
(node:93965) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:93965) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by divyenduz** [comment]
@pantharshit00 Looks like it is unable to read the certificate file, can you please try this with an absolute path to the certificate file?

**Comment by pantharshit00** [comment]
It works when it is in both `prisma` directory and `root` directory. Abosulte path also works.

**Comment by janpio** [comment]
Open questions:
Does this affect other stuff than migrate?

**Comment by pantharshit00** [comment]
Yes, it also affects prisma client as it also uses the same connection string and it is also unable to resolve without having identity files in both folders.

**Comment by Jolg42** [comment]
So we don't need to implement anything as we already do this in the code:
```
    this.engineConfig = {
      cwd: engineConfig.cwd || path.resolve(__dirname, "../../../prisma"),
```

That means that in your case you can use a relative path.
Example, my certificate is in the root folder, I have a prisma/schema.prisma with `postgresql://postgres:<REDACTED>@<REDACTED>:5432/postgres?schema=public&sslmode=require&sslcert=../server-ca.pem&sslidentity=../client-identity.p12&sslpassword=<REDACTED>`

You need to provide `../client-identity.p12` and `../server-ca.pem` relative to the prisma.schema here.

**Comment by Jolg42** [comment]
It works the same way in a `.env` file.

**Comment by pantharshit00** [comment]
We need to add this to the docs @nikolasburk
