### ISSUE TITLE
Photon crash when url doesn't connect to the right provider

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma2#1292]
## Description

Given the following datasource

```prisma
datasource db {
  provider = "sqlite"
  url      = "postgres://postgres:postgres@localhost:5432/testing?schema=test_7noov123fsdl"
}
```

Nothing will go wrong until I try to query something with Photon and it crashes

**Comment by pantharshit00** [comment]
Possible duplicate of https://github.com/prisma/prisma2/issues/1096

It should crash at the migration step. Crash on photon side is expected as you are providing a wrong url.

**Comment by divyenduz** [comment]
Closing this as a duplicate of #1096 as it is already in the milestone. If you think that this issue is different @Weakky, please feel free to reopen it and tag me.

**Comment by janpio** [comment]
Yeah, duplicate and as per https://github.com/prisma/prisma2/issues/1096#issuecomment-572051430 this should now at least return an error again.
