### ISSUE TITLE
Prisma 2 init produces incorrect schema

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1294]
Preview 19

Init - SQLite - Just the Prisma schema

All schemas: The schema contains @id and @unique together, which is incorrect. 

SQLite: The DB URL field is missing the DB name.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
