### ISSUE TITLE
prisma2@2.0.0-preview019 hang on "Preparing your database"

### ISSUE THREAD

**Issue by onecer** [prisma/prisma2#1298]
ENV:
prisma2:  2.0.0-preview019
system:  Deepin Linux 15.11
npm:  6.12.4
node:  v10.16.3
mysql: 5.7

When I try to create a new project.Follow this step
1. `prisma2 init test-server`
2. ` > Blank priject`
3. `> MySQL`
4. `Input db information`
5. `> Use Exists database` Empty Database
6. `> demo project`

than I suck on 
```
✔  Downloading the demo script from GitHub ...
✔  Extracting content to zeitgeber-server ...
✔  Installing dependencies with: `npm install` ...
⠧  Preparing your database ...
```
at now have been an hour a ago.

I try this step on other machine got the same results.

**Comment by onecer** [comment]
Centos：7
node: v12.13.0
npm: 6.13.6

Got the same result.

```
[root@xersoft ~]# prisma2 init test-server

Preparing your starter kit: GraphQL API (+ Auth)

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to test-server ...
✔  Installing dependencies with: `npm install` ...
⠏  Preparing your database ...
5  Seeding your database with: `npm run seed` ...

```

**Comment by pantharshit00** [comment]
I am actually able to reproduce this on CentOS 7 on digitalocean with a local mysql server setup within the box but not on locally on macOS.

I ran the command in debug mode and looks like somehow we are sending an invalid database name in CentOS (or basically or rhel based binaries)
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/22195362/72222747-51aad600-358e-11ea-95e9-af44ef1d3b43.png">

(Error report id 1122 for internal use)

**Comment by pantharshit00** [comment]
Looks like this reoccurrence of #778. 

On CentOS the cli is not printing the database name to the schema:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/22195362/72222805-da297680-358e-11ea-9a2a-35e18fa157cb.png">

The workaround here would manually add it and run the script. On macOS it prints it correctly.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
