### ISSUE TITLE
[Introspection] Different order of ENUMs when introspecting Postgres DB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1303]
When introspecting the same Postgres DB, the found ENUMs are sometimes returned in different orders which leads to diffs like this:

https://github.com/prisma/introspection-engine-output/commit/40fbdf6235204a209c9b7e34b99009f0135a2889#diff-c4afa267928e1af8a66e5a825f013d50

**Comment by divyenduz** [comment]
I did note this once, at any layer in the introspection (SQL response set or rust array that handles it), it could be that the result order is ambiguous. 

SQL result set's order is not guaranteed without an order by, probably this is that.

**Comment by divyenduz** [comment]
Maybe this: https://github.com/prisma/prisma-engine/blob/a8da337aac05d40da968e657bfdee398f2bee651/libs/sql-schema-describer/src/postgres.rs#L488-L492

**Comment by pantharshit00** [comment]
Not sure if I should mark this as a bug as this doesn't break the tool. Marking it as repro available for now.
