### ISSUE TITLE
I cant deploy to zeit now

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [prisma/prisma2#1307]
Hello im trying to deploy graphql-auth example to zeit now platform but is given me this error: 

 Changelog: https://github.com/zeit/now/releases/tag/now@17.0.0-canary.3
> Deploying ~\Documents\modern-apps\lightmatter\backend2 under golfredopf
> Using project express-photon
> NOTE: To deploy to production (express-photon-blond-iota.now.sh), run `now --prod`
> https://express-photon-b8wq0blvi.now.sh [2s]
> Error! Build failed
> Error! Check your logs at https://express-photon-b8wq0blvi.now.sh/_logs or run `now logs https://express-photon-b8wq0blvi.now.sh`

after use:

now -b POSTGRESQL_URL=@postgresql_url -e POSTGRESQL_URL=@postgresql_url

**Comment by xero0001** [comment]
Hello, what's written in that logs

https://express-photon-b8wq0blvi.now.sh

I think you should check them and show us.

**Comment by GolfredoPerezFernandez** [comment]
This is the error :D ..

> graphql-auth@ postinstall /zeit/100f4e5b
--
08:25:25 AM | > npm -s run generate
08:25:28 AM | Generating Photon.js to ./node_modules/@prisma/photon
08:25:31 AM | Done in 3.40s
08:25:33 AM | npm WARN graphql-auth@ No repository field.
08:25:33 AM | added 430 packages from 348 contributors in 24.438s
08:25:33 AM | Running "npm run build"
08:25:33 AM | > graphql-auth@ build /zeit/100f4e5b
08:25:33 AM | > npm -s run clean && npm -s run generate && tsc
08:25:36 AM | Generating Photon.js to ./node_modules/@prisma/photon
08:25:40 AM | Done in 3.99s
08:25:44 AM | Error: No output directory named "public" found.
08:25:44 AM | More details: https://zeit.co/docs/v2/platform/frequently-asked-questions#missing-public-directory
08:25:44 AM | at validateDistDir (/zeit/569c8a01f40bdc4f/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:132:15)
08:25:44 AM | at Object.build (/zeit/569c8a01f40bdc4f/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:374:13)
08:25:44 AM | at <anonymous>
08:25:44 AM | at process._tickDomainCallback (internal/process/next_tick.js:228:7)
08:25:45 AM | worker exited with code 20 and signal null
08:25:47 AM | done

**Comment by xero0001** [comment]
Have you setup now.json file?

```
{
  "name": "app-name",
  "version": 2,
  "builds": [
    {
      "src": "src/server.ts",
      "use": "@now/node@canary"
    }
  ],
  "routes": [
    {
      "src": "/",
      "dest": "src/server.ts"
    },
  ],
  "env": {
     ...
  },
  "regions": ["icn1", "hnd1"]
}

```
This is my now.json file. I placed it on the root directory.

You can change name, routes, env, regions.

**Comment by GolfredoPerezFernandez** [comment]
thanks that solved the issue... now im have another problem.. :/ .. when i try to fetch something from frontend i get:

Access to fetch at 'https://app-name.golfredopf.now.sh/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by pantharshit00** [comment]
Hi,

This is a CORS issue that can be fixed by using cors module on your server. For more information, read: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

For GraphQL auth example which uses graphql yoga, you can use the cors option bult in to GraphQL Yoga: https://github.com/prisma-labs/graphql-yoga#startoptions-options-callback-options-options--void----null-promisevoid

This is unrelated to Prisma now so I am going to close this, but feel free to reply here if you need any help.

**Comment by GolfredoPerezFernandez** [comment]
Thanks for you help... i cant get this to work...
My prisma server.ts:
import { GraphQLServer } from 'graphql-yoga'
import { permissions } from './permissions'
import { schema } from './schema'

import { createContext } from './context'

const options = {
 cors:{ origin: '*',
  methods: ["POST"],
  credentials: true,}
}

new GraphQLServer({
  schema,
  context: createContext,
  middlewares: [permissions],
}).start( options =>
  console.log(
    `🚀 Server ready at: http://localhost:4000\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#5-using-the-graphql-api`,
  ),
)

And my apollo client: 

const httpLink = createHttpLink({
  uri: 'https://app-name.golfredopf.now.sh',
})
  
  const client = new ApolloClient({
    cache: new InMemoryCache(),
    link: errorLink.concat(authLink).concat(httpLink),    
  });
give me this error:
{error: "idpiframe_initialization_failed", details: "Not a valid origin for the client: http://localhos…itelist this origin for your project's client ID."}error: "idpiframe_initialization_failed"details: "Not a valid origin for the client: http://localhost:8080 has not been whitelisted for client ID 658977310896-knrl3gka66fldh83dao2rhgbblmd4un9.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."__proto__: Object
AppBootstrapper.tsx:39 [GraphQL error]: Message: Error in Photon: 
Error: undefined target="exit" timestamp="2020-01-12T21:21:15.596Z" fields={"message":"1"}

**Comment by pantharshit00** [comment]
> Error: undefined target="exit" timestamp="2020-01-12T21:21:15.596Z" fields={"message":"1"}

Can you please use the alpha version of Prisma `npm install prisma2@alpha` and see what error message is there. We recently fixed the sereloization of error messages and this error would be more descriptive nore.

**Comment by xero0001** [comment]
Are you using Apollo Client for your frontend app?

If then, you can provide your apollo client settings.

I'm not very sure but your client fetch option also matters.

**Comment by GolfredoPerezFernandez** [comment]
I try this:

const httpLink = createHttpLink({
  uri: 'https://app-name.golfredopf.now.sh',
  credentials:'same-origin',
  fetchOptions: {
    mode: 'cors',
    method:['POST']
}  
})
with: 
const options = {
  cors:{ origin: '*',
  methods: ["POST"],
  credentials: true,}
  }

new GraphQLServer({
  schema,
  context: createContext,
  middlewares: [permissions],
}).start((options) =>
  console.log(
    `🚀 Server ready at: http://localhost:4000\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#5-using-the-graphql-api`,
  ),
)
 
and i get this error
: 
ApolloError.ts:57 Uncaught (in promise) Error: GraphQL error: Error in Photon: 
Error: undefined target="exit" timestamp="2020-01-14T17:07:44.932Z" fields={"message":"255"}
    at NodeEngine.engineReady (:8080/var/task/node_modules/@prisma/photon/runtime/index.js:3545)
    at :8080/var/task/node_modules/@prisma/photon/runtime/index.js:3468
    at new ApolloError (ApolloError.ts:57)
    at Object.next (QueryManager.ts:225)
    at notifySubscription (Observable.js:130)
    at onNotify (Observable.js:165)
    at SubscriptionObserver.next (Observable.js:219)
    at observables.ts:12
    at Set.forEach (<anonymous>)
    at Object.next (observables.ts:12)
    at notifySubscription (Observable.js:130)
    at onNotify (Observable.js:165)

**Comment by xero0001** [comment]
try this

FOR BACKEND

just delete options for allow every origin.

```
new GraphQLServer({
  schema,
  context: createContext,
  middlewares: [permissions],
}).start(() =>
  console.log(
    `🚀 Server ready at: http://localhost:4000\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#5-using-the-graphql-api`,
  ),
)
```

or if you want to allow only few urls

```
const options = {
  cors:{
  origin: [
  '~~~~'
  'http://localhost:3000',
  ],
  credentials: true,}
  }
```

FRONTEND

```
const httpLink = createHttpLink({
  uri: 'https://app-name.golfredopf.now.sh',
  credentials:'include',
  fetchOptions: {
    mode: 'cors',
    method:['POST']
}  
})
```

or

```
const httpLink = createHttpLink({
  uri: 'https://app-name.golfredopf.now.sh',
  credentials:'include',
  fetchOptions: {
    mode: 'no-cors'
}  
})
```

Try this and let me know!

**Comment by GolfredoPerezFernandez** [comment]
okok if i use: 
new GraphQLServer({
  schema,
  context: createContext,
  middlewares: [permissions],
}).start(() =>
  console.log(
    `🚀 Server ready at: http://localhost:4000\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#5-using-the-graphql-api`,
  ),
)
 with: 

const httpLink = createHttpLink({
  uri: 'https://app-name.golfredopf.now.sh',
  credentials:'include',
  fetchOptions: {
    mode: 'no-cors'
}  
}) 
i get : 
POST https://app-name.golfredopf.now.sh/ 500
(anonymous) @ httpLink.ts:134
Subscription @ Observable.js:183
subscribe @ Observable.js:262
(anonymous) @ index.ts:24
Promise.then (async)
(anonymous) @ index.ts:23
Subscription @ Observable.js:183
subscribe @ Observable.js:262
(anonymous) @ observables.ts:10
Subscription @ Observable.js:183
subscribe @ Observable.js:262
(anonymous) @ QueryManager.ts:222
(anonymous) @ QueryManager.ts:210
step @ tslib.es6.js:97
(anonymous) @ tslib.es6.js:78
(anonymous) @ tslib.es6.js:71
__awaiter @ tslib.es6.js:67
QueryManager.mutate @ app.js:3212
ApolloClient.mutate @ ApolloClient.ts:348
Mutation._this.mutate @ Mutation.tsx:225
Mutation._this.runMutation @ Mutation.tsx:181
onPress @ CreateTodoPanel.tsx:332
HoverButton._this._onPress @ HoverButton.tsx:39
Button._this.onClick @ Button.js:71
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:270
executeDispatch @ react-dom.development.js:561
executeDispatchesInOrder @ react-dom.development.js:583
executeDispatchesAndRelease @ react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:688
forEachAccumulated @ react-dom.development.js:662
runEventsInBatch @ react-dom.development.js:816
runExtractedEventsInBatch @ react-dom.development.js:824
handleTopLevel @ react-dom.development.js:4820
batchedUpdates$1 @ react-dom.development.js:18932
batchedUpdates @ react-dom.development.js:2150
dispatchEvent @ react-dom.development.js:4899
interactiveUpdates$1 @ react-dom.development.js:18987
interactiveUpdates @ react-dom.development.js:2169
dispatchInteractiveEvent @ react-dom.development.js:4876
Show 11 more frames
ApolloError.ts:57 Uncaught (in promise) Error: Network error: Unexpected end of JSON input
    at new ApolloError (ApolloError.ts:57)
    at Object.error (QueryManager.ts:256)
    at notifySubscription (Observable.js:134)
    at onNotify (Observable.js:165)
    at SubscriptionObserver.error (Observable.js:224)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at notifySubscription (Observable.js:134)
    at onNotify (Observable.js:165)


And With : 

const httpLink = createHttpLink({
  uri: 'https://app-name.golfredopf.now.sh',
  credentials:'include',
  fetchOptions: {
    mode: 'cors',
    method:['POST']
}  
  
})

i get:

Access to fetch at 'https://app-name.golfredopf.now.sh/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
ApolloError.ts:57 Uncaught (in promise) Error: Network error: Failed to fetch
    at new ApolloError (ApolloError.ts:57)
    at Object.error (QueryManager.ts:256)
    at notifySubscription (Observable.js:134)
    at onNotify (Observable.js:165)
    at SubscriptionObserver.error (Observable.js:224)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at notifySubscription (Observable.js:134)
    at onNotify (Observable.js:165)

**Comment by xero0001** [comment]
Try this.

```
const options = {
  cors:{
  origin: [
  '~~~~'
  'http://localhost:8080',
  ],
  credentials: true,}
  }
```

with

```
const httpLink = createHttpLink({
uri: 'https://app-name.golfredopf.now.sh',
credentials:'include',
fetchOptions: {
mode: 'cors',
method:['POST']
}
})
```

just included your localhost in origin list.

**Comment by GolfredoPerezFernandez** [comment]
hello.. Thanks for be patient.. now im having this issue with try to deploy to zeit now, this is the log:

Installing dependencies...
--
01:05:25 AM | This project is using a discontinued version of Node.js (8.10.x) and must be upgraded.
01:05:25 AM | Please set "engines": { "node": "12.x" } in your `package.json` file to upgrade to Node.js 12.
01:05:25 AM | This change is the result of a decision made by an upstream infrastructure provider (AWS).
01:05:25 AM | Read more: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html
01:05:25 AM | worker exited with code 20 and signal null

**Comment by xero0001** [comment]
Just follow what the log says.

Include

`
"engines": { "node": "12.x" }
`

this line in your package.json file, which is on the root directory.

**Comment by GolfredoPerezFernandez** [comment]
ok nice that work :D now using:
const options = {
  cors:{
  origin: [
  '~~~~'
  'http://localhost:8080',
  ],
  credentials: true,}
  }

and 

const httpLink = createHttpLink({
uri: 'https://app-name.golfredopf.now.sh',
credentials:'include',
fetchOptions: {
mode: 'cors',
method:['POST']
}
})

but still give this:

Access to fetch at 'https://app-name.golfredopf.now.sh/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
ApolloError.ts:57 Uncaught (in promise) Error: Network error: Failed to fetch
    at new ApolloError (ApolloError.ts:57)
    at Object.error (QueryManager.ts:256)
    at notifySubscription (Observable.js:134)
    at onNotify (Observable.js:165)
    at SubscriptionObserver.error (Observable.js:224)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at notifySubscription (Observable.js:134)
    at onNotify (Observable.js:165)

**Comment by xero0001** [comment]
Actually I've never used createHttpLink with prisma so I can't tell you what's wrong.

Wouldn't you find some examples using createHttpLink with graphql server?

All of the CORS problem is thrown out by browser. And with proper settings, you could really use this.

Sorry that I can't help you anymore.

**Comment by GolfredoPerezFernandez** [comment]
dont worry i going to keep trying :).. maybe you can help with this other issue https://github.com/prisma/prisma2/issues/1322

**Comment by xero0001** [comment]
I'm using zeit now :)

**Comment by pantharshit00** [comment]
You don't set cors option in the frontend, it is set by backend so no need to touch createHttpLink in the frontend. Only add `credentials: true` there if you are using cookies otherwise no need to add that option.

Now in the server, you are defining the options but you are actually not passing them. Use the following code to properly configure your server for cors:
```js
server.start(
  {
    cors: {
      credentials: true, // use if you are using cookies
      origin: process.env.NODE_ENV === 'production' ? process.env.PROD_FRONTEND_URL: 'http://localhost:8080'// use deployment url in production
    },
    endpoint: '/graphql',
    playground: '/graphql'
  },
  details => console.log(`Server is running on PORT ${details.port}`)
)
```


Also, for `target="exit"` error, please upgrade your photon version to see the actual error

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest version of `prisma2`.
You can try it out with `npm i -g prisma2`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by anle1991** [comment]
Is there a guide how to deploy prisma to zeit? The available guides seem outdated :( 
https://www.prisma.io/docs/tutorials/deploy-prisma-servers/zeit-now-and-google-cloud-sql-mohj5eiwot

**Comment by xero0001** [comment]
I recently realized that I was including

```
  "routes": [
    {
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
        "Access-Control-Allow-Headers": "X-Requested-With, Content-Type, Accept"
      },
      "src": "/graphql",
      "dest": "src/server.ts"
    },
]

```
this option in my now.json file.

Maybe this might have cleared my cross origin issue.
