### ISSUE TITLE
[Introspection] panic with table not found error

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1314]
Internal note: https://github.com/prisma/introspection-engine-output/issues/26

Sometime the introspection engine crashes with the following error: 

```
Error: [src/libcore/result.rs:1165:5] called `Result::unwrap()` on an `Err` value: "Table clubs not found"
```
Via https://github.com/prisma/introspection-engine-output/blob/8e75a5342e388bc4b7eb8220976af011484422aa/mysql_public/allsquare_stderr.log

Affected schema: https://github.com/prisma/database-schema-examples/tree/master/mysql/allsquare

Looks like the information schema has a table which is actually missing.

**Comment by janpio** [comment]
More cases:
https://github.com/prisma/prisma2/issues/1174
https://github.com/prisma/prisma2/issues/1173

**Comment by janpio** [comment]
Duplicate of https://github.com/prisma/prisma2/issues/1057
