### ISSUE TITLE
Error durring prisma2 init ( introspect fails on Raspberry Pi)

### ISSUE THREAD

**Issue by Germain67** [prisma/prisma2#132]
Hi, I tried to setup prisma2 on my raspberry pi.
Sadly, during prisma2 init, it fails at the introspection step with the following error output.

```
❯  Error in lift engine for rpc convertDmmfToDml:
     /home/pi/.nvm/versions/node/v11.4.0/lib/node_modules/prisma2/migration-engine: 1: /home/pi/.nvm/versions/node/v11.4.
0/lib/node_modules/prisma2/migration-engine: ELF: not found
   /home/pi/.nvm/versions/node/v11.4.0/lib/node_modules/prisma2/migration-engine: 2: /home/pi/.nvm/versions/node/v11.4.0/
lib/node_modules/prisma2/migration-engine: Syntax error: "(" unexpected
```

Steps to reproduce:
- Installed prisma2 on a Raspberry Pi 2b+ (32bit ARM)
- Run "prisma 2 init"
- PostgresSQL setup
- After connection succeeded, tried to introspect a new schema

Is this error somehow related to 32-bit architecture of the RPI and is there a way to solve this issue?

Thanks in advance for your answers!

**Comment by pantharshit00** [comment]
Can you please share architecture of your raspberry PI using `uname -a` command.

**Comment by Germain67** [comment]
Sure, this is the architecture details:

> Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux

**Comment by pantharshit00** [comment]
Ok, currently we don't build binaries for ARM. So please docker in the meanwhile

**Comment by Germain67** [comment]
> 
> 
> Ok, currently we don't build binaries for ARM. So please docker in the meanwhile

That might work but are there docker images available for ARM?

**Comment by herbertpimentel** [comment]
it also failing on mac machine. I have same "error  in lift engine" using mac when I try 

> prisma2 init

> uname -a
Darwin iMac-de-Herbert.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

trying to use postgres 

"PostgreSQL 10.5+tjap-20180921 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit"

I am using prisma2@2.0.0-preview1


is there a way to get a log file to figure out what is the problem ?

**Comment by pantharshit00** [comment]
@herbertpimentel I think you are running into https://github.com/prisma/lift/issues/10

**Comment by herbertpimentel** [comment]
@pantharshit00 I have posted there the Issue, but I am running on 5432

**Comment by herbertpimentel** [comment]
@Germain67 how did you get this introspection output ?!

**Comment by pantharshit00** [comment]
@Germain67 For now ARM support is planned. We have worked in the past couple of weeks to improve our platform support. https://github.com/prisma/specs/tree/master/binaries#tier-2


@herbertpimentel Looks like somehow binary was not installed. Can you please try installing prisma2 using `--unsafe-perm` ie `sudo npm install -g --unsafe-perm prisma2`

**Comment by Germain67** [comment]
> 
> 
> @Germain67 For now ARM support is planned. We have worked in the past couple of weeks to improve our platform support. https://github.com/prisma/specs/tree/master/binaries#tier-2
> 
> @herbertpimentel Looks like somehow binary was not installed. Can you please try installing prisma2 using `--unsafe-perm` ie `sudo npm install -g --unsafe-perm prisma2`

Glad to hear it's now on the roadmap, thanks a lot! 👍

**Comment by herbertpimentel** [comment]
> @Germain67 For now ARM support is planned. We have worked in the past couple of weeks to improve our platform support. https://github.com/prisma/specs/tree/master/binaries#tier-2
> 
> @herbertpimentel Looks like somehow binary was not installed. Can you please try installing prisma2 using `--unsafe-perm` ie `sudo npm install -g --unsafe-perm prisma2`

it is working now... I am so excited to work with it. Just tell me if I can help someway, especially if there's something I can help to make it work on windows.

**Comment by pantharshit00** [comment]
Windows support is planned and it will be released in the coming days.

**Comment by divyenduz** [comment]
Windows support is there in the latest preview. Once this is implemented, it would be possible to use a custom binary for ARM and other architectures: https://github.com/prisma/prisma2/issues/343

**Comment by pantharshit00** [comment]
Closing in favour of #861
