### ISSUE TITLE
Improve error message when OpenSSL is missing

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#1328]
Our Rust binaries depend on OpenSSL on runtime, meaning our users have to make sure the correct OpenSSL version is installed. We should improve our error messages when OpenSSL is not installed or the version doesn't match the binary's.

```
$ prisma2 generate
/usr/local/lib/node_modules/prisma2/query-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Should be something like:

```
$ prisma2 generate
/usr/local/lib/node_modules/prisma2/query-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Error: The Prisma query engine couldn't find OpenSSL on this machine.
You can install it by running `apt-get -qy update && apt-get install -qy openssl`.
```

One problem is that we don't know at this point what openssl version gets installed on the user's machine, which means we can't predict what their `binaryTargets` will look like. This also means that we may even mislead the user, thinking they have to install OpenSSL while they indeed have it installed, but provide the wrong version in their binaryTargets. We could fix that by checking for an installed OpenSSL when the binary fails with a message that they're just using the wrong binary target.

**Comment by steebchen** [comment]
Implemented via f4bd0c792e3fdfbc754592286fa92785c37ba38b

for further improvements see https://github.com/prisma/prisma2/commit/f4bd0c792e3fdfbc754592286fa92785c37ba38b#r36809707

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by steebchen** [comment]
Thanks! Over time, we may detect slightly different error messages, but we can just update them if we do.
