### ISSUE TITLE
Supress downloads when custom binary via environment variable is used

### ISSUE THREAD

**Issue by radicand** [prisma/prisma2#1329]
Opening a bug as suggested in https://github.com/prisma/prisma2/issues/861#issuecomment-574010817

I am running Prisma2 in arm64, an architecture that does not have precompiled binaries at this time. I have compiled the binaries appropriately and they work as well. When attempting to build a docker image, I set the ENV vars to point to the binaries, and during the `prisma2 build` command, Prisma attempts to download binaries (which 404 and throw a fatal error as a result) even though I have set the ENV to point to the binaries I've compiled. I believe that if custom binaries are provided via ENV, the download step should always skip out.

**Comment by pantharshit00** [comment]
Steps to reproduce: 
- Build your custom binaries from source(instructions here: https://github.com/prisma/prisma-engine/#building-prisma-engines)
- Point out to them via these env variables:
    `PRISMA_QUERY_ENGINE_BINARY`
    `PRISMA_INTROSPECTION_ENGINE_BINARY`
    `PRISMA_MIGRATION_ENGINE_BINARY`
- Run `prisma2 generate`
