### ISSUE TITLE
Connection error on Google Cloud Run

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma2#1330]
Since the undefined error was fixed I am getting this error in the last alpha running on serverless Google Cloud Run. It worked after redeployment. 

```
Error! $GraphQL error: Reason: called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) } in src/libcore/result.rs:1165:5
```

**Comment by pantharshit00** [comment]
Hm, where the database is hosted? The error suggests it is resetting the connection.

That might help me when I try to reproduce this.

**Comment by malekjaroslav** [comment]
The database is hosted on Google Cloud SQL - PostgreSQL

**Comment by malekjaroslav** [comment]
This error doesn't appear anymore, closing

**Comment by harole** [comment]
@malekjaroslav Same problem! Did you find the reason of this issue.

**Comment by Sytten** [comment]
Lots of work has been done recently on that, see issue https://github.com/prisma/prisma/issues/1559
