### ISSUE TITLE
Small docs issue/question @createdAt attribute

### ISSUE THREAD

**Issue by LydiaF** [prisma/prisma2#1332]
Hey,

In the [docs](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md), `@createdAt` is used as an example. Is it the case that, in prisma2, `@createdAt` is no longer an attribute and we should use `@default(now())`?

![image](https://user-images.githubusercontent.com/10000865/72436012-5d1d1d80-3797-11ea-9188-acd220abf400.png)

Thanks!

**Comment by nikolasburk** [comment]
Thanks a lot for raising this, @LydiaF  🎉  you were absolutely right, this was just a typo and you should use `@default(now())` instead of `@createdAt` going forward. I updated the docs accordingly 🙌

**Comment by benquan** [comment]
@nikolasburk 
These docs still have reference to @createdAt (at the end)
[https://www.prisma.io/docs/concepts/components/prisma-schema/data-model](url)

**Comment by janpio** [comment]
https://github.com/prisma/docs/pull/3674
