### ISSUE TITLE
Testing using without internet

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1338]
We should see what happens without internet.

**Comment by pantharshit00** [comment]
Current alpha works well without any issues if internet connectivity is not avaliable. You should obviously have prisma2 installed prior as expected though.

![image](https://user-images.githubusercontent.com/22195362/72613162-d877fe00-3954-11ea-95c0-86d96b0622da.png)


Version used: `prisma2@2.0.0-alpha.565, binary version: 1a0db4166ffce810428c731661582371d3ab88c4`
