### ISSUE TITLE
Implement SSL option for DB connections

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#134]
Right now it is not possible to use the SSL flag after the init flow as it hasn't been implemented yet.

**Comment by divyenduz** [comment]
Related https://github.com/prisma/prisma2/issues/109

**Comment by pantharshit00** [comment]
SSL flag has been implemented.

It is called sslmode and you can add it like so:

```groovy

datasource default {
  provider = "postgresql"
  url = "postgresql://xxxx:xxxx@xxxxxx.xxx/xxxx?schema=xxxx&sslmode=preferred"
}

```

Three ssl modes are supported which are as following:
1. preferred
2. required
3. disabled
