### ISSUE TITLE
Deploying to Now: Command failed with EACCES

### ISSUE THREAD

**Issue by momakes** [prisma/prisma2#1342]
```
Directory: /zeit/4284c074/node_modules/postinstall-postinstall
--
12:18:22 PM | Output:
12:18:22 PM | Error: Error: Command failed with EACCES: /zeit/4284c074/node_modules/prisma2/query-engine-rhel-openssl-1.0.x cli --dmmf
12:18:22 PM | spawn /zeit/4284c074/node_modules/prisma2/query-engine-rhel-openssl-1.0.x EACCES
12:18:22 PM | error Command failed with exit code 1.
```

Ever since preview16, I've been getting this error in every 5 deployments or so. Sometimes like today, after 4 deployments I'm still facing this error, and have no way to fix it.

I'm on preview18.2.
(Tried using alpha but it didn't install correctly on my local machine and was unable to download binary)

**Comment by pantharshit00** [comment]
Can you please share your `package.json` file? If possible please make a small git repository with a minimal reproduction.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest version of `prisma2`.
You can try it out with `npm i -g prisma2`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
