### ISSUE TITLE
Experimental flag is not indented correctly in help output

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1357]
See

![image](https://user-images.githubusercontent.com/183673/72611176-aa30f900-3929-11ea-8ac3-3e743b83684c.png)

**Comment by Jolg42** [comment]
Fixed with 
<img width="461" alt="Screenshot 2020-01-17 at 13 15 09" src="https://user-images.githubusercontent.com/1328733/72611858-71921f00-392b-11ea-85e3-c5879e940f57.png">
