### ISSUE TITLE
Change description of `generate`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1361]
Currently: `Generate Photon`

![image](https://user-images.githubusercontent.com/183673/72611428-596dd000-392a-11ea-9cfd-c5d72c340a22.png)

Should be replaced with other decscription, probably "Generate Prisma Client JS" for now. 

Maybe @nikolasburk has other input

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
