### ISSUE TITLE
Improve formatting of missing generator error message

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#1362]
It's hard to tell the "useful error message with instructions" apart from the stacktrace. We should improve & streamline our CLI error formatting.

![image](https://user-images.githubusercontent.com/1567498/72613465-da7b9600-392f-11ea-908d-f1c936a86cce.png)

**Comment by Jolg42** [comment]
I just tried it today and it works perfectly: 
<img width="783" alt="Screenshot 2020-01-21 at 11 13 39" src="https://user-images.githubusercontent.com/1328733/72796179-32234580-3c3f-11ea-9d2b-18c7cda766e6.png">

If the user cancels and says no it looks like this:
<img width="795" alt="Screenshot 2020-01-21 at 11 17 08" src="https://user-images.githubusercontent.com/1328733/72796492-b07fe780-3c3f-11ea-86b6-f6429519b438.png">

**Comment by janpio** [comment]
@Jolg42 Johannes' screenshot is from when you do not have a `package.json` in your folder - then it used to tell you just to run the command manually (which is/was also missing the npm channel @alpha or the specific version that should be installed). Not sure if this is now really resolved.

**Comment by Jolg42** [comment]
@janpio Indeed, I have a fix coming
