### ISSUE TITLE
Leftover `lift` in `migrate docs` output

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1365]
```
C:\Users\Jan\Documents
λ prisma2 migrate docs
Opening lift docs at https://github.com/prisma/prisma2/tree/master/docs
```

Maybe it makes more sense to remove the `docs` command completely for now though?

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
