### ISSUE TITLE
Introspection Error reporting does not exit on Windows

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1367]
Problem we had previously:

![image](https://user-images.githubusercontent.com/183673/72615786-c0dd4d00-3935-11ea-8503-ee6ddea54491.png)

After reporting an error, the process just does not return to command line. Ctrl+C also doesn't do anything.

```
C:\Users\Jan\Documents\throwaway\initTest
λ prisma2 -v
prisma2@2.0.0-alpha.571, binary version: 1a0db4166ffce810428c731661582371d3ab88c4
```

Terminal is cmd.exe via Cmder

**Comment by pantharshit00** [comment]
I can confirm this. I wasn't able to reproduce this on Mac but I was able to reproduce this on windows.

![image](https://user-images.githubusercontent.com/22195362/72806785-e80c8500-3c7b-11ea-8821-d1f03cf8208f.png)


I used the new `Windows Terminal`(you can get it from windows store) along with git bash as the shell.

Ready to go reproduction: https://github.com/harshit-test-org/prisma2-1367

Version used: `prisma2@2.0.0-alpha.584, binary version: 1a0db4166ffce810428c731661582371d3ab88c4`

**Comment by Jolg42** [comment]
Can't reproduce in preview 20 and latest alpha because this error doesn't prompt the error report anymore. (Or is it cached somewhere maybe?)
@pantharshit00 do you have a case where I can reproduce an error report with latest alpha?

**Comment by Jolg42** [comment]
I was able to reproduce on PowerShell actually

**Comment by janpio** [comment]
<3 <3 <3

**Comment by Jolg42** [comment]
Fixed with https://github.com/prisma/migrate/commit/75104daca036f374c279d1c7b355dfa475ad4ab3
