### ISSUE TITLE
Improve `introspect` command, backup behavior

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1369]
Current output of successful introspection:

```
C:\Users\Jan\Documents\throwaway\initTest
λ prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …
Done with introspection in 226ms

Moved existing prisma\schema.prisma to prisma\schema.backup.prisma
Wrote prisma\schema.prisma
```

It is unclear if this backup behavior is indeed what we want the command to do.

**Comment by pantharshit00** [comment]
I think the behaviour is correct here, you can use the backup file to diff against the introspected model and revert back if you don't get the intented model you want.

We just need to spec this out properly though.

**Comment by janpio** [comment]
Decision by @sorenbs: Remove backup behavior.
