### ISSUE TITLE
`npm install @prisma/client` and installation via prompt behave differently

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1374]
Depending on if you have a `package.json` in your project you will get a prompt to install `@prisma/client` or now. Both methods behave differently:

```
C:\Users\Jan\Documents\throwaway\1363>prisma2 generate
In order to use the "prisma-client-js" generator, you need to install @prisma/client to your project.
√ Do you want to install it now? ... yes
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @prisma/client@2.0.0-alpha.571
info All dependencies
└─ @prisma/client@2.0.0-alpha.571
Done in 3.01s.
```

```
C:\Users\Jan\Documents\throwaway\1363>prisma2 generate
Error: 
    Error: In order to use the "prisma-client-js" generator, you need to install @prisma/client to your project:   
    npm install @prisma/client
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183583:23
        at Generator.next (<anonymous>)
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183554:71
        at new Promise (<anonymous>)
        at module.exports.9949.__awaiter (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183550:12)
        at Object.prisma-client-js (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183575:47)
        at Object.<anonymous> (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:83452:114)
        at Generator.next (<anonymous>)
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:83369:71
        at new Promise (<anonymous>)

C:\Users\Jan\Documents\throwaway\1363>npm install @prisma/client

> @prisma/client@2.0.0-alpha.538 postinstall C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client
> node scripts/postinstall.js

undefined
Error: In order to use "@prisma/photon", please install prisma2. You can install it with "npm add -D prisma2".
    at main (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\scripts\postinstall.js:22:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @prisma/client@2.0.0-alpha.538 requires a peer of prisma2@* but none is installed. You must install peer dependencies yourself.
npm WARN 1363@1.0.0 No description
npm WARN 1363@1.0.0 No repository field.

+ @prisma/client@2.0.0-alpha.538
added 1 package and audited 1 package in 2.701s
found 0 vulnerabilities


C:\Users\Jan\Documents\throwaway\1363>
```

**Comment by janpio** [comment]
Just also noticed that yarn installs `alpha.571`, npm `alpha.538` - no idea what is going on there.

**Comment by janpio** [comment]
First output was with `package.json` added manually, second without. No other differences to project setup (just a empty folder with using `prisma2 init`)

**Comment by pantharshit00** [comment]
I am still only able to reproduce the part that I have reported above in both of the cases. Can you please try your reproduction once again with the new release version. 

My folder structure and output:
Case `#1`:
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/22195362/72897629-620a4000-3d48-11ea-8747-2a857e2474aa.png">

Case `#2`:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/22195362/72897670-7d754b00-3d48-11ea-9078-651ad253ecb6.png">

**Comment by timsuchanek** [comment]
We don't have this prompt anymore, therefore I'm closing this.

**Comment by deissibelle** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nestjs%2Ftcesting - Not found
npm ERR! 404
npm ERR! 404  '@nestjs/tcesting@^10.0.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sibelle Djumeghe\AppData\Local\npm-cache\_logs\2024-02-21T21_06_02_876Z-debug-0.log  


i got this error when i try to install prisma client

**Comment by deissibelle** [comment]
please help

**Comment by janpio** [comment]
That does not look related. If you think it is, please open a new GitHub discussion instead of commenting on a four year old issue. Thank you.
