### ISSUE TITLE
[Introspection] Crashes when default value contains line breaks

### ISSUE THREAD

**Issue by ejoebstl** [prisma/prisma2#1382]
I've observed the Prisma 2 introspection code crash when a default value is not a constant, but some expression, in my case also containing a new line. 

Consider a column in postgres with the following default value:

```
'Concatenated'||E'\n';
```

Introspection crashes with:

```
Schema parsing

error: Unexpected token. Expected one of: 
  -->  schema.prisma:389
   | 
388 |   columnName    String               @default("(Concatenated || 
389 | )")
   | ^ Unexpected token.
```

**Comment by janpio** [comment]
Needs decision: 
- Can we handle this? 
- Do we want to handle this? 
- How do we want to handle this?

**Comment by sorenbs** [comment]
DECISION: Initially we will not support newlines in default values. If introspection encounters a default value with newlines, it should not print it.

We do not need to explicitly handle this in the parser - it is acceptable that we give random parse errors.

**Comment by janpio** [comment]
Slight adaptation: Let's threat this as a light guardrail, and print a comment in the schema - but not send a warning to the CLI as it doesn't make a difference right now.

**Comment by sorenbs** [comment]
Just don't spend any time trying to print a multi-line, commented-out default value. No mess like this:

```
model User {
  name String //@default("who thi
//nks a name should
//
//have line breaks????!?")
}
```

**Comment by janpio** [comment]
lol no - just a comment that the default value is missing here because %explanation+link%

**Comment by janpio** [comment]
Default value is removed - but is currently not treated as guardrail yet (which is not super important, but would be nice to have).
