### ISSUE TITLE
Can no longer access photon/lift docs websites.

### ISSUE THREAD

**Issue by ssalbdivad** [prisma/prisma2#1384]
Navigating to [https://photonjs.prisma.io](https://photonjs.prisma.io) or [https://lift.prisma.io](https://lift.prisma.io) redirects me to the GitHub releases page at [https://github.com/prisma/prisma2/releases/](https://github.com/prisma/prisma2/releases/). Not sure if/where the standard landing pages for those projects exist at this point.

**Comment by nikolasburk** [comment]
Hey @ssalbdivad, this is intentional and the explanation will come with today's release. Keep an eye on https://github.com/prisma/prisma2/releases for more info 👀

**Comment by ssalbdivad** [comment]
@nikolasburk Good to know. Is that documentation hosted somewhere else now? In general I think it would be a good idea to make sure that an announcement has already been made and a replacement exists before taking something like that down.

**Comment by nikolasburk** [comment]
> Is that documentation hosted somewhere else now?

Are you referring to the code snippets that were shown on the website? These are now inaccessible unfortunately, the only replacement are the actual docs for the [Prisma Client API](https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md) and for [data modelling](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md).

We're currently rebuilding the website though and are planning to have a similar element again.

**Comment by ssalbdivad** [comment]
@nikolasburk As someone who's pretty immersed in the prisma ecosystem, I still relied regularly on  [https://photonjs.prisma.io](https://photonjs.prisma.io) for a quick refresher on syntax for simple interactions. I also use the markdown docs when I need to dive deeper, but it feels like a pretty significant loss that the project landing pages aren't available anymore.

I realize there are some breaking changes and that the team may want to shift how it communicates about Prisma 2, but as a whole it doesn't look like there are very many changes that would affect the usefulness of the hosted docs and code snippets. Has the team considered continuing to host the old docs pages and maybe just adding a note that some sections may be out of date while you work on a new landing page for the project?

**Comment by nikolasburk** [comment]
Hey @ssalbdivad, we're still discussing this internally. For a quick solution, you can go here to find a deploy of the Photon.js site before we added the redirect: https://5e1f377d376762000a9aa70d--homepage-v7-photonjs.netlify.com/

**Comment by ssalbdivad** [comment]
@nikolasburk This is a big help! Admittedly, the URL's not as memorable, so I'm glad autocomplete is a thing :bowtie: Will keep an eye out for further updates!

**Comment by nikolasburk** [comment]
Hey @ssalbdivad, thanks again for your feedback. We've decided to put the pages back up and added a banner to the top of both pages with a note about the renaming and a link to the release notes ✅

**Comment by ssalbdivad** [comment]
@nikolasburk I'm really glad to hear that! Thanks so much for the quick response and resolution. :bowtie:
