### ISSUE TITLE
Init with folder name does not emit folder name in message

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1390]
```
divyendusingh [p2-ci-raw]$ prisma2 --version
prisma2@2.0.0-alpha.584, binary version: 1a0db4166ffce810428c731661582371d3ab88c4
```

The behavior of new init is undefined (just spoke to Joël) but this used to work

![image](https://user-images.githubusercontent.com/746482/72797760-05bcf880-3c42-11ea-8cd3-ed4825320b7e.png)

**Comment by Jolg42** [comment]
Fixed :)
