### ISSUE TITLE
Preview 20 fails to install Prisma engines on Linux

### ISSUE THREAD

**Issue by artemzakharov** [prisma/prisma2#1400]
When I install Preview 20 on a Linux machine, it fails to install any of the required "engine" files, like `debian-openssl-1.1.x`, in the `prisma2` npm folder:

![image](https://user-images.githubusercontent.com/25446299/72857237-489ac280-3c7a-11ea-915b-b38b052f578f.png)

This happens regardless of whether the `npm i` command is run with `sudo` or not, and appears to be related specifically to Preview 20 because installing Preview 19 in the same way results in all of the required files being where they should be. 

It does not occur on Windows machines.

**Comment by pantharshit00** [comment]
@artemzakharov Can you please tell me which linux distribution are you using?

I tested it out on a linux box and it is working fine:
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/22195362/72896220-376ab800-3d45-11ea-8395-ea6b133ad600.png">


The output of `cat /etc/os-release/` of the Linux box that I used:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Can you also please provide me with the output of `cat /etc/os-release`

**Comment by artemzakharov** [comment]
This is the output for me:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
Looks identical unless I'm missing something, so not sure what's going on.

I double checked to make sure I wasn't going crazy, and this is the output of running `npm i -D prisma2@2.0.0-preview019`:

![image](https://user-images.githubusercontent.com/25446299/72952694-e90ee680-3d4f-11ea-9721-f06ebebf8e6a.png)

Then `sudo npm i -D prisma2@2.0.0-preview020`, immediately after:

![image](https://user-images.githubusercontent.com/25446299/72952736-093ea580-3d50-11ea-8fde-7642d37c7c46.png)

I was thinking this might be some kind of permissions issue, since this linux box is a cloud hosted VM, but I can't understand any circumstance under which the previous version would install the files fine, while the new version would not.

**Comment by pantharshit00** [comment]
Can you please try this again with `preview020.2`?

**Comment by artemzakharov** [comment]
Still happening with `preview020.2`. Tried it with `alpha` too, that doesn't work either.

**Comment by pantharshit00** [comment]
Well, can you also check openssl and linux kernel version? 

Please share the output of `uname -a` and `openssl version` 🙏 

Also, if you can tell me where this server is hosted I can try there and see if I can reproduce this.

**Comment by artemzakharov** [comment]
I was actually wrong, it's not a cloud VM, it's one that's hosted locally via HyperV on my Windows machine. My bad. 

Either way, it doesn't appear that anyone else is experiencing this issue, so I'm just going to assume that it's something on my end, and close this issue.

If someone else does run into it, they can leave a comment here, and we can look into it again.
