### ISSUE TITLE
Document onDelete option removal

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#1402]
Hello, I can't generate my client it gives me that now and nothing about that in the release notes:

<img width="651" alt="Screen Shot 2020-01-22 at 11 51 27 AM" src="https://user-images.githubusercontent.com/7302317/72888345-b17f4a80-3d0d-11ea-8ff5-520d2436bcc5.png">

And another error when I try to migrate:

![image](https://user-images.githubusercontent.com/7302317/72888394-c3f98400-3d0d-11ea-85a1-2465d5d55642.png)

**Comment by janpio** [comment]
Your second problem has been reported before and is being tracked in https://github.com/prisma/prisma2/issues/1395#issuecomment-576888331

**Comment by nikolasburk** [comment]
Sorry, we missed that in the release notes  and I just added it. TLDR:

> While not causing an error, the `onDelete` argument on the `@relation` attribute didn't have any effect (i.e., it hadn't been implemented yet). To make the API surface simpler, we removed it from the Prisma schema for now. 

Hope that helps, please let me know if you have any further questions!

**Comment by yovanoc** [comment]
Thanks but `While not causing an error` is not true so :/

**Comment by nikolasburk** [comment]
Ah sorry if that wasn't clear, this statement referred to versions earlier than `preview020` where it didn't cause an error. As of `preview020` it causes an error (that's why it's listed under breaking changes).

**Comment by yovanoc** [comment]
Ok, I get it, so will be available for GA ?

**Comment by pantharshit00** [comment]
@yovanoc You can modify the database schema directly to have onDelete behaviour.

**Comment by yovanoc** [comment]
Yeah I know but it will be very helpful to have prisma handling that :)

**Comment by pantharshit00** [comment]
Yes, we are aware of that and we will bring it back once it is implemented. Right now schema is misleading in a sense that it was not actually implemented.

**Comment by pantharshit00** [comment]
This was added to the release notes. I am closing this.

Opened a new issue about documentation: https://github.com/prisma/prisma2/issues/1406
