### ISSUE TITLE
Remove documenation about onDelete

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1406]
onDelete option was removed in preview020 because it was not implemented. It is still documented in the docs here: https://github.com/prisma/prisma2/blob/7b254e8e90ec45370de41b5551cc401a710cbd2f/docs/relations.md#the-relation-attribute

We should remove it

**Comment by nikolasburk** [comment]
The link pointed to a working branch, [it's already removed on `master`](https://github.com/prisma/prisma2/blob/master/docs/relations.md#the-relation-attribute).
