### ISSUE TITLE
Supply a custom path to Prisma schema file for CLI commands (i.e. `--schema`?)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1412]
This is useful when you want to run the commands from the root folder of your project for example and your `schema.prisma` file is in a subdirectory. It avoids changing directories.

- What is the naming of the flag/param? (path, schema, ...)
- Which commands require it?
- Also available via ENV var? (e.g. `PRISMA_SCHEMA_PATH`)
- How are the developers made aware of it being active?

**Comment by Jolg42** [comment]
@schickling I'm implementing it like this `--schema=./directory/prisma.schema`
Spec will be in Notion soon!

**Comment by janpio** [comment]
Internal: Can you link the spec here please @Jolg42?

**Comment by Jolg42** [comment]
There is none at the moment, Søren is on it :)

**Comment by Jolg42** [comment]
It is implemented as `--schema=./path/to/prisma.schema` (absolute or relative)

@sorenbs I can't find it in the spec, is it on a branch?

**Comment by Jolg42** [comment]
It is in https://github.com/prisma/specs/blob/master/cli/README.md#init in `Arguments` sections like
`schema specify the path used to read the schema.prisma file instead of the default path. The path can be absolute or relative. Note that the generation result is written to that same file.`

**Comment by aeharake** [comment]
@ Jolg42  Hello, did you manage to find a way to specify the path from .env?

> 
> 
> This is useful when you want to run the commands from the root folder of your project for example and your `schema.prisma` file is in a subdirectory. It avoids changing directories.
> 
>     * What is the naming of the flag/param? (path, schema, ...)
> 
>     * Which commands require it?
> 
>     * Also available via ENV var? (e.g. `PRISMA_SCHEMA_PATH`)
> 
>     * How are the developers made aware of it being active?

**Comment by aeharake** [comment]
> 
> 
> @ Jolg42 Hello, did you manage to find a way to specify the path from .env?
> 
> > This is useful when you want to run the commands from the root folder of your project for example and your `schema.prisma` file is in a subdirectory. It avoids changing directories.
> > ```
> > * What is the naming of the flag/param? (path, schema, ...)
> > 
> > * Which commands require it?
> > 
> > * Also available via ENV var? (e.g. `PRISMA_SCHEMA_PATH`)
> > 
> > * How are the developers made aware of it being active?
> > ```

Ok got it. We can set this from package.json:

  "prisma": {
    "schema": "prisma/schema.prisma"
  },

**Comment by Jolg42** [comment]
The docs are here https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location

**Comment by dexter0323** [comment]
> The docs are here https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location

Updating doc URL:

https://www.prisma.io/docs/orm/prisma-schema/overview/location#prisma-schema-location
