### ISSUE TITLE
Detect if unicode character can be rendered in CLI output before printing it

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1413]
For example `◭ Prisma makes your data easy` doesn't render correctly on Windows.

![image](https://user-images.githubusercontent.com/183673/72921983-87994880-3d4c-11ea-86ca-5b5962a9da74.png)

Can we maybe detect that and skip Unicode character?

**Comment by Jolg42** [comment]
I didn't find an easy way to detect that, so maybe we don't display the emoji on Windows? If `process.platform === "win32"` @timsuchanek

**Comment by janpio** [comment]
It works in some Windows command line things, sometimes 🤷‍♀

**Comment by Jolg42** [comment]
@janpio I didn't find an easy way to detect if the emoji could be printed so disabling on Windows is the best right now :)

**Comment by janpio** [comment]
Some more information:

Git bash could actually render the character.
Windows Terminal (Preview) as well - for both Powershell and cmd.exe 🐒 (Search for "terminal" in the Windows Store)

Any way we can recognize those?

**Comment by Jolg42** [comment]
@janpio Basic emojis don't render in my Git Bash or PowerShell here, so it is not an easy thing unfortunately.
Maybe trying to print it and looking at the result is the only reliable solution but that's a bit too much I think.

**Comment by janpio** [comment]
Making it not ugly by default is indeed enough for now. Should open an issue for re-enabling it in environments that support it though (Windows Terminal (Preview), maybe Git bash, other terminals that do)
