### ISSUE TITLE
Could not find a declaration file for module '@prisma/client'

### ISSUE THREAD

**Issue by akoufatzis** [prisma/prisma2#1421]
After upgrading to **preview020** I am experiencing the following issue:

Could not find a declaration file for module '@prisma/client'. '/Users/akoufatzis/Developer/arconsis/adi/hero2/hero-speedfactory-gw/node_modules/@prisma/client/index.js' implicitly has an 'any' type.
  Try `npm install @types/prisma__client` if it exists or add a new declaration (.d.ts) file containing `declare module '@prisma/client';`
 import { PrismaClient } from '@prisma/client'

I have following setup:
` "@prisma/client": "^2.0.0-preview020",
 "nexus": "0.12.0-rc.9",`

The issue arises in non generated code also.

**Comment by akoufatzis** [comment]
Issue is solved after running: `prisma2 generate`. But still I think that the project should compile before running the generate command even with a stub type implementation. What do you think? I am closing the issue but feel free to open it if this should be supported.

**Comment by janpio** [comment]
That is an interesting point @akoufatzis, and I kind of agree. Maybe we can even point to missing generation here, so give the user a pointer what exactly needs to be done.

Can you please just open a new issue just asking for this (with the error message you get when not running `prisma2 generate` first)? Thanks.
