### ISSUE TITLE
Photon Dart client generator

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma2#1422]
Will there be a Dart client generator? This will be especially relevant to Flutter developers using Prisma as their backend.

**Comment by steebchen** [comment]
Just to clarify, you want to use Prisma in your App using a local database, for example SQLite?

**Comment by nickreynke** [comment]
I want my app to be able to communicate with my Prisma server with the same models that the server exposes. There should also be serialization and deserialization to and from client-side models.

**Comment by nickreynke** [comment]
Oh and regarding the local database: Maybe some kind of caching system but the Dart client may contain methods to stream (real-time; `Stream`) or get (no real-time; `Future`) data from my Prisma server with its generated methods to obtain data.

**Comment by steebchen** [comment]
I just want to note here that this will only possible for local storage of a SQLite database. It's not possible for Prisma to directly integrate a client tool like Flutter/Dart with a remote database (let's say a Postgres instance on Google Cloud).

**Comment by nickreynke** [comment]
Ahhhh, sorry. Now I know what you mean. I meant a client that communicates with the Prisma server which itself then communicates with the appropriate database in the background.

Client code, that helps developing, serializing, deserializing and communicating with the server easier **->** Prisma Server **->** Database

**Comment by janpio** [comment]
"Prisma Server" is not really a thing in Prisma 2 any more. You have a Prisma Client that is a library in your code, which executes a binary engine that connects to your database.

If you want a client-server thing (clients being the Flutter based mobile apps), you would just have a Prisma Client in your server app that then offers its data via an API (REST, GraphQL, whatever) to the Flutter client that consumes that API. But everything Prisma would happen on the server.

**Comment by nickreynke** [comment]
Sorry, misunderstood the term "client" in this case. :) Makes sense now!
