### ISSUE TITLE
Api naming issue

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#1425]
On the latest alpha you changed the api, all is good for my other models but this one is not reachable

Version: `prisma2@2.0.0-alpha.627, binary version: d0cc0eaf7aaf1c0811915825b2ae338af0f40824`

![image](https://user-images.githubusercontent.com/7302317/73002839-eb7f4800-3e04-11ea-8557-940c5105ef97.png)

```prisma
model MachineData {
  id        CUID
  machineId String
  os        String
  osVersion Float
  osArch    String
  procFreq  Float
  procCores Int
  ram       Int
  instance  Instance
}
```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
