### ISSUE TITLE
Empty Introspection result could lead to much nicer error message and explanation

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1462]
https://github.com/prisma/prisma2/issues/1457 shows what happens if you introspect an empty database currently. 

While it is of course correct that there is an error message, this could also be an opportunity to educate the user and offer him and alternative to a happy path.

**Comment by timsuchanek** [comment]
Closing this in favor or https://github.com/prisma/prisma2/issues/1145 as this is a duplicate.
