### ISSUE TITLE
Improve SSL connection docs

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1463]
https://github.com/prisma/prisma2/blob/754620fcf105788f09c31a3a2f461852ad432eea/docs/core/connectors/postgresql.md#configuring-an-ssl-connection

Right now the docs for SSL configuration just briefly describes the parameters and doesn't actually tell how to generate certain things like PKCS12 files which are required for the connection.

I wrote a longer description of the parameters and how to generate here: https://github.com/prisma/prisma2/issues/1433#issuecomment-578646902 , we can use them in the docs.

**Comment by nikolasburk** [comment]
Thanks, added via this PR: https://github.com/prisma/prisma2/pull/1569
