### ISSUE TITLE
Wrong output from `prisma2 init` prints to import `PrismaClient` from 'prisma-client-js' instead of '@prisma/client'

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#1466]
Just saw the recent changes on Preview 20. I was wondering what’s the difference between both?

When I do `npx prisma2 init`, I got the following in the terminal with other stuff which I omitted for brevity:

```js
import { PrismaClient } from 'prisma-client-js'
// or const { PrismaClient } = require('prisma-client-js')

const prisma = new PrismaClient()
```

But in the [Getting Started](https://github.com/prisma/prisma2/blob/master/docs/getting-started.md) guide, I see on Step No. 7

```js
import { PrismaClient } from ‘@prisma/client’
```

Which one to use? Are both valid & one & the same? It’s confusing me :(

**Comment by nikolasburk** [comment]
Hey @deadcoder0904, the current output from `prisma2 init` is wrong and will be fixed soon. I'll leave this issue open to track this (also adjusted the title) 🙂 

The right way to import Prisma Client in your application is: 

```ts
import { PrismaClient } from ‘@prisma/client’
```

**Comment by janpio** [comment]
This has already been merged (See https://github.com/prisma/prisma2/blob/d4305267ee5b7d7c59e28e339716b7da0d4df50c/cli/introspection/src/commands/Init.ts#L139-L141 for current content) and is available in `alpha`, and will be included in the next preview release.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
