### ISSUE TITLE
Migration guide missing from Getting Started

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#1476]
So I created a brand new project & faced 1 issue:

> Invalid `prisma.()` invocation in

I faced this issue earlier too so I knew the solution was to do:

```sh
➜ prisma2 migrate save --name "Init" --experimental
➜ prisma2 migrate up --experimental
```

But it isn’t mentioned in the [Getting Started](https://github.com/prisma/prisma2/blob/master/docs/getting-started.md) guide.

I don’t think someone who is starting just now will know this so mention it plz ;)

**Comment by deadcoder0904** [comment]
There’s also 1 weird thing.

I get the following message twice:

```bash          
You are trying to apply a migration for Sqlite database /dev.db.
A database with that name doesn't exist at sqlite:./dev.db.
Do you want to create the database?

┌─ Database options ────────────────────────────────────────────────────────────────────┐
│                                                                                       │
│ ❯ Yes            Create new Sqlite database /dev.db                                   │
│   No             Don't create the database                                            │
│                                                
```

Both times when doing `➜ prisma2 migrate save –name “Init” –experimental` as well as when doing `➜ prisma2 migrate up –experimental` even thought the `save` command creates `dev.db`.

Definitely a bug in CLI.

**Comment by deadcoder0904** [comment]
Also, the output while doing `save` and `up` has some `lift` left out like:

```bash
➜ prisma2 migrate save --name "Init" --experimental
📼  lift save --name Init
.
.
.
Lift just created your migration 20200130125406-init in
.
.
.
```

And 

```bash
➜ prisma2 migrate up –experimental 
🏋️‍ lift up
```

But I think it might have already been fixed so won’t open another issue.

**Comment by pantharshit00** [comment]
> I faced this issue earlier too so I knew the solution was to do:

The new guide assumes that you are using introspection and have the database created already. But I agree we can add a note in there about this.


> I get the following message twice:

This is a known bug that we need to fix. Refer https://github.com/prisma/migrate/issues/316. A workaround here to prevent this, for now, is to use `file` protocol instead of `sqlite`

> Also, the output while doing save and up has some lift left out like:
Please follow this issue: https://github.com/prisma/migrate/issues/333


I have folded some of your comments so that we can quickly go through this ticket in the future.

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @deadcoder0904 🙌 we've [just added "Getting started"-guides for several scenarios](https://github.com/prisma/prisma2/pull/1553), you can find the one using `prisma2 migrate` here: https://github.com/prisma/prisma2/blob/master/docs/getting-started/start-from-scratch-with-empty-db/quickstart-prisma-migrate.md
