### ISSUE TITLE
Create "Getting started" escape hatch for non-existent databases

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1479]

**Comment by janpio** [comment]
Comment from Soren: We do not want that. The page can explain SQL and point to other tools, but should only tell people about experimental `migrate` features with a big, fat disclaimer.

**Comment by janpio** [comment]
Note: During the planning meeting we generalized this issue a bit.

**Comment by nikolasburk** [comment]
Added more "Getting Started" scenarios: https://github.com/prisma/prisma2/blob/master/docs/getting-started/README.md
