### ISSUE TITLE
Make using DATABASE_URL as default DB connection URL a best practice

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#1481]
- `DATABASE_URL` should be our new default connection URL env var name (→ works out of the box with Heroku)
- Docs + examples should point out that we strongly recommend to not check in the `.env` file to their VCS
- We need to do an extra good job of explaining how env vars are handled so developers can 100% understand how things are working.

**Comment by nikolasburk** [comment]
Wondering if we should include a `.gitignore` file when running `prisma2 init`?

**Comment by nikolasburk** [comment]
Fixed via https://github.com/prisma/prisma2/pull/1569
