### ISSUE TITLE
Create-react-app + prisma2 = Module not found: Can't resolve 'readline'

### ISSUE THREAD

**Issue by Suniron** [prisma/prisma2#1492]
Hello,

I'm trying to integrate prisma2 in my existing React App and i have a problem..

This app was created with create-react-app.

I put the exemple (in gettting started, step 4) into a ts file and i export the function `main()` to use this on React button click.

Now, when i do a `yarn start` (= `react-scripts start`) , i got this error on console:

```
Failed to compile.

./node_modules/@prisma/client/runtime/index.js

Module not found: Can't resolve 'readline' in '/home/myName/Path/To/App/node_modules/@prisma/client/runtime'
```

Anyone can help me ?

ps: Sorry for my bad english.. I hope that you understand me :(

**Comment by Suniron** [comment]
I can declare the function `main()` without the error message but if i call theese function, i have this error..

**Comment by xlxAciDxlx** [comment]
Related: #1272

**Comment by pantharshit00** [comment]
Prisma 2 is not intended for frontend use so you can't run it on the browser as it depends on some modules provided by Node.js standard library. You will use it on your backend to create an API and you will consume that API in your frontend.

Let me know if this has addressed your concern.

**Comment by Suniron** [comment]
My bad... thanks a lot, it's now ok for me.
