### ISSUE TITLE
[Introspection] Investigate and improve introspection speed

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1494]
Right now Introspection sometimes fails for big schemas (See https://github.com/prisma/prisma2/issues/1493). We should investigate and improve the behavior of Introspection by e.g. parallelizing queries or similar.

**Comment by tomhoule** [comment]
Magento has ~400 tables, we're doing ~1200 SQL queries to introspect at the moment (see the following log).

[logs.txt](https://github.com/prisma/prisma2/files/4165877/logs.txt)

We should be able to cut the number of queries by quite a lot with a small amount of work, so I'll try that.

**Comment by tomhoule** [comment]
After a first series of PRs, the number of introspection queries on the same database is down to 5 (from ~1400).

**Comment by tomhoule** [comment]
Current status:

- we optimized introspection queries on MySQL and now it is fast™
- we optimized one query on postgres (columns), but the others are more complicated, so we will do it when we have time or it becomes a necessity
