### ISSUE TITLE
`introspect`: "Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1500]
When running this `introspect` command `prisma2 introspect --url mysql://prisma:...@introspection-public-mysql-cluster.cluster-ro-clfeqqifnebj.eu-west-1.rds.amazonaws.com:3306/allsquare --print` (password via @janpio or @divyenduz), you get this error message:

```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:431:19)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at /Users/runner/runners/2.164.0/work/introspection-engine-output/introspection-engine-output/node_modules/prisma2/build/index.js:2:980933
    at new Promise (<anonymous>)
    at IntrospectionEngine.<anonymous> (/Users/runner/runners/2.164.0/work/introspection-engine-output/introspection-engine-output/node_modules/prisma2/build/index.js:2:979697)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/runners/2.164.0/work/introspection-engine-output/introspection-engine-output/node_modules/prisma2/build/index.js:2:974378)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  code: 'ERR_STREAM_DESTROYED'
}
Error: [src/libcore/result.rs:1165:5] called `Result::unwrap()` on an `Err` value: "Table clubs not found"
```

The first bit seems unwanted.

**Comment by pantharshit00** [comment]
I can reproduce this:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/22195362/73641228-b4772500-4695-11ea-8c5c-02821676f656.png">

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by pitops** [comment]
what is it exactly?? happens to prisma 1 as well

**Comment by khanh-bes** [comment]
Happens to me as well with preview 22

**Comment by lednhatkhanh** [comment]
Happens to me as well with preview 22 and even with alpha

**Comment by pantharshit00** [comment]
@lednhatkhanh Can you please let us know how we can reproduce this?

> what is it exactly?? happens to prisma 1 as well

We were trying to use the introspection engine after it was stopped. That is why it threw the error. For Prisma 1 it can be a very different cause.
