### ISSUE TITLE
Use Prisma2 on Raspberry Express server

### ISSUE THREAD

**Issue by Suniron** [prisma/prisma2#1505]
Hello,

Can i use Prisma2 on a Raspberry 3b+ Express server ?

I got an error about binaries..

Thanks

**Comment by pantharshit00** [comment]
Hm, I don't have a Raspberry Pi on hand. I would be difficult for me to reproduce.

**Comment by Jolg42** [comment]
I guess this is about https://github.com/prisma/prisma2/issues/861 as the Pi is ARM based. So one solution would be for @Suniron to compile the binaries and use the env vars like in the issue.

**Comment by pantharshit00** [comment]
Yeah, @Suniron did comment there: https://github.com/prisma/prisma2/issues/861#issuecomment-581032378

> I can't generate prisma2 client on Raspberry pi 3b+: node_modules/prisma2/query-engine-debian-openssl-1.1.x: cannot execute binary file.. :'(

I should have pasted the comment here. Looks like @Suniron didn't compile the binaries. Right now we don't ship ARM binaries so you will need to compile from source.

If that is indeed the case, this is a duplicate of #861

**Comment by pantharshit00** [comment]
Just to sum up #861 for you @Suniron, we don't ship official ARM support yet but you can compile Prisma from source if you want to check Prisma out on ARM. Here are the instructions on how you can do that: https://github.com/prisma/prisma-engine/#building-prisma-engines

After that just point Prisma client and CLI to these complied binaries using the following environment variables:
- PRISMA_QUERY_ENGINE_BINARY
- PRISMA_INTROSPECTION_ENGINE_BINARY
- PRISMA_MIGRATION_ENGINE_BINARY

**Comment by Suniron** [comment]
Thanks à lot ! I try this tonight 😁

**Comment by Suniron** [comment]
Hmmm i can't build on raspberry. I think that is not compatible with rust `1.4.1`... 🤔

**Comment by pantharshit00** [comment]
Try with the latest Rust version, we tend to use the latest features.

**Comment by Suniron** [comment]
@pantharshit00 , thank's for you answer.

I have the same problème when i do `cargo +nightly build` or `cargo +stable build`, after  `cargo build` or if i set nightly or stable as default before trying to build.

See:
```error[E0080]: could not evaluate constant
  --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/sharded-slab-0.0.6/src/page/slot.rs:54:24
   |
54 |     const LEN: usize = (cfg::WIDTH - C::RESERVED_BITS) - Self::SHIFT;
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to subtract with overflow
[...]```

**Comment by Suniron** [comment]
Same with `1.43.0` (the Day release).

It's look like the problem is caused by `sharded-slab-0.0.6`.
Anyone build correctly with raspberry ?

**Comment by Suniron** [comment]
I found the info!!

Please, who can update sharded-slab to 0.0.8?

Because this bug is fixed on new version of this.:
hawkw/sharded-slab@74d42dd

Thank's a lot :)

**Comment by pimeys** [comment]
@Suniron will be in the next alpha release. Eliza finally released tracing-subscriber 0.2 with my JSON log engine, so I could switch the engines to use the mainline again.

**Comment by pimeys** [comment]
And if you do cross-compilation to rpi, please share a Dockerfile for others to use too :)

**Comment by radicand** [comment]
@Suniron I was able to compile the binaries on arm (I commented about this in #861) - if you're still having issues, you can use the ones I built: https://github.com/radicand/cookbook/tree/master/server/prisma2-aarch64 - note it's for arm64, which you can easily enable on your RPi if you haven't already.

**Comment by Suniron** [comment]
Thanks ! 

So, i installed ubuntu 64 bits for ARM, it's OK now !!! I'm really happy :-D

**Comment by fabianmoronzirfas** [comment]
> Just to sum up #861 for you @Suniron, we don't ship official ARM support yet but you can compile Prisma from source if you want to check Prisma out on ARM. Here are the instructions on how you can do that: [prisma/prisma-engine#building-prisma-engines](https://github.com/prisma/prisma-engine/#building-prisma-engines)
> 
> After that just point Prisma client and CLI to these complied binaries using the following environment variables:
> 
>     * `PRISMA_QUERY_ENGINE_BINARY`
> 
>     * `PRISMA_INTROSPECTION_ENGINE_BINARY`
> 
>     * `PRISMA_MIGRATION_ENGINE_BINARY`
> 
> 
> If this doesn't help please wait till we release official ARM support

---

Sorry for reviving this thread. I managed to compile the prisma engines on Raspberry Pi without problems, but where should I put those variables?

- I did put them into a `.envrc` in the root of my project and did a `dirnev allow .` with no luck.
- I did an  

```
	export PRISMA_QUERY_ENGINE_BINARY=/home/pi/bin/query-engine
	export PRISMA_INTROSPECTION_ENGINE_BINARY=/home/pi/bin/introspection-engine
	export PRISMA_MIGRATION_ENGINE_BINARY=/home/pi/bin/migration-engine
```

in my ~/.zshrc and reloaded the session. Also no result.
- I added them to the `prisma/.env` in my project. No result either. 

In all the three cases on `npm i`, `npm ci` and on `npm run generate` (which does a `npm -s run generate:prisma && npm -s run generate:nexus`) I get this error

```plain 
Warning Precompiled binaries are not available for ARM.
> Downloading Prisma engines for arm-openssl-1.1.x [                    ] 0%Error: Not Found https://binaries.prisma.sh/master/0c2ec197653b278b2978845ef958db88824cd82e/arm-openssl-1.1.x/prisma-fmt.gz
```

And the process exits with an error.

**Comment by pantharshit00** [comment]
@fabianmoronzirfas Can you please sure you are on the latest version of Prisma? We had a regression in between here these flags were ignored. 

Also, please paste the output of `prisma --version` here.

**Comment by fabianmoronzirfas** [comment]
@pantharshit00 thanks for the swift reply. 

Running `./node_modules/.bin/prisma --version` also gives me that error message.

```bash
> Environment variables loaded from ./prisma/.env
> Warning Precompiled binaries are not available for ARM.
> Downloading Prisma engines for arm-openssl-1.1.x [                    ] >0%Error: Not Found https://binaries.prisma.sh/master/0c2ec197653b278b2978845ef958db88824cd82e/arm-openssl-1.1.x/prisma-fmt.gz
```

I can run cli with the `--help` flag but that does not give me a version.

Within my node_modules/@prisma/{cli,client}/package.json the versions for client and cli are "2.0.0-beta.5"

My whole package.json can be found [here](https://github.com/fabianmoronzirfas/enviro-plus/tree/master/server).

I'm trying to run this on 

```plain
Description:	Raspbian GNU/Linux 10 (buster)
Model:          Raspberry Pi 4 Model B Rev 1.1
Node.js:        v12.16.1
npm:            6.13.4
```

**Comment by radicand** [comment]
In your package.json, it shows beta.4 for cli.  Can you try updating to beta.5? I don't recall which version had the regression, but I'm using beta.5 on arm without issues.

**Comment by fabianmoronzirfas** [comment]
Did a npm install `@prisma/cli@latest` with `rm -rf node_modules` before that. No change. I'm running on `beta.5` 😭

**Comment by fabianmoronzirfas** [comment]
After skimming a little trough the source code It got me thinking. 

> There are 4 binaries but only three env variables?

So I added in `PRISMA_FMT_BINARY=/home/pi/bin/prisma-fmt` and now I get a different error.

```plain
Environment variables loaded from ./prisma/.env
Warning Precompiled binaries are not available for ARM.
Warning Precompiled binaries are not available for ARM.
Error: Unknown binaryTargets arm-openssl-1.1.x
```

At least I'm one step further.
I get the same error when copying the binaries manually into `node_modules/@prisma/cli` where they are downloaded to when the dl works.

**Comment by fabianmoronzirfas** [comment]
Finally I got this working by (for future reference):

- installing rust and [compiling](https://github.com/prisma/prisma-engines#building-prisma-engines) the binaries directly on the Raspberry Pi 
- adding the 4 environment variables to `./prisma/.env` and made them point to my compiled binaries

```plain
PRISMA_QUERY_ENGINE_BINARY=/home/pi/bin/query-engine
PRISMA_INTROSPECTION_ENGINE_BINARY=/home/pi/bin/introspection-engine
PRISMA_MIGRATION_ENGINE_BINARY=/home/pi/bin/migration-engine
PRISMA_FMT_BINARY=/home/pi/bin/prisma-fmt
```

- forking and cloning the whole prisma package
-  ran through first steps in [CONTRIBUTING.md](https://github.com/prisma/prisma/blob/master/CONTRIBUTING.md) to get this setup
- added  `'arm-openssl-1.1.x'` to `const knowPlatforms: Platform[]=[…`in `src/packages/engine-core/src/NodeEngine.ts`
- added `'arm-openssl-1.1.x'` to `type Platform = …` and `export const platforms = […` in `src/packages/get-platform/src/platforms.ts`
- ran through first steps in [CONTRIBUTING.md](https://github.com/prisma/prisma/blob/master/CONTRIBUTING.md) again to build all packages
- adapted my project to use `pnpm`
- linked the cli to my project `pnpm link ../../prisma/prisma-fork/src/packages/cli`
- ran my generate commands
- got a beer from the fridge
- padded my back


See my changes [github.com/fabianmoronzirfas/prisma/tree/feature-raspberry-pi](https://github.com/fabianmoronzirfas/prisma/tree/feature-raspberry-pi)

**Comment by pantharshit00** [comment]
That is some real dedication 😅. Thanks for documenting.
