### ISSUE TITLE
Prisma 2 preview 0.21 Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by enzoftware** [prisma/prisma2#1511]
After upgrade the prisma enviroment to the preview 0.21 all the fields in my objectTypes that refer to another object start failing with the message.

` {
  "data": null,
  "errors": [
    "Cannot read property 'findOne' of undefined"
  ]
}`

Here is the objectType.

```ts
export const PostLikeGql = objectType({
  name: 'PostLike',
  definition(t) {
    t.model.id()
    t.model.user() // This model is affected and doesn't work anymore
  },
})
```

If anyone could help, I try to clean and reinstall and teh error keeps. Thanks.

**Comment by pantharshit00** [comment]
@enzoftware We had a breaking change in `preview021` which broke compatibility with older version of nexus-prisma. Please upgrade to `nexus-prisma` version greater than `0.9.0` to fix this error.

**Comment by enzoftware** [comment]
Thanks, I forgot to update it in `devDependecies`
