### ISSUE TITLE
Remove enabled field from datasource block

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1512]
The "enabled" field on the datasource block is not used/implemented and will be removed soon. 

This issue tracks removing it from code and docs.

**Comment by divyenduz** [comment]
Internal note: This is a residue from the last planning meeting and it was on my list to create a tracking issue and mark it as a candidate.

**Comment by janpio** [comment]
@schickling is working on something related, so he should be aware of this issue.

**Comment by janpio** [comment]
Internal Note: @nikolasburk says already removed from docs, @mavilein says removed from code.
