### ISSUE TITLE
Prisma doesn't work on Azure windows functions

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#1518]
Running prisma results in this runtime azure functions error:

```
Result: Failure
Exception: Error: 
Invalid `prisma.()` invocation in
D:\home\site\wwwroot\prisma-e2e-windows-test\index.js:45:58



EACCES: permission denied, chmod 'D:\home\site\wwwroot\node_modules\@prisma\client\runtime\query-engine-windows.exe'
Stack: Error: 
Invalid `prisma.()` invocation in
D:\home\site\wwwroot\prisma-e2e-windows-test\index.js:45:58



EACCES: permission denied, chmod 'D:\home\site\wwwroot\node_modules\@prisma\client\runtime\query-engine-windows.exe'
    at PrismaClientFetcher.request (D:\home\site\wwwroot\node_modules\@prisma\client\index.js:79:27)
```

The underlying OS is Windows. When using Linux, everything works fine.

Reproduction is difficult because an azure account is required, but it's available in the [e2e testing repo](https://github.com/prisma/prisma2-e2e-tests/tree/feat/platforms/azure-windows/platforms/azure-functions-windows).

**Comment by janpio** [comment]
What is the easiest way to try to reproduce this locally on Windows?

Does the file `D:\home\site\wwwroot\node_modules\@prisma\client\runtime\query-engine-windows.exe` actually exist? What are its "file permissions" (which I did not know existed on Windows)? Does `prisma2` also have a binary like this? What is different between those?

**Comment by steebchen** [comment]
> What is the easiest way to try to reproduce this locally on Windows?

I don't know how to reproduce this locally. The file system on Azure may be read-only which denies changing the binary.

> Does the file D:\home\site\wwwroot\node_modules\@prisma\client\runtime\query-engine-windows.exe actually exist? 

Yes.

> What are its "file permissions" (which I did not know existed on Windows)?

I don't know. I'm having trouble figuring out reading logs from azure.

> Does prisma2 also have a binary like this? What is different between those?

I don't understand the question.

**Comment by janpio** [comment]
> I don't understand the question.

The `prisma2` installation should also have a file `query-engine-windows.exe`. Maybe something in permissions or other attributes of that file could point to what is wrong with the client one.

**Comment by schickling** [comment]
Related: https://github.com/prisma/prisma-client-js/issues/466

**Comment by Jolg42** [comment]
Works since I removed `chmod +x` when `process.platform === win32` from prisma-client-js (alpha 848)
