### ISSUE TITLE
Only support `.env` file next to `schema.prisma`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma2#1519]
As of now, the `prisma2` cli checks and uses a `.env` file in the current working directory. We will change this to only read a `.env` file which is in the same directory as the `schema.prisma` file.

As proposed in https://github.com/prisma/prisma-client-js/issues/454, we want to introduce support for a `.env` file in the Prisma Client.
As we want to limit the `.env` file usage only to the scope of Prisma and not the whole application, as that's not the responsibility of Prisma, the `.env` file will only be used by the Prisma Client, if it is next to `schema.prisma`.

This change also has to be reflected in the `prisma2` cli, it should only read a `.env` file, if it's next to the `schema.prisma` file, which is in most cases in the `./prisma` directory.

**Comment by Jolg42** [comment]
Current implementation is here
https://github.com/prisma/prisma-client-js/blob/7be5f9d607f8ba086a76904e0f54b5ef07f109dc/packages/photon/src/generation/TSClient.ts#L553

**Comment by homoky** [comment]
It leads to need of two env files. Would suggest to revert it.

**Comment by huv1k** [comment]
I second this, it leads to worse developer experience overall.

**Comment by Jolg42** [comment]
@homoky @huv1k so you could call `dotenv` explicitly like this in your code:

Folder structure
<img width="121" alt="Screen Shot 2020-02-25 at 12 18 09" src="https://user-images.githubusercontent.com/1328733/75242718-ebd67e80-57c8-11ea-8b0d-34df71a18457.png">

`npm install dotenv` to install & add the dependency in your package.json

```ts
import * as dotenv from "dotenv";
import { PrismaClient } from "@prisma/client";

dotenv.config();

async function main() {
  const prisma = new PrismaClient();

  const users = await prisma.user.findMany({});
  console.log(users);
}

main();
```

Here I have only one `.env` file in my project root folder and everything works perfectly 😉

**Comment by pantharshit00** [comment]
@Jolg42 I think that has another side to it that we the cli don't generate client from the root `.env` file.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/22195362/75258222-23b2e580-580c-11ea-8157-7e73c6e2f0e9.png">

**Comment by huv1k** [comment]
@pantharshit00 yes, exactly this :) Now you can't use `CLI` commands with `.env` file located in different paths.

**Comment by dkozma** [comment]
Thanks for the `dotenv` solution, @Jolg42.

Regarding the CLI, if we can specify the location of the .env file using `prisma2 generate` such as:
```
prisma2 generate --env-file=.env
```
 that would be helpful, since now I have to symlink my `.env` from the root, or have two files.

**Comment by homoky** [comment]
Solutions are great, but would not be better to keep things clean and simple?

**Comment by dkozma** [comment]
@homoky I wouldn't be against reverting this change either - I'm all for simplicity, and personally this change has caused more pain than it has solved.

**Comment by maartenraes** [comment]
Also in favor of reverting this, it breaks our pipelines because we use `.env`, `.env.test` and `.env.production` based on environments and during pipelines. 

Since there's only support for a `.env` and not for different environments based on NODE_ENV it's a pain to maintain now.

**Comment by janpio** [comment]
> and not for different environments based on NODE_ENV it's a pain to maintain now.

Can you elaborate on this in a new issue please? Might be an oversight of a use case we are not aware of and just didn't think about. Thanks 🙏

**Comment by maartenraes** [comment]
> > and not for different environments based on NODE_ENV it's a pain to maintain now.
> 
> Can you elaborate on this in a new issue please? Might be an oversight of a use case we are not aware of and just didn't think about. Thanks 🙏

Does this suffice? :-) 
https://github.com/prisma/prisma2/issues/1717

**Comment by janpio** [comment]
Absolutely - as soon as it is an explicit issue someone will think about it sooner or later.

**Comment by scriptcoded** [comment]
Is this change not supposed to go for `prisma2 migrate`? Should I raise an issue

**Comment by janpio** [comment]
Yes, creating a new issue is almost always the solution if something else got closed. I am not super sure what you mean by "go for `prisma2 migrate`", so looking forward to read about it in a new issue @scriptcoded.

**Comment by dizzyn** [comment]
Please reconsider this feature - to keeping two .envs (one for prisma, one for the rest) is confusing. Or please make that backward compatible - read also the root one if exists.

**Comment by janpio** [comment]
@dizzyn You can put the `.env` fiel anywhere you want for Prisma Client, you just need to load it manually yourself if it is anywhere than in this default location where Prisma Client itself takes care of the loading.

**Comment by dkozma** [comment]
@janpio Is there a way to point to an `.env` file not in the default location when using the CLI tools (e.g. `yarn prisma2 generate`)?

**Comment by janpio** [comment]
No, but a request that would enable that is tracked in https://github.com/prisma/prisma2/issues/1255 Please upvote it if you want this functionality and maybe leave a comment with your usecase.

**Comment by leohxj** [comment]
Prisma generate does not relay on env, right?
I pass special env when it runs.

**Comment by Jolg42** [comment]
@leohxj how do you pass the special env?

In 2.2.0 there is a problem with `.env` file loading with the CLI, this will be fixed in a patch next week. (https://github.com/prisma/prisma/pull/2981)

**Comment by leohxj** [comment]
@Jolg42 it is my mistake, I want to explant that `prisma generate` does not use env, `prisma save/up` use it.
but I remeber previous prisma version, generate also use env?? It should a bug that fixed.

**Comment by Jolg42** [comment]
So you probably hit the issue in your case, we will issue the fix on Monday :) Thanks!

**Comment by Jolg42** [comment]
@leohxj The issue is fixed in the latest version of @prisma/cli: 2.2.1

Related https://github.com/prisma/prisma/issues/2971

**Comment by leohxj** [comment]
@Jolg42 thanks

**Comment by gildniy** [comment]
I got them working with these scripts, as from [this issue](https://github.com/prisma/prisma/issues/1255)

```
    "start:dev": "cross-env NODE_ENV=development ts-node-dev --no-notify --respawn --transpile-only src/server.ts",
    "db:save-dev": "dotenv -e dotenv/development.env -- npx prisma migrate save --experimental",
    "db:up-dev": "dotenv -e dotenv/development.env -- npx prisma migrate up --experimental",
```
And I serve the environment variables from the `config/env.js` file:

```
const path = require('path')
const dotenv = require('dotenv')

const envPath = path.resolve(__dirname, `../../dotenv/${process.env.NODE_ENV}.env`)

dotenv.config({path: envPath});

const {JWT_SECRET} = process.env

export const envVars = {JWT_SECRET};
```
