### ISSUE TITLE
[Introspection] Investigate `panic-no-id-field-defined` schemas

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1524]
Some schemas currently fail in the QE step and throw a panic in Rust. We track these internally as `panic-no-id-field-defined` (`Model (probably) has @@id, but Query Engine panics because unsupported`).

We are working on fixing this limitation of course, but until that is not released, we are kind of blocked on these schemas. To unblock us, I want to investigate these schemas:

1. Look at model that is causing the panic
2. Find a way to unblock the QE
3. See what happens then
4. Commit that modified schema to our collection and deploy to special server, add to introspection analysis CI

It makes sense to start by looking only at a subset of them, e.g. only `mysql_public`.

(Internal: https://www.notion.so/prismaio/Modify-id-blocked-schemas-to-be-id-less-d0b09b8f36fc436a8afec1246fc471b4)

**Comment by do4gr** [comment]
This is fixed now, for an explanation see https://github.com/prisma/prisma2/issues/1515

**Comment by janpio** [comment]
Previous collection of schemas: https://github.com/prisma/prisma2/issues/1114#issuecomment-565805255

**Comment by janpio** [comment]
First result: https://github.com/prisma/introspection-engine-output/pull/148/commits/661b9c9a01c8f693ace601bb4bfb43a58b7aaaca

drupal, matomo, modx-revolution, northwind and wordpress are now passing with this change. chinook, concrete5 and employees are now failing with `Unable to resolve scalar field` (https://github.com/prisma/prisma2/issues/1377)

**Comment by janpio** [comment]
After the first AUMFIDARR merges, this error does not occur any more.
