### ISSUE TITLE
prisma2 generate fails in Heroku build

### ISSUE THREAD

**Issue by seanemmer** [prisma/prisma2#1525]
I am attempting to run Prisma inside of Heroku 18 node.js.  The following are from my package.json:

```
  "engines": {
    "node": "12.14.1"
  },
  "scripts": {
    "postinstall": "prisma2 generate"
  },
  "dependencies": {
    "prisma2": "2.0.0-preview021"
  }
```

I get the following error during installation:

```
Error: Error: Command failed with ENOENT: /tmp/build_beae1b0150b0593ec3b0251a339290fe/node_modules/prisma2/query-engine-debian-openssl-1.1.x cli --dmmf
spawn /tmp/build_beae1b0150b0593ec3b0251a339290fe/node_modules/prisma2/query-engine-debian-openssl-1.1.x ENOENT
```

**Comment by seanemmer** [comment]
I just confirmed that this issue occurs with the official apollo example repo when doing a vanilla Heroku deploy (i.e. git push heroku master):

https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-apollo-server

**Comment by schickling** [comment]
Additionally to improving this situation when using Prisma on Heroku, I suggest to generally improve the error handling in this scenario as described here: https://github.com/prisma/prisma-client-js/issues/466

**Comment by seanemmer** [comment]
I was able to get the build to succeed by setting the node version to 12.0.0
