### ISSUE TITLE
Improve documentation around securing your database connection with SSL

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma2#1527]
Recently I tried setting up prisma2 with a SSL-secured postgres database. 

There is some documentation about it [here](https://github.com/prisma/prisma2/blob/master/docs/core/connectors/postgresql.md).

However with the information provided here I was not able to get it to work for me.

I am not sure which of the parameters are required and how the connection string should look like in the end, especially, because there are paths to files in there.

Although maybe not related to prisma2 it would also be nice to know what is the best way to store the keys in prod

Edit: It might also be a good idea to link to some place where generating a S12 keystore(?) is explained

**Comment by BjoernRave** [comment]
Just saw this related issue: https://github.com/prisma/prisma2/issues/1463 
Maybe this is even a duplicate

**Comment by janpio** [comment]
You are right @BjoernRave - I was not aware of that one. Thanks for pointing this out, I will close this now then.
