### ISSUE TITLE
`@prisma/client@x is not compatible with prisma2@y. Their versions need to be equal.`, generates anyway

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1539]
```
C:\Users\Jan\Documents\throwaway\1496
λ npx prisma2@alpha generate
⚠️ @prisma/client@2.0.0-preview021 is not compatible with prisma2@2.0.0-alpha.735. Their versions need to be equal.
Generated Prisma Client to .\node_modules\@prisma\client
Done in 13.52s
```

Is this a warning or an error? The further output indicates it generated anyway. Should it do that or should it really fail?

**Comment by schickling** [comment]
Does this mean we have a systematic way to distinguish when it should be a warning because it's a best practice to keep the versions in sync vs an actual error due to incompatibility?

**Comment by janpio** [comment]
Talked a bit with Johannes what he means here:

He basically wants to know if we have a way to figure out if we a) just need to warn out of principle, but it will still work vs. b) we need to error as the versions fail that it is so incompatible that it can not work?

If we do not, just warning here is quite risky and might not be what we want/should do.

**Comment by schickling** [comment]
This should probably be specced out as well (cc @sorenbs).

**Comment by matthewmueller** [comment]
I've run into this as well and it took me about 5 minutes to understand what was going on. 

Some issues & suggestions:

1. You're probably going to assume `@prisma/photon@2.0.0-preview018.2` and `prisma2@2.0.0-preview018.2` are the same package when you first scan over it. We should make this more clear that the **Prisma Client** depends on a particular version of the **CLI**
2. We should call out that this is a warning and you may not need to deal with this.

Last a matter of opinion – this communicates to me that we're going to **regularly** make breaking changes to the Prisma Client runtime, so we **require** you to keep these packages in lockstep. We should know when we're going to make breaking changes and show this warning at those transition marks, not every time.

**Comment by janpio** [comment]
> 1. You're going to assume `@prisma/photon@2.0.0-preview018.2` and `prisma2@2.0.0-preview018.2` are the same package when you first scan over it. The names are too similar. We should make this more clear that the **Prisma Client** depends on a particular version of the **CLI**

The error message should probably make this more explicit by not just printing the package names, but annotating them in some way.

> 2\. We should call out that this is a warning and you may not need to deal with this. This is 5 minutes of focus lost on something that's not building my product.

In the comments above we are discussing if a warning is actually enough here or if this should/has to be an error.

> Lastly a matter of opinion: this communicates to me that Prisma is going to **regularly** make breaking changes to the Prisma Client runtime, so Prisma **requires** you to keep these packages in lockstep.
> 
> This makes me sad. We should know when we're going to make breaking changes and show this warning at those transition marks (with custom messages), not every single time.

Valid point, please open a new issue for this so this does not get lost.

**Comment by janpio** [comment]
Decision: We talked it through, and right now there is no reason to have this warning in the first place because CLI and Client can currently be used in any combination. In the future we might want to have a versioning system for the internal API, which could lead to errors on mismatch.

**Comment by Jolg42** [comment]
Based on this decision, I'll make a PR to remove this log @janpio.
Do we want to keep it as an internal debug log maybe?

**Comment by janpio** [comment]
If that is useful to you, sure! 👍

**Comment by Jolg42** [comment]
I removed it in https://github.com/prisma/prisma2/commit/45fbde1a3e37e9ad8c05099f6a4ddafd637c4a23
