### ISSUE TITLE
Improve DX about --experimental CLI commands

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1547]
- Help output should include information that --experimental is required
- Add a big fat warning to all the output, possibly backed by a docs page that explains what our experimental stuff means (by @nikolasburk)

**Comment by Jolg42** [comment]
So should we add it only to `prisma2 migrate --help` or also all the subcommands to be safe?

Suggestion for the warning text / format:
<img width="582" alt="Screen Shot 2020-02-07 at 15 03 43" src="https://user-images.githubusercontent.com/1328733/74035728-1d72db80-49bb-11ea-9d92-6667bec68458.png">

**Comment by janpio** [comment]
Let's start with the `--help` for now.

**Comment by Jolg42** [comment]
@janpio Tim suggested all lift commands and it's implemented like that. I guess we're extra safe now :)
