### ISSUE TITLE
Download prints many empty lines

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma2#1551]
![image](https://user-images.githubusercontent.com/1094804/74031814-cbc65300-49b2-11ea-8dc9-7dd415c334e9.png)

**Comment by Jolg42** [comment]
Can't reproduce with latest alpha @timsuchanek 
<img width="623" alt="Screen Shot 2020-02-14 at 15 31 41" src="https://user-images.githubusercontent.com/1328733/74540203-a354d080-4f3f-11ea-9de7-3ab599c9fd45.png">

**Comment by pantharshit00** [comment]
Same, I also can't reproduce this.

**Comment by timsuchanek** [comment]
Closing this until we have a reproduction.
