### ISSUE TITLE
How do I install the prettier schema?

### ISSUE THREAD

**Issue by SlateDave** [prisma/prisma2#1557]
Are there any resources on that yet?

**Comment by pantharshit00** [comment]
I am not sure what you are referring here. If you referring to the auto-formatting extension that we provide for vscode, you can get it from here: https://marketplace.visualstudio.com/items?itemName=Prisma.prisma

Otherwise, please elaborate your question a bit.

**Comment by flybayer** [comment]
The OP probably has the same question I have — is there currently any way to configure prettier to format `.prisma` files?

**Comment by pantharshit00** [comment]
@flybayer Currently no, we don't have a prettier plugin for Prisma. Right now the only way to format Prisma schema is the vscode extension.

**Comment by janpio** [comment]
Someone should open a proper feature request issue that explains why a pure prettier plugin would be beneficial to the VSCode extension 👍

**Comment by flybayer** [comment]
I opened issue #1761 to request a prettier plugin.

**Comment by janpio** [comment]
Thanks @flybayer - I think we can close this now. If someone has additional reasons for having a prettier plugin, please post to #1761 🙏 🚀

**Comment by ezzcodeezzlife** [comment]
Use `npx prisma format` command, for more details check help npx @prisma/cli format -h
