### ISSUE TITLE
Prisma2 CLI is binary on Ubuntu 16.04 doesn't link to install libssl

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#157]
Starting `2.0.0-preview-1` Prisma2 is downloading the wrong binary
![image](https://user-images.githubusercontent.com/22195362/61134144-93be6680-a4dc-11e9-91fb-f2ac92adf086.png)

It should download linux-glibc instead on linux-lamba on Ubuntu 16.04 x86-64

Detection was working correctly in 0.0.128

![image](https://user-images.githubusercontent.com/22195362/61134241-d3854e00-a4dc-11e9-9a0f-faba048730b0.png)

**Comment by pantharshit00** [comment]
Ok, I was using Ubuntu 16.04 which comes with libssl 1.0.2.

Right now we are directly fetching the binary for lambda if we have libssl 1.0.2(https://github.com/prisma/photonjs/blob/96301aef4c49290170e8b569e558199eeb8ee4c4/packages/fetch-engine/src/download.ts#L336) which should not be the case.

Ubuntu 16.04 is supported till April 2021 so we should definitely fix this.

**Comment by timsuchanek** [comment]
@pantharshit00 the behavior is correct and intended. The `linux-lambda` links to libssl 1.0.2, which is the default for Ubuntu 16.
The problem is rather setting up proper libssl on Ubuntu 16, which is a documentation issue.

**Comment by ansarizafar** [comment]
Is there any solution? I am still unable to use Prisma2 cli on Ubuntu 16.04.

**Comment by pantharshit00** [comment]
Immediately solution will be to upgrade to ubuntu 18.04

**Comment by divyenduz** [comment]
This issue gets more urgent as it is the default option of netlify

![image](https://user-images.githubusercontent.com/746482/62881652-8e994500-bd30-11e9-94fc-19e162f9755a.png)

**Comment by divyenduz** [comment]
To mitigate this, we plan to have Ubuntu 16.04 in our build pipeline and the CLI while installation will detect Ubuntu 16.04 and download the correct binary.

**Comment by dpetrick** [comment]
This is done. New build target is added and afaik @timsuchanek added it to the available targets.

**Comment by divyenduz** [comment]
I can confirm that this works in `alpha`. Please re-open the issue if the problem persists.
