### ISSUE TITLE
Quickstart Prisma Migrate Error

### ISSUE THREAD

**Issue by BenJeau** [prisma/prisma2#1573]
### Description
I've been trying the [Prisma Migrate Quickstart](https://github.com/prisma/prisma2/blob/master/docs/getting-started/start-from-scratch-with-empty-db/quickstart-prisma-migrate.md), but when I reach the last step, I get this strange error (by strange I mean that I can connect to the database via psql and query the "public"."User" table and this error says that it does not exist),

```
Reason: Error occurred during query execution:
ConnectorError(ConnectorError { 
   user_facing_error: None,
   kind: QueryError(Error{ 
      kind: Db,
      cause: Some(DbError{ 
         severity: "ERROR",
         parsed_severity: Some(Error),
         code: SqlState("42P01"),
         message: "relation \"public.User\" does not exist",
         detail: None,
         hint: None,
         position: Some(Original(13)),
         where_: None,
         schema: None,
         table: None,
         column: None,
         datatype: None,
         constraint: None,
         file: Some("parse_relation.c"),
         line: Some(1159),
         routine: Some("parserOpenTable")
      })
   })
})
```

Would anyone have a pointer?

### System
OS: Ubuntu 18.04

**Comment by pantharshit00** [comment]
Hi @BenJeau,

I tried out our quickstart guide to make sure that steps are correct and they indeed work. The error message suggest that tables are missing from your database. 

So can you please run `npx prisma2 migrate save --experimental` and `npx prisma2 migrate up --experimental` in order to create the tables and try the script again.

Let me know if you are still getting into any trouble.

**Comment by pantharshit00** [comment]
Internal note: I am not moving this to migrate repository as this is related to documentation.

**Comment by BenJeau** [comment]
I reran both commands, it gave me a different error, something along the lines `message: "permission denied for relation User"`.

After deleting the database and rerunning the steps in the quickstart multiple times, it magical works... not sure what I did to make it work, but thank you for the help :)

**Comment by pantharshit00** [comment]
Ok, I am going to close this. Feel free to comment here or open a new issue if you still encounter any problems.
