### ISSUE TITLE
[Introspection] Change work distribution between CLI and Introspection Engine

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma2#1576]
Currently the CLI does several RPC calls during `introspect`:

1. Introspect on the Introspection Engine with a url which returns a datamodel including datasource and generators
2. Get Config on the Query Engine to get the datasources and generators from the datamodel
3. Get DMMF via the Query Engine which parses the datamodel and can lead to datamodel validation errors
4. DMMFToString on the Query Engine, which returns the datamodel string the CLI then prints

This leads to a mix up of introspection errors and validation errors as well as query engine errors. 

We want to change this to more clearly separate responsibilities between the engines:
The CLI should:
1. Call introspection on the Introspection Engine with a complete schema including datasources and generators
       A. The Introspection Engine then calls getConfig itself to get the datasource
       B. It then introspects the datasource and renders the datamodel into the schema
       C. It returns this unchecked to the CLI which stores it
2. The user can then call generate or validate in a separate step which will trigger the validation of the datamodel by the parser and potentially return validation errors

**Comment by janpio** [comment]
For Introspection CI this will mean we will not get the validation errors from `introspect` any more, but that we have to call `generate` (or `validate`) to get them. This will probably change where and how we get the output we need to analyse as well @divyenduz

**Comment by timsuchanek** [comment]
Implemented in the latest alpha.
