### ISSUE TITLE
[Redwood.js] provider = "redwood"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1578]
Redwood wants to enable their users to use SQLite in dev, and Postgres in production. To enable that, they need some special logic:

- Redwood creates the schema with a (virtual) provider called `redwood`
- When calling Prisma commands, Redwood uses `--schema` to supply a dynamically generated version of the schema where `redwood` is replaced depending on the environment (with `sqlite` or `postgres`)

(Internal context: https://www.notion.so/prismaio/provider-redwood-fd04ffcc9c684a9bb5cdb5d5a5fc2ecc + https://prisma-company.slack.com/archives/CL0AJEVSA/p1580897189010000)

---

Tasks:

- Double check that `--schema` works for this
- Schema validator and VSCode (and whoever else looks at the provider) have to be happy about `redwood`
- (Optional) Our CLI could detect redwood specific stuff (like `redwood`) and point user to use it instead of Prisma directly (because directly we will not do the replacing things and stuff might break)

**Comment by steebchen** [comment]
I can confirm that `--schema` works for the commands `generate`, `migrate save` and `migrate up`.

Providing `redwood` as a provider fails, because Prisma is not aware of such a provider. I'm not quite sure if we need this when redwood dynamically replaces this value before sending the schema to the Prisma CLI.

**Comment by janpio** [comment]
## Current state in VS Code:
![image](https://user-images.githubusercontent.com/183673/74339679-db73dc00-4da4-11ea-8bca-23c0c5997b46.png)

## Current output for `prisma2` CLI commands:
```
C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood>npx prisma2 validate
Error: Schema parsing
error: Datasource provider not known: "redwood".
  -->  schema.prisma:9
   | 
 8 | datasource db {
 9 |   provider = "redwood"
   | 

Validation Error Count: 1
```

```
C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood>npx prisma2 generate
Error: Schema parsing
error: Datasource provider not known: "redwood".
  -->  schema.prisma:9
   | 
 8 | datasource db {
 9 |   provider = "redwood"
   | 

Validation Error Count: 1
```

```
C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood>npx prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:413:19)
    at writeOrBuffer (_stream_writable.js:401:5)
    at Socket.Writable.write (_stream_writable.js:301:11)
    at C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood\node_modules\prisma2\build\index.js:2:900273
    at new Promise (<anonymous>)
    at IntrospectionEngine.<anonymous> (C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood\node_modules\prisma2\build\index.js:2:899037)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood\node_modules\prisma2\build\index.js:2:893464)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
 ERROR  Oops, an unexpected error occured!
[src\libcore\result.rs:1188:5] called `Result::unwrap()` on an `Err` value: ErrorCollection { errors: [SourceNotKnownError { source_name: "redwood", span: Span { start: 447, end: 456 } }] }
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry
```
(Connected error report for Introspection: https://prisma-errors.netlify.com/report/1954)

## Experimental CLI commands:
```
C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood>npx prisma2 studio --experimental
Failed to generate Photon client: Error: Schema parsing
error: Datasource provider not known: "redwood".
  -->  schema.prisma:9
   | 
 8 | datasource db {
 9 |   provider = "redwood"
   | 

Validation Error Count: 1
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood\node_modules\prisma2\build\index.js:2:2166778)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood\node_modules\prisma2\build\index.js:2:2163038)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

```
C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood>npx prisma2 migrate save --experimental
Error: Get config {"is_panic":false,"message":"error: Datasource provider not known: \"redwood\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"redwood\"\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Datasource provider not known: \"redwood\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"redwood\"\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
```

```
C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood>npx prisma2 migrate up --experimental
Error: Get config {"is_panic":false,"message":"error: Datasource provider not known: \"redwood\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"redwood\"\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Datasource provider not known: \"redwood\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"redwood\"\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
```

**Comment by janpio** [comment]
I think Redwood should already be able to fully build what they are aiming for, `--schema` works and if they call all the CLI commands with that `redwood` should never make it to Prisma CLI to fail this way.

We now have to decide where and how we want to either a) enable `redwood` as a valid value or b) fail with a nicer error message that tells people to use the Redwood CLI.

@schickling?

**Comment by janpio** [comment]
(Internal repo to be able to test with `provider=redwood` directly: https://github.com/prisma/prisma2-provider-redwood)

**Comment by janpio** [comment]
We are waiting here for Redwood to give feedback on if this all actually works, and to be able to test it out ourselves. If necessary, we might add some handling to our VSCode extension and our CLI.

**Comment by cannikin** [comment]
@janpio Thanks for this! I'm a little confused as to how to test it, however. 

* Is all of this in the latest preview022 or is there another branch we need to be testing against? 
* What do we actually pass to the `--schema` flag, a string or the location to a file? 
* If we're passing whatever we want through `--schema` do we really need to use `"redwood"` at all, couldn't we just set that to `sqlite` or `postgresql` based on what our `url` connection string is set to?

**Comment by janpio** [comment]
- The `--schema` functionality is available since `preview022`.
- `--schema` takes a filename
- ... which allows you to create a temporary version of the schema with `"redwood"` being replaced with the real value. In my understanding you would still have the user visible `prisma.schema` with `"redwood"` and do the replacement on runtime.

Does this help or was something lost along the way here?

**Comment by cannikin** [comment]
We got it! It looks like this is working for us, thanks so much!

**Comment by janpio** [comment]
Wonderful. Let me know if you hit any kinks or have ideas how to improve or change the behavior.

**Comment by janpio** [comment]
Further work here is not necessary, Redwood is mostly looking forward to https://github.com/prisma/prisma2/issues/1487 now.
