### ISSUE TITLE
Improve .raw`` template literal API with parameters

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1583]
The current .raw`` template literal API is limited (no parameters allowed)

## Current status

```ts
const result = await prisma.raw`SELECT * FROM USER;`
// result = [
//   { "id":1, "email":"sarah@prisma.io", "name":"Sarah" },
//   { "id":2, "email":"alice@prisma.io", "name":"Alice" }
// ]
```

## Current limitation
It's currently not possible to pass any arguments to the SQL statement:

```ts
// not possible
const userId = 1
const result = await prisma.raw`SELECT * User WHERE id = ${userId};`
```
https://github.com/prisma/prisma2/blob/docs/preview022/docs/prisma-client-js/api.md#raw-database-access

We could use https://github.com/blakeembrey/sql-template-tag

**Comment by Jolg42** [comment]
Reopen for docs update needed @nikolasburk 

It's now possible to use parameters and they will be escaped.

```js
const table = `USER`
const result = await prisma.raw`SELECT * FROM ${table};`
```

**Comment by janpio** [comment]
Please open a new issue for the separate docs update.

**Comment by Jolg42** [comment]
@janpio moved the docs update to https://github.com/prisma/prisma2/issues/1688
