### ISSUE TITLE
Document workarounds for No-identifier-tables

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1588]
We do not support No-identifier-tables (no PK, no UNIQUE) right now and thus have to comment them out in the schema for now. When this happens, we want to output a warning to the user that includes a link (https://github.com/prisma/prisma2/issues/1574) to some documentation that tells them how possibly work around this to make these tables accessible to Prisma Client.

1. Add a Primary Key (e.g. Int, auto_increment) to the table
2. Add a UNIQUE Index to the table
3. Add a virtual `(@)@unique` to the table (investigation if this is possible at https://github.com/prisma/prisma2/issues/1587)

**Comment by nikolasburk** [comment]
Added via https://github.com/prisma/prisma2/pull/1656

Note that you can link to the new section with: https://pris.ly/d/introspection#common-workarounds
