### ISSUE TITLE
Error in Studio from v0.0.116 to v0.0.117

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma2#159]
Ever since migrating from `prisma2@0.0.1xx` to `prisma2@0.0.117` and higher, I’m encountering the following error (use a new sqlite db for development each time). It’s still working for `prisma2@0.0.116` so whatever happened between `0.0.116` and `0.0.117` broke something.

`prisma2 lift save && prisma2 lift save && prisma2 dev`

![image](https://user-images.githubusercontent.com/11673745/61166499-38dc3d80-a4e3-11e9-9f32-b0d9d6937cfc.png)

**Comment by nickreynke** [comment]
I am getting kind of the same issues here with version `prisma2@2.0.0-preview-1, binary version: 30a33bde5b1d9f79e0a48491749528da76002e24` of Prisma2 when I run the following with an environment variable:

```bash
POSTGRES_URL="postgresql://prisma:prisma@localhost:5433/prisma" prisma2 dev
```

This is the output when I open `http://localhost:5555/`:

<img width="543" alt="Screenshot 2019-07-14 at 11 13 48" src="https://user-images.githubusercontent.com/3816295/61181576-beb5d100-a628-11e9-8f78-417a3f9b6807.png">

**Comment by Megoos** [comment]
> Ever since migrating from `prisma2@0.0.1xx` to `prisma2@0.0.117` and higher, I’m encountering the following error (use a new sqlite db for development each time). It’s still working for `prisma2@0.0.116` so whatever happened between `0.0.116` and `0.0.117` broke something.
> 
> `prisma2 lift save && prisma2 lift save && prisma2 dev`
> 
> ![image](https://user-images.githubusercontent.com/11673745/61166499-38dc3d80-a4e3-11e9-9f32-b0d9d6937cfc.png)

I have the same problem. After version 0.0.114 does not work.

**Comment by pantharshit00** [comment]
I can confirm this. This is still present in `prisma2@2.0.0-alpha.12, binary version: c11e72b1065b73d01f881b7f53501f2b5e33c7ae`. 

To reproduce this, just start a new project and try to open the studio

**Comment by madebysid** [comment]
Hey @heymartinadams @nickreynke @Megoos, sorry for the delay in this response. We've been making some significant changes to Studio over the last few weeks, and I believe this error should be gone now. Could you guys try updating `prisma2` to the latest preview (preview-3) and try again?

If you still see it, please let me know and I'll look into it!

**Comment by pantharshit00** [comment]
Yes, it is working fine in preview 3
