### ISSUE TITLE
`prisma init` Folder handling

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#16]
How should we handle when running `prisma init` in a directory with existing files? Should we also allow for `prisma init [new-folder]`? 

Let's also see what we can learn from this: https://zeit.co/blog/now-init

**Comment by divyenduz** [comment]
This workflows is already in the CLI, we should consider removing it if anything speaks against it.

**Comment by schickling** [comment]
@divyenduz continued here: https://github.com/prisma/specs/issues/21
