### ISSUE TITLE
Unable to compile TypeScript following "Get Started" Guide - Could not find a declaration file for module '@prisma/client'

### ISSUE THREAD

**Issue by robin-macpherson** [prisma/prisma2#1600]
**Set up:**
- `@prisma/client: 2.0.0-preview021`
- `Prisma2: 2.0.0-preview021`

While following the newest [Get Started Guide](https://github.com/prisma/prisma2/blob/master/docs/getting-started/start-from-scratch-with-empty-db/quickstart-prisma-migrate.md) upon reaching the last step and trying to execute the `index.ts` script, I got the following error:

```
src/index.ts:1:30 - error TS7016: Could not find a declaration file for module '@prisma/client'. '/Users/robinmacpherson/robinmacpherson/backend/node_modules/@prisma/client/index.js' implicitly has an 'any' type.
  Try `npm install @types/prisma__client` if it exists or add a new declaration (.d.ts) file containing `declare module '@prisma/client';`

1 import { PrismaClient } from '@prisma/client'
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/34203886/74455925-ed07c300-4e3a-11ea-9200-75e35018113b.png)

**src/index.ts**
```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// A `main` function so that we can use async/await
async function main() {
  const user1 = await prisma.user.create({
    data: {
      email: 'alice@prisma.io',
      name: 'Alice',
      posts: {
        create: {
          title: 'Watch the talks from Prisma Day 2019',
          content: 'https://www.prisma.io/blog/z11sg6ipb3i1/',
          published: true,
        },
      },
    },
    include: {
      posts: true,
    },
  })
  const user2 = await prisma.user.create({
    data: {
      email: 'ryan@example.com',
      name: 'Ryan',
      posts: {
        create: [
          {
            title: 'Robin Is The Best!',
            content: "I'm telling you, it's true!",
            published: true,
          },
          {
            title: 'Journaly Is Going To Be Great',
            content: 'I am so excited to test out Journaly',
            published: false,
          },
        ],
      },
    },
    include: {
      posts: true,
    },
  })

  console.log(
    `Created users: ${user1.name} with (${user1.posts.length} post) and ${user2.name} with (${user2.posts.length} posts) `,
  )
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.disconnect()
  })

```

**Comment by pantharshit00** [comment]
Hello, I tested out our getting started guide and it works.
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/22195362/74532935-6ba55300-4f56-11ea-8d2f-25a15ce82556.png">


I would guess that you installed `@prisma/client` before you wrote your datamodel or forgot the save the model so our postinstall hook doesn't automatically generate the client. So can you please run `prisma2 generate` and try this again.

Maybe @nikolasburk want to take a look here and make this step explicit.

**Comment by robin-macpherson** [comment]
@pantharshit00 Thank you, this worked! Would you like me to open a quick Pull Request to make this step/requirement more explicit in the guide?

**Comment by nikolasburk** [comment]
Sounds good, how about adding `prisma2 generate` as an additional step after the `migrate` commands, so basically inserting it as the between the current steps 9 and 10?

Note that this shouldn't be necessary because `npm install @prisma/client` already generates Prisma Client, but I think it doesn't hurt making that step more explicit 👍 so yeah, a PR would be more than welcome @robin-macpherson 🙏

**Comment by robin-macpherson** [comment]
@nikolasburk @pantharshit00 PR is up! ✌🏼 I did infer a few things and try to add a little clarity for some users, please let me know if I got anything wrong or if you feel the little extra note is unnecessary and I'll be happy to make the changes right away 😊
