### ISSUE TITLE
[DataModel] Compound Foreign Keys and Index Definitions

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma2#1606]
The `@@index` definition currently has to refer to datamodel fields, but in the case of compound foreign keys  two or more database fields are collapsed into one datamodel field. The indexes on the other hand can refer to the underlying database fields which are not in the datamodel (apart from being in the `@map`). 

The `@@unique` definition theoretically has the same issue, but since we do not render it in the case of relations but instead make the relation 1:1 this issue does not surface. 

<img width="723" alt="Screen Shot 2020-02-14 at 11 05 40" src="https://user-images.githubusercontent.com/16278407/74521631-f6b42800-4f19-11ea-8f64-6cad6e036561.png">

**Comment by do4gr** [comment]
There is a similar problem with @@id on the Mondial MySql schema: 

<img width="944" alt="Screen Shot 2020-02-17 at 10 50 13" src="https://user-images.githubusercontent.com/16278407/74642499-640ec580-5173-11ea-8480-a58af2109dd3.png">

**Comment by mavilein** [comment]
@do4gr : I don't think this is the same thing. The casing is just wrong in this case. The field name is `province` and it is being referred to as `Province`.

**Comment by do4gr** [comment]
@mavilein I don't think it's a casing issue. The field is called province because this is a compound foreign key pointing to the model Province. Introspection therefore gave the combined field the name province. 

The @@id refers to the database columns Name and Province of which Province gets hidden since it is combined with Country into one relation field named province. If the spelling had been the same it would have accidentally worked.

**Comment by janpio** [comment]
Further examples:

mysql_127\AdventureWorks2014.log
![image](https://user-images.githubusercontent.com/183673/76107974-02a37f00-5fda-11ea-9b07-3e510930bf20.png)
```prisma
model SalesOrderDetail {
  CarrierTrackingNumber String?
  LineTotal             Float
  ModifiedDate          DateTime
  OrderQty              Int
  rowguid               String              @unique
  SalesOrderDetailID    Int                 @default(autoincrement())
  UnitPrice             Float
  UnitPriceDiscount     Float               @default(0)
  /// This used to be part of a relation to SalesOrderHeader
  SalesOrderID          Int
  specialOfferProduct   SpecialOfferProduct @map(["SpecialOfferID", "ProductID"])

  @@id([SalesOrderDetailID, SalesOrderID])
  @@index([SalesOrderID], name: "FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID")
  @@index([specialOfferProduct], name: "FK_SalesOrderDetail_SpecialOfferProduct_SpecialOfferIDProductID")
  @@index([rowguid], name: "GUID_SalesOrderDetail")
  @@index([ProductID], name: "IX_SalesOrderDetail_ProductID")
}
```

---

mysql_127\Basketball_men.log
![image](https://user-images.githubusercontent.com/183673/76108044-22d33e00-5fda-11ea-8097-afcac0fa1583.png)
```prisma
model awards_coaches {
  award   String?
  id      Int      @default(autoincrement()) @id
  lgID    String?
  note    String?
  coaches coaches? @map(["coachID", "year"]) @relation(references: [coachID, year])

  @@index([coachID], name: "coachID")
  @@index([coaches], name: "coachID_2")
  @@index([coaches], name: "coachID_3")
  @@index([coaches], name: "year")
  @@index([coaches], name: "year_2")
  @@index([year, coachID, lgID], name: "year_3")
}
```

---

mysql_127\tpcc.log
![image](https://user-images.githubusercontent.com/183673/76108197-70e84180-5fda-11ea-82fe-390a3c630a9c.png)
```prisma
model C_Order_Line {
  ol_amount     Float?
  ol_delivery_d DateTime?
  ol_dist_info  String?
  ol_number     Int
  ol_quantity   Int?
  c_Stock       C_Stock?  @map(["ol_i_id", "ol_supply_w_id"])
  /// This used to be part of a relation to C_Order
  ol_o_id       Int
  /// This used to be part of a relation to C_Order
  ol_d_id       Int
  /// This used to be part of a relation to C_Order
  ol_w_id       Int

  @@id([ol_o_id, ol_d_id, ol_w_id, ol_number])
  @@index([ol_i_id], name: "ol_i_id")
  @@index([c_Stock], name: "ol_i_id_2")
  @@index([ol_o_id, ol_d_id, ol_w_id], name: "ol_o_id")
  @@unique([ol_w_id, ol_d_id, ol_o_id, ol_number], name: "C_Order_Line_I1")
}
```

---

mysql_127\tpce.log
![image](https://user-images.githubusercontent.com/183673/76108296-983f0e80-5fda-11ea-99d7-cb3c7b99b95c.png)
```prisma
model E_HOLDING {
  H_DTS             DateTime?
  H_PRICE           Float
  H_QTY             Float
  e_HOLDING_SUMMARY E_HOLDING_SUMMARY @map(["H_CA_ID", "H_S_SYMB"])
  /// This used to be part of a relation to E_TRADE
  H_T_ID            Float             @id

  @@unique([H_CA_ID, H_S_SYMB, H_DTS, H_T_ID], name: "E_HOLDING_INDX1")
}
```

**Comment by janpio** [comment]
It is interesting to note, that the `mysql_127\Basketball_men.log` now looks slightly different from back when @do4gr posted his screenshot. The `@@index` now has a lot more `coaches` which I think might be a bug - the order of the fields _matters_ for indexes so we can not just replace it with the relation name.

**Comment by janpio** [comment]
There could/should also be cases where `@@id` is affected by this. Possibly this is not the case, as the errors are hidden by other errors (e.g. the one mentioned before in https://github.com/prisma/prisma2/issues/1606#issuecomment-586907016) - or it really is uncommon enough that none of our schemas have that.

**Comment by janpio** [comment]
I talked the situation through with @sorenbs and he generally agrees that being able to use the underlying column/field of course makes sense because that is what is happening. It is just awkward right now because `@map` is usually not used on Prisma level, but database level.

The problem is, that `@map` here is used in a different way than we usually use it (This is not documented in the specs, but implemented and there is issue about it at https://github.com/prisma/specs/issues/345 that describes something quite similar to what is implemented.)

A suggestion for a different syntax that avoid the overloading of `@map`: Use `@relation(fields: [...])` instead of `@map([...])`.

**Comment by janpio** [comment]
Actually, my last message shows a problem with my suggestion:
`@map` explicitly refers to database columns, and uses quotes to be able to refer to names PSL does not support. My suggestion `fields` does not, so we might have to have an additional @map in some cases which of course is quite ugly and messy. (This is not the case in any of the schemas we have I think, but could potentially be the case of course)

Unfortunately that thought also shows why using the `@map` values in `@@index` etc is "wrong" as well: Indexes should use field names, but in `@map` we list column names.

**Comment by janpio** [comment]
Another iteration then:

```diff
model E_HOLDING {
  H_DTS             DateTime?
  H_PRICE           Float
  H_QTY             Float
+ e_HOLDING_SUMMARY E_HOLDING_SUMMARY @map(["H_CA_ID", "H_S_SYMB"])
- e_HOLDING_SUMMARY E_HOLDING_SUMMARY @relation(fields: [H_CA_ID @map("_H_CA_ID"), H_S_SYMB @map("9H_S_SYMB")])
  /// This used to be part of a relation to E_TRADE
  H_T_ID            Float             @id

  @@unique([H_CA_ID, H_S_SYMB, H_DTS, H_T_ID], name: "E_HOLDING_INDX1")
}
```

This example assumes the columns are called `_H_CA_ID` and `9H_S_SYMB` which is unsupported because of the `_` and the `9` at the beginning of the string. That requires an `@map` for the field. But as they are part of a relation, the renamed field is put into `@relation(fields ...)`. The `@@unique` can the refer to the field name that is defined inside `fields`, but the engine can still know about the real column name via the `@map`.

**Comment by sorenbs** [comment]
I think this is the right approach.

There are quite a few things to consider:

### Prisma schema primitives.

Almost everything in the schema should operate on or reference prisma schema primitives. I believe `@map` is the only exception.

Therefore, the current implementation is too simplistic, and Jan's suggestion is an improvement. It introduces an extra layer, treating the fields that make up a compound relation as first class schema elements.

### Name conflicts?

Assume one of the columns in the compound relation has the same name as the relation field. We would have to disallow this:

```diff
model E_HOLDING {
  H_DTS             DateTime?
  H_PRICE           Float
  H_QTY             Float
+ e_HOLDING_SUMMARY E_HOLDING_SUMMARY @map(["e_HOLDING_SUMMARY", "H_S_SYMB"])
- e_HOLDING_SUMMARY E_HOLDING_SUMMARY @relation(fields: [e_HOLDING_SUMMARY , H_S_SYMB @map("9H_S_SYMB")])
  /// This used to be part of a relation to E_TRADE
  H_T_ID            Float             @id

  @@unique([H_CA_ID, H_S_SYMB, H_DTS, H_T_ID], name: "E_HOLDING_INDX1")
}
```

### Terminology

We now have two kinds of fields related to relations. What do we call them?

`relation field` and `sub relation field`?

```prisma
model E_HOLDING {
  relation_field E_HOLDING_SUMMARY @relation(fields: [sub_relation_field @map("relation_column")])
}
```

### Exposing sub relation fields in client

In the future we could choose to expose the sub relation fields in the client. This would resolve the [request to include sub relation fields in the default selection set](https://github.com/prisma/prisma-client-js/issues/217).

- We would probably want them to default to being read-only.
- We might want to also support filtering on them.
- because they share the namespace with normal fields, we don't need to wrap them or treat them specially in any way, which is nice.

### Syntax for @map on sub relation fields

This would be the first time we allow nested attributes:

```prisma
model E_HOLDING {
  relation_field E_HOLDING_SUMMARY @relation(fields: [sub_relation_field @map("relation_column")])
}
```



An alternative syntax could be:

```prisma
model E_HOLDING {
  relation_field E_HOLDING_SUMMARY @relation(fields: [sub_relation_field]) @map(["relation_column"])
}
```

This works relatively well for relations with one column, but gets complicated 

### Must the sub relation fields be explicitly spelled out in all cases?

For relations with more than one column, probably yes.

For relations

**Comment by janpio** [comment]
> Assume one of the columns in the compound relation has the same name as the relation field. We would have to disallow this:

We would probably comment something out as a guardrail here.

> We now have two kinds of fields related to relations. What do we call them?
> 
> `relation field` and `sub relation field`?

`relation sub field`?

> In the future we could choose to expose the sub relation fields in the client.

Let's consider this separately.



> An alternative syntax could be:
> 
> ...

That is much cleaner and I prefer it over mine. 

> This works relatively well for relations with one column, but gets complicated with multiple columns:
> 
> ...

That is ok, as this really is an uncommon case and it still follow sound logic.



> For relations with just a single column, the following simplification could be allowed when the `relation field` and `relation column` has the same name:
> 
> ...
> 
> turns into
> 
> ...

Yes, in my understanding the relation would be named by the relation field anyway by default so no need to specify this again. If you want to customize this though, you will have to use the syntax.

> Indexes (and any other schema construct for that matter) must reference the fields, not the underlying columns.

Correct.

> We could allow a shortcut to reference the `relation field` in addition to the `sub relation field`:

Yes and no. It is probably much easier to standardize on the relation sub field name. Using the relation field name would not be explicit for compound indexes as the order of the columns in the index is not clearly spelled out in the index, just by looking at the relation definition which might change.

**Comment by sorenbs** [comment]
Great. Seems like we have agreement on all points. (I agree with you on the last point, no reason to complicate things!)

**Comment by do4gr** [comment]
> This works relatively well for relations with one column, but gets complicated with multiple columns:
> 
> ```prisma
> model E_HOLDING {
>   relation_field E_HOLDING_SUMMARY @relation(fields: [sub_relation_field1, sub_relation_field1]) @map("relation_column1", "relation_column2")
> }


In this case what happens if only some fields need to be renamed? For example the first and the last out of three. One would need to map all of them in this case right?

**Comment by sorenbs** [comment]
@do4gr - One would need to map all of them, yes.

**Comment by mavilein** [comment]
I would like to suggest one further simplification to the suggested syntax. To me the current syntax proposal feels very heavy for those reasons:
- What's the purpose of the name of the sub relation field when it does not exposed in the client? E.g. for `@relation(fields: [sub_relation_field]) @map(["relation_column"])` the name seems to be irrelevant.
- The syntax seems very dense. Name conflicts with other fields are very hard to spot.
- With this approach we have 3 types of fields: scalar, relation and sub relation fields.

I would like to suggest an approach with which we could stick to the two types scalar and relation field. My suggestion is to turn relation fields into a completely virtual concept. Here are the rules i have in mind:
- Every column of an underlying table gets mapped to a simple scalar field. Even those ones that are part of a foreign key and therefore represent a relation.
- Relation Fields can be constructed by building upon those scalar fields. This way relation fields become very similar to foreign keys in SQL. A foreign key like `FOREIGN KEY (a, b) REFERENCES OtherTable(col1, col2)` is turned into `relationField OtherTable @relation(fields: [a,b], references: [col1, col2]`.
- Scalar fields that are used within a relation field become read only. (as already suggested by @sorenbs earlier)

Here's a more detailed example:

**SQL schema**
```sql
CREATE TABLE post (
    id serial NOT NULL,
    author_first_name text NOT NULL,
    author_last_name text NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (author_first_name, author_last_name) REFERENCES user(first_name, last_name)
);

CREATE TABLE user (
    id serial NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE(first_name, last_name)
); 
```

**corresponding Prisma schema**
```prisma
model Post {
    id Int @id
    authorFirstName String @map("author_first_name")
    authorLastName String @map("author_last_name")
    editorId Int @map("editor_id")

   // a relation field referencing the compound unique of `User`
    author User @relation(fields: [authorFirstName, authorLastName], references: [firstName, lastName])
   // a relation field referencing the id of `User`
    editor User @relation(fields: [editorId], references: [id])

  @@map("post")
}

model User {
    id Int @id
    firstName String @map("first_name")
    lastName String @map("last_name")

    @@unique([firstName, lastName])
    @@map("user")
}
```

**Comment by do4gr** [comment]
Should be fixed by https://github.com/prisma/prisma-engines/pull/621
