### ISSUE TITLE
Environment variable not found on latest alpha release

### ISSUE THREAD

**Issue by impowski** [prisma/prisma2#1613]
OS: `MacOS`
Prisma Version: `prisma2@2.0.0-alpha.785, binary version: 3e74ccae138e0c7330c1d8f2a67fb7a234d220e8`

When I'm running a `prisma2 generate` I get this error:
```console
Error: Schema parsing
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 
```

`DATABASE_URL` is present inside `.env` file.

**Comment by janpio** [comment]
![image](https://user-images.githubusercontent.com/183673/74557376-50d7dc00-4f60-11ea-92e3-50ee97253eb3.png)

**Comment by timsuchanek** [comment]
Thanks for reporting @impowski!
This is a breaking change, we intentionally introduced in alpha.
https://github.com/prisma/prisma2/issues/1519
So please move the `.env` file into the `./prisma` folder, then it should work again.
