### ISSUE TITLE
HPE_INVALID_CONSTANT error when downloading prisma executables

### ISSUE THREAD

**Issue by Johannes-B-stock** [prisma/prisma2#1617]
I'm behind a proxy and cannot get introspect or migrate to work. I've tried all solutions from other issues and comments and set the Proxy env variables, etc. 
The same script is working on my PC at home, but not on my laptop that is behind a proxy. 
According to this issue https://github.com/nodejs/node-v0.x-archive/issues/8514 the problem is that the header of the response is malformed or missing. 

I tried the recent prisma2 version and @alpha, both failing. 
Anyone some ideas how I could fix this?

**Comment by janpio** [comment]
Can you please show us the output you are getting?
What variables have you tried, in what combinations?

**Comment by Johannes-B-stock** [comment]
I don't know why, but just tried it again and now it is working. Might have been in issue with my proxy. Sorry for the trouble.
