### ISSUE TITLE
Prisma2 docs site

### ISSUE THREAD

**Issue by frandiox** [prisma/prisma2#1625]
Hi!  Would you consider adding a quick temporary site for rendering Prisma 2 docs? It's a bit slow to navigate them on GitHub.

As a suggestion for minimum effort, you can simply add this repo to Netlify and build it using Vuepress. It doesn't require any change in the repo itself, only simple config on Netlify UI:
![image](https://user-images.githubusercontent.com/1634092/74704451-d8b93100-5253-11ea-9aff-fd3661f4324b.png)

You get a site like this (using my fork, but it won't update automatically since I'm not part of the org): https://prisma2-docs.netlify.com/

It's faster to navigate and there's a search input. It can be improved by adding a sidebar and what not, but that requires adding one file to the repo. I can prepare a PR if you want.

Otherwise, it should be possible to do the same thing with React and Zeit.

**Comment by pantharshit00** [comment]
Hi @frandiox,

Thanks for giving this a thought. We are currently working on a documentation website internally which we will release along with the initial Prisma Client launch. So right now we won't like to maintain two separate instances of the website. 

Also, could you please add a `/robots.txt` file to your docs instance. If Google lists these pages, it can hurt our documentation ranking in the future.

You can use the following `robots.txt`:
```
User-agent: *
Disallow: /
```

**Comment by frandiox** [comment]
@pantharshit00 Yeah, just meant it as a temporary solution. I guess an unofficial site using a fork will do for now.

I've updated the site and will likely remove it when the official docs site is released 👍
