### ISSUE TITLE
Document MySQL unix socket connection usage

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1629]
See: https://github.com/prisma/prisma2/issues/1508#issuecomment-587358236

Right now we only document postgresql unix socket connection usage(https://github.com/prisma/prisma2/blob/754620fcf105788f09c31a3a2f461852ad432eea/docs/core/connectors/postgresql.md#connecting-via-sockets) but connection strings are different for mysql and postgresql due to us making a decision to follow how mysql and postgresql implement this feature

You can see this unit test for mysql socket usage: https://github.com/prisma/quaint/blob/master/src/connector/mysql.rs#L335

**Comment by nikolasburk** [comment]
I added the example from the unit test ([commit](https://github.com/prisma/prisma2/commit/23f4d703d679dfff94f9cdeb81cf8c45c908ed7d)), anything you think should be documented here @pantharshit00? (If so, please reopen the issue 🙂 )
