### ISSUE TITLE
Failing to create M:N relation in project.prisma

### ISSUE THREAD

**Issue by james2mid** [prisma/prisma2#163]
I'm receiving the following error when I execute `prisma2 generate`: `Did not find a relation for those for model ExchangeMarket and field quote`.

The models look like this:

```
model ExchangeMarket {
  id        String        @id @unique @default(cuid())
  exchange  Exchange
  base      Coin          @relation(name: "CoinMarkets")
  quote     Coin          @relation(name: "CoinQuoteMarkets")
  ticks     MarketTick[]
}
```

```
model Coin {
  id            String            @id @unique @default(cuid())
  symbol        String  
  name          String            @unique
  logo          String?
  description   String
  platform      Coin?
  max           Float?
  markets       ExchangeMarket[]  @relation(name: "CoinMarkets")
  qmarkets      ExchangeMarket[]  @relation(name: "CoinQuoteMarkets")
  aggregates    AggregateTick[]
}
```

Am I using the `@relation` attribute in the correct way? If not, is it an issue with the generator?

There's also [an issue](https://stackoverflow.com/questions/56899764/ambiguous-relation-when-generating-prisma?noredirect=1#comment100402802_56899764) on StackOverflow about this. I thought it was more appropriate to ask here.

**Comment by pantharshit00** [comment]
I can't reproduce this with version `prisma2@2.0.0-alpha.21, binary version: 52ef5caca6a0ada3460c4ba01c9a73edd07ae9f`. 

I think we have fixed some bugs related to self-relation so can you please try this again?

**Comment by james2mid** [comment]
I've reverted to Prisma V1 until it comes out of preview so I no longer have a project on prisma2. This is quite a common feature so I'm going to assume it's been fixed.
