### ISSUE TITLE
`Error: P4001 The introspected database was empty: undefined` url or file if sqlite should be displayed instead of undefined

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1633]
With alpha 793 on an empty PostgreSQL database:
 
<img width="628" alt="Screen Shot 2020-02-18 at 14 05 50" src="https://user-images.githubusercontent.com/1328733/74738887-10c27300-5258-11ea-900b-d8f50efdf213.png">

Code:
https://github.com/prisma/prisma2/blob/bdf085e8107683f7de12f31ffd267c16134efda4/cli/introspection/src/commands/Introspect.ts#L109

**Comment by softmarshmallow** [comment]
share us your solution

**Comment by Jolg42** [comment]
@softmarshmallow That was a display bug affecting SQLite fixed in this commit https://github.com/prisma/prisma/commit/1a7324be660279718d6c0d290d79e36fa3703c7c

So no solution here 🤷‍♂️ 

If you see this message double check your connection url and you can also try to open it using TablePlus to see what's inside.
