### ISSUE TITLE
Prisma2 and Docker

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#164]
Hello,
I search for this but not  found.

I see the tutorial from Code Mochi and I clearly don’t understand some docker configurations. So I ask if there will be an official docker image for running prisma2 ? thanks

**Comment by pantharshit00** [comment]
Hi,

We are releasing Prisma 2 as a library rather than a server. So you will use it as just another dependency for your application. So will create a docker image just like for another node app(or any other language we will support in the future).

**Comment by yovanoc** [comment]
But usually we exclude node_modules folder, here we have to find a nice way to include the generated photon, etc

**Comment by pantharshit00** [comment]
You can configure the output property. 

```groovy
generator js {
	provider = "photonjs"
	output = "./generated/photon"
}
```

That way you can generate photon anywhere you want

**Comment by harri121** [comment]
```

**Comment by marcjulian** [comment]
I am trying to dockerize a Nest application with Prisma2 and I used your tip @harri121 and prisma2 generate works but is showing the following errors: 

```
> prisma2 generate

Generating Photon.js Client to /usr/src/app/node_modules/@generated/photon
Done in 5.09s

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

The repo is available here https://github.com/marcjulian/nest-prisma2

**Comment by pantharshit00** [comment]
These warnings are normal.

I think our watcher depends upon the chokidar npm library which depends on fs-events which is mac specific package. npm will just skip its installation.

Read more here: https://github.com/fsevents/fsevents

**Comment by marcjulian** [comment]
Okay good to know, so I can just ignore the warnings.

**Comment by CaptainChemist** [comment]
@yovanoc thanks for checking out code mochi and sorry that I didn't notice this issue earlier- definitely let me know over on the site if you have any issues with running prisma 2 in the docker environment. The idea is to exclude copying the node_modules from your computer and instead running `npm install` as a line in the Dockerfile so that you install everything using a linux operating system instead of your native OS. By the same logic, generating the @generated folder in the docker environment instead of your native os is definitely a good best practice.

@harri121 's Dockerfile looks great as well- thaks for including that!

**Comment by yovanoc** [comment]
Can we have an example with a monorepo (yarn workspaces) ?

**Comment by pantharshit00** [comment]
@yovanoc Can you please open a separate issue for that?

**Comment by yovanoc** [comment]
https://github.com/prisma/prisma2/issues/400 , done :)

**Comment by janpio** [comment]
@divyenduz Please create a example for this.

**Comment by divyenduz** [comment]
Example PR: https://github.com/prisma/prisma-examples/pull/746

**Comment by divyenduz** [comment]
An example of docker exists here: https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/docker

I am closing this issue, please re-open a new issue if there is anything more specific that you are interested in. 

Thanks 🙌

**Comment by Muntasir2001** [comment]
> [https://github.com/prisma/prisma-examples](https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/docker)

Hi @divyenduz 

The example doesn't seem to exist on GitHub anymore. Is it possible for you to have a look and resend the correct link for it?

Thanks

**Comment by janpio** [comment]
The PR still exists @Muntasir2001 and shows the code that was used back then: https://github.com/prisma/prisma-examples/pull/746/files You can see that it does not actually do anything Prisma specific - as Prisma is just a library, all you need to do is to make your applicaiton run in Docker, and then make your application use Prisma as it would in any deployment situation.

**Comment by Muntasir2001** [comment]
> The PR still exists @Muntasir2001 and shows the code that was used back then: https://github.com/prisma/prisma-examples/pull/746/files You can see that it does not actually do anything Prisma specific - as Prisma is just a library, all you need to do is to make your applicaiton run in Docker, and then make your application use Prisma as it would in any other deployment situation.

Just like what I thought, thanks @janpio
