### ISSUE TITLE
Remove MongoDB from documentation

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1646]
We do not support MongoDB right now, so it should not be mentioned in the docs (especially not with "coming soon"):

https://github.com/prisma/prisma2/blob/master/docs/core/connectors/mongo.md
https://github.com/prisma/prisma2/blob/master/docs/core/connectors/README.md
https://github.com/prisma/prisma2/blob/master/docs/glossary.md#data-source-connector
https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#connector-attributes
https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#naming-conventions

**Comment by nikolasburk** [comment]
Agree 👍 removed all mentions of Mongo via https://github.com/prisma/prisma2/pull/1647
