### ISSUE TITLE
Find methods

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#165]
Hello, I’ve just a simple question, Why find’s methods doesn’t return an optional object in case. because now typescript say that the object is always there

**Comment by timsuchanek** [comment]
Thanks @yovanoc that's a good question and just a bug in the current implementation.
We'll fix it in the coming preview release.

**Comment by yovanoc** [comment]
I think is better than that because I think testing with an if it's not undefined instead of throwing that kind of error

![image](https://user-images.githubusercontent.com/7302317/61396432-06a65380-a8c8-11e9-9150-3b34261fe958.png)

**Comment by yovanoc** [comment]
Hello, Just to ask and not to bother you, when have you planned to do this? big thanks

**Comment by crimson-med** [comment]
Hello,

I'm using prisma2 on my project in typescript and i'm getting the same issue. Any idea when this will be resolved?

**Comment by divyenduz** [comment]
New Photon API change supersedes this https://github.com/prisma/specs/tree/master/photonjs

**Comment by yovanoc** [comment]
@divyenduz Hello, when this spec will be active? Thanks

**Comment by yovanoc** [comment]
What are your plans about that please?

**Comment by divyenduz** [comment]
In a few weeks, I suppose, please track this issue to track the progress of that.

**Comment by yovanoc** [comment]
Oh I see that we can close this now :)
