### ISSUE TITLE
NullConstraintViolation

### ISSUE THREAD

**Issue by iherger** [prisma/prisma2#166]
I have the following models (simplified for reporting the issue):
```prisma
model User {
  id         String        @default(cuid()) @id @unique
  email      String        @unique
  staff      Staff?
}

model Staff {
  id        String   @default(cuid()) @id @unique
  user      User
  active    Boolean?
}
```

When trying to add a user with the following query 
```graphql
mutation {
  createOneUser (data: {
    email: "user@gmail.com"
  }) {
    id
    email
  }
}
```
I get the following error
```json
"error": "ConnectorError(NullConstraintViolation { field_name: \"User.staff\" })"
```
This seems odd, since the `staff` field in the `User` model is optional. I have other 1-1 relations with the same problem.

**Comment by pantharshit00** [comment]
I can no longer reproduce any of these conditions now with `prisma2@2.0.0-preview-5, binary version: 29f6d9f7f6d0a85cc30df1809733612bab56a1c5`

These have been fixed between the updates
