### ISSUE TITLE
[Introspection] Order of fields in @@index changes with alpha 808 for PostgreSQL

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1666]
Before:
`  @@unique([standup_id, user_id], name: "standups_users_standup_id_user_id_key")`

After:
`  @@unique([user_id, standup_id], name: "standups_users_standup_id_user_id_key")
`

**Comment by tomhoule** [comment]
I have a branch with a test that eliminates the sql-schema-describer as a source for that bug, I'm going to investigate other components of the introspection engine next.

**Comment by tomhoule** [comment]
So it's not the recent postgres changes.

**Comment by tomhoule** [comment]
More details: https://github.com/prisma/introspection-engine-output/commit/499a474d1ecc3748f99cba8e7c3d81e3efa3bad3#diff-b356c3cdfdb5e1dc64622395cf9eb467

**Comment by tomhoule** [comment]
PR with the actual fix: https://github.com/prisma/prisma-engines/pull/525

**Comment by tomhoule** [comment]
prisma/prisma-engines#525 is merged, let's confirm that the problem is fixed on the large introspection test suite and we can close this issue :tada:

**Comment by janpio** [comment]
Confirmed <3
