### ISSUE TITLE
Unclear rust error: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#1677]
When a relation is null, Prisma is throwing an unclear error:

```
  engine stdout { timestamp: 'Feb 21 14:24:17.391',
  level: 'ERROR',
  target: 'prisma',
  fields:
   { message: 'PANIC',
     reason: 'called `Option::unwrap()` on a `None` value',
     file:
      '/rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs',
     line: 15,
     column: 40 } } +21ms
  engine { error:
  engine    { Error: socket hang up
  engine        at createHangUpError (_http_client.js:323:15)
  engine        at Socket.socketOnEnd (_http_client.js:426:23)
  engine        at Socket.emit (events.js:203:15)
  engine        at endReadableNT (_stream_readable.js:1145:12)
  engine        at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } } +1ms
  prisma-client Error: PANIC
  prisma-client     at currentRequestPromise.then.catch.e (/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/node_modules/@prisma/client/runtime/index.js:1:16175)
  prisma-client     at process._tickCallback (internal/process/next_tick.js:68:7) +8ms
Error: 
Invalid `prisma.posts.findOne()` invocation in
/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/src/schema.ts:71:18

   67 return ctx.prisma.post.findMany({
   68   where: {
   69     OR: [
   70       { title: { contains: args.searchString } },
→  71       PANIC
    at PrismaClientFetcher.request (/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/node_modules/@prisma/client/index.js:89:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

related code (don't mind the stack trace above – it's wrong due to the JS madness)

```typescript
author: (parent, args, ctx: Context) => {
  return ctx.prisma.post
    .findOne({
      where: { id: parent.id },
    })
    .author() // error happens here
},
```

reproduction available at https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-sdl-first:

```
git clone https://github.com/prisma/prisma-examples
cd prisma-examples/typescript/graphql-sdl-first
yarn install
yarn prisma2 generate
yarn dev &
pid=$!

sleep 10

curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"query {\n  feed {\n    id\n    content\n    author {\n      id\n      name\n      email\n    }\n  }\n}"}' --compressed

kill "$pid"
```

related:  https://github.com/prisma/prisma-examples/issues/1484

**Comment by janpio** [comment]
Similar error message, in a completely different place: https://github.com/prisma/prisma2/issues/1692

**Comment by pantharshit00** [comment]
Unable to reproduce this with `prisma2@2.0.0-alpha.831, binary version: b1752e02f2f7d6243ce0171f7a357fbf6887083d`.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/75247331-aed5b080-57f7-11ea-91dd-2a8749fec683.png">

Also, prisma/prisma-examples#1484 is now closed so please try this again.

**Comment by pantharshit00** [comment]
> Similar error message, in a completely different place: #1692

This unrelated to #1692. `Option::unwrap()` on a `None` value ` is a common rust panic is `Option` type is used quite a lot in Rust.

**Comment by steebchen** [comment]
@pantharshit00 This issue is not about the error itself, just about the fact that the error message "called `Option::unwrap()` on a `None` value" is unclear and should be improved. If the database has a null value (which it now doesn't have anymore since we didn't plan that, but it did have a null value before), this error happens. You should be able to reproduce it when using prisma-examples before commit `2b1d5bc`.

**Comment by pantharshit00** [comment]
Still unable to reproduce with `2b1d5bca68b39fee775736e409ce13548faca8d3` or even `fb74a7e8a9ffaf9a336f44f84eb9441134cfd93e` commits.

**Comment by steebchen** [comment]
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/5013932/75257856-2ca9b400-5818-11ea-963d-dbace29720e2.png">

Weird, I can still reproduce it with `2b1d5bca`

**Comment by pantharshit00** [comment]
Ah ok, I can reproduce this with `prisma2@2.0.0-preview022, binary version: f608db3b9e4f50f9a384356e532357b0a525969a` but not with the latest alpha `prisma2@2.0.0-alpha.831, binary version: b1752e02f2f7d6243ce0171f7a357fbf6887083d`

Can you please confirm this as well?

**Comment by steebchen** [comment]
Yep, I can confirm this. I guess we can close this then...

**Comment by tomhoule** [comment]
I confirm I couldn't reproduce this with the latest alpha as well :+1:
