### ISSUE TITLE
prisma generate does not work on node:12 image

### ISSUE THREAD

**Issue by macrozone** [prisma/prisma2#1678]
we use a node:12 image on our gitlab-ci. there `yarn install` should trigger `prisma2 generate`.

it thows an error:

```
Error: Error: Command failed with ENOENT: /path/to/project/node_modules/prisma2/query-engine-debian-openssl-1.1.x --enable_raw_queries cli --dmmf
```

i can also log into the pod running this build and i see that this path indeed does not exist.

seems similar to https://github.com/prisma/prisma2/issues/1635 and https://github.com/prisma/prisma2/issues/1642

the base image is not an alpine, but the `node:12` image, so it should be supported.

**Comment by macrozone** [comment]
edit: i removed node_modules on that pod and did a yarn install again and now it works.

have to check whether this has to do with how we cache node_modules on gitlab-ci

**Comment by macrozone** [comment]
closing, it seems the cached node_modules folder had not the right binaries. 

maybe it would be good if `prisma2 generate` would try to reinstall missing stuff

**Comment by pantharshit00** [comment]
@macrozone We further improved our binary checking logic in https://github.com/prisma/prisma-client-js/commit/551970475faf9c94961655dd154b6732def31eca so this should not occur anyways now. It is avaliable in alpha
