### ISSUE TITLE
Middlewares, like graphql-shield, are catching global errors

### ISSUE THREAD

**Issue by BenJeau** [prisma/prisma2#1680]
When adding a middleware to either `graphql-yoga` or to `apollo-server`, such as `graphql-shield`, and throwing an error on purpose in one of the resolvers, the middleware catches the Error and the original error is not being thrown/shown.

## Reproduction

* Starting off with the [blog example](https://github.com/prisma-labs/nexus-prisma/tree/master/examples/blog) in the `prisma-nexus` repo
* Adding `graphql-shield` 
  * `yarn add graphql-shield`
  * Adding it to the array of middlewares to `graphql-yoga` middlewares: [shield({})] - with or without any permissions)
* Add a `throw new Error('message')` in one of the resolvers
  * Ex: adding `throw new Error('custom error message')` to the first line of the blog query resolver method
* Making a request to the modified resolver
  * Ex: In graphql playground, executing the following query `{ blog(id: 1) {id} }` will raise an error with the message being "Not Authorised!" instead of "custom error message"

**Comment by pantharshit00** [comment]
Moved to https://github.com/prisma-labs/nexus-prisma/issues/613. Please continue conversation over there.
