### ISSUE TITLE
Add docs for .raw`` template literal API with parameters #1583

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1688]
It's now possible to use parameters and they will be escaped.

```js
const userId = 1
const result = await prisma.raw`SELECT * User WHERE id = ${userId};`
```

**Comment by nikolasburk** [comment]
Is this already on `master`?

**Comment by RafaelKr** [comment]
@nikolasburk it is :)
https://github.com/prisma/prisma-client-js/pull/522

**Comment by nikolasburk** [comment]
Seems like this was already documented: https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#setting-variables 👍

**Comment by pantharshit00** [comment]
@nikolasburk Tag itself is documented but there are no examples showing that we can use parameters inside it. I think we should add that. This issue concerns about that.

**Comment by RafaelKr** [comment]
@pantharshit00 The link of Nikolas actually shows how to set variables.

**Comment by pantharshit00** [comment]
Ah, sorry I scrolled past it 🙈. Thanks @RafaelKr
