### ISSUE TITLE
Support for Array of primitives 

### ISSUE THREAD

**Issue by tristancaron** [prisma/prisma2#169]
Currently `String[]` is not supported. Would it be possible to support it and automatically handle joins or serializations?

**Comment by pantharshit00** [comment]
They are supported now. We will create a table that will store the position and value of the primitive in a SQL connector.

![image](https://user-images.githubusercontent.com/22195362/61470051-fb255c00-a99d-11e9-82b9-d429ba6c48f5.png)


Version: prisma2@2.0.0-alpha.21, binary version: 52ef5caca6a0ada3460c4ba01c9a73edd07ae9f

**Comment by tvvignesh** [comment]
@pantharshit00 

Hi. Not sure if I am doing this wrong. But, while the table migration get created for me when using Array of Primitives, I am not able to do any operations on them (screenshot below) - I am trying to add a list of strings when doing Photon create and it fails to get created.

![Screenshot from 2019-10-27 16-00-40](https://user-images.githubusercontent.com/1165845/67633216-39061a80-f8d3-11e9-944d-68e9f1ba8f15.png)

Also, when I try the same in Admin UI, it shows a different error (screenshot attached)

![Screenshot from 2019-10-27 15-58-10](https://user-images.githubusercontent.com/1165845/67633235-5f2bba80-f8d3-11e9-989a-d89ca86fcc70.png)

This is the schema I have:

```
model Notification {
    id                    String   @default(cuid()) @id
    mode                  String
    destinationUserIDList String[]
    deliveryDate          DateTime
    payload               String
    status                String
    tagIDList             String[]
    createdDate           DateTime @default(now())
    updatedDate           DateTime @updatedAt
}
```

And this is the code I am trying in seed.js

```
const { Photon } = require("@generated/photon");
const photon = new Photon();
// const moment = require("moment");
/**
 * SEED FUNCTION FOR ACCOUNTS TO LOAD INITIAL TEST DATA
 */
async function main() {
    const notification1 = await photon.notifications.create({
        data: {
            mode: "email",
            deliveryDate: new Date(),
            destinationUserIDList: ["123", "456"],
            status: "pending",
            payload: '{"hello":"world"}'
        }
    });

    console.log({ notification1 });
}

main()
    .catch(e => console.error(e))
    .finally(async () => {
        await photon.disconnect();
    });
```

@madebysid In the same context, I noticed that I was not able to edit any of the primitive array fields when adding records via Prisma Admin UI as well with no error logs in the console.

**Comment by tvvignesh** [comment]
I got the array of primitives working by using the set keyword. Digged through the prisma generated source code and found that it was declared as 
```
export declare type TheClassName = {
    set?: Enumerable<string> | null;
}
```

So, I tried this and it worked. This may need to be documented if not done already.

```
const notification1 = await photon.notifications.create({
        data: {
            mode: "email",
            deliveryDate: new Date(),
            destinationUserIDList: {
                set: ["123", "456"]
            },
            status: "pending",
            payload: '{"hello":"world"}'
        }
    });
```

Thanks.

**Comment by pantharshit00** [comment]
Yes, you will need to use the set operation. 

Can you please create a new issue for this in regards to documenting this properly.

**Comment by tvvignesh** [comment]
> Yes, you will need to use the set operation.
> 
> Can you please create a new issue for this in regards to documenting this properly.

Done. Link to the issue: https://github.com/prisma/prisma2/issues/853

**Comment by tvvignesh** [comment]
@pantharshit00 Was just wondering if is it just me where it says Postgres does not support array of primitives or is it intended?

![Screenshot from 2019-12-25 15-51-27](https://user-images.githubusercontent.com/1165845/71442981-6e41b400-272e-11ea-847c-3f0c8df8648f.png)

**Comment by xero0001** [comment]
@tvvignesh I'm experiencing the same issue.

And I'm using mysql 5.6

<img width="497" alt="스크린샷 2019-12-26 오후 12 47 05" src="https://user-images.githubusercontent.com/8829251/71456660-db605280-27dd-11ea-9057-333e46acfc04.png">

**Comment by tvvignesh** [comment]
@xero0001 I can understand that behavior on MySQL because @timsuchanek said in this thread (slack): https://prisma.slack.com/archives/CKQTGR6T0/p1576778944004300?thread_ts=1576778944.004300

That "From now on, only Postgres supports scalar lists". 

Since my problem was with Postgres itself, hence raised the issue.

**Comment by pantharshit00** [comment]
I think it is just a bug in the extension. It is being tracked here: https://github.com/prisma/vscode/issues/38
