### ISSUE TITLE
Document logging options (via `DEBUG` env var)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1697]
When using Prisma Client, you can set different log levels via the `DEBUG` env var. This needs to be documented. Eg.: `DEBUG=prisma-client` or `DEBUG=*`

**Comment by pantharshit00** [comment]
We use the popular nodejs logging library `debug`: https://www.npmjs.com/package/debug

Many other packages like express also use the same library. So when you initialize `debug, you give your debugger a namespace like shown below:

```
const debug = require('debug')('prisma-client')
```

and it is shown in the debug output when you enable it via the `DEBUG` environment variable:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/75246407-b4ca9200-57f5-11ea-9561-e6878251c2c9.png">


So `DEBUG=*` enables all the debug loggers and `DEBUG=prisma-client` only enables the debug output for Prisma namespace. The two major namespaces that we use in the client right now are `prisma-client` and `engine` so you can only enable debug output from these using `DEBUG=prisma-client,engine`.


Also, if you want to force the debug output regardless of the `DEBUG` env, you can pass the debug option in the Prisma client constructor like so `new PrismaClient({ __internal: {debug: true}})`

**Comment by nikolasburk** [comment]
Documented via: https://github.com/prisma/prisma2/pull/1801/files
