### ISSUE TITLE
"The init command does not take any argument"

### ISSUE THREAD

**Issue by Keyframe** [prisma/prisma2#1703]
I found out about Prisma, and Prisma2 and decided to give it a spin. I followed the documentation and various examples over the interwebz, and I failed on the first of the first(est!) steps. What gives? 

`npx prisma2 init example`

yields: `Error: The init command does not take any argument.`

fine. I did just the `npx prisma2 init` in the current dir and I got a `prisma` directory with `schema.prisma` in it. None of that fancy CLI tool showed in docs, examples, prisma videos on youtube..

My question is, is this something gone wrong and if not where can I find up-to-date documentation and news? Documentation in repo ain't it as well.

**Comment by pantharshit00** [comment]
I think this is expected right now as we have designed the flow to mainly support existing projects while prisma migrate is experimental.

But I do think this is a useful feature.

**Comment by Keyframe** [comment]
Fair enough. Keep in mind this is the first thing one sees when opening the docs, it made me turn away from the docs and the project altogether until I can trust the docs / later date.

**Comment by pantharshit00** [comment]
@Keyframe You can find our new documentation website here: https://prisma.io/docs
