### ISSUE TITLE
Using `env(DB_URL)` breaks prisma2 generate

### ISSUE THREAD

**Issue by maartenraes** [prisma/prisma2#1716]
Since the change of the .env file we noticed that not providing a DB_URL environment parameter breaks `prisma2 generate`, yet we don't really understand nor approve that Prisma needs to know where our database is, or should access it during a docker build in our case.

```log
26-Feb-2020 12:17:34 | Step 11/15 : RUN npm run generate:prisma
-- | --
26-Feb-2020 12:17:34 | ---> Running in bf988cf58d7f
26-Feb-2020 12:17:34 |  
26-Feb-2020 12:17:34 | > registration-system-webp@0.0.1 generate:prisma /app
26-Feb-2020 12:17:34 | > prisma2 generate
26-Feb-2020 12:17:34 |  
26-Feb-2020 12:17:36 | Error: Schema parsing
26-Feb-2020 12:17:36 | error: Environment variable not found: POSTGRES_URL.
26-Feb-2020 12:17:36 | -->  schema.prisma:7
26-Feb-2020 12:17:36 | \|
26-Feb-2020 12:17:36 | 6 \|   provider  = "postgresql"
26-Feb-2020 12:17:36 | 7 \|   url       = env("POSTGRES_URL")
26-Feb-2020 12:17:36 | \|
```

**Comment by janpio** [comment]
We totally agree and have this issue to track and implement this change: https://github.com/prisma/prisma2/issues/800

You can subscribe that issue to get a notification when it is finished and implemented.
