### ISSUE TITLE
nexus-prisma now supports preview022

### ISSUE THREAD

**Issue by scriptcoded** [prisma/prisma2#1719]
`nexus-prisma@0.10.0` ships with support for `preview022`. The latest release message still says that you shouldn't update though:

> warning If you're currently using Prisma together with nexus-prisma, do not upgrade yet as there's still an issue that needs to be fixed in nexus-prisma for the new preview version..

Made myself confused, so perhaps the text should be updated?

https://github.com/prisma-labs/nexus-prisma/issues/605
https://github.com/prisma-labs/nexus-prisma/pull/608

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @scriptcoded, just fixed that in the release notes 🙏
