### ISSUE TITLE
Better handling of introspect crash

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1728]
Reproduction https://github.com/prisma/prisma2/issues/1648

Current error
<img width="817" alt="Screen Shot 2020-02-28 at 14 33 07" src="https://user-images.githubusercontent.com/1328733/75552749-4543e500-5a37-11ea-84d4-71d9ca621a52.png">

We should handle & output a better user facing error here.

**Comment by janpio** [comment]
Especially the `Error [ERR_STREAM_DESTROYED] ...` thing should be caught and hidden.

**Comment by janpio** [comment]
So much better: https://github.com/prisma/introspection-engine-output/commit/79beb9033c9dcc41c2cf6765f5183136b4b678a6
