### ISSUE TITLE
Will golang client be available?

### ISSUE THREAD

**Issue by soqt** [prisma/prisma2#174]
When do we expect to see golang client for Prisma2?

**Comment by pantharshit00** [comment]
I can't give you an ETA yet but we have a spec for the Go client.

https://github.com/prisma/specs/tree/master/photon-go-client

Please take a look. We would love to hear your thoughts on this.

**Comment by dvelitchkov** [comment]
@pantharshit00 - that link is a 404 for me.

**Comment by pantharshit00** [comment]
@dvelitchkov Updated link: https://github.com/prisma/specs/tree/master/photongo

**Comment by steebchen** [comment]
Closed in favor of #571 where the status fo the Go client is tracked.

**Comment by divyenduz** [comment]
Closing this one
