### ISSUE TITLE
Some schemas after introspection return `ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1615, message: "Prepared statement needs to be re-prepared", state: "HY000" })) })`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2#1746]
Schemas
- mysql_public/ciboard3pro
- mysql_public/contao
- mysql_public/drupal
- mysql_public/employees
- mysql_public/fluxbb
- mysql_public/joomla
- mysql_public/lychee
- mysql_public/matomo
- mysql_public/modx-revolution
- mysql_public/opencart
- mysql_public/orangehrm
- mysql_public/phpbb
- mysql_public/shopware
- mysql_public/sportsdb
- mysql_public/typo3-v9
- mysql_public/xpressengine
- mysql_public/zencart

Full error from Prisma Client
```
- cb_banner_group findMany({}) Error: 
Invalid `prisma.cb_banner_groups.findMany()` invocation in
/home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public/ciboard3pro/index.js:2428:40

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1615, message: "Prepared statement needs to be re-prepared", state: "HY000" })) })
```

**Comment by pimeys** [comment]
Seems like a bug in MySQL server. See: https://stackoverflow.com/questions/4380813/how-to-get-rid-of-mysql-error-prepared-statement-needs-to-be-re-prepared

I'd upgrade to the latest MySQL and at least set the mentioned configuration variable and restart MySQL:

> The error went away for me when I added table_definition_cache=5000 in my /etc/my.cnf file (under the [mysqld] section), and restarted mysqld. Note that my.cnf may be in a different location for you.

**Comment by Jolg42** [comment]
The error disappeared from new run https://github.com/prisma/introspection-engine-output/pull/198/files

@janpio Should we close this then?

**Comment by Jolg42** [comment]
Could not reproduce with 842, 843, 844 so closing until we get a reproduction.
