### ISSUE TITLE
Support for introspecting tables without an ID field

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#175]
Introspecting discourse DB for example yields the following error: 

![image](https://user-images.githubusercontent.com/746482/61392072-597b0d80-a8be-11e9-9dc3-41745be5e395.png)

**Comment by matthewmueller** [comment]
@pantharshit00 please update with your findings. Specially, under what cases does introspection show up as `Int` and in what case does it properly link to the other models.

**Comment by matthewmueller** [comment]
Nevermind, so I think I know what's going on. This is still an issue @pantharshit00. It happens when that join table doesn't specify it's relationship to the other tables:

```sql
CREATE TABLE public.categories_web_hooks (
    web_hook_id integer NOT NULL,
    category_id integer NOT NULL
);
```

Introspection **is** able to pick up when you do specify the relationships:

```sql
CREATE TABLE public.categories_web_hooks (
    web_hook_id integer NOT NULL references web_hook (id),
    category_id integer NOT NULL references categories (id)
);
```

This is technically on discourse to fix, maybe they do it for performance reasons, but we may want to have some smart prompts here to help out. cc/ @schickling

**Comment by janpio** [comment]
Could the `references ...` be just assumed from the naming here?

**Comment by pantharshit00** [comment]
I think we might need to introduce a new directive for this that can carry this information that user can add manually or we can derive via naming or we can prompt to select the join tables in the cli(that we can't infer)

Join tables actually doesn't follow any particular conventions. For example, WordPress uses multiple column indexes for them while discourse just stores integers without any reference.

**Comment by matthewmueller** [comment]
To set the stage a bit, for introspection we're trying to reconstruct a graph with arrows 

![image](https://user-images.githubusercontent.com/170299/65314281-50483e80-db96-11e9-8ad6-2a36ce9e4c2a.png)

In the best case the schema will tell us where to draw these arrows. This signal would probably be via `references`, but we can also use other heuristics like what you mentioned:

1. Could the references ... be just assumed from the naming here?
2. WordPress uses multiple column indexes

**Comment by janpio** [comment]
This should be turned into a issue in prisma/specs which will suggest a change to an existing spec ("Introspection").

**Comment by divyenduz** [comment]
Closing this as I think this is already tracked in the new introspection.
