### ISSUE TITLE
AWS Lambda timed out

### ISSUE THREAD

**Issue by UWellFail** [prisma/prisma2#1754]
Currently, I use `prisma2@2.0.0-preview022`, `nexus@0.12.0-rc.13`, `nexus-prisma@0.10.0`

I deploy the app (with nexus-prisma crud) with Serverless to AWS Lambda and I have some problems.
After executing some query at the deployed endpoint, I couldn't open the `graphql playground` in the browser because lambda function now is timed out, but all the time while the page tries to open I can make requests to the endpoint with Graphql Playground app and these queries execute fine. After lambda timed out I can reload the page with graphql playground and that will work fine.

This is AWS X-Ray for lambda:
![image](https://user-images.githubusercontent.com/46130993/75791973-66317080-5d7e-11ea-9fb9-0a5e4711cfd1.png)
In logs only this:
![image](https://user-images.githubusercontent.com/46130993/75792040-79444080-5d7e-11ea-83e1-e9738e959ccd.png)

**Comment by UWellFail** [comment]
This problem only appears when using nexus-prima crud. If I use my custom resolver and add prisma.disconnect(); after prisma operations, then this problem is not observed.

**Comment by UWellFail** [comment]
I fixed that problem by `graphql-middleware` for all queries adding prisma.disconnect() after execution.
It's working, but it is not a good solution I think.

**Comment by timsuchanek** [comment]
Thanks for reporting @UWellFail! It would be really awesome, if you could have a minimal reproduction repo, so that we can reproduce this!
It highly depends how you call the lambda function. Normally lambda should end the call.

**Comment by UWellFail** [comment]
https://github.com/UWellFail/prisma2--1754

**Comment by pantharshit00** [comment]
I was unable to reproduce this with the instance that I have deployed: https://v47qk2xs35.execute-api.us-east-1.amazonaws.com/dev/


Also, try this again with the latest version `preview023`.

**Comment by UWellFail** [comment]
@pantharshit00 
I reproduced this error with your deployed instance.

https://www.dropbox.com/s/rd4gj26xovrlozr/Screen%20Recording%202020-03-06%20at%2019.05.23.mov?dl=0

**Comment by pantharshit00** [comment]
Thanks for the video. Indeed I can also reproduce this after I followed the video.

**Comment by d2kx** [comment]
Another thing you can probably do is to set

`context.callbackWaitsForEmptyEventLoop = false;`

for the Lambda handler instead of disconnecting the Prisma client and in the beginning of the handler check if Prisma/whatever the name of your Prisma client instance is already exists, as a warm Lambda runtime container would be able to reuse a previous instance, if the Prisma client instance is created outside of the Lambda handler function.

**Comment by janpio** [comment]
Internal Note: First investigation by @timsuchanek at https://prisma-company.slack.com/archives/CUXLS0Z6K/p1584459490008300

**Comment by Jolg42** [comment]
I reproduced the timeout with https://github.com/UWellFail/prisma2--1754

I solved the timeout by modifying https://github.com/UWellFail/prisma2--1754/blob/master/src/index.js with 
```diff
exports.server = (event, context, cb) => {
+  // Set to false to send the response right away when the callback executes, instead of waiting for the Node.js event loop to be empty.
+  context.callbackWaitsForEmptyEventLoop = false;

  return lambda.createHandler({
    cors: {
      origin: '*',
    },
  })(event, context, cb);
};
```

**Comment by UWellFail** [comment]
@Jolg42 I try this solution, its solves my problem

**Comment by hdngr** [comment]
This should be in the docs 😄
