### ISSUE TITLE
Introspection does not "auto" resolve ambiguous relations

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#176]
Introspecting chinook DB yields a datamodel with this error: 

![image](https://user-images.githubusercontent.com/746482/61392486-356bfc00-a8bf-11e9-9cc4-52df181d33e2.png)

**Comment by janpio** [comment]
This should be turned into a specs issue that will change the "Introspection" spec where a solution will be found and then later introduced via a PR.

**Comment by divyenduz** [comment]
This should be tracked in the new introspection already.
