### ISSUE TITLE
Make introspection work with Discourse DB

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#177]
Discourse is a good example of an existing setup. 

Known issues:
https://github.com/prisma/prisma2/issues/175

**Comment by matthewmueller** [comment]
Known issues:

1. Introspection in Rust
2. Composite index support

**Comment by janpio** [comment]
TODO: Dependency graph of problems and issues

**Comment by janpio** [comment]
Dependency graph now exists, work is in progress.

**Comment by janpio** [comment]
We're working on this with new Introspection Push.
