### ISSUE TITLE
Root folder .env file reading failed - Bug or Feature?

### ISSUE THREAD

**Issue by dizzyn** [prisma/prisma2#1770]
I have just upgraded from **2.0.0-preview021** to **2.0.0-preview023**

I have .env file in my root folder with this content:
````
DATABASE_URL=file:dev.db
DATASOURCE_PROD=false
DATASOURCE_DEV=true
````
And prisma schema in the **/prisma/schema.prisma** with:
````
datasource prod {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  enabled  = env("DATASOURCE_PROD")
}

datasource dev {
  provider = "sqlite"
  url      = env("DATABASE_URL")
  enabled  = env("DATASOURCE_DEV")
}
````
When i call **as** I got the error:

![image](https://user-images.githubusercontent.com/2071816/76072037-8ab46500-5f97-11ea-8cb8-228b2c791ed1.png)

Seems it can not read my .env file.

Is that **bug** or should I split my .env file in two and place one into the prisma folder?

Thank you.

**Comment by pantharshit00** [comment]
@dizzyn 

We are going to tackle this with https://github.com/prisma/prisma2/issues/1255 which will allow you to specify which env file you want prisma to use.

**Comment by janpio** [comment]
In the meantime you can for example use `dotenv-cli` as a workaround: https://www.npmjs.com/package/dotenv-cli Just use that to load your `.env` file before calling `prisma2 generate` or any other `prisma2` command.

**Comment by pantharshit00** [comment]
Closing in favour of #1255 for now
