### ISSUE TITLE
Edgedb syntax

### ISSUE THREAD

**Issue by ansarizafar** [prisma/prisma2#181]
EdgeDB https://edgedb.com has great syntax for data model and query language and we can use some of its features like inheritence and access control in Prisma2. Please check the doc and these links https://edgedb.com/roadmap and  https://edgedb.com/blog/we-can-do-better-than-sql

**Comment by janpio** [comment]
@schickling will look into this at some point.

**Comment by janpio** [comment]
Thanks for your input, we considered this and are not going to look into this further in the foreseeable future.
