### ISSUE TITLE
Postgresql: dmmfString parse error

### ISSUE THREAD

**Issue by alvinsj** [prisma/prisma2#1813]
In `schema.prisma` generated by `postgresql` provider

```
model some_table {
  //...
  status String @default("'APPROVED'::character varying")
}
```

generates an invalid `dmmfString`:

```
"default":"'APPROVED'::character varying" // ',' expected.ts
```

**Comment by janpio** [comment]
This should already be fixed in `prisma2 generate` of the current alpha.

If you want to use the version you are currently using, you can replace `@default("'APPROVED'::character varying")` with `@default("APPROVED")` in your schema to make it work again.

Thanks for reporting!
