### ISSUE TITLE
@default(cuid()) must be used with @id

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma2#183]
The [limitations documentation](https://github.com/prisma/prisma2/blob/master/docs/limitations.md) says the following:

```
Models must have an @id attribute and it must take one of these forms:
- Int @id
- String @default(uuid())
- String @default(cuid())
```

However, when I try the third form, I have the following error:
<img width="759" alt="Screenshot 2019-07-19 at 13 45 32" src="https://user-images.githubusercontent.com/6669733/61533066-0d4ddb80-aa2c-11e9-9520-d1b1e09195ce.png">
```
Error validating model "User": One field must be marked as the id field with the `@id` directive..
```

Either the documentation forgot to add the `@id` (and I can make a PR to update it), or there is a bug in Prisma

**Comment by pantharshit00** [comment]
Hi,

This look like a typo in the limitations page. You also need to annotate the field with `@id`.

So all possible options are :
- `Int @id`
- `String @id @default(uuid())`
- `String @id @default(cuid())`

Thanks for reporting! I will fix that page
