### ISSUE TITLE
Cannot use @relation(id) without more arguments

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma2#184]
The [relation documentation](https://github.com/prisma/prisma2/blob/master/docs/relations.md) shows how to use the `@relation` directive:

```
@relation(\_ fields?: Identifier[], name?: String, onDelete?: CascadeEnum)
```

and shows one example:

```
model User {
  id        Int        @id
  customer  Profile?   @relation(id)
}

model Profile {
  id    Int     @id
  user  User?
}
```

However, when trying to use `@relation(id)` (without "name" and "onDelete"), I get the following error:
<img width="701" alt="Screenshot 2019-07-19 at 13 53 32" src="https://user-images.githubusercontent.com/6669733/61533367-fcea3080-aa2c-11e9-802e-008ab34a428f.png">
```
Expected a String value, but received literal value "id".
```

**Comment by pantharshit00** [comment]
Thanks for reporting. Documentation is wrong here. You can use the following syntax.
```groovy
model User {
  id        Int        @id
  customer  Profile?   @relation(references: [id])
}

model Profile {
  id    Int     @id
  user  User?
}
```


I will update the docs
