### ISSUE TITLE
Prisma2 '--enable-raw-queries' issue while query/mutation using generated prisma2-client

### ISSUE THREAD

**Issue by SameerChorge94** [prisma/prisma2#1843]
**Description:**

I've been trying to perform query/mutation using generated prisma2 client, But it returns the below error
```
Invalid `prisma.user.findMany()` invocation in
D:\demos\Prisma2_Test\Prisma2_Updated_Version_Check\src\schemaManager\schemaManager.ts:97:52


error: Found argument '--enable-raw-queries' which wasn't expected, or isn't valid in this context
        Did you mean --enable_raw_queries?
USAGE:
    query-engine-windows.exe --enable_raw_queries
For more information try --help
    at PrismaClientFetcher.request (D:\demos\Prisma2_Test\Prisma2_Updated_Version_Check\src\apps\test\demo\prisma\generated\client\runtime\index.js:1:47615)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Steps to reproduce the issue:**
1. Setup datamodel and database using the prisma2 client with prisma2 version `2.0.0-preview024` or `2.0.0-preview023`
2. Execute Prisma2 Migrate and Prisma2 generate commands.
3. Access the generated client using below code
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
4. Try to query the model using below code
`  var users = await prisma.user.findMany();`
5.It returns the above mentioned error 

**`Expected Result:`**
By using generated client and performing Query/Mutation actual result should be returned.

**`Actual Result`**
By using prisma2 version `2.0.0-preview022`  It works fine but while using prisma2 version  `2.0.0-preview024` or `2.0.0-preview023` It returns the above error and not able to perform the query/mutation to database.

**`System:`**
prisma2: "2.0.0-preview023" OR "^2.0.0-preview024"
@prisma/client : "2.0.0-preview023" OR "2.0.0-preview024"

**Comment by janpio** [comment]
This points to that your binaries are older than what the packages you are using are expecting. This should happen at all.

How exactly did you update to the newer previews? Anything special about the query engine binary on your system? (env var or anything?)

**Comment by malekjaroslav** [comment]
This happened to me before, I think I resolved it by removing node_modules and reinstalling them

**Comment by SameerChorge94** [comment]
Closing the issue as it was resolved after updating below versions of npm packages **globally** 
```
prisma2: "^2.0.0-preview024"
@prisma/client : "2.0.0-preview024"
```
Also by removing existing node_modules and reinstalling them in the project structure..

**Comment by janpio** [comment]
Oh, did you maybe use a global `prisma2` with a different version accidentally? (e.g. by calling `prisma2 generate` instead of `npx/yarn prisma2 generate`. That kind of would make sense, and give us an idea how to reproduce this.

**Comment by SameerChorge94** [comment]
Yes, 
For reproducing the issue Prisma2 version for my project node_modules was `2.0.0-preview024`
and Global node_modules version was `2.0.0-preview022`, that's why it was returning the error while calling database using generated prisma client.
