### ISSUE TITLE
Virtual back-relation field is pluralized in 1:1 relation

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1850]
I have this SQL schema:

```sql
CREATE TABLE users (
	user_id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(256),
	email VARCHAR(256) UNIQUE NOT NULL
);

CREATE TABLE profiles (
	profile_id SERIAL PRIMARY KEY NOT NULL,
	bio TEXT,
	user_id INTEGER NOT NULL UNIQUE REFERENCES users(user_id) 
);
```

Notice that `user_id` on `profiles` has a `UNIQUE` constraint, so when introspecting we're inferring a 1:1 relation:

```prisma
model profiles {
  bio        String?
  profile_id Int     @default(autoincrement()) @id
  user_id    users
}

model users {
  email    String    @unique
  name     String?
  user_id  Int       @default(autoincrement()) @id
  profiles profiles?
}
```

However, the virtual back-relation field `profiles` on `users` in the Prisma schema is still pluralized even though there can max be 1.

**Comment by janpio** [comment]
The name is just the name of the table/model - nothing we can do about that really.

**Comment by nikolasburk** [comment]
Ah I see, I though it was intentionally pluralized! In that case I guess we can indeed close this and have to wait for https://github.com/prisma/prisma2/issues/1705 and https://github.com/prisma/specs/issues/432 which will probably improve the situation here.
