### ISSUE TITLE
Add Errors, when generating code from prisma schema

### ISSUE THREAD

**Issue by Manuelbaun** [prisma/prisma2#1860]
Hi folks,

first off, I really like the Prisma project. It's really easy to get started with and the dev flow is awesome. I know, it's not ready for Prod., but I like to report some difficulties I found while using it.

1.  when writing a model and define a field with`@unique` and specify an `@@index([])` as well like here: 
	```prisma
	model User {
	  id   Int    @id @default(autoincrement())
	  name String @unique
	
	 @@index([name])
	```
	
	the generation throws an error but does not tell you, what's wrong. So you go and comment everything out, till it works again. It would be great, to point out what might be wrong in the schema.

2. I had some issues with SQLite and the schema. First, I show you, what my schema looked like and the typescript code.

	`Schema.prisma`:
	```prisma
	datasource db {
	  provider = "sqlite"
	  url      = "file:./prisma.sqlite"
	}
	
	generator client {
	  provider = "prisma-client-js"
	}
	
	model User {
	  id        String    @default(cuid()) @id
	  email     String    @unique
	  password  String
	  createdAt DateTime? @default(now())
	  updatedAt DateTime? @updatedAt
	  firstName String
	  lastName  String
	  role      Role
	}
	
	enum Role {
	 USER ADMIN
	}
	```
	
	`Code`:
	```typescript
	import { PrismaClient } from '@prisma/client';
	
	const prisma = new PrismaClient({
	  log: ['info', 'query', 'warn'],
	});
	
	async function main() {
	  console.log(' before open db');
	  // --- no output after here
	  try {
	    const res = await prisma.user.create({
	      data: {
	        email: 'bob@prisma.io',
	        firstName: 'Bob',
	        lastName: 'Hemple',
	        password: '1234',
	        role: 'USER'
	      },
	    });
	
	    console.log('Created:', res);
	  } catch (e) {
	    console.error(e);
	  }
	
	  console.log('Searching for ');
	  const u = await prisma.user.findMany();
	  console.log('users:', u);
	  await prisma.disconnect();
	  console.log('Done');
	}
	
	main();
	```
	Some of you might spot, SQLite does not support `enums`. But primsa does not complain about it and generated everything successfully. Then, when executing the code, nothing happens. No errors, nothing. The only thing that shows in the terminal is the line `before open DB` and then the script finishes.  The SQLite DB was empty, no user got added. 
	
	After removing the enum in the user role, it did work. It would be great if using enums with SQLite should throw some errors in the schema. The code above is very similar to the docs, where it you find SQLite and enum. This needs also an update I guess. First example: [Doc-Link](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md)

I hope this information helps you guys. Keep up the good work.

**Comment by janpio** [comment]
> 1.
> the generation throws an error but does not tell you, what's wrong. So you go and comment everything out, till it works again. It would be great, to point out what might be wrong in the schema.

Can you please share the error you are getting here?

**Comment by Manuelbaun** [comment]
Here is the error, it actually says something about the index
```
 ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: index User.name already exists)
```

**Comment by pantharshit00** [comment]
I had split this points into three separate issues so that we can track them separately:
1. I opened https://github.com/prisma/migrate/issues/376

Actually prisma migrate throws that error instead of prisma client generation. Prisma client doesn't care about underlying constraints and it generates without any error.

2. I opened https://github.com/prisma/migrate/issues/377 and a documentaion issue https://github.com/prisma/prisma2/issues/1906

I wrote a description in the issue. 

Please subscribe to those issues now.
