### ISSUE TITLE
Prisma2 Multi-Tenancy Support with only single generated Prisma2 client

### ISSUE THREAD

**Issue by SameerChorge94** [prisma/prisma2#1873]
## Problem
I have been trying Prisma2 example with multi-tenant support without any third party package support.
Accoring to current prisma2 versions one needs to provide the schema name in datasource connection string ( If not provided it takes public schema as default schema ).

As per our project plan we needs the same datamodel in all database schema to manage the multiple Tenants database for security reasons.

But with current prisma2 versions if we provide the different schema name and deploy the changes then it genetate the new prisma client for each schema,

Which is not feasible solution for our project plan as we'll need to manage seperate prisma clients for each tenant also if the datamodel changes occured then need to deploy same changes manually to each schema.

Also the project size will increase as we generate seperate prisma2 client for each schema seperately.

## Solution
Accoring to our problem we want to provide only database connection string in datasource and generate only one prisma2 client,

And if we provide the schema name to the generate prisma client then it should deploy the datamodel if not present to the schema, 

if datamodel exist to the schema then it should return the requested data from the database schema provided.

As per this feature, we'll only need the one prisma client which can accept the schema name to provide the multi-Tenancy support for the prisma2. 

## Alternatives
I have tried some packages for multi-tenant support but it manages the different prisma-client for each schema which is not feasible for out project plan.

As we're stuck on this issue for our project plan, Suggest any workarounds are available if any.

**Comment by janpio** [comment]
Have you tried using an environment variable for your database connection string like the example `schema.prisma` does, when using `prisma2 init` to create a minimal setup? Sounds to me like that could solve your problem already.

**Comment by SameerChorge94** [comment]
Yes it works, for different schemas with same datamodel i needed to migrate database to all the 
schemas seperately and generated only one prisma client for all of them.

If i change the env path for the for the database url in generated prisma client -> schema.prisma file
then it points to the database which is provided in schema file.

But for our project plan this env URL needs to be change dynamically  according to the request for particular schema, Is there any way where we can provide the prisma client to refer the particular schema URL dynamically
```
const { PrismaClient } = require('./generated/client');
const prisma = new PrismaClient();
```
using above code

**Comment by SameerChorge94** [comment]
Closing this issue, as we found one workaround, to generate one prisma client and manage different schema connection with its own data,
Follow below code for explanation:
```
const prisma 						= new PrismaClient();
let newSchemaPath 				= path.join(__dirname, './newSchema.prisma');
prisma.engineConfig.datamodelPath 	= newSchemaPath;
prisma.engine.datamodelPath 		= newSchemaPath;

```
As per the above code prisma does provide the engine config details where we can provide the different datamodel path to follow that schema for the CRDU API,

By this workaround we'll be able to point to the different schema as per the each request and achieve the Multi-Tenancy without generating seperate prisma clients for each schema.

@janpio thank you for your reply, and please check this workaround and suggest any changes if any to improve it and feel free to reopen if there are chances of improvement.
