### ISSUE TITLE
@id fields mentioned to be read only but are not

### ISSUE THREAD

**Issue by PHILLIPS71** [prisma/prisma2#1877]
## Bug description
I've been reading through the docs and playing around within the API, where I've ran into an issue that doesn't quite make sense. That is that models marked with an id annotation are being included in the generated UserUpdateInput.

From reading below found within the [documentation](https://www.prisma.io/docs/1.34/datamodel-and-migrations/datamodel-POSTGRES-knum/) is that id fields shouldn't be exposed here since they are read only, which makes sense. I don't want users to be able to modify this field.

> The fields annotated with the @id, @createdAt and @updatedAt directives are managed by Prisma and read-only in the exposed Prisma API.

Unsure if this is intended functionality or a bug, but it's rather annoying. Is there any built in annotation or plans to implement a read only annotation that would prevent this?

## Expected behavior
Following with what the documentation has mentioned I'd expect that the annotated id field would not be exposed within the UserUpdateInput type

## Prisma information 
Running PostgreSQL with the following model

```
model User {
  id         String   @default(cuid()) @id
  email      String   @unique
  username   String   @unique
  password   String
  avatar     String?
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}
```

**Comment by janpio** [comment]
> From reading below found within the [documentation](https://www.prisma.io/docs/1.34/datamodel-and-migrations/datamodel-POSTGRES-knum/) is that id fields shouldn't be exposed here since they are read only, which makes sense. I don't want users to be able to modify this field.
> 
> > The fields annotated with the @id, @createdAt and @updatedAt directives are managed by Prisma and read-only in the exposed Prisma API.

This is documentation from Prisma 1.34 - which is totally different from Prisma 2.x.The correct documentation currently lives at https://github.com/prisma/prisma2/tree/master/docs

**Comment by PHILLIPS71** [comment]
I see, totally makes sense then just assume they would be very similar as before. Is there any plans to provide read only annotations, or is it just best to create my own input types for these cases?  Functionality like this seems like it would become very useful.

**Comment by pantharshit00** [comment]
Right now the current behaviour for IDs in prisma 2 is that they are optionally exposed in the API. So if you don't provide them in the create input, they will get automatically created and we also give you an option to specify.
