### ISSUE TITLE
Return null for NULL values

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#1878]
It would be nice to be able to differentiate between null and undefined, NULL is a proper value in SQL, so it should be a proper value in JS too.

```sql
create table teams (
  id serial primary key not null,
  token integer unique not null,
  name text not null
);
create table users (
  id serial primary key not null,
  email text not null unique,
  team_id int references teams (id)
);
insert into teams ("token", "name") values (1, 'a');
insert into users ("email", team_id) values ('a', NULL);
insert into users ("email", "team_id") values ('b', 1);
```

```js
client.users.findMany({ where: { team_id: null } })
```

**Actual**

```js
[
  {
    email: 'a',
    id: 1
  }
]
```

**Expected**

```js
[
  {
    email: 'a',
    id: 1,
    team_id: null
  }
]
```

Integration test here: https://github.com/prisma/prisma2/blob/9afe7e6b0e9a2f185099590ef50b6ee3db37773c/cli/prisma2/src/__tests__/integrate.postgresql.test.ts#L1595

**Comment by pantharshit00** [comment]
This is expected. Relations are not included in the result. You need to explicity opt in to include relation using the `include` key:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/22195362/77339410-ba15f080-6d51-11ea-8291-2ad892ec858f.png">

```ts
async function main() {
  const test = await db.users.findMany({
    where: { team_id: null },
    include: { team_id: true }
  });
  console.dir(test, { depth: Infinity });
}
```

**Comment by matthewmueller** [comment]
Oh. That's odd. I would have thought `include` was only for relations, not for local foreign keys. cc @schickling

**Comment by pantharshit00** [comment]
We already have a issue for this :) 

#829
