### ISSUE TITLE
Database Connectors

### ISSUE THREAD

**Issue by jlarmstrongiv** [prisma/prisma2#1893]
## Problem
There are many requests for database types, such as MongoDB, Neo4j, Dgraph, Druid, Oracle, etc.  I’m using a more obscure database, and I don’t ever expect Prisma to offer first class support for it.  However, I would like to invest my own time into trying to make one.

## Solution
Echoing https://github.com/prisma/prisma/issues/1006#issuecomment-340290344 An API for “database-adaptors” to ascribe to.  Or documentation and an example on how to write my own adapter.  I don’t know where to start.

## Alternatives
Not writing an adapter.  Or, not using Prisma.  Or, writing my own queries and mutations with nexus-prisma instead of having them generated for me.

## Additional context
I am under the impression that there will always be more databases to support and maintain, and that having a systematic way for the community to contribute to the less popular databases would be beneficial in the long run.

**Comment by pantharshit00** [comment]
We do have plans for it but this will happen far in the future.

You can watch Marcus' talk on this subject: https://youtu.be/RAoXdyI_PH4?t=581

**Comment by jlarmstrongiv** [comment]
Looking forward to the Core Connector Pattern 👍

**Comment by hinogi** [comment]
Did it ever happen?
