### ISSUE TITLE
prisma2 convert

### ISSUE THREAD

**Issue by tanghw** [prisma/prisma2#190]
prisma2 convert --help

Convert a datamodel 1.1 to datamodel 2

Usage

  prisma convert

Options

  -h, --help       Displays this help message

Examples

  $ cat old-datamodel.prisma | prisma convert > new-datamodel.prisma
prisma should be prisma2

**Comment by tanghw** [comment]
prisma2 lift up
Error: Cannot run prisma lift up because there is a prisma dev command running in this directory.
Please stop prisma dev first, then try prisma lift up again,
and so on,should double check

**Comment by timsuchanek** [comment]
Regarding `prisma2 convert` - Can you elaborate on what the exact problem is?
`cat datamodel.prisma | prisma2 convert` is working.

Regarding `prisma2 lift up` - do you see that error message incorrectly, so is `prisma2 dev` not running?
Otherwise, everything behaves as intended.
