### ISSUE TITLE
Fix Github "Used by" metric for this repository

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#1907]
Right now the Github used by the metric for this repository is trying to aggregate usage of `@prisma/generator-helper`.
![image](https://user-images.githubusercontent.com/22195362/77324404-b1ff8600-6d3c-11ea-8136-cb0e54b44423.png)

It should track usage of `prisma2` package instead.

**Comment by janpio** [comment]
https://github.community/t5/How-to-use-Git-and-GitHub/quot-Used-by-counter-quot-not-showing-all-projects-and-main-one/m-p/51098#M11010

**Comment by janpio** [comment]
Fixed via manual action from Github: https://github.community/t5/How-to-use-Git-and-GitHub/quot-Used-by-counter-quot-not-showing-all-projects-and-main-one/m-p/51446#M11053
