### ISSUE TITLE
Allow query of relation ID

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma2#1914]
## Problem
When using GraphQL, it is usual to have a resolver for a field that is in another table. For example, consider this graphql schema:
```graphql
type User {
    id: ID!
    address: Address
  }

  type Address {
    city: String!
    zipCode: String!
  }
```

With the prisma schema:
```prisma
model User {
  id    Int @id @default(autoincrement())
  address Address?
}

model Address {
  id        Int     @id @default(autoincrement())
  city      String
  zipCode   String
```

Using a resolver for `Address`:

```javascript
User: {
    address: (parent: any, _args: any, ctx: Context) => {
      const id = parent.address; // This is not possible
      return ctx.prisma.address.findOne({
        where: { id },
      });
    },
 }
```

It currently is not possible to make a query directly on the database because we do not have the ID from the parent. 

## Solution
The solution would be to fetch the ID if the user did not specify the relation in the `include`. That would allow future queries to take place using this ID. I understand that it is not possible for some relations, but for 1:1 relations that is very important.

## Alternatives
I could not find any alternative that makes only one query to the address table (without a join to the user table).

**Comment by Sytten** [comment]
Note: This is a simple example, so one could propose that we join directly on the parent field. Although true, this would become unpractical very fast the more denormalized our data is. It is also inconvenient, because the developer has the remember to include all the possible fields all the time (including in the mutations if the type is returned).

**Comment by pantharshit00** [comment]
I understand the feature request but for this specific use case you have mentioned you can do something like this:
```js
 return ctx.prisma.user.findOne({
        where: { id: parent.id },
      }).address()
```

Now back to original feature request. This has been already asked here: https://github.com/prisma/prisma2/issues/829

So I am going to close this one as a duplicate.

**Comment by Sytten** [comment]
Agreed thanks for linking the issue. I just saw this way of doing this morning in the documentation.
