### ISSUE TITLE
No Support for query operators in prisma 2

### ISSUE THREAD

**Issue by AmitGutpa** [prisma/prisma2#1928]
Hi,

I am working with Prisma 2 and I want to query the database to get data greater than a specific date. I did not see anywhere any support for operators in Prisma 2

**Comment by Sytten** [comment]
It is possible to specify `gte` and other operators in the `where`. Your IDE should actually autocomplete it.

**Comment by pantharshit00** [comment]
Yep, we support these calls. Example:

Model:
```prisma
model User {
  id String @id @default(cuid())
  name String
  createdAt DateTime @default(now())
}
```

Example client call:
```ts
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  const data = await prisma.user.findMany({
    where: {
      createdAt: {
        gte: "2020-03-26T12:59:32.060Z",
      },
    },
  });
  console.log(data);
}

main();
```

**Comment by pantharshit00** [comment]
I am going to close this. Feel free to ask any further questions here or open a new issue.
