### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by newtack** [prisma/prisma2#193]
In this announcement (
https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5)

it refers to a spec (https://github.com/prisma/rfcs/blob/0002-datamodel-2/text/0002-datamodel.md) which is a broken link.

Can you please fix it?

**Comment by pantharshit00** [comment]
Thanks for reporting! We will update the link

**Comment by nikolasburk** [comment]
Fixed, the new link is: https://github.com/prisma/specs/tree/master/prisma-schema
