### ISSUE TITLE
Big picture blog post

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma2#1944]
## Problem
Due to Graphcool’s expiration on July 1, I’ve been attempting to migrate a side project to the new Prisma Framework.

I’ve been developing using GraphQL servers for quite some time now, and in large part because of Prisma’s earlier influence (`graphcool`, `graphql-yoga`, `nexus`, `prisma-nexus`, etc.) So when I upgraded to the new Prisma Framework, I naturally attempted to launch a GraphQL Server using some of Prisma’s new documentation. It was impossible, since there was no documentation out there — only a few docs that highlighted how to publish serverless functions via Zeit Now or Netlify instead.

## Solution
With the introduction of the new Prisma Framework, I was surprised how Prisma’s focus has been shifting away from GraphQL towards unlocking Prisma’s power through accessing individual lambda functions via REST endpoints. It makes perfect sense: low latency, hyper-targeted functions, etc.

I think it would be awesome if Prisma published a blog post about how individual REST APIs make more sense with Prisma (in most cases, I’d imagine) than full-fledged GraphQL servers. Of course, the documentation would also need to be updated so developers can quickly reference full-fledged examples (including authentication) hosted via Zeit or Netlify.

The new Prisma Framework is basically a huge paradigm-shift, from what I can tell. Now that everyone and their mother has jumped on the GraphQL bandwagon 😄... it might be time to let them know there’s an even better (faster, more flexible) way ☺️

**Comment by d2kx** [comment]
While the documentation for Prisma 2 lives in this repository right now and the official homepage is still serving Prisma 1 docs, there has been no shift in focus with the Prisma framework in that sense. Prisma (2) works great with both GraphQL and REST, and those are not dependent on each other. I don't have statistics but I'd be surprised if GraphQL wasn't the dominant option for most Prisma users.

GraphQL-Yoga was an attempt to make setting up Apollo Server easier at a time when Apollo Server version 1 was around. Apollo Server 2 made GraphQL-Yoga more or less redundant. You can find Apollo Server documentation here: https://www.apollographql.com/docs/apollo-server/

Nexus is actually in the process of expanding with the (financial) help of Prisma, and is looking into adding things like Authentication and Authorization for the upcoming releases. The same applies to nexus-prisma, which is being adapted for the next version of the Nexus library/framework.

If you have at least some knowledge of this tech, which it sounds like you do, you can take a quick look into Prisma's numerous example repositories to get started quickly: https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-apollo-server

The new Prisma CLI for Prisma 2 also offers to create sample projects with the setup already done if you need help.

Individual Lambda functions would actually likely increase the latency btw., as you are more likely to face cold functions. The Apollo Server for a GraphQL API works great with Lambda however, and apollo-server-lambda is even officially supported by the Apollo team.

**Comment by heymartinadams** [comment]
Thanks, @d2kx. Yeah, the folks at Prisma clarified with me this morning that that was a misunderstanding on my part. Indeed, Prisma truly is agnostic in this matter.

Closing now, for the reasons you so eloquently pointed out.
