### ISSUE TITLE
Update DB workflow guides to new relation syntax

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1981]
We have a number of DB workflows guides in the [new docs](https://prisma2.netlify.com/) (private repo [here](https://github.com/prisma/prisma2-docs)) which are using the current (soon outdated) relation syntax. 

- https://prisma2.netlify.com/guides/database-workflows/foreign-keys/postgresql
- https://prisma2.netlify.com/guides/database-workflows/foreign-keys/mysql
- https://prisma2.netlify.com/guides/database-workflows/foreign-keys/sqlite
- https://prisma2.netlify.com/guides/database-workflows/cascading-deletes/postgresql
- https://prisma2.netlify.com/guides/database-workflows/cascading-deletes/mysql
- https://prisma2.netlify.com/guides/database-workflows/cascading-deletes/sqlite

The last step in each of these guides is the introspection of the DB that was created throughout the guide and run Prisma Client queries, e.g. here:

- https://prisma2.netlify.com/guides/database-workflows/foreign-keys/postgresql#4-introspect-your-database-with-prisma

The Prisma schema that's resulting from introspection needs to be updated to use the new relation syntax.

Note that the introspection result should be adjusted to adhere to the following conventions:

- virtual back relation fields should be lowercased and for to-many relations pluralized, this should be explicitly mentioned in the guide and a link to this page should be provided: https://prisma2.netlify.com/reference/tools-and-interfaces/prisma-client/configuring-the-prisma-client-api
- the relation scalar field also should be named after the physical relation field but end on `Id`, e.g. if the relation field is called `author`, the relation scalar field should be called `authorId`

It should be ensure that the very last step of running the given Prisma Client code works _exactly_ as described in the tutorial.

**Comment by janpio** [comment]
> The Prisma schema that's resulting from introspection needs to be updated to use the new relation syntax.
> 
> Note that the introspection result should be adjusted to adhere to the following conventions:

That means that people will get quite a different Introspection result when they follow the tutorial themselves. Wouldn't it make more sense to adapt the scripts to the schema that Introspection returns?

**Comment by janpio** [comment]
First commit are there: https://github.com/prisma/prisma2-docs/pull/48/commits

I also did all the things in a repo to make future iterations easier - no more copy paste from the article necessary (maybe we could even load parts of the content from there on build of the docs?)

**Comment by janpio** [comment]
And the second batch: https://github.com/prisma/prisma2-docs/pull/48/commits/b0c6ba667f5650a0dd9ef9673e047fd8bed5e208 + https://github.com/prisma/prisma2-docs/pull/48/commits/38f67794bca15fddf31a00805498d2c8e89aee0a + https://github.com/prisma/prisma2-docs/pull/48/commits/d4850bacedff8f519ba0da3c147e4f90a035c7e8

@nikolasburk, the current content of `content/04-guides/01-database-workflows/06-cascading-deletes/02-mysql.mdx` shows all the indexes and constraints have the same name. Did you do anything special here or is this just MySQL default? (Seems that constraints are unique per database, and the index name is taken from the constraint by default if present - so I could not create all the constraints with the same name.)

**Comment by janpio** [comment]
https://github.com/prisma/prisma2-docs/pull/48 is ready for review @nikolasburk 

For next time: https://github.com/prisma/prisma2-docs-demos
