### ISSUE TITLE
errors in nexus-prisma-typegen/index.d.ts with typescript@3.9.0-beta

### ISSUE THREAD

**Issue by alexichepura** [prisma/prisma2#1982]
## Bug description
I tried [TS3.9 beta ](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/). It gives some perf boost BTW.
No issues with TS3.8

There are errors in node_modules/@types/nexus-prisma-typegen/index.d.ts
<img width="663" alt="Screen Shot 2020-03-28 at 10 46 30" src="https://user-images.githubusercontent.com/5582266/77818334-a4525380-70e2-11ea-8510-51ca393e5e2d.png">
<img width="725" alt="Screen Shot 2020-03-28 at 10 45 51" src="https://user-images.githubusercontent.com/5582266/77818339-a74d4400-70e2-11ea-8f17-830c7ca62065.png">

## How to reproduce
1. yarn add -D typescript@3.9.0-beta
2. ./node_modules/.bin/prisma2 generate
3. ts-node --transpile-only src/schema
4. try to compile project or goto node_modules/@types/nexus-prisma-typegen/index.d.ts

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: "@prisma/cli": "^2.0.0-preview025"
- Node.js version: v13.7.0

**Comment by pantharshit00** [comment]
Moved here https://github.com/graphql-nexus/nexus-schema-plugin-prisma/issues/636

Please open nexus-prisma related issues there in the future.
