### ISSUE TITLE
node_modules inside /prisma folder: Cannot find module '@generated/photon'.

### ISSUE THREAD

**Issue by ScottAgirs** [prisma/prisma2#199]
Not sure if bug or intended, or I'm missing something, but:

at step [#7.5](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#75-create-a-basic-setup), or when Creating a basic setup, I got TS yelling at me "Cannot find module '@generated/photon'."

Then I checked and it appears that after running `prisma2 generate` the output for `@generated` is inside the `/prisma` folder, where schema.prisma is located, rather than root or the normal node_modules location:
_*the two commented out output lines is what I tried as a workaround_
![image](https://user-images.githubusercontent.com/11737572/61593545-b8869e00-abae-11e9-80d6-2d0159d8ac26.png)

my `schema.prisma` file:

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://xxx:xxxx@ec2-54-83-1-101.compute-1.amazonaws.com:5432/xxx?schema=public&sslmode=prefer"
}


generator photonjs {
  provider = "photonjs"
  // output   = "../node_modules/@generated/nexus-prisma"
  // output   = "node_modules/@generated/nexus-prisma"
}

model Migration {
  revision          Int       @id
  applied           Int
  databaseMigration String    @map("database_migration")
  datamodel         String
  datamodelSteps    String    @map("datamodel_steps")
  errors            String
  finishedAt        DateTime? @map("finished_at")
  name              String
  rolledBack        Int       @map("rolled_back")
  startedAt         DateTime  @map("started_at")
  status            String

  @@map("_Migration")
}

model User {
  id    String  @id @default(cuid())
  name  String?
  email String  @unique
}
```

**Comment by ScottAgirs** [comment]
I can see that `/prisma/node_modules/@generated` appears in autogenerated files, when generating GraphQL boilerplate with SQLite via the CLI interactive wizards, so, I guess all is correct there, however, even with the boilerplate in place and after running all the setup commands according to tutorial, I still get `Cannot find module @generated/*` error: 
![image](https://user-images.githubusercontent.com/11737572/61594002-b1628e80-abb4-11e9-9792-798a43c6cdea.png)

**Comment by timsuchanek** [comment]
Thanks for reporting @ScottAgirs! Please delete `prisma/node_modules` and use the latest `prisma2@2.0.0-preview-2`, there we fixed the bug. Please let me know if it's still an issue for you, then we'll reopen.
