### ISSUE TITLE
when a id field is optional and defaults to uuid(),  the ModelWhereInput.id is UUIDFilter instead of StringFilter

### ISSUE THREAD

**Issue by macrozone** [prisma/prisma2#1998]
I could not verify if this is a prisma problem or nexus, so i posted the full issue on prisma-nexus repo:

https://github.com/graphql-nexus/nexus-schema-plugin-prisma/issues/634

see there for details

**Comment by pantharshit00** [comment]
GraphQL generation is completely handled by nexus so we can't give you an answer in terms of the client. Please wait for an answer in the other ticket
