### ISSUE TITLE
Prisma on linux

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma2#2]
`libssl1.1.so is missing`

**Comment by sorenbs** [comment]
[Reported by  Al Str in Slack](https://prisma.slack.com/archives/CKQTGR6T0/p1561045188070400?thread_ts=1561035076.063400&cid=CKQTGR6T0):

> Hello, I installed the newer openssl version required by prisma. There are some tutorial on the web (keep attention, the lib need to be shared) But prisma2 has another required library glibc 2.18 (centos has 2.17-260) and seems this cannot be upgraded because is a core part of the whole centos system. This upgrade will cause a "non booting" system.
> 
> Currently I don't think there is a possibility to run prisma2 with centos.

**Comment by schickling** [comment]
Related: https://github.com/prisma/specs/issues/2

**Comment by ansarizafar** [comment]
I am getting this error

![image](https://user-images.githubusercontent.com/5788284/61168917-c0bb5980-a56e-11e9-88a1-b75ceb4518d2.png)

**Comment by timsuchanek** [comment]
@ansarizafar which linux distribution and version are you using?
Please share the result of `uname -a`

**Comment by ansarizafar** [comment]
```
Linux home 4.4.0-151-generic #178-Ubuntu SMP Tue Jun 11 08:30:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by timsuchanek** [comment]
Thanks a lot! So it sounds like it's solved for you now?
It looks like it's mostly a documentation issue around installing libssl.
Which steps (commands) did you take install libssl1.1?

**Comment by ansarizafar** [comment]
https://github.com/prisma/lift/issues/19 was resolved by installing recommended library libssl1.1 but not this one. Now I am getting above mention error (Screenshot) with the latest preview release. I got this reply on slack from @divyenduz 

>  looks like binary resolution broke in the latest version, installing the correct libssl version should do for now. We will resolve it soon.

**Comment by divyenduz** [comment]
@ansarizafar : That was my understanding of the issue then, update on that is binary fails to link to an existing `libssl`, we are looking into it.

**Comment by ansarizafar** [comment]
I am still getting the same error with preview3.

**Comment by timsuchanek** [comment]
Thanks for letting us know @ansarizafar! We very likely have to extend our default build setup to support more Linux distributions as even with the same libssl version the bindings can differ in where libssl is in the fs.
Which version of Ubuntu is it that you're using?

**Comment by ansarizafar** [comment]
I am using Ubuntu 16.04.

**Comment by aliedp** [comment]
please make support for ubuntu 18.04 lts

**Comment by ivorpad** [comment]
I came across this error too in Ubuntu 16.04.6 LTS

```bash
Error: Error in lift engine for rpc listMigrations:
  /usr/local/lib/node_modules/prisma2/migration-engine: /lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found (required by /usr/local/lib/node_modules/prisma2/migration-engine)
```

```bash
/usr/local/lib/node_modules/prisma2/migration-engine: /lib/x86_64-linux-gnu/libcrypto.so.10: 
version 'libcrypto.so.10' not found (required by /usr/local/lib/node_modules/prisma2/migration-engine)
```

`# libssl version -a`

```bash
OpenSSL 1.1.1a  20 Nov 2018
built on: Thu Aug  1 00:09:03 2019 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
```

**Comment by divyenduz** [comment]
Closing this issue as it contains multiple issues, all of which are addressed except https://github.com/prisma/prisma2/issues/157

If there is an issue with your distribution, please create a new issue with the specifics 🙏

**Comment by tianhuil** [comment]
I'm encountering this on Ubuntu 16.  I get the following error on `prisma2=2.0.0-preview-8` while running `prisma2 init hello-prisma2`:
```
DMMF To DML /home/vagrant/sql-speed/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2: /usr/lib/libssl.so.10: version `libss
l.so.10' not found (required by /home/vagrant/sql-speed/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2)
```

For your information:
```
$ uname -a
Linux michael2 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by divyenduz** [comment]
@tianhuil Thanks for raising this, this was a known issue with ubuntu 16 that we fixed in preview 9
https://github.com/prisma/prisma2/issues/157

Please update the CLI version/re-generate using `prisma2 generate` and try again. 

I am closing this issue, please re-open a new issue if the problem persists for you and tag me on the new one. 

🙌

**Comment by createvo** [comment]
Hello, 
I don't think this issue started from my report in slack should be close.
I continued to have problems with glib library 2.18 because on centos there is 2.17 version installed. 
My understanding is that the upgrade it is not safe for the server.

![prisma2centos7](https://user-images.githubusercontent.com/34287914/66713124-eabb2c80-eda6-11e9-8f4d-6a79642fa755.JPG)

**Comment by pantharshit00** [comment]
@createvo 

Can you please give us more information about your OS like the version?


Output of `uname -a` would also be helpful.

I'd recommend you to open a new issue with the requested information

**Comment by createvo** [comment]
I edited my previous comment with the info. There was on slack. 
Anyway yes, a new issue could be more helpful! 
Thanks
