### ISSUE TITLE
Alphanumeric identifier bug

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#201]
I don't know if I've done something wrong but in case I put my "bug" here. Thanks

![image](https://user-images.githubusercontent.com/7302317/61594755-c9a3cf00-abef-11e9-8614-317a0630c3b6.png)

**Comment by mavilein** [comment]
Hey @yovanoc ,

thanks for reaching out! The parser error is not very helpful yet unfortunately. You need to specify it as `@@unique([user, achievement])`. Even with this fix it won't work yet as we have not implemented this feature yet. May i ask where you found out about that feature? I wonder whether our documentation is not clear about this fact.

**Comment by yovanoc** [comment]
![image](https://user-images.githubusercontent.com/7302317/61732002-f20d0400-ad7c-11e9-84b3-5d74f13b6b2a.png)

On the lift front page, thanks for your clear answer!
