### ISSUE TITLE
sqlite `@id @default(cuid())` marks field as required

### ISSUE THREAD

**Issue by go-viorica** [prisma/prisma2#214]
I'm having the following schema: 

```

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator photon {
  provider = "photonjs"
}


model Comment {
  id         Int      @id @map("i_id")
  internalId String   @id @map("s_id") @default(uuid()) @unique
  text       String   @map("s_text")
  createdAt  DateTime @map("dtu_creation") @default(now())
  updatedAt  DateTime @map("dtu_last_update") @updatedAt

  @@map("tbl_comments")
}
```

after using `prisma2 generate`, the generated type will be:

```
export declare type CommentCreateInput = {
    internalId: string;
    text: string;
};
```

where `internalId` is required

**Comment by tristancaron** [comment]
I tried with
```
  internalId                  String?       @map("s_uid") @default(cuid())
```

It's set to `null` when I add a new row.

**Comment by timsuchanek** [comment]
Thanks for reporting @go-viorica! We'll look into it.
@tristancaron that's an unrelated bug, which we will release a fix for soon.

**Comment by mavilein** [comment]
@go-viorica : Thanks for reporting! 🙏  I noticed that your model has two fields that are marked with `@id`. This is actually invalid. The id field denotes the primary identifier of a model. Therefore it must have exactly one. I just implemented a validation that rejects this model. 
Can you share your reasoning for modeling it this way? 
I assume you really needs just one of them so I suggest one of the following:
1. Remove one of the id fields in your model.
2. Remove at least `@id` from one of the fields.
