### ISSUE TITLE
[Suggestion] Move all Prisma packages to the `@prisma` scope

### ISSUE THREAD

**Issue by ChristianJacobsen** [prisma/prisma2#215]
Hi,

just thought I'd voice a suggestion to move all of Prisma's packages to the `@prisma` scope. Currently there is both `nexus` and `@prisma/nexus` with the docs for `nexus-prisma` referencing `@prisma/nexus` but depending on `nexus` itself.

When Babel made the change to scoped packages about a year or two ago, that made finding any and all official packages so much easier. I think the same could be said for Prisma. Having an umbrella to search under will make finding/discovering packages made by the organization so much easier. It will also allow the organization to release community "owned" (i.e. not a repo by the `prisma` user) under the umbrella if they deem it fit and then the package will have a 'Seal of Approval'.

Just a thought, but I think it would be a nice change.

**Comment by timsuchanek** [comment]
That's a great point, I also like that. We'll discuss it internally!

**Comment by nikolasburk** [comment]
Related: https://github.com/prisma/photonjs/issues/88

**Comment by janpio** [comment]
We agree, but not important enough to tackle right now. @jasonkuhrt will look into this soon.

**Comment by jasonkuhrt** [comment]
Thanks for raising the issue. Yep we want to make sure we get this right. We'll have to think carefully about what a namespace means for us and where to draw lines. For example nexus is agnostic to prisma and vice-versa. Nexus has or will have its own plugin ecosystem. Prisma 2 has generators. When binds nexus to prisma is nexus-prisma. Should nexus become its own namespace? Should nexus-prisma live under it? Or under prisma? How about FLUID (current its own gh org)? A proper audit will take place later this year, taking stock of our/community situation/needs and looking at anything we can learn from amongst existing lay of the land.

**Comment by janpio** [comment]
@jasonkuhrt Can you please recreate this in a `prisma-labs` repo or make a note on your list? Thanks.

**Comment by schickling** [comment]
All Nexus-related packages will most likely be published under the `@nexus` NPM namespace in the future.

We're also planning to publish all JS-based Prisma tools under the `@prisma` NPM namespace.

**Comment by ChristianJacobsen** [comment]
@schickling I think that's a really good plan. Namespacing makes it easy to associate packages with a product as opposed to prefixing it with a package name + hyphen (looking at you eslint...).
