### ISSUE TITLE
Endpoint and Prisma Binding

### ISSUE THREAD

**Issue by cesarve77** [prisma/prisma2#216]
I'm wondering if Prisma 2 will have an endpoint just like Prisma 1 has.

And what is the future of Prisma Binding

Thanks

**Comment by Errorname** [comment]
You can find the answer on the PhotonJS website: https://photonjs.prisma.io/

In the FAQ, under **`Does Photon support GraphQL schema delegation and GraphQL binding?`**

> GraphQL schema delegation connects two GraphQL schemas by passing the info object from a resolver of the first GraphQL schema to a resolver of the second GraphQL schema. Schema delegation also is the foundation for GraphQL binding.
>
>Prisma 1 officially supports both schema delegation and GraphQL binding as it exposes a GraphQL CRUD API through the Prisma server . This API can be used to as foundation for an application-layer GraphQL API created with GraphQL binding.
>
>With Prisma 2, Prisma's query engine doesn't expose a spec-compliant GraphQL endpoint any more, so usage of schema delegation and GraphQL binding with Prisma 2 is not officially supported. To build GraphQL servers with Prisma 2, be sure to check out GraphQL Nexus and its nexus-prisma integration. GraphQL Nexus provides a code-first and type-safe way to build GraphQL servers in a scalable way.

**Comment by cesarve77** [comment]
Perfect thanks!

**Comment by timsuchanek** [comment]
Thanks @cesarve77 for asking and @Errorname for taking care!
