### ISSUE TITLE
`prisma dev`: Improve rendering for small terminal windows

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#23]
![image](https://user-images.githubusercontent.com/1567498/59554671-becd9d00-8fa6-11e9-8fd3-13d88dbfa7e0.png)

We could also enforce an absolute minimum size and render something along the lines of "Window not big enough" when it's too small.

**Comment by timsuchanek** [comment]
Fixed in latest version. I added media queries for the UI and once the terminal window is smaller than a certain row count, it'll be scrollable.
