### ISSUE TITLE
Lift - 2 Scenarios

### ISSUE THREAD

**Issue by kleydon** [prisma/prisma2#231]
Hi, I'm wondering how database migrations will work with Lift in Prisma2, in two scenarios:

1) Say I started out with a "FullName" field, and later, want to break this out into "First Name" and "Last Name", and populate First/Last from Full. When does this population happen? If I use the "after" hook, the "FullName" field still exists after I populate the database. Do I need a second migration to then delete the FullName field?

2) Say I have a migration I want to perform that doesn't change the structure of the database at all. For instance, I want to add 20$ to an existing "amount" field for every user, and I want the event checkpointed in time. How would you approach this via Lift?

Thanks,

-K

**Comment by pantharshit00** [comment]
You can use hooks before and after hooks for this.
https://github.com/prisma/specs/tree/master/lift#writing-before-or-after-migration-scripts

Using these you can perform database operations like modifying the fields using database client at that point

So for the first scenario what you will do is:
1. Create a new optional field "first" and "last"
2. Using after step, populate them with correct data using the "FullName" field
3. Make them required from a new migration
4. Delete full name if you want


For the second scenario, you will use the same datamodel with no diff in your migrations folder. Then you can perform this data operation the after step. But really for this, I think it is mostly done via script then a migration as you typically don't want to keep track of this as it not data agnostic and affect things if you want to rebuild that database with separate dataset.

**Comment by kleydon** [comment]
Thanks for the clarification!

In case related feedback is useful: I'm imagining that as a developer-user, I would want any/all changes to a database (which don't take place through natural usage of connected app(s)) to be _in the same place_ - so that I can look at the change history chronologically, and know that I am looking at a _complete_ set of (developer) changes. It sounds like this will be possible - which seems exciting!
