### ISSUE TITLE
Will the release version of prisma2 support subscriptions and aggregation?

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma2#234]
Hi.
I don't see subscriptions and aggregates in the current preview version, I am worried that these features are not available when prisma2 is released.
In addition, when will the release of prisma2? I am planning to open a new project, I am going to use prisma2. It's great.👍

**Comment by pantharshit00** [comment]
For aggregations, the API has been speced out, it will be implemented over the coming weeks: https://github.com/prisma/specs/tree/master/photon-aggregration-api

For subscriptions, there are plans for an events engine as mentioned by Marcus in his talk here(https://www.youtube.com/watch?v=RAoXdyI_PH4) but we will handle that after Prisma 2 is launched and generally available. We will need to carefully spec that out first.

**Comment by schickling** [comment]
Closing in favor of https://github.com/prisma/photonjs/issues/5#issuecomment-516729970
