### ISSUE TITLE
`prisma init` didn't mention in output where it downloaded/installed the project

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#240]
```
[...]
<  Back                (Language selection)
√ Downloading starter from https://api.github.com/repos/prisma/photonjs/tarball/master
√ Extracting content to C:\Users\Jan
× Installing dependencies 👩‍🚀

  Your template has been successfully set up!

  Here are the next steps to get you started:
    1. Run prisma2 lift save --name init to create a migration.
    2. Run prisma2 lift up to apply the migration.
    3. Run yarn seed to seed the database.
    4. Run yarn start (Runs the default script)
    5. That's it !
```

Seems this created `C:\Users\Jan\prisma` but didn't mention that to make it discover-able.

(preview-2)

**Comment by janpio** [comment]
Oh, seems you are actually not expected to go into that `prisma` folder, otherwise the suggested command fails:

```
C:\Users\Jan\prisma>prisma2 lift save --name init
Error: Could not find C:\Users\Jan\prisma\prisma\schema.prisma
```

That surprised me.

**Comment by pantharshit00** [comment]
We currently expect Prisma files to be stored in a prisma folder inside your project folder.

So a typical structure is:
```sh
.
├── prisma
│   ├── schema.prisma
│   └── seed.js
├── src
│   └── script.js
├── README.md
├── package.json
└── yarn.lock
```


There is already a feature request for customization of this path #225 

Also, this is being tracked via this issue in the spec repository: https://github.com/prisma/specs/issues/21

So I think we can close this as a duplicate of those two.

**Comment by janpio** [comment]
This actually wasn't about what it does, but about what it communicated in the output to the user. I followed some instructions (unfortunately can't remember exactly which ones, but did the SQLite thing) and I wasn't aware that I should do that in some project folder (I thought it would create one), and also I got not output what it had done so I had to start looking in the filesystem.

**Comment by divyenduz** [comment]
@janpio What is your suggestion to move this forward?

**Comment by janpio** [comment]
This is from the suuuper old `init` which does not exist any more.
