### ISSUE TITLE
Documentation should clarify not implemented features

### ISSUE THREAD

**Issue by Akkuma** [prisma/prisma2#251]
It would be really helpful if the documentation was kept in sync with the capabilities prisma2 has today and have features such as embed noted as not currently being implemented.

**Comment by pantharshit00** [comment]
We currently have this limitation file: https://github.com/prisma/prisma2/blob/master/docs/limitations.md

**Comment by Akkuma** [comment]
> https://github.com/prisma/prisma2/blob/master/docs/limitations.md

That is definitely helpful as I've looked at it before, but it reads as more of a high level limitations during the preview state rather than limitations about every feature. If that file were updated it would still require pulling it up side-by-side while reading the rest of the documentation to ensure you can use the feature today.

**Comment by janpio** [comment]
Thanks for bringing this to our attention @Akkuma, we agree with your comment and decided to tackle this in this milestone. We will also further improve the `limitations.md` document to be more structured and have more information.

I close this now as we will be using https://github.com/prisma/prisma2/issues/433 to track the update to our documentation.
