### ISSUE TITLE
Error: spawn E2BIG

### ISSUE THREAD

**Issue by witt3rd** [prisma/prisma2#254]
Trying to run `prisma2 generate` (`preview-3`) on an 18MB model file results in `Error: spawn E2BIG`

**Comment by schickling** [comment]
Thanks a lot for reporting this issue. It seems pretty rare to have a schema file that’s larger than a mega byte. Would you mind elaborating on your use case @witt3rd?

**Comment by witt3rd** [comment]
I am trying to create a GraphQL wrapper for an industry standard database: https://github.com/rbhughes/pg_ppdm

**Comment by jmadson** [comment]
I'm receiving the same error message. We have 400+ Postgres tables. I was following the tutorial:

- ran `prisma2 init`, which generated the `schema.prisma` file based on those tables. The file size is only 268 KB.
- Attempted to run `prisma2 generate` to generate the photon client

Received error message:

```
Error: spawn E2BIG
```

**Comment by schickling** [comment]
Thanks a lot for providing this additional information. We'll be looking into it!

**Comment by thortek** [comment]
I'm now receiving the same `Error: spawn E2BIG`.  I attempted to execute` prisma2 generate` running on Ubuntu 18.04.2 with Postgres 11 in Docker on Digital Ocean.  I've only got 102 tables created and a 158kb `project.prisma` file causing this.  This same build process has worked just fine on my local iMac.

**Comment by thortek** [comment]
BTW, with the exact same setup I described yesterday except that I updated to preview5, I get the following more detailed error: 
```
Error: Error: Command failed with exit code 7 (E2BIG): /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf
spawn E2BIG
```

**Comment by timsuchanek** [comment]
This requires more research.

**Comment by thortek** [comment]
I have a sample reproduction here to hopefully help track this down: https://github.com/thortek/prisma2-issue254-reproduction

**Comment by divyenduz** [comment]
I am able to reproduce @thortek's reproduction. 

Related: https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument

**Comment by janpio** [comment]
This specific bug can now be attempted to be fixed.

**Comment by divyenduz** [comment]
I can confirm that `lift save` and `lift up` work even with 10k models. 

Save takes around 1500s
Up takes around 70s

**Comment by williamluke4** [comment]
I'm currently receiving the same issue 
1) Ran `prisma init`
2) Selected Postgres
3) Added Heroku Postgres Credentials
4) Selected Existing Schema (127 Tables, 7880KB)
5) `E2Big`
It appears that there are errors in the config that is printed when it fails but digging through the dump is very cumbersome. For example, this is one of the errors I found 
```
"documentation\":\"Field name normalization failed because of a conflicting field name.\\n
  Could not auto-generate backwards relation field, field name would be ambiguous.\\nPlease specify the name of this field and the name of the relation manually.\\nIt references 
  PropertyAccess.nearestLocalAirport.\"
```
Any chance of just logging the documentation

**Comment by thortek** [comment]
I was able to get around this bug by removing all comment lines from my `schema.prisma` file.

**Comment by paales** [comment]
I'm running into this issue when I'm trying to introspect an existing database. It seems we're not able to pass around such big files. Should be 'easy' to fix by writing the output to a file and then loading that file content, or maybe pipe it into the command?

**Comment by divyenduz** [comment]
Unfortunately, this got dropped in the current sprint 🙏 

I will raise it again next week. Please raise your voice here with reactions and comments to get this some prioritization points 🙏

**Comment by witt3rd** [comment]
Just update your documentation to say you only support small databases, saving people from having to discover it for themselves.

**Comment by jmadson** [comment]
Just chiming in. This is a must-have for our team.

**Comment by williamluke4** [comment]
Please make this a priority! This is a major blocker when trying to transition from prisma1 to prisma2

**Comment by timsuchanek** [comment]
We did some research on this and it turns out, that for a schema with 1000 models, we generate 500k lines of code with a file size of 30mb.
The TypeScript compiler is not able to handle the compilation of that.

Next steps:
1. Reduce output size. There are a few places, where we can shave a bit of size off.
2. Directly generate `@generated/photon/index.js` and `@generated/photon/index.d.ts` without the TypeScript compiler

**Comment by jmadson** [comment]
Would it help if the TypeScript types were generated into different files (eg. one per model) and then each of those were simply exported from the index file? Then it might be possible to chunk the code gen.

For example, the files for the generated JS and TypeScript typings for a User model might look like:

`@generated/photon/user.js`
`@generated/photon/user.d.ts`

Then inside `@generated/photon/index.d.ts` it could export the user types:
```
export * from "./user";
```

Splitting it out like this might help it to scale better when you have hundreds or even thousands of models. For example, I'm not sure my IDE likes parsing files that are tens of MBs in size...

**Comment by divyenduz** [comment]
We just had a discussion about this issue, we have to push it back a few weeks (3-4) to solve it properly after https://github.com/prisma/photonjs/issues/238 (a lot of related changes) is implemented. 

However, to temporarily unblock people, we can do #621, which I already raised for the next sprint 🙏 

Please bear with us on this one, it is a high priority for us and on our mind, we are working towards fixing this every sprint 🙌

**Comment by mohib0306** [comment]
I tried the latest [Preview#14](https://github.com/prisma/prisma2/releases/tag/2.0.0-preview014)  locally and then executed `prisma2 init` to generate `prisma.schema`  for my local DB. The DB has 288 tables and it failed with the message `spawn E2BIG`. 
It was mentioned in https://github.com/prisma/prisma2/issues/621 that it will likely be part of the Preview#14 that this issue will be addressed. Is there any update on it.

p.s. I already tried `--max-old-space-size` but that didn't help as well

**Comment by divyenduz** [comment]
I can confirm that this reproductions is still reproducible https://github.com/divyendu-test/p2-254

With this error 
![image](https://user-images.githubusercontent.com/746482/66741052-e8bf9f00-ee74-11e9-85db-33abd763b534.png)

**Comment by Manouli** [comment]
Tried to use this on our existing DB and unfortunately it won't work. Hopefully we can get it soon.

**Comment by farukg** [comment]
Hi,
I have the same Issue. I had it also with prisma1. I tried again today and unfornutaly it still doesnt work.
prisma2 says `61 tables, 2.58 MB` Thats not much, right?
I think --max-old-space-size is not the correct direction to investigate, besides that it doesnt work in my case, i tried lowering it, just to see what happens to 1. If you do that, you get a real  `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

![image](https://user-images.githubusercontent.com/1577842/68058875-b9c17e00-fcfa-11e9-9a34-5fd9228285ae.png)

With values above some threshold  ~70MB i get a lot of json output of the schema:
First  few lines: 
![image](https://user-images.githubusercontent.com/1577842/68059046-5a17a280-fcfb-11e9-9613-cd7283bd07dd.png)
and the last lines:
![image](https://user-images.githubusercontent.com/1577842/68059122-8b906e00-fcfb-11e9-8d44-68a814c5d190.png)

i tried values between 500 - 12000 it always raises E2BIG Error. :(
its also the same when going via prisma2 init instead of the the introspect command.
Last time i had this issue couple of month ago, i googled a lot, and found almost nothing...i remember it was something about node's threading lib... child.process or fork of new Thread or so....maybe you know more about this

Hope i could help

**Comment by Manouli** [comment]
@timsuchanek Did this get fixed?

**Comment by timsuchanek** [comment]
@Manouli it'll take still a bit until it's out, the CI pipeline is stuck. I'll ping you once it's out!

**Comment by timsuchanek** [comment]
We have a new alpha out, which already fixes it for schemas of the size of 1000 models. It seems like schemas with 10000 models are not yet working. We'll investigate and do a fix soon!

**Comment by Manouli** [comment]
@timsuchanek that should more than enough for me :) Thank you so much

**Comment by williamluke4** [comment]
2.0.0-preview016 fixed this error for me

**Comment by timsuchanek** [comment]
Update: In https://github.com/prisma/prisma2/releases/tag/2.0.0-preview016.2 we pushed the limits a bit further again - a schema with 3000 models is now working.
The next (and last) big leap to get to even bigger schemas is an optimization to the Photon generator code.

**Comment by Manouli** [comment]
@timsuchanek I can confirm that its working for me now. Thank you so much for dealing with this.
