### ISSUE TITLE
Typescript export ModelClient

### ISSUE THREAD

**Issue by ManAnRuck** [prisma/prisma2#257]
the *Model*Client is currently not exported.
It's needed to handle the ESLint rule `@typescript-eslint/explicit-function-return-type`.

example code: typescript-graphql example

<img width="1003" alt="Bildschirmfoto 2019-07-27 um 22 08 57" src="https://user-images.githubusercontent.com/2183135/61999137-3240ef00-b0bb-11e9-82fd-82005fcaef83.png">
<img width="656" alt="Bildschirmfoto 2019-07-27 um 22 06 30" src="https://user-images.githubusercontent.com/2183135/61999142-408f0b00-b0bb-11e9-8b71-2fee69b7c24e.png">

**Comment by timsuchanek** [comment]
Thanks for reporting! Done in latest alpha.
