### ISSUE TITLE
CLI generated `undefined` when you enter and delete a field in database credentials flow.

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#26]
To Reproduce:
1. Go the credentials entering flow
2. Add a field
3. remove the field.

**Comment by timsuchanek** [comment]
Fixed in the latest version.

**Comment by tvvignesh** [comment]
@timsuchanek This occurs even now when you try to press the delete button (backspace works though) - Using prisma2@2.0.0-preview-3.1 - Screenshot below.

![undefined](https://user-images.githubusercontent.com/1165845/62069196-59cbbf00-b255-11e9-9562-855a424cbd8f.png)

**Comment by schickling** [comment]
This will be fixed as part of #278

**Comment by divyenduz** [comment]
I am still able to reproduce parts of this on Mac, on a Mac

`delete` key acts like backspace on windows/linux systems
- Not reproducible here anymore

`fn` + `delete` key acts like delete on windows/linux systems
- It is reproducible here

**Comment by timsuchanek** [comment]
We disabled the `Delete` key for now.
