### ISSUE TITLE
How to provide the DB connection string in a more secure fashion?

### ISSUE THREAD

**Issue by artemzakharov** [prisma/prisma2#261]
Right now, the connection string is stored in the `schema.prisma` file in its full glory - host, username, **password**, you name it. This obviously isn't secure, as it means anyone who has access to the file has full access to the database, yet the file can't simply be git ignored and stored securely, as it also contains the entire data model and is required to actually do back end development.

Is there any way to provide this string from, say, an environment file?

**Comment by iherger** [comment]
You can use environment variables: https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#using-environment-variables

**Comment by pantharshit00** [comment]
Yes, you will provide them using environment variables similar to passing it in javascript. There we also store these secrets in environment variables.
