### ISSUE TITLE
Option to specify path for Photon & Nexus output files

### ISSUE THREAD

**Issue by artemzakharov** [prisma/prisma2#262]
As of right now, when looking for a place to put the generated code, Photon & Nexus apparently either find or create a `node_modules` folder, and then place the code in the `@generated` sub-directory of it. This works fine on a simple test project, but I'm running into an issue where I have a mono-repo setup with multiple projects in it:

1. If I structure the project such that the generated code is placed in the `node_modules` folder at the *root* of the project, then I'll suddenly have potential conflicts between different Photon/Nexus projects all overwriting the same locations. 
2. If I structure the project such that Photon/Nexus essentially create a new `node_modules` folder for each project, I'm now apparently unable to actually import the client, as the `import Photon from "@generated/photon"` found in the tutorial only seems to work for the root `node_modules` folder, and I get various "cannot find module" errors if I try to import the various clients directly, like via `foo/node_modules/@generated/photon`. 

What's the best way to go about handling multiple Photon/Nexus projects in a single repo?

**Comment by pantharshit00** [comment]
You can configure the path using the output property:

```groovy
generator js {
  provider = "photonjs"
  output   = "./generated/photon"
}
```

**Comment by artemzakharov** [comment]
@pantharshit00 I tried what you suggested, and while it did indeed output to the specified directory (I used `prisma/generated/photon`), I'm getting this error when I try to start the server:

```
Error: Cannot find module 'prisma/generated/photon'
```
What's interesting is that Typescript doesn't give me any kind of warning or error prior to actually starting the server, and everything seems to import file - it's only when I actually start it that I get this error, and the server crashes.

I've tried using other locations as well, but the only one that ever works is inside `node_modules`.

**Comment by pantharshit00** [comment]
If the output is outside of your node_modules folder, you will need to specify a relative path unless you have defined a babel or webpack plugin or configured your tsconfig to resolve that.

Try this:
```ts
import Photon from './prisma/generated/photon';
```

**Comment by artemzakharov** [comment]
That worked, not sure why a relative path was explicitly required when the import appeared to be valid when using an absolute path (typescript gave off no warnings and I had full access to autocomplete on types and such) but I guess that's a thing I'll have to keep in mind. Thanks!

**Comment by timsuchanek** [comment]
@artemzakharov `./` is needed, as this is a Node.js convention. Paths without a `./` or `/` are resolved as a node module.

As of now we don't have the option to provide the path to the schema file, but feel free to create an issue!
