### ISSUE TITLE
Support Enum's Default Value which value contains underscore 

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma2#270]
For example:
```
enum Relation_EmployerStateEnum {
    ON_JOB
    OFF_JOB
}
```
This looks like good,
But when I try to make this enum's field's default value, I got error:
![image](https://user-images.githubusercontent.com/3894825/62047145-4c560b00-b23c-11e9-9a35-aa6b535fd190.png)
(By the way, the problem's line number showed in the vscode problem's panel always bigger than the actual line number )

Even in some cases(#266 ), this problem leading the vscode problems panel report strange problem -- "Unexpected token. Expected one of: ."--
 and other existing problems are not shown because of  this.

**Comment by mavilein** [comment]
Thanks for reporting this! 🙏 
A fix is available on alpha now.
