### ISSUE TITLE
[Suggestion] Optimize the Prisma2 Spec Document Example

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma2#272]
In the prisma spec [Multiple-Reference Relationships](https://github.com/prisma/specs/tree/master/prisma-schema-language#multiple-reference-relationships), I think this example maybe misleading, so I suggest change the example from 
```
model User {
  id        Int         @id
  asked     Question[]  @relation("asker")
  answered  Question[]  @relation("answerer")
}

model Question {
  id        Int   @id
  asker     User  @relation("asker")
  answerer  User  @relation("answerer")
}
```
to
```
model User {
  id        Int         @id
  asked     Question[]  @relation("FK_Question_User_Asked")
  answered  Question[]  @relation("FK_Question_User_Answerered")
}

model Question {
  id        Int   @id
  asker     User  @relation("FK_Question_User_Asked")
  answerer  User  @relation("FK_Question_User_Answerered")
}
```
because the original example make devolpers think the relation name must equals to their corresponding field name.(in this case, they may think the relation name must be "asker" and "answerer")

**Comment by pantharshit00** [comment]
cc @nikolasburk 

Thanks for your feedback :)

**Comment by schickling** [comment]
I'd suggest to remove the `FK_` prefix though:

```prisma
model User {
  id        Int         @id
  asked     Question[]  @relation("Question_User_Asked")
  answered  Question[]  @relation("Question_User_Answerered")
}

model Question {
  id        Int   @id
  asker     User  @relation("Question_User_Asked")
  answerer  User  @relation("Question_User_Answerered")
}
```

**Comment by nikolasburk** [comment]
Thanks a lot for your input @zzyyzz1992, I just updated the spec here: https://github.com/prisma/specs/blob/master/schema/Readme.md#multiple-reference-relationships
