### ISSUE TITLE
Serverless (Faas) compatibility

### ISSUE THREAD

**Issue by mcongy** [prisma/prisma2#276]
Hello,

I have multiple questions regarding Prisma2 usage in serverless environments.

1. In limitations section, you mentioned that

> Processes 1 request at a time, no parallelism during the early preview period.

Is this a problem in serverless environments?
(1 VM execute 1 lambda at a time, no need for connection pooling).

2. Using database adapters (or ORMs) in serverless (FaaS) environments is tricky, because:
a) there can be even several thousands of concurrent lambdas executing at a particular time 
b) there isn't a shared connection pool
c) database connection pool is limited size. Lambda function either has to close the connection when it's finished (not very performant, because no connection can be reused) or we have to schedule another lambda that closes zombie connections (connections that are not used for more than time, after which the lambda gets "cold" and it's context is destroyed). Or there might be a better solution. 
For example you can check out this package that wraps mysql adapter for serverless environments https://github.com/jeremydaly/serverless-mysql
More context:
https://www.jeremydaly.com/reuse-database-connections-aws-lambda/

Does Prisma plan to add support for this?

Thank you!

**Comment by sorenbs** [comment]
Hey @mcongy - great questions :-)

1)
You are correct. This limitation only pertains to the query engine running on a single instance. If you are only ever sending 1 request at a time, then this is not a concern. This will often be a case with Lambda as you point out, but even with Lambda there are cases where a single Http request results in multiple database requests. During the Prisma 2 preview these will be handled serially, even if your runtime would support parallel execution. This is a temporary limitation that we will lift before the GA release.

2)
You are exactly right. We believe that the various database hosting providers will solve this issue by providing scalable connection proxy servers. DOs new [Postgres offering](https://www.digitalocean.com/products/managed-databases/) comes with pgbouner by default, and AWS is working on a [data api](https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/) that enable you to use a more scalable request/response pattern for querying an Aurora database.

That being said, using Photon with any database should be as seamless as possible. We already have the ability to detect that photon is running in a serverles environment, and I think it would be a good idea to support the workaround that is implemented in serverless-mysql.
Do you have any thoughts on how this should work and be configured?
It would be great if you could open a separate feature request for this providing as much context as possible.

Thank you!

**Comment by seanemmer** [comment]
Also exploring support for serverless.  The use case I'm planning for is apollo-server-lambda + Photon running inside of a netlify function (although zeit is a potential alternative).

What are the implications of running the Photon query engine binary inside of a lambda.  I anticipate a high volume of cold starts and if the binary adds a material amount of time to a cold start this will translate to response time latency.

**Comment by divyenduz** [comment]
Thanks for the great discussion and feedback everyone 🙌 

We also documented the characteristics of Photon in a FaaS like environment here: 
https://github.com/prisma/prisma2/blob/master/docs/photon/deployment.md#photon-in-faas-environment-eg-aws-lambda-netlify

I am closing this issue, please feel free to open a new issue if you think that something is not addressed by the documentation.

**Comment by iRoachie** [comment]
@divyenduz Do you have any examples of how this would be different if using the graphql setup?
