### ISSUE TITLE
EPIC Implement new `prisma init` CLI flow

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#278]
See https://prisma-specs.netlify.com/cli

**Comment by janpio** [comment]
3 RPCs:
- Check if database exists
- 
-

TODO fill @timsuchanek

**Comment by timsuchanek** [comment]
Ideally should run on a single connection instead of a pool, so that we don't need to wait 3sec until the pool times out if the connection can't be established.

**Comment by divyenduz** [comment]
Related: https://github.com/prisma/prisma2/issues/399

**Comment by divyenduz** [comment]
This is implemented in `prisma2@2.0.0-alpha.150`, please open a new issue if you run into a specific bug/feature request. It is build as per this spec: https://prisma-specs.netlify.com/cli/
