### ISSUE TITLE
Datasource url should be optionally dynamic (preserve env())

### ISSUE THREAD

**Issue by chrisui** [prisma/prisma2#287]
Currently `prisma generate` with a datasource of `env()` appears to write in the value at build time. This breaks stateless builds (which are always runtime configurable and doesn't require prevent building between environments).

It would be better if `env("NAME")` could instead be built into `process.env["NAME"]`.

Ie.

```
datasource pg {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

Should generate...

```
class Photon {
  internalDatasources = [
    {
       "name": "pg",
       "connectorType": "postgresql",
       "url": process.env["DATABASE_URL"],
       "config": {}
    }
  ]
}
```

**Comment by Errorname** [comment]
Hello! There is a discussion about this here: #227, you can explain your use case there to push this subject forward

**Comment by timsuchanek** [comment]
Fixed in latest version.

**Comment by kldzj** [comment]
Hi @timsuchanek, it seems like the generated client still (or possibly again?) contains the database connection string. Is there something other than creating a post-postinstall script that replaces the connection string with a call to read from process.env that we can do on our side?
