### ISSUE TITLE
Connect only once

### ISSUE THREAD

**Issue by tristancaron** [prisma/prisma2#288]
With a relation `many to many`, if we connect something with the same ID, it just makes twice the connection. Would it possible to connect only if it's not already connected?

**Comment by pantharshit00** [comment]
I think if you make the relation unique, you will be able to connect only once.
Example:
```groovy
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photonjs"
}

type ID = String @id @default(cuid())

model X {
  id   ID
  data String
  y    Y[]    @unique
}

model Y {
  id    ID
  stuff String
  x     X[]    @unique
}
```

So when you will try to create the item again, it will throw a unique constraint violation.
