### ISSUE TITLE
Studio intermittently fails with a ECONNREFUSED Error

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#299]
Original comment: https://github.com/prisma/prisma2/issues/114#issuecomment-516159575

Studio/photon are most likely unable to connect to the binary.

**Comment by schickling** [comment]
Hitting the same problem:
![image](https://user-images.githubusercontent.com/1567498/62204157-ea58eb00-b38c-11e9-84df-3f84a36cacce.png)

**Comment by schickling** [comment]
Here's a reproduction:
[new-server.zip](https://github.com/prisma/prisma2/files/3456138/new-server.zip)

**Comment by madebysid** [comment]
Fixed with preview.4

**Comment by tvvignesh** [comment]
Hi. The same error occured again, but this time, not in studio but when I was running the seed against the database as mentioned in the screenshot below. I guess that studio is not the only thing connecting to the binary. Won't the same thing happen in prod when running via script unless the binary is actually fixed?

![Screenshot from 2019-10-27 12-00-51](https://user-images.githubusercontent.com/1165845/67630674-70fc6600-f8b1-11e9-98f8-d971550f6c98.png)

**PS:** I ran the same command again in few seconds and then it worked. So, looks like sort of race condition.

And this is what I had in seed.js

```
const { Photon } = require('@generated/photon');
const photon = new Photon();
const moment = require('moment');
/**
 * SEED FUNCTION FOR ACCOUNTS TO LOAD INITIAL TEST DATA
 */
async function main() {
    const user1 = await photon.users.create({
        data: {
            firstName: 'Vignesh',
            lastName: 'T.V.',
            username: 'tvvignesh',
            displayName: 'Vignesh',
            dob: moment('1992-12-30').toDate(),
            settingListID: [],
            tagListID: [],
            email: {
                create: [
                    {
                        emailAddress: 'vignesh@timecampus.com',
                        emailType: 'primary',
                        alias: 'primary email',
                        settingListID: [],
                        tagListID: []
                    }
                ]
            },
            phone: {
                create: [
                    {
                        contactNo: '+91-7358445777',
                        alias: 'personal mobile',
                        contactType: 'primary',
                        settingListID: [],
                        tagListID: []
                    }
                ]
            }
        }
    });

    console.log({ user1 });
}

main()
    .catch(e => console.error(e))
    .finally(async () => {
        await photon.disconnect();
    });

```
