### ISSUE TITLE
Lift: Enum list migrations do not seem to work

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#300]
Steps to reproduce:

1. `prisma2 init` with MySQL + New schema
2. Create one model with an enum list. Schema I used:
```
datasource db {
  provider = "mysql"
  url      = "mysql://root:prisma@localhost:3306/prisma2managed?sslmode=prefer"
}

model User {
  id          Int        @id
  permissions Permission[]
}

enum Permission {
  ADMIN
  USER
  COLLABORATOR
  OWNER
}
```

3. `prisma2 lift save && prisma2 lift up`

If you take a look at the DB now, there isn't a `permissions` column for the `User` table.

FWIW, non-list enums work fine. (`permissions Permission`)

**Comment by mavilein** [comment]
This is fixed and available on alpha now.
