### ISSUE TITLE
Suggestions and ideas

### ISSUE THREAD

**Issue by ansarizafar** [prisma/prisma2#301]
Prisma2 can be a game changer and the goal is to make data access simple, fast and easy for the developers. Currently, each project must have a schema.prisma in prisma folder where we define data sources and models and then we use prisma2 cli commands to save a migration in the project folder, create migration hooks in saved migration folder, apply migration, generate clients and then use Prisma admin to mange data(add/modify/delete/find). 

There are few issues with this approach. 

- The current workflow has too many steps and multiple tools(Prisma2 Cli, photon, lift, Prisma admin) to learn which is against the goal of Prisma2. 
- Each project already use some method/file to store project related config and it should not be required to store database connection info in another place (schema.prisma).
- If I want to use the same database with multiple different projects written in Nodejs, Go etc then where should I create the schema file and define models, save migrations and generate clients for multiple languages/projects in this case.
- Query engine generate multiple database queries for a single photon query which means multiple database round trips and increased latency. https://github.com/prisma/photonjs/issues/151

I think we can do better. I am suggesting a different approach to further simplify the workflow and make it easy to understand and use Prisma. 

Schema represents the current structure/state of the database and it should be stored in the database. If we can store versioned schema with some meta data in the database then we don't need schema.prisma file in each project and we don't even need Prisma2 cli/lift to save migrations in the file system, apply migrations and generate client with cli commands. We only need one tool (Prisma Admin) to manage schema(Create/Introspection/Edit/Apply/Rollback/Import/Export/Generate client) both in development and production environments. Here is the new workflow.

- Use Prisma Admin UI to create/modify/apply versioned schema in each database. If you want a virtual database (Models from multiple data sources) then use import syntax to import required models from multiple data sources in the main/master database. Generate migration whenever a new schema version is applied to the database but don't store it. If the developer wants to see the DDL then he should be able to select an option in the UI.
- Generate Prisma client(any language) for active/current schema and save it in any project folder  with Prisma admin.
- Import prisma function from generated Prisma client and pass database connection string as a parameter.

I would also like to suggest Svelte/Sapper https://svelte.dev in place of React for creating fast and light weight Prisma admin UI.

**Comment by divyenduz** [comment]
@ansarizafar Thanks for the great suggestions and feedback, we are incorporating many of these already 🙌 

I will close this issue for now (unless you or anyone else has more to add to it). I welcome you to create a new issues after we have the new workflows in place. 

Please ping me via a comment if you think that this issue should not be closed.
