### ISSUE TITLE
`prisma2 generate` generates files into wrong directory

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma2#306]
I am working with the [Prisma2 Tutorial](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md) but am getting stuck where someone has to perform a `prisma2 generate`. (https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#6-generate-photon-js)

It gets generated into the `prisma/node_modules/` directory but should get generated into the root `node_modules/` directory. My working directory is `Prisma2` which contains the root `node_modules/` directory.

Prisma version: **2.0.0-preview-3.2**

<img width="276" alt="Screenshot 2019-08-01 at 15 37 48" src="https://user-images.githubusercontent.com/3816295/62298466-544bc000-b473-11e9-896d-b45ed8f768fb.png">

**Comment by nickreynke** [comment]
**Update**: After removing both `node_modules/` directories and running `npm install` again it works.

Don't know what that was. Will open the issue again when it happens again.

<img width="195" alt="Screenshot 2019-08-01 at 15 57 05" src="https://user-images.githubusercontent.com/3816295/62299402-2d8e8900-b475-11e9-8c1a-cd2f5f822e14.png">

Dont

**Comment by darioielardi** [comment]
I'm having the same problem, when I get to that tutorial step and I run `prisma2 generate` it generates the client in a `node_modules` folder inside the `prisma` folder, which is the only folder in the project. 

So I tried to run `npm init`, delete the generated folder ( the whole new `prisma/node_modules` ) and then run again `prisma2 generate`, which now managed to generates the client in the root folder of the project.

**Comment by pantharshit00** [comment]
I can now confirm this. 

This only happens when there is no `node_modules` folder in the root at first.
