### ISSUE TITLE
Improve error message when DB not migrated

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#31]
Is there anything we can do to improve the user experience when a user forgot to migrate their database (or it doesn't exist)?

![image](https://user-images.githubusercontent.com/1567498/59346383-70a06b80-8d12-11e9-9dc8-b21abdbb89fd.png)

**Comment by schickling** [comment]
Will be specced out as part of https://github.com/prisma/specs/issues/3

**Comment by divyenduz** [comment]
This should be implemented with the errors spec.
