### ISSUE TITLE
cli flags for non-interactive

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma2#313]
Sometimes a developer wants to script, write guide, or like the cli and in those cases passing flags to fulfill prompts is desired. Example:

```
❯ prisma2 init myblog

 What kind of database do you want to introspect?
 ──────────────────────────────────────────────────

❯  SQLite              Beginner's choice
❯  MySQL               MySQL compliant databases like MySQL or MariaDB
❯  Postgres            PostgreSQL database
```

Example flag

```
prisma2 init --db postgres
```

I left the issue more general than about just `init` because I am assuming there are other instances.

**Comment by rizowski** [comment]
My particular issues is around the generated client. If an error generated by the photon client were to escape say for passing too many arguments to `.findOne` the errors are pretty printed with color and other formatting. When those kind of errors are caught or returned to the client, it is very difficult to see what they are saying. It will also gunk up logs if we were to send them to services like loggly or elasticsearch. 

So the ability to turn this off either in the photon client or in the cli would be preferred.

**Comment by janpio** [comment]
Thanks @rizowski, although related this is a different problem than what @jasonkuhrt initially wrote about (input in non interactive scenarios). I think your issue https://github.com/prisma/photonjs/issues/195 captures your problem pretty well and should be the location to track this problem.

**Comment by tvvignesh** [comment]
Requesting to take this issue on priority. I was trying to get prisma2 lift commands in package.json scripts and get it running via Dockerfile but it was stuck since it was expecting for input from me.

![Screenshot from 2019-12-22 19-05-08](https://user-images.githubusercontent.com/1165845/71322486-04d36280-24ee-11ea-8d19-fd744c56a122.png)

**Comment by janpio** [comment]
There is an option for you @tvvignesh: `-c, --create-db   Create the database in case it doesn't exist`. You can learn about this an similar options via `prisma2 lift up --help`.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
