### ISSUE TITLE
ESLint error: '@generated/photon' should be listed in the project's dependencies.

### ISSUE THREAD

**Issue by schmidsi** [prisma/prisma2#314]
I'm trying to run eslint on my prisma2 test project and it gives me the following error:

'@generated/photon' should be listed in the project's dependencies. Run 'npm i -S @generated/photon' to add it  
From [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md)

Installing `@generated/photon` (obviously) does not work.

I see some possible solutions:
- Create a dummy `@generated/photon` repo that is only a placeholder and empty
- Try to make the `@generated` prefix an NPM standard.
- I just remove/disable this rule.
- Put @generated/photon in the "peerDependencies" or "optionalDependencies". I'm not sure if this gives weird side-effects? At least it would not try to install if I run `yarn` or `npm install`.
- Change the config so the generated files are placed somewhere else. But I actually like the `@generated` prefix.

Thoughts?

**Comment by ljharb** [comment]
bundledDeps is the right place; a PR to the import plugin would be welcome.

**Comment by divyenduz** [comment]
This also ties into the discussion around this: https://github.com/prisma/photonjs/issues/88

If we have a npm package scope that we "own", adding an optional dependency might be a way to make the linter work.

**Comment by cloverich** [comment]
Found this issue before I knew you could change the generated output via config. Linking for any other lost souls: https://github.com/prisma/prisma2/blob/master/docs/photon/codegen-and-node-setup.md

**Comment by schmidsi** [comment]
Should be fixed with the next version of eslint-plugin-import. Just put `@generated/photon` into `bundledDependencies` in `package.json`.

See https://github.com/benmosher/eslint-plugin-import/issues/1436
