### ISSUE TITLE
Prisma CLI merges `graphql` and `graphql-auth` examples when "GraphQL Boilerplate" is selected in `prisma2 init`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#321]
It should download only the `graphql` example but seems to weirdly mix it with `graphql-auth`, e.g. the `index.ts` file has the contents from `graphql` but there are lots of files/folders from `graphql-auth`.

**Comment by ManAnRuck** [comment]
is it also possible to add the selection for the other GraphQL examples in cli init process?

**Comment by nikolasburk** [comment]
> is it also possible to add the selection for the other GraphQL examples in cli init process?

Yes, we're actually working on `prisma2 init` this week where we'll improve it a lot. We actually have a "spec" for the entire flow that you can see [here](https://prisma-specs.netlify.com/cli/init/).

**Comment by deadcoder0904** [comment]
I think I just made #373 which is duplicate I think. Closing that one.

**Comment by deadcoder0904** [comment]
Just wanted to mention one thing I mentioned in the duplicate issue 👇

> Also, I just noticed it does not contain .gitignore by default so I was uploading node_modules. I think it would be cool if a default [.gitignore](https://github.com/github/gitignore/blob/master/Node.gitignore) is included in every example.

**Comment by divyenduz** [comment]
This is fixed in `prisma2@2.0.0-alpha.150`, please re-open a new issue if the problem persists for you.
