### ISSUE TITLE
Tab characters make schema parser unhappy + unclear error

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#327]
Steps to reproduce:

1. In a new `schema.prisma` file, type in:
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://siddhant@localhost:5432/experiments?schema=public"
}

model User {
  id      Int    @id
}
```

2. If you're on VSCode, `Cmd+Shift+P` -> Convert indentation to Tabs

`prisma2 dev` or a lift save + up will now fail.

FWIW, the VSCode plugin does complain before running the migration, but it is not clear what the error actually is.

**Comment by matthewmueller** [comment]
fixed by: https://github.com/prisma/prisma2/issues/327
