### ISSUE TITLE
Suggestion: Order of fields in the DMMF should be the same as the schema definition order

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#330]
For a datamodel like so:
```
model User {
  id Int @id
  cField String
  aField String
}
```

The order of fields in the DMMF would be:
1. aField
2. cField
3. id

Suggestion: 
Order should be:
1. id
2. cField
3. aField

Studio uses this order to render inputs in the details panel

**Comment by pantharshit00** [comment]
Unable to reproduce this. Order is correct: 

![image](https://user-images.githubusercontent.com/22195362/62490398-d0813300-b7e6-11e9-89ed-a849220b8cc9.png)

I am using prisma2@2.0.0-alpha.91, binary version: 7b1615a0376f0428948c4410e57a0b61c03d5960

**Comment by madebysid** [comment]
Digging around a bit more, I can't seem to reproduce this either anymore :/
Maybe it was something I was doing wrong yesterday. Closing as unactionable.
