### ISSUE TITLE
mysql attribute varchar error

### ISSUE THREAD

**Issue by bukede** [prisma/prisma2#335]
```
datasource ms {
  provider = "mysql"
  url      = env("MYSQL_URL")
}

generator photon {
  provider = "photonjs"
}

model User {
  id   Int    @id
  name String @ms.varchar(20)
}
```

prisma2 generate
Error: Schema parsing error: Attribute not known: "@ms.varchar".
  -->  schema.prisma:18
   | 
17 |   id   Int    @id
18 |   name String @ms.varchar(20)
19 | }

prisma2@2.0.0-preview-5
mysql 10.3.11-MariaDB

**Comment by pantharshit00** [comment]
They are not implemented yet. Related to #194

**Comment by henninghall** [comment]
@pantharshit00 So at the moment, do you know if there is a way to make a, for instance, VARCHAR field larger than the default?

**Comment by pantharshit00** [comment]
You can modify the underlying database manually for now.

**Comment by henninghall** [comment]
Alright, yes that is what I have been doing so far. Thanks for your great work! 🙂
