### ISSUE TITLE
Add API to override specific migration engine binary

### ISSUE THREAD

**Issue by infoverload** [prisma/prisma2#337]
For people using non-officially supported operating systems, there are multiple binaries that need to be moved to multiple different paths and be renamed. 

Right now, there is capability to specify a custom Prisma binary when running the Prisma2 CLI: https://github.com/prisma/specs/tree/master/binaries#api-additions , but one would have to manually swap out the migration-engine binary.  

It would be nice to have an API for the migration-engine binary as well.

**Comment by janpio** [comment]
@steebchen says we have this now, and he is using it with Photon Go 🚀 
Thanks for the issue @infoverload!
