### ISSUE TITLE
Custom binary platforms for query engine

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#343]
Recently, we implemented most parts of [this spec](https://github.com/prisma/specs/tree/master/binaries#api-additions). 

[Custom binaries](https://github.com/prisma/specs/tree/master/binaries#3-development-machine-is-mac-but-we-need-a-custom-binary-in-production) (manually compiled) section is still to be implemented though.

**Comment by mavilein** [comment]
The required part in the Prisma schema parser is done.

**Comment by janpio** [comment]
Sync between @mavilein and @timsuchanek necessary.
Spec is not "finished enough" to start implementation, ping @divyenduz

**Comment by divyenduz** [comment]
The spec is ready now to be implemented: https://github.com/prisma/specs/tree/master/binaries#how-to-fetch-binaries-1

**Comment by divyenduz** [comment]
This majorly impacted the following: 

1. Windows users (other users which we did not support yet) -> Windows the major use case is supported now
2. `platforms` -> `binaryTargets` rename -> This was suggested in the spec to avoid SEO wars with a future product that might include platforms. That is tracked here: https://github.com/prisma/prisma2/issues/553

This reduces the priority of this issue for now.

**Comment by janpio** [comment]
Internal note: Dropped as re-prioritized.

**Comment by janpio** [comment]
What exactly is not implemented here @divyenduz? ENV vars like `PRISMA_QUERY_ENGINE_BINARY` or the compiling part?

**Comment by divyenduz** [comment]
Yes, env vars like `PRISMA_QUERY_ENGINE_BINARY` are tracked by this issue, how to compile a custom binary is already documented (maybe?) I remember doing it but can't find it anymore, so maybe a separate issue for that. 

Renaming (a subset of this issue), is tracked here: https://github.com/prisma/prisma2/issues/553

**Comment by janpio** [comment]
Can you try to apply https://github.com/prisma/specs/blob/master/meta/specs.md#implemented-vs-not-implemented to the spec then for that? Thanks.

**Comment by timsuchanek** [comment]
Released in the latest preview.

**Comment by divyenduz** [comment]
The variables `PRISMA_QUERY_ENGINE_BINARY` and `PRISMA_MIGRATION_ENGINE_BINARY` are ignored by the CLI. 

I validated this by providing an incorrect path, it should have thrown and error but it worked instead.

**Comment by janpio** [comment]
Please open a new bug report for this @divyenduz instead of reopening the feature issue.

**Comment by pantharshit00** [comment]
There is already an issue about this: https://github.com/prisma/prisma2/issues/1034

I am closing this one
