### ISSUE TITLE
Clarify when/whether limitations are expected to be resolved

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#345]
While currently `limitations.md` describes **what** kind of limitations exists, it doesn't give any indication **when** and **whether** they are expected to be resolved. (Especially in regards to the GA release.) We should clarify this.

**Comment by janpio** [comment]
https://github.com/prisma/prisma2/pull/360 has been merged which improves on this a bit. I want to take another shot at it though to make it a bit more user friendly.

**Comment by janpio** [comment]
https://github.com/prisma/prisma2/pull/431 is still WIP and wilil be influenced by our cleanup of the docs and specs.
