### ISSUE TITLE
[Priview6.1]Prisma2 Generate Error: SyntaxError: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma2#349]
`prisma2 generate` ====> `Error: SyntaxError: Unexpected token P in JSON at position 0`
[my schema](https://gist.github.com/zzyyzz1992/9eab9a4a2b886cdf8e13c79a2f225bfd)

**Comment by zzyyzz1992** [comment]
preview5 works fine

**Comment by pantharshit00** [comment]
I am unable to reproduce this.

![image](https://user-images.githubusercontent.com/22195362/62857465-55071080-bd15-11e9-8b88-927dcb6d8d1c.png)


Try wiping out your node_modules and trying this again.

**Comment by zzyyzz1992** [comment]
Me either.Sorry to bother you.

**Comment by pantharshit00** [comment]
No problems at all. Keep reporting any issues that you encounter 🙂
