### ISSUE TITLE
Support node <9.7

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#351]
Prisma generate on node 9.7 fails with failing to find [this function](https://nodejs.org/api/util.html#util_util_getsystemerrorname_err). 

Node docs mention that it was introduced in 9.7. 

We need to polyfill it.

**Comment by Akkuma** [comment]
Support for node 8 itself ends in Jan 2020. The polyfill would be useful for 3-6 months post GA at most?

**Comment by infoverload** [comment]
I am unable to recreate this bug on Ubuntu 16.04 and Ubuntu 18.04 using Node version 8.  

prisma2 generate seems to work fine against this model https://github.com/infoverload/prisma2-workshop/blob/master/prisma/schema.prisma

**Comment by divyenduz** [comment]
Closing this issue for now, it was only observed on @infoverload's machine and hence, it is not reproducible anymore.
