### ISSUE TITLE
Lift and Photon search for database in different folders

### ISSUE THREAD

**Issue by sameoldmadness** [prisma/prisma2#356]
Given a schema

```groovy
datasource db {
  provider = env("PRISMA_PROVIDER")
  url      = env("PRISMA_URL")
}

generator photon {
  provider = "photonjs"
}

model Role {
  id    String @default(cuid()) @id
  role  String @unique
}
```

and `package.json`

```json
{
  "private": true,
  "scripts": {

    "dev": "PRISMA_PROVIDER=sqlite PRISMA_URL=file:./dev.db prisma2 dev",
    "seed": "PRISMA_PROVIDER=sqlite PRISMA_URL=file:./dev.db ts-node prisma/seed.ts"
  },
  "dependencies": {
    "prisma2": "^2.0.0-preview-6.1",
    "ts-node": "^8.3.0",
    "typescript": "^3.5.3"
  }
}
```

and seeding script

```ts
import Photon from "@generated/photon";

new Photon().roles
  .create({
    data: {
      role: "DEFAULT"
    }
  })
  .then(console.log)
  .catch(console.error)
  .finally(() => process.exit());
```

when I run prisma2 dev and seed script

```
yarn dev
yarn seed
```

I see an error

```
Invalid `photon.()` invocation in /Users/roman.paradeev/workspace/photon-tslint-bug/prisma/seed.ts:4:4
Reason: Error in connector: Error querying the database: no such table: dev.Role
```

and I see two databases created.

- `<project root>/prisma/dev.db` created by `prisma2 dev`
- `<project root>/dev.db` created by `ts-node prisma/seed.ts`

When I change `PRISMA_URL` for seed script

```json
    "dev": "PRISMA_PROVIDER=sqlite PRISMA_URL=\"file:./dev.db\" prisma2 dev",
    "seed": "PRISMA_PROVIDER=sqlite PRISMA_URL=\"file:./prisma/dev.db\" ts-node prisma/seed.ts"
```

seeding script runs without errors.

**Comment by pantharshit00** [comment]
I can confirm this.

Reproduction: https://github.com/harshit-test-org/issue-prisma2-356

**Comment by divyenduz** [comment]
@pantharshit00 : Does the usage of sqlite from Photon create another DB? (which is normal SQLite connector behavior)

I am interested in knowing when does the first DB gets created (probably during `lift up`?) and when does the 2nd one get created (probably during `yarn seed`).

**Comment by pantharshit00** [comment]
I am also not sure how the database was created here via the seed script.

I think photon should not perform any kind of database creation or migration operations.

cc @timsuchanek

**Comment by divyenduz** [comment]
Thanks, so, you confirm that indeed the seed script creates the SQLite file right? I guess that is normal behavior of SQLite connectors (at least in Python), maybe node does the same. 

Which essentially boils this down to a path issue, where the expected path is counter-intuitive. 

> Lift is working with Prisma schema file as the CWD. Photon works with the process CWD. 

@pantharshit00 Do you agree with this?

**Comment by pantharshit00** [comment]
Yes, I agree with this

**Comment by schickling** [comment]
The provided `env("PRISMA_URL")` value should always be relative to the `schema.prisma` file.

**Comment by sameoldmadness** [comment]
Still broken for me.

**Comment by pantharshit00** [comment]
I can confirm this is still an issue.

**Comment by timsuchanek** [comment]
My apologies, a package wasn't updated properly. It's fixed now in `prisma2@2.0.0-alpha.185`.

**Comment by divyenduz** [comment]
I can reproduce a variation of this with `prisma2@2.0.0-alpha.204, binary version: f39ee6664e1d7cf5054e351f3f1dfcaf52402712`

With this in my schema file (located in `<root>/prisma/dev.db`)

```
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}
```

Lift performs migrations in `prisma/dev.db`
However, running Photon query creates a new DB in `<root>` folder.

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
