### ISSUE TITLE
photon and prisma 2

### ISSUE THREAD

**Issue by terion-name** [prisma/prisma2#358]
Articles say that prisma 2 is actually photon + lift. And photon can operate without prisma server.

Also they say that prisma server still exist and is rewritten in rust. And there is no data about using photon with new prisma server.

Can somebody, please, explain:
1. Does photon operate with new prisma server?
2. If yes, for what? What are pros and cons of using new prisma server over direct db connection?
3. If not, then what is the point and purpose of new prisma server?

**Comment by matthewmueller** [comment]
Hey @terion-name!

The prisma server still exists, but it exists locally now inside `node_modules`. The reason for this is that it allows us to focus our engineering efforts on creating a really well-tested and powerful data access system. The choice in Rust is that it's an embed-friendly, safe language with predictable performance.

Having this "sidecar server" will also allow you to seamlessly move to a remote server setup as you grow and your data access patterns need to be more managed & controlled.

**Comment by terion-name** [comment]
@matthewmueller ow, this makes sense.

But how (if it can now) prisma server can operate as a sidecar server? I need to use multiple (hundreds) of microservices with prisma, using own prisma server in each of them would be a quite an overhead as I suppose. Or it won't much?

**Comment by matthewmueller** [comment]
@terion-name You'll have many options:

1) Run a dedicated sidecar for each process
2) Run a shared sidecar across processes
3) Run a shared sidecar on a remote server

Right now just support 1) but we'll support all 3 options in the future.

As far as performance, we're currently focused on stability, later we'll optimize performance and I can provide better stats then.

**Comment by terion-name** [comment]
@matthewmueller thank you for explanation. I hope that memory footprint of rust server will be low, because in other case with several hundreds or them running in k18s I'll be f**** up 😅
