### ISSUE TITLE
Rename `project.prisma` to `schema.prisma`

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#36]
We have settled on the terminology that the schema file `schema.prisma` contains data sources, data model definition and generators.

This is described in further detail here: https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md

**Comment by timsuchanek** [comment]
Updated in all examples. The CLI now supports both `schema.prisma` and `project.prisma` to not break existing projects.

**Comment by schickling** [comment]
Related: https://github.com/prisma/prisma2/issues/126
