### ISSUE TITLE
SQLite relative path is broken

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#367]
A path specified in the `url` property when using the SQLite connector.

![image](https://user-images.githubusercontent.com/1567498/63101812-22118680-bf7a-11e9-8d98-1eb155f169f0.png)

![image](https://user-images.githubusercontent.com/1567498/63101820-2473e080-bf7a-11e9-8f72-d95f8419623d.png)

**Comment by schickling** [comment]
Closing in favor of #356

**Comment by timsuchanek** [comment]
Unrelated to #356

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
