### ISSUE TITLE
Updating data in M:N relation

### ISSUE THREAD

**Issue by cypcz** [prisma/prisma2#368]
I have two models:

```
model Post {
  id            String         @id @default(cuid())
  title         String
  categories    Category[]
}

model Category {
  id      String        @id @default(cuid())
  name    String
  posts   Post[]
}
```

Category is defined before the post is created. Creating post itself is fine, the connections in `_CategoryToPost` table are created. The problem arises when trying to update the post categories. What happens is that the old ones are not deleted and the new ones are added to the `_CategoryToPost` table. So if I update post and I don't make any change to the post categories, they duplicate in the `_CategoryToPost` table.

The code for updating is following:

```
                const updatedPost = await photon.posts.update({
                    where: { id: args.id },
                    data: {
                        title: args.title,
                        categories: {
                            connect: args.categories.map(categoryId => ({
                                id: categoryId
                            }))
                        }
                    }
                });
```

**Comment by pantharshit00** [comment]
I can confirm this bug.

It will be fixed via a big refactoring that we are currently doing.

**Comment by divyenduz** [comment]
Thanks Harshit for updating the existing comment with more context.

**Comment by pantharshit00** [comment]
I am no longer able to reproduce this with `prisma2@2.0.0-alpha.154, binary version: be94336b7af27074b7484cdd17353db0e749965e`

A unique index is now created in the link table:

![image](https://user-images.githubusercontent.com/22195362/63958374-db5a7b00-caa7-11e9-9892-0737449ebab9.png)

**Comment by cypcz** [comment]
Today I updated to version `prisma2@2.0.0-alpha.160` and the issue is still there. Once I try to update the post with the same category, the relation gets duplicated.

![image](https://user-images.githubusercontent.com/29678037/64345256-4c41eb80-cff0-11e9-95a9-19d52fd39ffc.png)

@pantharshit00 could you check it out again, please?

**Comment by pantharshit00** [comment]
I am still unable to reproduce.

You might need to remigrate your DB instance from scratch.

**Comment by cypcz** [comment]
Indeed, you are right. Works fine. Thank you!
