### ISSUE TITLE
findMany works but findOne doesn't work

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#379]
I am using the basic GraphQL boilerplate, the one without auth.

My `prisma/schema.prisma` file looks like:

```graphql
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photonjs"
}

generator nexus_prisma {
  provider = "nexus-prisma"
}

model Pokemon {
  id      String        @default(cuid()) @id @unique
  number  Int
  name    String
  attacks PokemonAttack
}

model PokemonAttack {
  id      Int      @id
  special Attack[]
}

model Attack {
  id     Int    @id
  name   String
  damage String
}
```

I changed my `src/index.js` to:

```js
const { GraphQLServer } = require('graphql-yoga')
const { join } = require('path')
const { makeSchema, objectType, idArg, stringArg } = require('@prisma/nexus')
const Photon = require('@generated/photon')
const { nexusPrismaPlugin } = require('@generated/nexus-prisma')

const photon = new Photon()

const nexusPrisma = nexusPrismaPlugin({
  photon: ctx => ctx.photon,
})

const Attack = objectType({
  name: "Attack",
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.damage()
  }
})

const PokemonAttack = objectType({
  name: "PokemonAttack",
  definition(t) {
    t.model.id()
    t.model.special()
  }
})

const Pokemon = objectType({
  name: "Pokemon",
  definition(t) {
    t.model.id()
    t.model.number()
    t.model.name()
    t.model.attacks()
  }
})

const Query = objectType({
  name: 'Query',
  definition(t) {
    t.list.field('pokemon', {
      type: 'Pokemon',
      args: {
        name: stringArg(),
      },
      resolve: (parent, { name }, ctx) => {
        return ctx.photon.pokemon.findMany({
          where: {
              name
          }
        })
      },
    })
  },
})

const Mutation = objectType({
  name: 'Mutation',
  definition(t) {
    t.crud.createOnePokemon({ alias: 'addPokemon' })
  },
})

const schema = makeSchema({
  types: [Query, Mutation, Pokemon, Attack, PokemonAttack,  nexusPrisma],
  outputs: {
    schema: join(__dirname, '/schema.graphql'),
  },
  typegenAutoConfig: {
    sources: [
      {
        source: '@generated/photon',
        alias: 'photon',
      },
    ],
  },
})

const server = new GraphQLServer({
  schema,
  context: request => {
    return {
      ...request,
      photon,
    }
  },
})

server.start(() => console.log(`🚀 Server ready at http://localhost:4000`))
module.exports = { Pokemon }
```

And my `prisma/seed.js` looks like:

```js
const Photon = require('@generated/photon')
const photon = new Photon.default()

async function main() {
  const pikachu = await photon.pokemon.create({
    data: {
      name: "Pikachu",
      id: '123132',
      number: 215,
      attacks: {
        create: {
          special: {
            create: {
              name: "Abra cadabra",
              damage: "100",
            }
          }
        }
      }
    }
  })
  console.log({ pikachu })
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await photon.disconnect()
  })
```

Now if I use `findOne` instead of `findMany`, it doesn't work:

```js
ctx.photon.pokemon.findOne({
     where: {
        name
     }
})
```

Is this intentional because FWIW I think it should work?

**Comment by deadcoder0904** [comment]
It throws this error:

```js
Error: 
Invalid `photon.pokemon.findOne()` invocation in /src/index.js:49:35

{
  where: {
    name: 'Pikachu'
    ~~~~
  }
}

Unknown arg `name` in where.name for type PokemonWhereUniqueInput. Did you mean `id`?
Available args:
type PokemonWhereUniqueInput {
  id?: ID
}
```

**Comment by pantharshit00** [comment]
This is expected. `name` is not a unique field so there is always a possibility of more than one matches when you are filtering by name. So it is available in `findMany` but not in `findOne`. If you want to make it available in `findOne`, add the `@unique` directive to it and regenerate the client.

**Comment by deadcoder0904** [comment]
Can't it just return the first one if it's more than one? Idk this feels weird to me.

Also, would love to have autocomplete on `ctx.photon.` if it's possible :)

**Comment by pantharshit00** [comment]
You can have autocompletion on `ctx.photon` if you use typescript.

Also, if it just returns the first result, it will defeat the purpose of the method which is to retrieve the list of data satisfying the given condition. For your use case, just access the first member of the returned array.

**Comment by deadcoder0904** [comment]
Ohh I wish I could have access to autocomplete using just JS as it's too much trouble without it seriously.

I think `findOne` sounds like `I'll find any one thing from the database which satisfies a condition` so yeah kinda disagree on that. I know how to access it now but spent a quite a lot of time thinking why it wasn't working. Maybe try raising this internally :)

**Comment by deadcoder0904** [comment]
Okay here's the weird thing, maybe this is enough proof to raise internally ⸺

This is what my `pokemon` query is ⸺

```graphql
# list all pokemons
query pokemons {
  pokemons {
    id
    number
    name
    attacks {
      special {
        id
        name
        damage
      }
    }
  }
}
```

And it returns the following ⸺

```json
{
  "data": {
    "pokemon": [
      {
        "id": "123132",
        "number": 215,
        "name": "Pikachu",
        "attacks": {
          "special": [
            {
              "id": 1,
              "name": "Abra cadabra",
              "damage": "100"
            }
          ]
        }
      }
    ]
  }
}
```

Well technically it should return only one `pokemon` so there is no need of an array but because I have `findMany` instead of `findOne` therefore it will return an array.

Here's the related code ⸺

```js
const Query = objectType({
  name: 'Query',
  definition(t) {
    t.crud.findManyPokemon({
      alias: 'pokemons'
    })
    t.list.field('pokemon', {
      type: 'Pokemon',
      args: {
        name: stringArg(),
      },
      resolve: (parent, { name }, ctx) => {
        return ctx.photon.pokemon.findMany({
          where: {
              name
          }
        })
      },
    })
  },
})
```

This means I have to write my frontend to use `data.pokemon[0]` every time instead of `data.pokemon` even though it's not an array.

This is just one of a kind use-case & I believe there might be many more like this. This really doesn't make any sense.

**Comment by kleydon** [comment]
@pantharshit00 wrote: >>`name` is not a unique field so there is always a possibility of more than one matches when you are filtering by name. So it is available in `findMany` but not in `findOne`. If you want to make it available in `findOne`, add the `@unique` directive to it and regenerate the client.

How about the case of `@id` fields, which are _implicitly_ unique (but not decorated with `@unique`)? Wondering if `findOne` should work in this case...

**Comment by meyer9** [comment]
You should definitely be able to query against a non-unique field in addition to a unique field.

For example, let's say I have the following schema:
```
model Object {
  id    Int @id
  owner User
}
```

I want to query by ID and owner. Maybe just require _at least 1 unique field_ and also allow querying by `owner`. Then, it returns at most 1 field, but we can add additional constraints to the query.

**Comment by janpio** [comment]
(Best open a new issue @meyer9 if you want this to be considered - closed issues are mostly ignored for that.)

**Comment by OmgImAlexis** [comment]
@meyer9 seems this is the closest we can get for now.

```ts
const show = await prisma.objects.findMany({
    where: {
        id: 'id-here',
        owner: 'owners-id-here'
    },
    take: 1
}).then(_ => _[0]);

**Comment by m1m6** [comment]
> @meyer9 seems this is the closest we can get for now.
> 
> ```ts
> const show = await prisma.objects.findMany({
>     where: {
>         id: 'id-here',
>         owner: 'owners-id-here'
>     },
>     take: 1
> }).then(_ => _[0]);
> ```

I had the same issue and solved it by specifying the `take` count

**Comment by OmgImAlexis** [comment]
> > @meyer9 seems this is the closest we can get for now.
> > ```ts
> > const show = await prisma.objects.findMany({
> >     where: {
> >         id: 'id-here',
> >         owner: 'owners-id-here'
> >     },
> >     take: 1
> > }).then(_ => _[0]);
> > ```
> 
> I had the same issue and solved it by specifying the `take` count

The take count is specified there.
