### ISSUE TITLE
Support MySQL 8 (currently MySQL 8 is not supported)

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#384]
(I am using a digitalocean mysql 8 instance)
Right now the CLI doesn’t support MySQL 8 as it using an older client.

![image](https://user-images.githubusercontent.com/22195362/63371774-5b932900-c3a2-11e9-9f21-468418818aff.png)

This might automatically be fixed with the introspection rewrite in Rust.

Also, lift is able to connect to the instance but it is unable to save migrations. It is able create the `_Migrations` table but when I run `prisma lift save --name 'init'` it is unable to save the migration in the file system and unable to create tables.

![image](https://user-images.githubusercontent.com/22195362/63371909-9e550100-c3a2-11e9-9772-cf2c802f711d.png)

**Comment by pantharshit00** [comment]
Made a separate issue for the second part of this issue: https://github.com/prisma/lift/issues/107

**Comment by janpio** [comment]
Default MySQL installation on Windows via e.g. Chocolatey is MySQL 8 - so having this (or at the very least a more informative error message!) would be nice.

**Comment by janpio** [comment]
Possible workaround posted here: https://github.com/prisma/prisma2/issues/38#issuecomment-532176320

**Comment by janpio** [comment]
Just a note, MySQL is aware:
![image](https://user-images.githubusercontent.com/183673/65134020-f31c8380-da03-11e9-9236-e8b5bd1e57c1.png)

**Comment by AhmedElywa** [comment]
In Mac i use this for solve problem 

```
$ mysql -uroot -pPassowrd
$ ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Strong Pass';
```
and work good but get another problems in use #516

**Comment by janpio** [comment]
Yes, that is the workaround I linked to in https://github.com/prisma/prisma2/issues/384#issuecomment-532589572 - we will continue our investigation of #516 and see if this is a side effect or another unconnected problem.

**Comment by tomhoule** [comment]
I did some investigation and was able to confirm that for me, it happens only in the `prisma2 init` flow with MySQL 8. The connection to the database at this stage is done on the typescript side and doesn't go through the migration engine nor the introspection engine, as far as I could tell.

I can also confirm the migration issue mentioned above is a separate bug, I'm working on fixing it.

**Comment by Dieff** [comment]
I believe that this issue was also a cause of a panic I recently received from `prisma2 dev`. Reverting to mysql5 fixed the issue.

```
dieff@hex ~/W/B/c/api> prisma2 dev

   Watching for changes in prisma/schema.prisma
   No changes yet

 Error

   Error: Error in migration engine: thread 'tokio-runtime-worker-0' panicked at 'get data_type', src/libcore/option.rs:1034:5
   stack backtrace:
      0: backtrace::backtrace::libunwind::trace
                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
      1: backtrace::backtrace::trace_unsynchronized
                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
      2: std::sys_common::backtrace::_print
                at src/libstd/sys_common/backtrace.rs:47
      3: std::sys_common::backtrace::print
                at src/libstd/sys_common/backtrace.rs:36
      4: std::panicking::default_hook::{{closure}}
                at src/libstd/panicking.rs:200
      5: std::panicking::default_hook
                at src/libstd/panicking.rs:214
      6: migration_engine::main::{{closure}}
      7: std::panicking::rust_panic_with_hook
                at src/libstd/panicking.rs:481
      8: std::panicking::continue_panic_fmt
                at src/libstd/panicking.rs:384
      9: rust_begin_unwind
                at src/libstd/panicking.rs:311
     10: core::panicking::panic_fmt
                at src/libcore/panicking.rs:85
     11: core::option::expect_failed
                at src/libcore/option.rs:1034
     12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
     13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
     14: sql_schema_describer::mysql::SqlSchemaDescriber::get_table
     15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
     16: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
     17: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe
     18: <sql_migration_connector::sql_database_migration_inferrer::SqlDatabaseMigrationInferrer as migration_connector::database_migration_inferrer::DatabaseMigrationInferrer<s
ql_migration_connector::sql_migration::SqlMigration>>::infer
     19: <migration_engine::commands::infer_migration_steps::InferMigrationStepsCommand as migration_engine::commands::command::MigrationCommand>::execute
     20: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::infer_migration_steps
     21: migration_engine::api::rpc::RpcApi::create_sync_handler
     22: tokio_executor::enter::exit
     23: tokio_threadpool::blocking::blocking
     24: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     25: futures::future::chain::Chain<A,B,C>::poll
     26: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     27: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     28: futures::future::chain::Chain<A,B,C>::poll
     29: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     30: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     31: <futures::future::either::Either<A,B> as futures::future::Future>::poll

```

I had migrated my data development to a new instance of mysql running 8.x, instead of 5.7.x.

Here are details for my system:
```
$ uname -ra
Linux hex 5.3.0-arch1-1-ARCH #1 SMP PREEMPT Mon Sep 16 03:29:01 UTC 2019 x86_64 GNU/Linux
$ prisma2 --version
prisma2@2.0.0-preview-12, binary version: 2292f8d0c3bd11fe9cca7c6df4a10061bf58fd18
```

The output from the error above is probably a case of bad error handling. Rather than panicking and dumping the Rust stacktrace, there should probably be a message to the user. Let me know if I should open a separate issue.

**Comment by janpio** [comment]
Please do that @Dieff - then we can let a developer double check that this was already resolved via recent work on the migration engine (which gave you this nice error) 🚀

**Comment by divyenduz** [comment]
Internal note: Dropping from this sprint, we will pick this up again in 2 weeks when @do4gr is back.

**Comment by janpio** [comment]
If you mean the Introspection part, that the TS Introspection can not handle MySQL 8, then I agree. This might take some time.

**Comment by tomhoule** [comment]
Yes exactly, sorry for the ambiguity.

**Comment by janpio** [comment]
(I was actually just using my comment to repeat this and make it explicit for everyone ;) )

**Comment by darrylyoung** [comment]
Do you think we’ll get MySQL 8 support with Prisma 1? I’m almost done building a Prisma (1) app and wanted to deploy to Digital Ocean but just found out that they only support MySQL 8 and Prisma 1 doesn’t.

I’d use Prisma 2 if support was there but I know the official release is still a bit away so I’m kind of stuck. Any advice?

**Comment by divyenduz** [comment]
> Do you think we’ll get MySQL 8 support with Prisma 1?

We will not have MySQL 8 support with Prisma 1. I suggest using MySQL 5.7 with some other provider for now and migrate to DO with MySQL 8 once Prisma 2 is there.

**Comment by darrylyoung** [comment]
Hi, @divyenduz. Thank you for your response. That's a little disappointing but I really appreciate the transparency. 👍

**Comment by janpio** [comment]
MySQL 8 is fully supported with Prisma2 for quite some time now (as the mentioned CLI command was fully rewritten) 🚀
