### ISSUE TITLE
Temporary error telemetry docs

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#396]
As discussed during our planning meeting, we should create a telemetry document that outlines the current behavior during the preview period and links to https://github.com/prisma/specs/issues/76 for details after the GA release.

Content:
- Description of the interactive confirmation flow
- Which data is being shared
- Overview of how telemetry will work after GA

**Comment by nikolasburk** [comment]
The docs can be found here: https://github.com/prisma/prisma2/blob/telemetry/docs/telemetry.md

I will merge the `telemetry` branch on Thursday with the release.
