### ISSUE TITLE
Create a Windows Binary

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#4]
High-level: create a binary for windows and add it to the [Table of binaries](https://github.com/prisma/specs/tree/master/binaries#table-of-binaries)

There's very likely more low-level work to do here. Might be worth trying: `cargo build --target x86_64-pc-windows-gnu` to see if we get lucky.

**Comment by mpcen** [comment]
Any ETA on Prisma2 + Windows support?

**Comment by janpio** [comment]
The currently is no ETA on this. We are aware of the 👍 and ❤️ here, and I am typing this comment from nice Surface Book 2, so be assured I think about it a lot. But not sure when we have the time and resources to actually tackle it. Will keep you updated.

**Comment by timsuchanek** [comment]
We have to investigate, how involved this is, as it means to add a new build environment to our buildkite setup.

**Comment by janpio** [comment]
Internal note: @dpetrick could cross compile a Windows binary that worked on my Windows machine. This leaves "only" the build setup and installation/download.

**Comment by dpetrick** [comment]
This is done on my end. Tim needs to confirm that this also works now for the engine fetching + photon.

**Comment by janpio** [comment]
Implementation on the client side will be tracked in https://github.com/prisma/prisma2/issues/460
