### ISSUE TITLE
Parse connection string URLs when you paste them in the host

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#40]
Based on: https://youtu.be/81PtwbpQEck?t=179

Also: https://cldup.com/XtBQsfFCge.mp4

When pasting the full connection string into the first field, it should be recognized and parsed, the resulting values put into the correct fields for convenience.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
