### ISSUE TITLE
Init flow creates projects inside a "prisma" folder, if it exists

### ISSUE THREAD

**Issue by kuldar** [prisma/prisma2#41]
If a working directory includes a "prisma" folder, then the `init` flow seems to create a project inside of that, instead of the current folder.

![test](https://user-images.githubusercontent.com/1710629/60103456-ea4b4700-975f-11e9-8d71-0fb79dad2146.gif)

**Comment by schickling** [comment]
Related to #16

**Comment by schickling** [comment]
Continued here: https://github.com/prisma/specs/issues/21

**Comment by timsuchanek** [comment]
Belongs to https://github.com/prisma/prisma2/issues/278
