### ISSUE TITLE
Virtual properties

### ISSUE THREAD

**Issue by alizahid** [prisma/prisma2#411]
How do I define virtual properties for my Prisma models? I remember having a similar issue with Prisma v1, too, but cannot remember the exact details.

My model

```
model Post {
  id String @id @default(cuid())
  body String
  comments Comment[]
}

model Comment {
  id String @id @default(cuid())
  body String
}

model User {
  id String @id @default(cuid())
  posts Post[]
  comments Comment[]
}
```

Now I want to add a virtual property called `commented<boolean>`, for instance, to `Post`, which returns `true` if the user has commented on this post.

If I try to just do `post.commented = true` in my resolver, TypeScript gives a warning. What's the best approach for this?

**Comment by pantharshit00** [comment]
I think this is intended as the post object that is returned is type-safe. You will need to manually type it to a property containing you additional properties if you want to do sometime like this.

Here is an example:

```ts
import Photon, { Post } from '@generated/photon';

type PostWithComments = Post & { commented?: boolean }
const photon = new Photon();

async function main() {
  const data: PostWithComments = await photon.posts.findOne({ where: { id: "xxx" }});
  // Compute this field.
  data.commented = true;
}

main()

```

**Comment by alizahid** [comment]
Thank you. I’ve taken a different approach, but just wanted to check if this was supported or not.

Any plans to allow this type of extension in the future?

**Comment by pantharshit00** [comment]
I don't really know, maybe you can open a feature request for computed fields. I think one way to achieve them is to support SQL Views.
