### ISSUE TITLE
MySQL new schema creation does not work

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#42]
CLI gets stuck on `prisma2 lift up` when the MySQL URL contains a schema that does not exist.

**Comment by mavilein** [comment]
@divyenduz : This behaviour is implemented and should work. Can you provide a repro with a datasource configuration?

**Comment by divyenduz** [comment]
Sure, this is a repro file: https://github.com/divyenduz/p2-mysql/tree/master

The DB mentioned in the datasource (in Prisma schema file) does not exist and on running `lift up` the error mentioned in the `failed-migrationProgress-20190702151624.md` file is observed.

**Comment by timmushen** [comment]
In testing this, I receive the following error: 

I have confirmed the connection. DB exits, table schema does not. 

`datasource db {
  provider = "mysql"
  url      = "mysql://root@localhost:3306/prisma"
  default  = true
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User
}`

# Runs correctly
prisma2 lift save --name init

# Creates error
prisma2 lift up 

`Error: Error in lift engine for rpc applyMigration:
  thread 'main' panicked at 'Connecting to MySQL failed: ConnectionError(Error(Some("IoError { failed to fill whole buffer }"))`

**Comment by alexthegoodman** [comment]
I also experience an error when creating a new MySQL database schema.

**Comment by hagnerd** [comment]
Just had the same thing happen with Postgres.

**Comment by mavilein** [comment]
The next preview release will contain a fix for this.
