### ISSUE TITLE
Remove limitation on 1 request at at time

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#420]
To quote `limitations.md`:

> Processes 1 request at a time, no parallelism during the early preview period. This will be fixed before GA.

**Comment by nlarusstone** [comment]
Don't want to be too much of a bother, but wanted to repost this from https://github.com/prisma/photonjs/issues/236.

As we're hoping to use prisma2 in some of our upcoming workflows, it would be great if we could get a status update on the parallelism and maybe a rough roadmap/timeline of when this is expected to get solved.

Thanks so much!

**Comment by JackCA** [comment]
@nikolasburk  does closing this mean it’s implemented?🤞

**Comment by nikolasburk** [comment]
Hey @JackCA, yes was just about to add a comment that this will be available in the `preview016` release that's _just about_ to happen... give us a few more minutes!
