### ISSUE TITLE
Examples and Docs should not use both @id and @unique

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma2#426]
In a lot of bug reports i see `@id` and `@unique` being used in conjunction e.g.:
```
model User {
  id    String  @default(cuid()) @id @unique
 ...
}
```

This is not necessary though. `@id` already implies that something is unique. Hence `@unique` is not needed. I think we should go through our docs and examples and remove it to avoid that this pattern proliferates further.

**Comment by nikolasburk** [comment]
I've found this only in the examples and removed the additional `@unique`: https://github.com/prisma/prisma-examples/commit/5f8b6db5770dcac5e33a68975bc236c26363353e
