### ISSUE TITLE
Update documentation to not contain not yet implemented functionality

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#433]
Right now many specs don't differentiate between the parts that are already implemented, and parts that are future facing and describe our goal instead of current reality.

We want to avoid any confusion here, and thus decided that all documentation regarding not implemented features should be removed. 

If users probably expect some functionality to be there, it should be added to `limitations.md` which will also include a link to a tracking issue of the implementation of the feature. 

In some cases, it might also be worth mentioning a limitation and missing feature in the docs themselves, with a link to the limitations file and possibly tracking issue as well.

**Comment by janpio** [comment]
(This issue was directly added to Preview 9 as it supersedes https://github.com/prisma/prisma2/issues/251 which we committed to tackle in this release anyway.)

**Comment by janpio** [comment]
Note: The work on `limitations.md` is still WIP, also we need to check the rest of the docs for correctness regarding implementation state.

**Comment by nikolasburk** [comment]
I believe the docs now match the state of the implementation, I suggest open specific issues when we learn that this isn't instead of keeping this one open.
