### ISSUE TITLE
Graphql-yoga subscriptions withFilter

### ISSUE THREAD

**Issue by ryanking1809** [prisma/prisma2#454]
I have a basic pubsub working here using the boilerplate and graphql-yoga: 
https://github.com/ryanking1809/prisma2_subscriptions
https://codesandbox.io/s/github/ryanking1809/prisma2_subscriptions/tree/sql-lite

With a publish mutation:
```js
const Mutation = objectType({
  name: 'Mutation',
  definition(t) {
   //...
    t.field('publish', {
      type: 'Post',
      nullable: true,
      args: {
        id: idArg(),
      },
      resolve: async (parent, { id }, ctx) => {
        const post = await ctx.photon.posts.update({
          where: { id },
          data: { published: true },
          include: { author: true }
        });
        ctx.pubsub.publish("PUBLISHED_POST", {
          publishedPost: post
        });
        return post
      },
    })
  },
})
```

And a subscription - I'm just returning `true` to make sure `withFilter` (from `graphql-yoga`) is working.
```js
const Subscription = objectType({
	name: "Subscription",
	definition(t) {
		t.field("publishedPostWithEmail", {
            type: "Post",
            args: {
                authorEmail: stringArg({ required: false })
            },
            subscribe: withFilter(
                (parent, { authorEmail }, ctx) => ctx.pubsub.asyncIterator("PUBLISHED_POST"),
                (payload, { authorEmail }) => true
            )
        });
	}
});
```
Returning the following on `publish` (you can copy and paste these into codesandbox - which is neat!)
```gql
mutation {
  publish(
    id: "cjzwz39og0000nss9b3gbzb7v"
  ) {
    id,
    title,
    author {
      email
    }
  }
}
```
```gql
subscription {
  publishedPostWithEmail(authorEmail:"prisma@subscriptions.com") {
    title,
    content,
    published
  }
}
```

```js
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Subscription.publishedPostWithEmail.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "publishedPostWithEmail"
      ]
    }
  ],
  "data": null
}
```

For some reason, it's returning `data: null`. When I log `payload.publishedPosts` in the filter function it seems as though everything is there.

```js
{ id: 'cjzwqcf2x0001q6s97m4yzqpi',
  createdAt: '2019-08-29T13:34:26.648Z',
  updatedAt: '2019-08-29T13:54:19.479Z',
  published: true,
  title: 'Check Author',
  content: 'Do you save the author?',
  author:
   { id: 'sdfsdfsdfsdf',
     email: 'prisma@subscriptions.com',
     name: 'Prisma Sub' } }
```

Is there something I'm missing?

---

ps. I have pubsub working without filters
```gql
subscription {
  publishedPost {
    title,
    content,
    published,
    author {
      email
    }
  }
}
```
So it makes me think it has more to do with the `withFilter` function than Prisma itself. 
Is that correct?

**Comment by ryanking1809** [comment]
Don't worry, I just had to await some async stuff...

**Comment by ryanking1809** [comment]
Actually, I'm still having issues. Updated the original question.

**Comment by ryanking1809** [comment]
Finally got it figured out! 🙌

The subscription function needs to be named after the key in the pubsub.
So if you have a publish function like the following:
```js
ctx.pubsub.publish("PUBLISHED_POST", {
          publishedPost: post
        });
```
then you have to name your subscription `publishedPost`
```js
		t.field("publishedPost", {
			type: "Post",
			args: {
				authorEmail: stringArg({ required: false })
			},
			subscribe: withFilter(
				(parent, { authorEmail }, ctx) =>
					ctx.pubsub.asyncIterator("PUBLISHED_POST"),
				(payload, { authorEmail }) => payload.publishedPost.author.email === authorEmail
			)
		});
```

Interestingly, if you have 2 keys
```js
ctx.pubsub.publish("PUBLISHED_POST", {
          publishedPost2: post,
          publishedPost3: post
        });
```
Then if you name your subscription `publishedPost2` then `publishedPost3` is ommited from the results.

I'm not sure how subscribing to many messages works yet 🤔

I should be able to do everything I need to do with this, but at the same time, it would be nice to have more flexibility when you come round to working on subscriptions!

**Comment by ryanking1809** [comment]
Oddly if you subscribe to 2 messages you get back all the data
```js
ctx.pubsub.publish("PUBLISHED_POST", {
          publishedPost: post,
          publishedPost2: post
        });
        ctx.pubsub.publish("PUBLISHED_POST_X", {
          publishedPostX: post,
          publishedPostY: post
        });
```
```
ctx.pubsub.asyncIterator([
						"PUBLISHED_POST",
						"PUBLISHED_POST_X"
					]),
```
returns `publishedPost`, `publishedPost2`, `publishedPostX`, `publishedPostY`

So you can get around the above issue by subscribing to an array with a single item and the name of the subscription becomes irrelevant.
```
		t.field("publishedPostXYZ", {
			type: "Post",
			args: {
				authorEmail: stringArg({ required: false })
			},
			subscribe: withFilter(
				(parent, { authorEmail }, ctx) =>
					ctx.pubsub.asyncIterator([
						"PUBLISHED_POST"
					]),
				(payload, { authorEmail }) => {
					return payload.publishedPost.author.email === authorEmail;
				}
			)
		});
```
---

So seems like this might be a bug? But is it with Prisma, or Apollo?

**Comment by kanso-git** [comment]
Hello
I am using subscription like below:

```
import { subscriptionField } from 'nexus'

export const SubscriptionPost = subscriptionField('posts', {
  type: 'PostSubscriptionPayload',
  subscribe(root, args, ctx) {
    return ctx.prisma.$subscribe.post({
      mutation_in: ['CREATED', 'UPDATED'],
      node: {
        content_contains: 'test'
      }
    })
  },
  resolve(payload) {
    return payload
  }
})
```
and i am able to get everything i need .
To be honest I didn't get why you are using the subscription in that manner 
please see code sample at:

[https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-subscriptions](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-subscriptions)

could you please or anyone  explain the difference between these tow manners of implemeting subscriptions ,

many thanks in advance

**Comment by ryanking1809** [comment]
@kanso-git `ctx.prisma.$subscribe` doesn't appear to be from Prisma2. This works with Photon?

I'm using the above pubsub model above as a way to circumvent subscriptions not being implemented in Prisma2 (https://github.com/prisma/prisma2/issues/298). It looks like it might be more flexible as well, allowing you to subscribe to events outside of a Prisma.

**Comment by divyenduz** [comment]
Closing this in favor of https://github.com/prisma/prisma2/issues/298

**Comment by batFormat** [comment]
Some issue, still not work.

Subscription return `"data": null`

```
 pubsub.publish("transaction", { transaction })
```

```
import { subscriptionField } from 'nexus'

export const Subscription = subscriptionField('transaction', {
  type: 'Transaction',
  subscribe: (root, args, ctx) => ctx.pubsub.asyncIterator(['transaction']),
  resolve: payload => {
    return payload
  },
})
```
