### ISSUE TITLE
Unable to use two fields with @default(now()) directive

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#457]
Right now query engine will throw a parsing error when we try to execute a create query against a model with two DateTime fields marked with `@default(now())` directive.

![image](https://user-images.githubusercontent.com/22195362/63933318-9f5af200-ca76-11e9-9e5d-533ecbb557e5.png)

Reproduction: https://github.com/harshit-test-org/prisma-p2-457 

Steps:
1. Clone this repo and install node dependencies
2. Run `prisma2 dev`
3. Run `ts-node src/script.ts`
4. See the error

**Comment by divyenduz** [comment]
Note: This relates to the query engine expression work.

**Comment by matthewmueller** [comment]
internal note: dropping as part of a larger refactor that we'll get to later.

**Comment by divyenduz** [comment]
Closing as duplicate of https://github.com/prisma/photonjs/issues/183
