### ISSUE TITLE
CLI + Photon: Download and use Windows binary

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#460]
With https://github.com/prisma/prisma2/issues/4 closed, the Windows binaries are available and can be used, Photon and Lift "just" have to know about, download and use them properly.

**Comment by janpio** [comment]
Notes: Jan will provide a clear error description.

**Comment by divyenduz** [comment]
Also, the CLI should download the correct binaries on windows.

**Comment by janpio** [comment]
Starter Kit > JavaScript > Script (Node.js) > SQLite

```
C:\Users\Jan\Documents>prisma2 init prismaWindows

Preparing your starter kit: Script (Node.js)

✔  Downloading the starter kit from GitHub ...
⠙  Extracting content to prismaWindows ...
3  Installing dependencies with: `npm install` ...
4  Preparing your database ...
 ERROR  Error during command execution

Schema parsing 'C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-linux-glibc-libssl1.1.0' is not recognized
 as an internal or external command,
operable program or batch file.
```

![image](https://user-images.githubusercontent.com/183673/64109452-d9cad480-cd7f-11e9-9dbc-6e8f38f7eda4.png)

So it tries to download the linux binary, which is obviously not an executbale on Windows. A `prisma.exe` could possible be executed here.

**Comment by janpio** [comment]
Follow up error of Lift is described here: https://github.com/prisma/lift/issues/22 But I can retest that one when `init` can actually download the correct binary.

**Comment by janpio** [comment]
Additional information: 
Already during `npm install` things go wrong depending on the command line you use to install: https://github.com/prisma/prisma2/issues/503
It makes sense this causes the follow up error mentioned in https://github.com/prisma/prisma2/issues/460#issuecomment-527101677

**Comment by janpio** [comment]
To summarize:
1. Because of `test` which is not available in `cmd.exe` the download of the engine fails
2. Even when it works (Cmder) it downloads the wrong engine
3. Later it either can't find the engine (1) or can't run it (2)
4. Lift will also fail to execute the migration engine

**Comment by janpio** [comment]
We took care of 2-4, 1 still has to be done (probably via some random npm package that replaces `test` usage (ask tim what the goal of it was))

Retest https://github.com/prisma/prisma2/issues/505 after stuff was merged.

**Comment by janpio** [comment]
https://github.com/prisma/prisma2/pull/518 is one way to solve 1) - although there might be other/better alternatives.

**Comment by janpio** [comment]
PRs have been merged, only some testing left before we can close this 🚀

**Comment by janpio** [comment]
Yay, everything seems to work.
