### ISSUE TITLE
Version control in data layer

### ISSUE THREAD

**Issue by ragnorc** [prisma/prisma2#462]
It would be great to have version control not only for schema alterations but also for changes in the data. It would make it possible to collaborate on data, revert and merge changes etc. 

Are there any plans to implement this? If not, is that something the community would work on?

**Comment by schickling** [comment]
While this is a very interesting idea (which we discussed internally quite a bit) at the current point there are no concrete plans to solve this problem "at the Prisma level". This might change in the future but until then, it would be great to see what the community is able to come up with to provide solutions to this problem! 🚀

**Comment by vladimirdjurdjevic** [comment]
This makes sense for parts of database which holds static, a configuration like data. It could be treated as a migration actually. Imagine you have some kind of app behavior config in the database, and you want to tweak it between versions. It's really like a database migration which ideally could be applied with lift during CD pipeline. I described how I imagine seeding functionality here #9 . Here is one quote: "seeding from code for integration testing, and from version controlled files for development and production". Now I am thinking, this seeding from files could work fine for development with clear and seed strategy, but for production, it would be much better if we had migration with the lift to incrementally seed static production data as part of deployment.

**Comment by divyenduz** [comment]
Thanks for raising this issue, our current take is that this will not happen in the Prisma layer but there are related technologies like https://github.com/liquidata-inc/dolt

Prisma can have a connector for these in future to support this functionality. 

I am closing this issue, please ping me on the issue if you would like this issue to remain for further discussion.
