### ISSUE TITLE
`prisma2 init` navigation infinite loop

### ISSUE THREAD

**Issue by ChristianJacobsen** [prisma/prisma2#466]
Hi!

If you start `prisma2 init` and select the following:

Starter Kit => JavaScript => Back => Back => Blank project => SQLite => Confirm => JavaScript, you'll be back in the `Select starter kit` dialog. If you select `Script (Node.js)` you will be sent back to `Supported databases` and the loop continue from the `SQLite` step above.

This is using `preview-9`.

**Comment by janpio** [comment]
I can confirm the observed behavior.

**Comment by deadcoder0904** [comment]
I'm on a Mac & I don't even have to do `Back`. It happens that I select `GraphQL + Auth` & it just keeps on giving `downloading starter from github....` & infinite loop.

I thought it was my internet connection but I can open GitHub issues lol, that too fast :)

**Comment by janpio** [comment]
Still happens in `preview-9.1` for me.

**Comment by divyenduz** [comment]
Dropping this for this sprint, in terms of prioritization.

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Still happening in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
