### ISSUE TITLE
`Blank project` selection in `prisma2 init` flow ends on hanging `No example selected` message

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#467]
I want to set up a blank project with a Postgres DB hosted on Heroku, here's my flow:

![](https://imgur.com/zLOFcCO.png)

![](https://imgur.com/Ktx0oB8.png)

![](https://imgur.com/IOd3cDD.png)

After clicking connect, the flow ends by hanging on this screen:

![](https://imgur.com/rVV0yWb.png)

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
