### ISSUE TITLE
Table not being created in MySQL 5.7.21

### ISSUE THREAD

**Issue by tristancaron** [prisma/prisma2#470]
Using preview-9

Working with SQLite is working, but with MySQL it leads to errors.

That works fine
```
prisma2 lift save --name 'init'
```

Then lifting is alright, it's even saying it created the tables.
```
prisma2 lift up

🏋️‍ lift up


Database Changes:

Migration            Database actions            Status

20190830084921-init  30 CreateTable statements.  
```

But when I look a the database, there is nothing but `_Migration`.

**Comment by janpio** [comment]
Did this use to work before?

**Comment by tristancaron** [comment]
Yes, but I can’t remember which version. We stopped using MySQL and swapped to SQLite because IDs were not being incremented.

**Comment by pantharshit00** [comment]
Duplicate of https://github.com/prisma/prisma2/issues/384

Please confirm that you are using MySQL 8

**Comment by tristancaron** [comment]
It’s in the title… MySQL 5.7.21

**Comment by pantharshit00** [comment]
Sorry, it just went out of my mind. Comment of that issue though, it already has a reproduction.

**Comment by tristancaron** [comment]
Thank you very much! We really appreciate your work and support. I’ll stay tuned.
