### ISSUE TITLE
Defaults are not being used in the new init flow

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#471]
I just started going through `prisma2 init` and provided my DB credentials. Right after pasting in the host, an error message occurred: 

![image](https://user-images.githubusercontent.com/4058327/64026936-01335e80-cb40-11e9-837b-2d4d0b83d8af.png)

**Comment by pantharshit00** [comment]
Defaults are in general are not being used:
![image](https://user-images.githubusercontent.com/22195362/64027553-8fb6d880-cb5e-11e9-847d-dec4650cdc1d.png)

**Comment by divyenduz** [comment]
Note: Init flow changes, re-sync next week

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Still present in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
