### ISSUE TITLE
README should be removed from `Blank project` -> ... -> `Demo script` option

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#472]
When selecting **Blank project** at the beginning of the `prisma2 init` flow and selecting the **Demo script** at the end, there shouldn't be a README file (also see [spec](https://prisma-specs.netlify.com/cli/init/demo-scripts/)).

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
`README.md` is still present in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
