### ISSUE TITLE
Can't select `Just the Prisma schema` option in `Blank project` flow during `prisma2 init`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#473]
After going through the flow:

1. Blank project
1. PostgreSQL
1. Provide DB for Heroku-hosted Postgres DB (create new schema)
1. TypeScript
1. Just the Prisma schema

## Actual behavior

The CLI hangs on this screen:

![image](https://user-images.githubusercontent.com/4058327/64030295-8c175780-cb46-11e9-9ed2-257213b6a56c.png)

## Expected behavior

Expected generated file: **schema.prisma** with these contents:

```
datasource postgresql {
  provider = "postgresql"
  url           = "postgresql://sqp
labgtqjrwun:XXX@ec2-176-34-184-174.eu-west-1.compute.amazonaws.com/d8q8dvp22kfpo3?
schema=myschemax&sslmode=prefer"
}

generator photonjs {
  provider = "photonjs"
}
``` 

Printed output:

```
Navigate into the project directory:                 
$ cd hello-world                                     
                                                     
Start Prisma's development mode to enable access to  
Prisma Studio and watch schema.prisma for changes:   
$ prisma dev                                         
                                                     
Your data model is empty. Learn about data modeling: 
https://pris.ly/d/data-modeling/                  
                                         
Learn more about Prisma 2:
https://github.com/prisma/prisma2/

If you encounter any issues, please report them here:
https://github.com/prisma/prisma-examples/issues/new
```

The first line should only be printed if a project name was provided to `prisma2 init`, e.g. `prisma2 init hello-world`

**Comment by matthewmueller** [comment]
"Please wait a few years" 😂

**Comment by AWey95** [comment]
I'm getting the exact same issue as well.

**Comment by nikolasburk** [comment]
@AWey95 to work around this, please use the `Demo script` option for now. You can then delete all additional files except for `schema.prisma` and will basically end up in the same state as if you chose `Just the Prisma schema`.

**Comment by divyenduz** [comment]
I can confirm this with Postgres too

Related issue: https://github.com/prisma/prisma2/issues/496

These two issues make both flows in Postgres have hiccups 🙏
