### ISSUE TITLE
Use `yarn` if available

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#474]
I started using `yarn` since the `npm` fiasco.

It's a pain to remove dependencies installed after `npm install` & then manually doing `yarn`.

I think it would be much nice if `yarn` is used if it's installed or just give me an option `prisma2 init example --yarn` so that I can directly install using `yarn`.

**Comment by sidharthachatterjee** [comment]
Hello from Gatsby! Here is how we handle this:

- We ask the user to pick a preferred package manager on first run and persist that in ~/.config
- We include lock files for both in official starters and delete the appropriate one on gatsby new ...

This is at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/init-starter.js#L30

**Comment by schickling** [comment]
@nikolasburk let's incorporate this into our init flow!

**Comment by janpio** [comment]
Next step: Let's define/spec how exactly this should work, so this can be handed over to engineering 🙏

**Comment by divyenduz** [comment]
Dropped: studio init flow impacts this

**Comment by divyenduz** [comment]
This is done in the latest preview. `npm install -g prisma2`

**Comment by renemonroy** [comment]
This doesn't seem to work when using Yarn workspaces. It always throw an error while installing dependencies.

```
✔  Downloading the starter kit from GitHub ...
✔  Extracting content to bookmarks-web-client ...
⠦  Installing dependencies with: `npm install` ...
4  Preparing your database ...
5  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

warning package.json: No license field
warning Missing version in workspace at "/Users/project/path", ignoring.

Error:
  Error: In order to use the "photonjs" generator, you need to install @prisma/photon to your project:
    npm add @prisma/photon
...
error Command failed with exit code 1.
```

**Comment by divyenduz** [comment]
@renemonroy Can you please create a new GH issue with a minimal reproduction? 🙏

**Comment by renemonroy** [comment]
#1199
