### ISSUE TITLE
Unspecified relations assumed to be one to one

### ISSUE THREAD

**Issue by ryanking1809** [prisma/prisma2#477]
If I have a `schema.prisma` file like the following:

```
model Task {
  id        String   @default(cuid()) @id @unique
  account Account
}

model Account {
  id        String   @default(cuid()) @id @unique
}
```

Prisma creates a `task` column in the Account table with a foreign key. Wouldn't it be safer to presume this to a be a one to many relationship, as I haven't strictly defined a task column?

**Comment by matthewmueller** [comment]
@ryanking1809 thanks for bringing this up! I have a hunch you've done a lot of schema modeling with SQL 😊

If you think about it relationally, you'd be totally right. The Prisma schema is more like a graph and we've been inspired by how intuitive GraphQL models relationships. In Prisma 2, **one-to-many** looks like this:

```groovy
model Task {
  id        String   @default(cuid()) @id @unique
  account Account[]
}

model Account {
  id        String   @default(cuid()) @id @unique
}
```

**Comment by ryanking1809** [comment]
@matthewmueller Thanks Matt, I might try to explain in more detail, just to clarify we're talking about the same thing.

If I have the following schema, one side of the relationship isn't defined
```gql
model Task {
  id        String   @default(cuid()) @id @unique
  account Account
}
model Account {
  id        String   @default(cuid()) @id @unique
}
```

Prisma fills in the gaps by adding a relation to the accounts table
```gql
model Task {
  id        String   @default(cuid()) @id @unique
  account Account
}
model Account {
  id        String   @default(cuid()) @id @unique
  task Task ###Assumed by Prisma (but not actually defined in the schema)
}
```

When I migrate Prisma will add the `task` column to the database table of `Account`, even though it hasn't been defined in the schema (I still need to test if this creates migration issues). I wasn't expecting Prisma to add columns to tables unless I specified it in the schema. Is this intentional behaviour?

If Prisma did need to assume the other side of the relationship that is not defined in the schema. Wouldn't it be safer to assume that the relationship is one-to-many in order to avoid adding an unspecified column to the database? Like so?
```gql
model Task {
  id        String   @default(cuid()) @id @unique
  account Account
}
model Account {
  id        String   @default(cuid()) @id @unique
  tasks Task[] ###Assumed by Prisma (but not actually defined in the schema)
}
```

**Comment by matthewmueller** [comment]
@ryanking1809 thanks for clarifying! You're right that I misunderstood your original post. This is because we place the one-to-one column on the model that comes first alphabetically (Account vs. Task). 

This is an interesting case and I've brought it up to the backend team, I'll let you know once I hear from them if this is intentional or something we'll change.

**Comment by ryanking1809** [comment]
Thanks @matthewmueller 

I've also had a chance to test the migrations in this scenario, and if I decide to define the relation after migrating the initial setup then Prisma appears to drop the original post-column which could lead to data loss if not careful.

So if you migrate this:
```gql
model Task {
  id        String   @default(cuid()) @id @unique
  account Account
}
model Account {
  id        String   @default(cuid()) @id @unique
}
```

Then migrate this:
```gql
model Task {
  id        String   @default(cuid()) @id @unique
  account Account
}
model Account {
  id        String   @default(cuid()) @id @unique
  tasks Task[]
}
```

Then the migration will drop the column, losing data.
```json
{
  "version": "0.2.7",
  "steps": [
    {
      "stepType": "CreateField",
      "model": "Account",
      "name": "tasks",
      "type": {
        "Relation": {
          "to": "Task",
          "to_fields": [],
          "name": "AccountToTask",
          "on_delete": "None"
        }
      },
      "arity": "list",
      "isUnique": false
    },
    {
      "stepType": "DeleteField",
      "model": "Account",
      "name": "task"
    },
    {
      "stepType": "UpdateField",
      "model": "Task",
      "name": "account",
      "type": {
        "Relation": {
          "to": "Account",
          "to_fields": [
            "id"
          ],
          "name": "AccountToTask",
          "on_delete": "None"
        }
      }
    }
  ]
}
```

**Comment by mavilein** [comment]
Hey there @ryanking1809 ,
thanks for your feedback 🙏 ! Here's an outline of our reasoning for the current behavior:
- In Prisma 1 we had the rule to treat **unspecified fields always as a list**. This had the onfortunate consequence that the following example resulted in a many to many relation:
```gql
model Task {
  id        String   @default(cuid()) @id
  account Account[]
}

model Account {
  id        String   @default(cuid()) @id
}
```
- In Prisma 2 we decided that **unspecified fields are always singular**. This fixes the aforementioned example to be one to many. But it lead to the surprising behavior you found.

I wonder if we should change that rule based on this feedback. We go with the following rule:
If the back relation field is unspecified and the specified field is:
1. a list: infer the back relation field as singular field.
2. singular: infer the back relation as a list. 

So in both cases we would make sure that if only one side is specified the resulting relation would be one to many.

**Comment by mavilein** [comment]
One more comment: We should be aware that the back relation field is also exposed in the photon API. We originally wanted to have a very very simple rule so that the appearing back relation field does not confuse people (when is it a list and when singular?). This new rule would be more complex. But i have the feeling that it is still more intuitive and hence there would not be as much confusion.
Let's see whether someone can find flaw with this new rule :-)

**Comment by ryanking1809** [comment]
Interesting... 🤔

In my experience with traditional ORMs is that if If the back relation field is unspecified and the specified field is:
 - a list: an error is thrown as there's not enough information to infer the relationship (especially without modifying the database in a way which was not specified by the user)
 - singular: infer the back relation as a list, as this can be done without modifying the database

My preference would be to make sure all database modifications are strictly specified in the schema, and if it's possible to infer a relation without modifying the database, then do that. 

However, I'm thinking you could avoid the issue altogether by forcing the user to always define both sides of the relation, throwing an error if only one side of the relation is defined.

**Comment by petra-fw** [comment]
Thanks for the elaboration on how a relation behaves if one part is left out. On contrary to what you have planed we have exactly that use case. We want to end up with a n:m relation but with one counterpart missing. The following snippet should clarify this. We would like to have category in the model post where different categories apply. On the model category we are not interested which post belong there, so we do not want to include this in the model. But there is the possibility that two posts belong to the same category. If this is modeled to one category than many relations will be lost. Will there be a possibility / work around with for example annotation.
`model Post {
  id         Int        @id
  categories Category[]
}

model Category {
  id    Int    @id
}`

**Comment by sorenbs** [comment]
@petra-fw - the way to achieve that is to simply spell out the full data model:

```
model Post {
  id         Int        @id
  categories Category[]
}

model Category {
  id        Int    @id
  posts     Post[]
}
```

This will add a posts field to your photon client, but you can simply ignore it. If you are creating a GraphQL API using Nexus for example, you can choose to not map that field through. Would you prefer if we introduced an attribute that will make photon ignore a field entirely.

**Comment by divyenduz** [comment]
Internal note: Spoke to Marcus
![image](https://user-images.githubusercontent.com/746482/70911288-e06d1700-2011-11ea-91dd-0aadadc0aa1b.png)
![image](https://user-images.githubusercontent.com/746482/70911355-085c7a80-2012-11ea-8aeb-000e1d086dbf.png)

Related issue, explicitness of relations: https://github.com/prisma/specs/issues/267

With Preview 18, this is the new migrated structure: 

```sql
CREATE TABLE "Account" (
  "id" TEXT NOT NULL   ,
  PRIMARY KEY ("id")
);

CREATE TABLE "Task" (
  "account" TEXT NOT NULL   REFERENCES "Account"(id) ON DELETE RESTRICT,
  "id" TEXT NOT NULL   ,
  PRIMARY KEY ("id")
);
```

I am closing this issue, please ping me here if you think that this issue is not resolved yet. 

Thanks
