### ISSUE TITLE
Minor UI issue with `init` flow

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#480]
After running through the following `init` flow:

- Starter kit
- TS
- Script
- SQLite

I get the following output:

![image](https://user-images.githubusercontent.com/4058327/64101778-e09d1b80-cd6e-11e9-86c0-fb7354fca3fd.png)

In the sentence: 

```
Start Prisma's development mode to enable access to Prisma Studio and watch schema.prisma for changes:
```

the `for changes` should be printed in gray instead of white.

**Comment by janpio** [comment]
https://github.com/prisma/prisma2/blob/7ca17143bbaceadbf243e4ef84889d2098e95dc5/cli/introspection/src/prompt/screens/Step61Success.tsx#L57-L64

**Comment by pantharshit00** [comment]
Made a quick PR for this: https://github.com/prisma/prisma2/pull/481

This was caused by the extra reset prop which resets the applied dim prop in chalk(ink just wraps that API)

**Comment by janpio** [comment]
Ohoh, I see this again in `prisma2@2.0.0-alpha.172`. Cna you retest this @pantharshit00 please?

**Comment by pantharshit00** [comment]
@janpio 

Unable to reproduce on Mac with `prisma2@2.0.0-alpha.178, binary version: c29a2b977d631657c87b1bd8e0e880c110844331`

![image](https://user-images.githubusercontent.com/22195362/64733656-c7306800-d502-11e9-952b-c9e7f7c7c789.png)

Can you please retest this on latest alpha. Otherwise, this is a window specific problem.

**Comment by janpio** [comment]
The `for changes` is bolder than `watch` in your screenshot, which confirms the reproduction @pantharshit00 - because of the color choice of your terminal it just isn't as visible.

**Comment by janpio** [comment]
This is still broken:

![image](https://user-images.githubusercontent.com/183673/67165580-2b0e4200-f387-11e9-83a3-9263d6bae707.png)

**Comment by pantharshit00** [comment]
I can confirm this, looks like this was introduced by this change: https://github.com/prisma/prisma2/commit/6ff63fabba7a659f408771269a46531df4c6da7e#diff-61cd5dc4bbd9ee1dd273b9a5bcfc0ca5

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem be gone after that 🚀
