### ISSUE TITLE
[Windows] `prisma2 init`  Unexpected end of JSON input

### ISSUE THREAD

**Issue by MattXtrem** [prisma/prisma2#483]
Hello Team Prisma ! 
I just tried the new preview of prisma2 on **Windows** and when i execute the prisma2 init cmd, I get an issue about json format. You have probably already known but I didnt any ticket about this. 
Details of the case.
Laumch cmd prisma2 init
-> blank project
-> SQLite
-> javascript
-> demo script

ERROR  Error during command execution

SyntaxError: Unexpected end of JSON input

Let me know if you need more info !

**Comment by janpio** [comment]
Can you please post your `prisma2 -v` output?
What command line are you using? Admin or normal user? How did you install `prisma2`?

It is expected that `prisma2` does not work on Windows yet, but with a slightly different error, see here for screenshot and explanation: https://github.com/prisma/prisma2/issues/460#issuecomment-527101677

**Comment by MattXtrem** [comment]
Hi @janpio 

It's a pleasure for me. 
So, that's the prisma version I use: 
`prisma2@2.0.0-preview-9.1, binary version: bbbeff6f84b408e534ebd866bfd378748e6d6611`

I tried admin and normal user, and I installed prisma2 globally, 

![image](https://user-images.githubusercontent.com/6517002/64280125-c6229800-cf50-11e9-95aa-51f7d6e71980.png)

**Comment by janpio** [comment]
Thanks - interesting. I tried again, and still get the error that I linked to above.

You recreation steps is missing information on the tools selection: Do you leave both Photon and Lift activated?

Also your console can actually show the ✔️ which my `cmd.exe` fails. What command line are you using - Cmder?

**Comment by MattXtrem** [comment]
Nice catch, it's **cmder**
recreation steps:
- Blank project
- SQLite
- Photon + Lift
- Javascript
- Demo SCript

And I tried on 2 different windows receiving the same issue.

**Comment by janpio** [comment]
I assume you also installed using Cmder on both machines?
How long did it take for you to get that error? I just waited 20 minutes and it is still spinning. Strange.

(We released a `preview-10` today, which should not influence this, but maybe still try to upgrade and see if it is still reproducible.)

**Comment by MattXtrem** [comment]
I also tried with the new preview ! Same result ! And it's immediate ! (Sorry for the delay ;) )

**Comment by janpio** [comment]
This should now be fixed in `alpha`, if you have the time try it with `npm install -g prisma2@alpha`. If it is not, please also post the output to the install command (as the correct binary should already be downloaded there).
