### ISSUE TITLE
Init flow - support return key/enter for navigation/toggle

### ISSUE THREAD

**Issue by AWey95** [prisma/prisma2#485]
Here is the current flow of `Prisma2 init`

> Blank project 
> PostgresSQL
-----------------
PostgresSQL database credentials.

This is the section where the issues arise.

First issue I noticed is that I am no longer able to `Enter` through the fields. You have to use arrows to go up and down. If you click `Enter` before providing all of the fields, it automatically tries to connect to and you end up with a connection ERROR (obviously).

Second issue, after entering all my database credentials, you're unable to check off `Use SSL`.

Trying to connect to my Heroku Postgres database without SSL enabled leads to the following.

`ERROR - no pg_hba.conf entry for host "198.54.304.261", user "yfhrbmzjdqtrqr", database "d9ugfgs87rs38qp", SSL off`

**Comment by nikolasburk** [comment]
Hey @AWey95, you can toggle the SSL-checkbox kusing <kbd>SPACE</kbd>. We need to make this clear during the CLI flow.

**Comment by AWey95** [comment]
> Hey @AWey95, you can toggle the SSL-checkbox kusing SPACE. We need to make this clear during the CLI flow.

Okay, I'll try this out and close the issue if it works. Is there any reason the CLI flow was changed? Not being able to `Enter` through the options seems unintuitive to me.

**Comment by divyenduz** [comment]
I will keep this issue open for enter support.

**Comment by divyenduz** [comment]
Current behavior: 

Postgres credentials form, enter tries to submit the form and doesn't move to next. This sounds correct to me. 

Tool selection, enter does nothing, space toggles the checkmark. We can support enter here. 

Next steps: Jan is rethinking init.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
