### ISSUE TITLE
Init w/ TS, GraphQL, Postgres: Failed at the typescript-graphql@ seed script.

### ISSUE THREAD

**Issue by ScottAgirs** [prisma/prisma2#489]
When initialising Typescript Starter kit with GraphQL API:

prisma2 init backend > Starter Kit > TypeScript > GraphQL API

I get the following error:
![image](https://user-images.githubusercontent.com/11737572/64205762-bf1f5b00-ce66-11e9-80cf-48aa6b2dbf5a.png)

**Comment by pantharshit00** [comment]
Duplicate of https://github.com/prisma/prisma2/issues/482
