### ISSUE TITLE
Redact password in the init flow

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#492]
Right now in the init flow the password property is not redacted and anyone can peek and read it or can take a screenshot that contains the password. 

We should redact the password.

![image](https://user-images.githubusercontent.com/22195362/64244338-7af38f80-cf26-11e9-9e7c-3ef62aa81099.png)

**Comment by divyenduz** [comment]
Note: Init flow changes, re-sync next week

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
