### ISSUE TITLE
`init`: Wrong "Back" detail

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#499]
```
prisma2@2.0.0-preview-9.1, binary version: bbbeff6f84b408e534ebd866bfd378748e6d6611
```

Run `prisma2 init foobar`, then `Blank project > SQLite > Confirm (without changing anything) > JavaScript` leads to:

```
C:\Users\Jan\Documents>prisma2 init prisma2_483_2

  Start with a runnable demo script or just the Prisma schema
  Demo scripts showcase usage of the Photon API

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                    │
│ > Demo script              Simple script with API examples                                                         │
│   Just the Prisma schema   Most minimal setup                                                                      │
│                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

< Back (Tool selection)
```

![image](https://user-images.githubusercontent.com/183673/64326141-b5facf00-cfc9-11e9-9079-867f40fb851d.png)

The correct description detail would be "Language Selection" probably. 

(Windows, cmd.exe)

**Comment by janpio** [comment]
Can you please confirm this happens on non-Windows OS as well @pantharshit00? Thanks.

**Comment by pantharshit00** [comment]
I can confirm this:

![image](https://user-images.githubusercontent.com/22195362/64361904-2128bd80-d02b-11e9-8c46-49bfbe8db1ae.png)

**Comment by janpio** [comment]
Note: Dropped as there might be changes in `init` again soon.

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Still present in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
