### ISSUE TITLE
Invalid state in `prisma2 init`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#502]
Was playing around with `preview-10` and these steps:

``` 
    Blank project
    SQLite
    Photon + Lift
    Javascript
    Demo Script
```

Somehow I ended up here:
![image](https://user-images.githubusercontent.com/183673/64386466-7f5c9d00-d039-11e9-91ee-952ad147b968.png)

The "Back" has no functionality at all with the Enter key.

(It is possible  I accidentally chose "MySQL" instead of "SQLite" during the flow, which I fixed by going back and then correcting to "SQLite". Might need some playing around to repro. Update: I just reprod it without selecting the wrong one.)

**Comment by janpio** [comment]
Note: Dropped as there might be changes in `init` again soon.

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Could not reproduce any more in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`
