### ISSUE TITLE
`prisma2` commands could fail more gracefully when query and migration engine are not present

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#508]
Problems like https://github.com/prisma/prisma2/issues/506 or https://github.com/prisma/prisma2/issues/503 lead to the query and migration engine binaries not being present, which leads to follow up errors when e.g. using `prisma2 init` later.

Although we of course want to fix these actual errors, it might be worth it to add some error handling of the binaries not being present or executable and have nicer error messages about that.

**Comment by divyenduz** [comment]
![image](https://user-images.githubusercontent.com/746482/70807431-d4891700-1dbd-11ea-96c4-efaf75d279a3.png)

It is a better error than before, this is not yet covered by the errors spec, it should be documented here: https://github.com/prisma/specs/tree/master/errors#prisma-cli

The spec only covers it for Photon's runtime https://github.com/prisma/specs/tree/master/errors#p1006-binary-not-found

**Comment by janpio** [comment]
This is actually good enough, it is very clear and will give us enough information in issue to start the search for the real reason.
