### ISSUE TITLE
Studio shows no data after installing preview 10 

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma2#509]
Today I installed the latest Prisma preview, opened Studio and even through I have data in the database and queries return them, Studio is empty:

<img width="1920" alt="Screenshot 2019-09-06 at 11 30 31" src="https://user-images.githubusercontent.com/7753942/64417687-dc883b00-d099-11e9-9022-b7db77239c90.png">

**Comment by malekjaroslav** [comment]
Might be related to https://github.com/prisma/prisma2/issues/495

**Comment by divyenduz** [comment]
Do you see any logs? If you check the inspector (I think that the shortcut is cmd + shift + i)

**Comment by malekjaroslav** [comment]
Hi @divyenduz, yes I see: 
<img width="1245" alt="Screenshot 2019-09-06 at 16 34 49" src="https://user-images.githubusercontent.com/7753942/64436310-60efb380-d0c4-11e9-8f5e-2c4a3c7ebb03.png">

**Comment by divyenduz** [comment]
Ah yes, please clear your index DB.

**Comment by malekjaroslav** [comment]
Crearing DB helped

**Comment by malekjaroslav** [comment]
@divyenduz Thanks! It solved the issue

**Comment by shoaibsharif** [comment]
I still have a problem but my console is showing up this error. 
```
Project load failed:  TypeError: Cannot read property 'id' of undefined
    at oi.switch (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at oi.i (studioBundle.js:16)
    at li.init (studioBundle.js:108)
```

![Screenshot from 2019-09-07 11-21-54](https://user-images.githubusercontent.com/29075110/64478750-c47bee80-d161-11e9-926b-da27cabc9098.png)

**Comment by janpio** [comment]
You should open a separate about this @shoaibsharif

**Comment by shoaibsharif** [comment]
@janpio All right I am opening a new issue.
