### ISSUE TITLE
[feature request] Add commands for manually  update the schema to database

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma2#511]
hi guy! I want to make a feature request.

My current datamodel exceeds 400 lines of code, and I found that `prisma2 dev` no longer works, causing me to fail to update the schema to the database.It always shows `No changes yet`, like this [`prisma2 dev` doesn't generate](https://github.com/prisma/prisma2/issues/495)

So I suggest add a new cli command to manually generate and update the schema to use it when prisma2 dev is not working, and it no longer needs to detect if schema.prisma has changed.

**Comment by divyenduz** [comment]
This is already possible with: 

`prisma2 lift save` - to write unapplied migrations to the file system, and,
`prisma2 lift up`

Does that answer your question?

**Comment by sessionboy** [comment]
@divyenduz  Thank you for your help.

But I think this is problematic. I tried updating my schema with `prisma2 lift save` and `prisma2 lift up`, it executed the command without any prompts, and my schema was not updated, it is still the old schema.

**Comment by pantharshit00** [comment]
Those two commands are the ones that will migrate your database schema.

If those two are not working, please share a reproduction with us 🙏

**Comment by divyenduz** [comment]
@sessionboy : Also, please share your OS/DB and Prisma schema file, and the output of these commands with `export DEBUG=*`

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
