### ISSUE TITLE
[Feature request] Connect to new datasource at runtime

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma2#512]
I am currently re-writing [prisma-multi-tenant](https://github.com/Errorname/prisma-multi-tenant) to use Prisma2 and handle the management part that Prisma1 had.

Because we could theoretically create an infinite number of tenants (and for some other reasons), I would like to be able to connect to any datasources at runtime, even when it has not been defined in the schema.prisma file and therefore generated.

Ex:
```
const tenant = new Photon({
      datasources: {
        db: {
          connectorType: "postgres",
          url: "postgres://someurl:5432"
        }
      }
    })

tenant.doSomething()
```

Would that be possible to do?

**Comment by Errorname** [comment]
I read somewhere (can't remember where) that the generated files were dependant on the types of the datasources, so I could have a datasources for each possible type (pgsql, mysql, sqlite, ...) and then dynamically change the url and enable them at runtime. But that's kind of cumbersome and I would prefer not to impose changes to the schema.prisma file.

**Comment by divyenduz** [comment]
I think you read that here: https://github.com/prisma/photonjs/issues/184

However, an alternative to support cross DB photon can be to generate a Photon client based on the intersection of the DB feature. We are heavily mapping this out in the capabilities spec here: https://github.com/prisma/specs/issues/110

Happy to know your thoughts on this. 

BTW, if you think that this is a duplicate of #184, please feel free to close it, not required though :)

**Comment by Errorname** [comment]
I hadn't seen the issue, but I guess that could solve this. I'll close this issue for now and wait for it to be implemented 👍
