### ISSUE TITLE
working type definition example

### ISSUE THREAD

**Issue by fiws** [prisma/prisma2#52]
The [type definition example](https://github.com/prisma/prisma2-docs/blob/master/data-modeling.md#type-definitions)

```prisma
type Numeric Float @pg.numeric(precision: 5, scale: 2)
                   @ms.decimal(precision: 5, scale: 2)
```

gives me this error: `Unexpected token. Expected one of: Start of block ("{").`

A working example would be nice. (And also more docs on it in general)

**Comment by ejoebstl** [comment]
The equals sign is missing in the example. [Fixed](https://github.com/prisma/prisma2-docs/commit/0ce0c8693cf188199162fbfee701bf222701dd3d).

Please note that connectors do not export any custom attributes (`@xx.numeric, @xx.decimal etc.`) as of now.

**Comment by nelsonpecora** [comment]
@ejoebstl I'm not quite sure what the last line in your comment means. Does it mean that _no_ type definitions are currently working? If so, where can we find docs/tickets to track the status of this?

**Comment by ejoebstl** [comment]
Type definitons work, but I do not know if database connectors provide types yet.

I'm sure @divyenduz can provide more answers.
