### ISSUE TITLE
[Windows] "'C:\Program' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#531]
`prisma2@2.0.0-alpha.172, binary version: 96c499d9956096a0f06d01f0e6fdf6e90ce89c24`

`init` wizard selection: `Blank project > SQLite > Confirm (with both) > JavaScript > Demo script` leads to:

```
C:\Users\Jan\Documents\throwaway>prisma2 init p2WinTest4

Preparing your demo script (JavaScript) ...


Preparing your demo script (JavaScript) ...

✔  Downloading the demo script from GitHub ...
✔  Extracting content to p2WinTest4 ...
✔  Installing dependencies with: `npm install` ...
⠋  Preparing your database ...
 ERROR  Error during command execution

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

This points to some exec/spawn using a non quoted / not shell escaped path of an executable (e.g. `node` and `npm` are installed in `C:\Program Files\nodejs` for me, but could also be binary or something like that).

**Comment by janpio** [comment]
This case the script is using the CLI itself, which in this case is:
```
C:\Users\Jan\Documents\throwaway>where prisma2
C:\Program Files\nodejs\prisma2
C:\Program Files\nodejs\prisma2.cmd
```

**Comment by brunocrosier** [comment]
I also get this, however, if you select "just the prisma schema" instead of "demo script" in the last option, it seems to work

I assume there's an issue with the script installation process on windows, as all the other demo scripts also cause the same error

**Comment by elliscwc** [comment]
![image](https://user-images.githubusercontent.com/29953232/65210712-aa7dcc80-dace-11e9-96ac-48f683cc5123.png)
I'm facing this same issue, while I also stuck with "just the prisma schema" option.. It just says `Processing the blank project`.
I'm using Windows 10 and powershell

**Comment by janpio** [comment]
> while I also stuck with "just the prisma schema" option.. It just says `Processing the blank project`.

Please open a new issue for that separate problem.

We are actively working on fixing this one here.

**Comment by brunocrosier** [comment]
@timsuchanek i just uninstalled prisma2 on windows, and reinstalled. Then I ran `prisma2 init` and chose the GraphQL API starter kit. Again, I see this output:

```

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to ./ ...
✔  Installing dependencies with: `npm install` ...
⠋  Preparing your database ...
5  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by divyenduz** [comment]
`npm i -g prisma2@2.0.0-alpha.204` I can repro on this version, re-opening till we figure out the alpha publishing/further fix.

**Comment by brunocrosier** [comment]
@divyenduz i just realized - maybe the Windows patch was not included in the 2.0.0-alpha.204 version?

**Comment by janpio** [comment]
Yes @brunocrosier, that is our current thinking there. Still investigating.

**Comment by brunocrosier** [comment]
@janpio I just tried `npm i -g prisma2@2.0.0-alpha.205` (which I assume has the proposed windows fix) and encountered the same issue.

**Comment by janpio** [comment]
Then this assumption is probably not true - or the fix didn't work. We don't know yet and are still investigating.

**Comment by janpio** [comment]
Confirmation that the problem still exists in `alpha.205`:

```
C:\Users\Jan\Documents
λ npm install -g prisma2@alpha
C:\Program Files\nodejs\prisma2 -> C:\Program Files\nodejs\node_modules\prisma2\build\index.js

> prisma2@2.0.0-alpha.205 install C:\Program Files\nodejs\node_modules\prisma2
> node download-build/index.js || echo ""

> Downloading windows binary [====================] 100%




+ prisma2@2.0.0-alpha.205
updated 1 package in 13.781s

C:\Users\Jan\Documents
λ cd throwaway\

C:\Users\Jan\Documents\throwaway
λ prisma2 init 531

Preparing your demo script (JavaScript) ...

✔  Downloading the demo script from GitHub ...
✔  Extracting content to 531 ...
✔  Installing dependencies with: `npm install` ...
⠋  Preparing your database ...
 ERROR  Error during command execution

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by janpio** [comment]
This should be fixed now in the just release `preview-13`.

**Comment by brunocrosier** [comment]
Congrats! Can confirm this error is fixed. There is another issue relating to Windows though which I have just opened: #614
