### ISSUE TITLE
Write minimal tutorial for production deployment

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#54]
Combinations based on:

DB:

- [ ] DigitalOcean
- [ ] (Render)

API:

- [ ] ZEIT
- [ ] Netlify
- [ ] Render

Important: Should work well with serverless functions + relational DBs.

**Comment by divyenduz** [comment]
The first wave of examples are available at https://github.com/prisma/photonjs/tree/master/examples/deployment-platforms

**Comment by yovanoc** [comment]
Seems a perfect idea ! It would be great to have Kubernetes/Docker examples !

**Comment by haysclark** [comment]
> The first wave of examples are available at https://github.com/prisma/photonjs/tree/master/examples/deployment-platforms

Looks like these deployment docs are now located here:
https://github.com/prisma/prisma2/blob/master/docs/photon/deployment.md

**Comment by schickling** [comment]
Closing this for now as how @haysclark pointed out, we've created a set of examples and docs. If you're looking for more specific docs/examples, please create a new issue.
