### ISSUE TITLE
MySQL connection timeout 

### ISSUE THREAD

**Issue by kunalgorithm** [prisma/prisma2#547]
Hi,  I’m trying to connect to a MySQL database using prisma2, and I’m continuously met with `Error querying the database: DriverError { Could not connect: connection timeout } date=2019-09-12T04:49:54.257Z`

In me schema I have
```
datasource db {
  provider = "mysql"
  url      = "mysql://MY_MYSQL_ENDPOINT"
}
```

I'm using `"prisma2": "^2.0.0-preview-10"` and trying to connect to a remote MySQL database using AWS RDS

**Comment by pantharshit00** [comment]
@kunalgorithm 


I am successfully able to connect to an RDS MySQL database instance. Can you please sure that your computer's IP(or all IPs) are whitelisted in the inbound security rules for your database in the AWS dashboard?

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
