### ISSUE TITLE
Project bootstrapped by the init flow should use the latest version of prisma2

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#548]
I am on `prisma2@2.0.0-preview-11, binary version: 408c0c08746064a56c8ba7cb167bad49f1d2c2f7`

Right now any new project initialized by prisma2 cli is using a specific version of prisma2 instead of using the latest version:
![image](https://user-images.githubusercontent.com/22195362/64814377-f4dbe680-d5c0-11e9-9aa8-4e63ae7b8e28.png)

**Comment by janpio** [comment]
How was this fixed - one off fix in the `devDeps` or some automation?
