### ISSUE TITLE
Refactor generator handling

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#55]
Right now generators are hardcoded and shipped with the `prisma2` CLI. We should open up the generator API to let users bring their own generators (e.g. for `prisma-test-utils`) and `nexus-prisma`).

Also see: https://gnorm.org

**Comment by timsuchanek** [comment]
Nope, there is no assumption of the Node.js in there, you can provide any binary.

**Comment by timsuchanek** [comment]
Shipped already for a  while  :)
