### ISSUE TITLE
Rename platforms to binaryTargets

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#553]
This change for decided in the binaries spec: https://github.com/prisma/specs/tree/master/binaries

Reason: To avoid future SEO conflicts with a Prisma project that has platforms in it. 

Implementation is still pending for this.

**Comment by mavilein** [comment]
This probably also requires some work in the backend. We should coordinate about this @timsuchanek

**Comment by timsuchanek** [comment]
Released in the latest preview.
