### ISSUE TITLE
Relations NULLED after migration

### ISSUE THREAD

**Issue by cypcz** [prisma/prisma2#557]
After a change to the `schema`, `prisma2 lift save` and `prisma2 lift up`, all the relations in the database are nulled.

This is how M:N relation table looks like after `prisma2 lift up`.
![image](https://user-images.githubusercontent.com/29678037/65120320-b9d91900-d9ed-11e9-93a0-bdb4d3360a8e.png)

Happens in 1:N relation, too.
![image](https://user-images.githubusercontent.com/29678037/65120492-058bc280-d9ee-11e9-934f-e39e12233fd1.png)

Using Postgres and prisma2 version `2.0.0-alpha.160`

**Comment by pantharshit00** [comment]
Can you please share your datamodel and what exact change you made?

Maybe share a copy of your migrations folder so that we can see what migrations were applied.

**Comment by cypcz** [comment]
You can download schema and migrations [here](http://s000.tinyupload.com/index.php?file_id=51168690439022315577).

I tried to add `testField  String?` to the `Project` model.

**Comment by pantharshit00** [comment]
I think your issue was related to https://github.com/prisma/lift/issues/100 which has been fixed now. 

Please use the latest preview or alpha version of Prisma 2

**Comment by cypcz** [comment]
If I update to `2.0.0-preview-11`, first I get `Error: Get config Error: Command failed with exit code 13 (EACCES)`. Then I ran `chmod -R 777 node-modules` to change permissions but now I get `Error: Get config SyntaxError: Unexpected token P in JSON at position 0`. 

Everything works fine with `2.0.0-alpha.160`. Were there any changes introduced that might cause these issues?

**Comment by pantharshit00** [comment]
Yes, that is possible as Prisma 2 is in preview so we will introduce breaking changes in the preview period.

I will recommend you to start fresh with your schema

**Comment by malekjaroslav** [comment]
@cypcz can we close this?

**Comment by divyenduz** [comment]
> @cypcz can we close this?

Do you think it is resolved? Or are you prompting for us to look into it?

**Comment by cypcz** [comment]
Sorry, I was off for holidays. Yes, I no longer experienced the issue.
