### ISSUE TITLE
Hitting Heroku connection limit when running prisma2 dev in terminal

### ISSUE THREAD

**Issue by emolr** [prisma/prisma2#567]
I'm running prisma2 on Heroku (hobby dev) and it's using up all 20 available connections from only being used by myself in development.

Here is the response when trying to query my database in graphql playground using the typescript authentication starter project.

```
{
  "data": null,
  "errors": [
    {
      "message": "\n\u001b[31mInvalid \u001b[1m`photon.()`\u001b[22m invocation in \u001b[4m/Users/emil/Documents/lab/prisma2/src/resolvers/Query.ts:14:33\u001b[24m\u001b[39m\n\n\n\n\u001b[31mError querying the database: db error: FATAL: too many connections for role \"**********\" date=2019-09-18T20:27:18.737Z\u001b[39m",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "me"
      ]
    }
  ]
}
```

Screenshot of Heroku overview:
<img width="1381" alt="Screenshot 2019-09-18 at 22 31 36" src="https://user-images.githubusercontent.com/2789549/65183893-b46ae580-da64-11e9-9548-aa12b186d58e.png">

**Comment by pantharshit00** [comment]
Hi, 

Thanks for reporting this. I think it a connection pooling issue. Photon is opening a new connection per request right now. 

We have an issue for connection pooling in which we have listed some ways you can prevent this and also we are trying to explore new ways to solve this. Please have a look here: https://github.com/prisma/photonjs/issues/228

For now, I am going to close this one as a duplicate. Please feel free to comment on that other issue 🙂

**Comment by emolr** [comment]
Thank you @pantharshit00.

I eventually moved to google cloud sql to continue my work :)
