### ISSUE TITLE
Support custom SSL certificates in the connection string

### ISSUE THREAD

**Issue by aputinski** [prisma/prisma2#568]
I read through several issues referencing SSL (https://github.com/prisma/prisma2/issues/134, https://github.com/prisma/prisma2/issues/109), and they seem to indicate it was implemented, but even after specifying all the correct ssl related query parameters in my connection string (which I have verified connects using `psql`, I get the error: `FATAL: connection requires a valid client certificate`.

I'm using `prisma2@2.0.0-preview-11`

**Comment by emolr** [comment]
@aputinski 
Maybe i'm asking the wrong question, but are you trying to connect via the standalone Prisma Studio application? 
I'm having issues connecting through that. 

But i'm able to connect to my Heroku posgres database using the `?sslmode=prefer` in my datasource url without any issues in the schema.prisma file.

**Comment by pantharshit00** [comment]
@aputinski Can you please share your connection string? Please redact any sensitive information in that and share that with us.

@emolr Standalone studio still requires much work right now. Please report any issues that you find here: https://github.com/prisma/studio

**Comment by aputinski** [comment]
@pantharshit00 `postgres://postgres:<PASSWORD>@<HOST>?sslmode=verify-ca&sslcert=<CLIENT_CERT_PATH>&sslkey=<CLIENT_KEY_PATH>&sslrootcert=<ROOT_CERT_PATH>`

**Comment by pantharshit00** [comment]
We don't `sslrootcert` and `sslcert` parameters. The parameters that we support can be found here: https://github.com/prisma/prisma-query/blob/87ebf0d09c086d7b0a1fbc6141decc75fadb97e1/src/connector/postgres.rs#L95

I am marking this as a feature request with a change in the title.

**Comment by aputinski** [comment]
Thanks for the update. Really enjoying `prisma2`! This is blocker for using Google Cloud SQL on Zeit because I can't whitelist IPs and I can't use the Google Cloud SQL Proxy.

**Comment by malekjaroslav** [comment]
Related: https://github.com/prisma/prisma2/issues/525

**Comment by pimeys** [comment]
It's not super simple to implement, some concerns:

- In which format the certificate is? There are quite many of them and sometimes we should convert between them to get the connector to work.
- The TLS connector supports pem certs quite easily.
- Needs to be tested with a database requiring a custom certificate.

1 day for work, two for testing.

**Comment by janpio** [comment]
@aputinski Can you provide some more information re the questions @pimeys posted? Especially `Google Cloud SQL on Zeit` would probably be interesting.

**Comment by aputinski** [comment]
@pimeys @janpio Looks like Google Cloud SQL uses PEM certificates.

**Comment by pimeys** [comment]
There are some limitations what we can do if we don't want to statically link to OpenSSL.

One way is to download the root cert, client cert and client key from Google, and convert the client cert and key into a pkcs12 database, protected with a password. Doable with openssl command line client or what I heard also with OSX system tools.

On Linux it should require the user to do:

```bash
openssl pkcs12 -export -out client-identity.p12 -inkey client-key.pem -in client-cert.pem
```

Then the connection string could look like this:

```
postgres://postgres:<PASSWORD>@<HOST>?sslmode=verify-ca&sslidentity=<PKCS12_PATH>&sslpassword=<PKCS12_PASSWORD>&sslrootcert=<ROOT_CERT_PATH>
```

This requires product input and writing instructions for all supported platforms.

**Comment by pimeys** [comment]
The SSL params required in this feature:

- `sslmode=(disable|prefer|require)`: Disable: do not use TLS. Prefer: prefer TLS if possible, accept plain text connections. Require: require TLS or fail if not possible. Default: `prefer`
- `sslcert=<PATH>`: path the the server certificate, in Google's case this is the `server-ca.pem`.
- `sslidentity=<PATH>`: path to the PKCS12 certificate database created from client cert and key.
- `sslpassword=<PASSWORD>`: the PKCS12 password.
- `sslaccept=(strict|accept_invalid_certs)`: If set to strict, any missing value in the certificate will lead to an error. In Google's case, especially if the database doesn't have a domain name, the certificate might miss the domain/IP address, causing an error when connecting. Set this value to `accept_invalid_certs` to bypass this check. Please be aware the security consequences of this setting.

**Comment by pimeys** [comment]
The corresponding commit in `prisma-query`: https://github.com/prisma/prisma-query/commit/b0607ce118e3704879caff8f529eee4ee4a13d96.

The corresponding commit in `prisma-engine`: https://github.com/prisma/prisma-engine/commit/2b78c35cf302bf80ae5aaa863c5eee0d09541f83

This will be now available in the next alpha, or if interested in testing right now, by pulling and compiling the `prisma-engine` manually.

Tested with Google SQL, disabling access without a certificate.
