### ISSUE TITLE
Document the HTTP proxy feature

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#577]
After https://github.com/prisma/photonjs/pull/229 and https://github.com/prisma/prisma2/pull/576 are merged. 

Fixes: https://github.com/prisma/prisma2/issues/506
Spec issue: https://github.com/prisma/specs/issues/157

**Comment by nikolasburk** [comment]
Just added some docs for using HTTP proxies [here](https://github.com/prisma/prisma2/pull/591). Note that I took some inspiration from the [Prisma 1 docs](https://www.prisma.io/docs/prisma-cli-and-configuration/using-the-prisma-cli-alx4/#using-a-http-proxy-for-the-cli) on it, please let me know if some information is not accurate @divyenduz 🙌

**Comment by janpio** [comment]
https://github.com/prisma/prisma2/pull/576 is not merged yet, so not sure if this is actually available.

**Comment by divyenduz** [comment]
@janpio I thought the same but since it is available in 2 days, no point in doing a revert.

**Comment by timsuchanek** [comment]
For people who get here from google, you can find the docs here: https://github.com/prisma/prisma2/blob/master/docs/prisma2-cli.md#using-a-http-proxy-for-the-cli
