### ISSUE TITLE
introspection file contains undefined

### ISSUE THREAD

**Issue by carstenbaumhoegger** [prisma/prisma2#58]
I've just used prisma2 to generate an introspection file of my existing prisma1 database.

When I run `prisma2 introspect` the generated `datamodel-12345xy.prisma` file does only contain the string "undefined".

When I run `prisma2 init testproject` prisma2 generates a folder `testproject/prisma` with a file `project.prisma` that contains my database introspection.

Used prisma2-version: `0.0.110` 
Used database: `mySQL 5.7`

**Comment by schickling** [comment]
Thanks a lot for reporting this @carstenbaumhoegger. We'll look into it as it's related to #11.

**Comment by divyenduz** [comment]
We [rewrote introspection](https://github.com/prisma/prisma2/releases) recently. Can you please see if this issue still exists in the latest alpha or preview?

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
