### ISSUE TITLE
Update prisma studio version

### ISSUE THREAD

**Issue by shoaibsharif** [prisma/prisma2#588]
I just noticed one issue, when I upgrade to `prisma2@2.0.0-preview-12`, the prisma studio doesn't work. Then, I upgrade to `prisma2@2.0.0-alpha.193`, it solved the issue. I've checked the version of Studio of `prisma2@2.0.0-preview-12` which was `0.92.0` and  `prisma2@2.0.0-alpha.193` has version `0.95.0`. Can you upgrade the Studio version in `prisma2@2.0.0-preview-12`? Is there any difference between them?

**Comment by janpio** [comment]
`alpha` are just newer builds that are published during the week representing current development process, and `preview`s are coordinated (currently) weekly releases that are more stable (or not, see the problem you are having with Studio). 

You should be good using `alpha.193` with the newer studio `0.95.0`.

**Comment by shoaibsharif** [comment]
Thanks. Got it. Just wanted to point this out to you guys because I want you to release the version as soon as possible. Loving it!
