### ISSUE TITLE
Getting ENOENT when quering with preview > 11

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma2#590]
After installing preview-12 I am getting this error when running a query:
``
spawn node_modules/@generated/photon/runtime/query-engine-darwin ENOENT
``

Downgrading to preview 11 solves it.

**Comment by janpio** [comment]
Can you check in `node_modules/@generated/photon/runtime/` if a binary `query-engine-darwin` exists there?

**Comment by divyenduz** [comment]
@malekjaroslav Are you using a macbook?

**Comment by malekjaroslav** [comment]
I got it to work by removing all migrations and starting from scratch.

**Comment by pantharshit00** [comment]
@malekjaroslav Just so that we can be sure here, can you please share your operating system information.

**Comment by malekjaroslav** [comment]
@pantharshit00 yes I use macbook

**Comment by malekjaroslav** [comment]
Sorry, so I was too quick to reply. It is still not working. This is the content of the runtime folder.
<img width="309" alt="Screenshot 2019-09-23 at 16 36 20" src="https://user-images.githubusercontent.com/7753942/65435168-53565f80-de20-11e9-96cc-775c3d3a79f3.png">

**Comment by pantharshit00** [comment]
We haven't tested Photon in MacOS Catalina as Catalina is in public beta.

So now we can either Wait till public release of it next month or we can test it right now.

**Comment by malekjaroslav** [comment]
I would be grateful for testing it. I can help if needed.

**Comment by janpio** [comment]
You just did - but we have to confirm and reproduce this independently to be able to know if we can even try to fix it ;) Thanks for the offer though.

**Comment by malekjaroslav** [comment]
@janpio @pantharshit00 As Catalina is now public are you planning to look into this?

**Comment by pantharshit00** [comment]
Starting to upgrade my laptop just now, will look into this for sure :)

**Comment by janpio** [comment]
How did you install `prisma2` @malekjaroslav? Can you share the output you get when installing please?

**Comment by pantharshit00** [comment]
I was unable to reproduce this in Catalina as well:
![image](https://user-images.githubusercontent.com/22195362/66466426-5009d780-eaa0-11e9-9877-5d81d8e0e456.png)

It is running fine and performing the required operations:
![image](https://user-images.githubusercontent.com/22195362/66466798-edfda200-eaa0-11e9-892d-d46e01e9d8a8.png)

**Comment by malekjaroslav** [comment]
I still have the issue with ` "prisma2": "2.0.0-preview013.3",` I install it as a local dependency calling it  with `yarn prisma2`.  

`spawn node_modules/@generated/photon/runtime/query-engine-darwin ENOENT`

**Comment by malekjaroslav** [comment]
I have also tried to delete the DB and start from scratch. I have also tried to run it in a docker container.

Had the same error in both cases in two projects...

**Comment by pantharshit00** [comment]
Can you send us a screenshot of the permission of the files of the photon's runtime folder?

Goto `node_modules/@generated/photon/runtime/` and run `ls -al`. Then please paste the screenshot here.

**Comment by janpio** [comment]
It might also be interesting if you could uninstall and install it again and send us the full output of the 2 commands.

**Comment by pantharshit00** [comment]
Permissions look correct to me. 

Are you able to execute the binary like so:
![image](https://user-images.githubusercontent.com/22195362/66653931-bcc6d280-ec56-11e9-9a2b-ee3ad6b6daaf.png)

**Comment by malekjaroslav** [comment]
@pantharshit00 Yes, I can execute it like this

**Comment by pantharshit00** [comment]
Well, then which Node.js version are you using? I am using `v10.16.0`.

Also, are you using nvm or any other node js version manager.

**Comment by malekjaroslav** [comment]
I now switch to v10.16.0 with nvm, still the same...

<img width="1178" alt="Screenshot 2019-10-11 at 20 43 30" src="https://user-images.githubusercontent.com/7753942/66656383-108de780-ec68-11e9-8c31-5d26aac0b80e.png">

**Comment by malekjaroslav** [comment]
UPDATE:
When I query through Photon directly, it works! So I guess the issue is somewhere int the graphql middleware. Any idea what could it be?

**Comment by pantharshit00** [comment]
Are you building the project using webpack?

**Comment by malekjaroslav** [comment]
Yes

**Comment by malekjaroslav** [comment]
I will create a reproduction and send it here

**Comment by divyenduz** [comment]
Ah, thanks for the thorough investigation Harshit. 

@malekjaroslav https://github.com/prisma/photonjs/issues/119, you will have to use webpack copy plugin to move the binaries over to the bundled folder. Does that make sense? Happy to provide an example if you want.

**Comment by malekjaroslav** [comment]
I use [backpackjs](https://github.com/jaredpalmer/backpack) to build the project, so webpack can be accessed and modified in `backpack.config.js`


[photon-webpack.zip](https://github.com/prisma/prisma2/files/3718315/photon-webpack.zip)

**Comment by malekjaroslav** [comment]
@divyenduz ok, got it. So I need to move `query-engine-darwin` to the build folder? But I photon knows where it is?

**Comment by divyenduz** [comment]
Photon should know where it is as long as the depth (in terms of folders) of the move remains the same.

**Comment by malekjaroslav** [comment]
Can you please give me some example? I still can't figure it out...

**Comment by malekjaroslav** [comment]
Got it to work thanks to https://www.npmjs.com/package/webpack-node-externals. Thanks!
