### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::4000

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#594]
Basically my port is in use, it should however show an option to open another port just like `create-react-app` does it :)

**Comment by divyenduz** [comment]
Which command is this? This very likely looks like a app level code. None of the Prisma tools run anything on `4000` afaik 🤔🙏

**Comment by deadcoder0904** [comment]
Ohh shit, idk what i was smoking 😂

But to confirm where do we put the PORT at? Here's my [code](https://github.com/deadcoder0904/test-optimistic-ui/tree/master/server).

It's just a GraphQL API boilerplate (without auth) but the PORT is only specified in `console.log` [here](https://github.com/deadcoder0904/test-optimistic-ui/blob/master/server/src/index.js#L80)

**Comment by deadcoder0904** [comment]
Found the solution on https://github.com/prisma/graphql-yoga.

I changed the code to change the default PORT -

```js
const opts = {
  port: 4001,
}

server.start(opts, ({ port }) =>
  console.log(
    `🚀 Server ready at: http://localhost:${port}\n⭐️ See sample queries: http://pris.ly/e/js/graphql#6-using-the-graphql-api`,
  ),
)
```

This can be added to the GraphQL example as I think beta testers are running multiple applications at the same time.
