### ISSUE TITLE
Limitations: Missing out of scope, Details for Custom Types

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#603]
After https://github.com/prisma/prisma2/pull/431 was merged, the "out of scope" section should also include more things, and the custom types should have some examples.

**Comment by schickling** [comment]
Done ✅

**Comment by janpio** [comment]
Commit was https://github.com/prisma/prisma2/commit/506fa953dc37d4e1737e6e9f96c99ebb481f2b79
