### ISSUE TITLE
Why are the db config and generators mixed with the schema definition?

### ISSUE THREAD

**Issue by kitze** [prisma/prisma2#606]
I'm curious if there's a reason behind this:
```
generator photon {
  provider = "photonjs"
}

generator nexus_prisma {
  provider = "nexus-prisma"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}
```

being inside the `schema.prisma` file. I think it makes more sense if it's in a separate file.

**Comment by matthewmueller** [comment]
@kitze Hey! I was the one that pushed for Prisma having a single syntax that supports both configuration and schema definitions in a single file. I was inspired by how syntaxes like HCL (Terraform's language) are able to nicely model relationships in text. 

Terraform is a different product than Prisma, so not everything makes sense. We had to think about what to apply and what didn't make sense in our domain. The conclusion we came to was that it's all configuration. The schema definition is actually just "configuration for your database".

That being said, we anticipate that many people will prefer to separate this configuration from the schema. In the past, we used YAML for configuration and GraphQL's SDL syntax for the schema definition. This made the separation mandatory. We wanted to make this separation optional.

It's not implemented yet, but soon you'll be able to import `.prisma` files. Here's a spec for how that will look: https://github.com/prisma/specs/tree/master/schema#importing-schemas

**Comment by kitze** [comment]
@matthewmueller Thanks for the clarification, that makes sense and I like it that it's optional. The issue can be closed unless someone else has something to add 👍

**Comment by schickling** [comment]
Closing this for now. In case someone else feels the Prisma schema should be split up by default into a configuration and a separate data model definition file, please comment in this thread! 🙏

**Comment by rajington** [comment]
@matthewmueller was there more on the decision to use a non-SDL format for the schema? it feels like everything in [data modeling](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md) (including the datasource) could be defined using directives:
```
@datasource(sqlite, {
  url: "file:data.db"
  provider: "sqlite"
})

type User {
  id: ID!
  createdAt: DateTime! @default(now())
  email: String! @unique
  name: String
  role: Role! @default(USER)
  posts: [Post!]!
  profile: Profile
}

type Profile {
  id: ID!
  user: User!
  bio: String!
}

type Post {
  id: ID!
  createdAt: DateTime! @default(now())
  updatedAt: DateTime! @updatedAt
  author: User!
  title: String!
  published: Boolean! @default(false)
  categories: [Category!]!
}

type Category {
  id: ID!
  name: String!
  posts [Post!]!
}

enum Role {
  USER
  ADMIN
}
```
one thing that drew me to Prisma was that datamodel, and it's departure seems surprising and less standardized/shareable

**Comment by divyenduz** [comment]
@tianhuil Thanks for the feedback

> I would like to be able to separate out datasource from the schema. We often want to have the same app running on several databases (production, staging, testing, QA, dev) and being able to swap databases, while keeping the same schema would be valuable.

Isn't something like this possible with 

```prisma
datasource ds {
  provider = "mysql"
  url = env("DB_URL")
}
```

And then per environment changing the DB_URL. This also conforms to [12 factor](https://12factor.net/config) apps. 

I am closing this one, please re-open a new issue with a suggestion of you do not agree with me and tag me on that one 🙏
