### ISSUE TITLE
Optimize Prisma generate

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#611]
Continuation of https://github.com/prisma/prisma2/issues/254

Issue that tracks the next steps as [outlined here](https://github.com/prisma/prisma2/issues/254#issuecomment-534587673)

Pasting that comment here: 

We did some research on this and it turns out, that for a schema with 1000 models, we generate 500k lines of code with a file size of 30mb.
The TypeScript compiler is not able to handle the compilation of that and crashes.

Next steps:

1. Reduce output size. There are a few places, where we can shave a bit of size off.
2. Directly generate @generated/photon/index.js and @generated/photon/index.d.ts without the TypeScript compiler.

**Comment by timsuchanek** [comment]
This is done in the latest version :)
