### ISSUE TITLE
[Mac] "Photon binary for current platform darwin could not be found" when running photon query

### ISSUE THREAD

**Issue by s7au** [prisma/prisma2#619]
Hi there. Not sure if this is a similar issue to #549. I am calling this from a netlify function inside a gatsby application. Basically stuck the graphql-auth starter into a lambda function so replaced 'GraphQLServer' with 'GraphQLServerLambda' and server.start(() =>{}) with exports.handler = lambda.handler. When I navigate to http://localhost:8000/.netlify/functions/photon and input a query inside the ui I get this:

```
Error: 
Invalid `return ctx.photon.posts.findMany()` invocation in /Users/s7au/gatsby-test/lambda/photon.js:233787:33

  233783 });
  233784 t.list.field('feed', {
  233785   type: 'Post',
  233786   resolve: (parent,[object Object], args,[object Object], ctx) => {
→ 233787     return ctx.photon.posts.findMany(

Photon binary for current platform darwin could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
  platforms = ["native"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `darwin`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
```
If I adjust to add platforms=["native"] it changes the message to:
```
Photon binary for current platform darwin could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
  platforms = ["native", "darwin"]
}
```
OS: macOS Mojave 10.14.5
npm -v: 6.11.3
prisma2 -v : prisma2@2.0.0-preview-12, binary version: 2292f8d0c3bd11fe9cca7c6df4a10061bf58fd18

**Comment by divyenduz** [comment]
`darwin` is the binary for macos, [this is](https://github.com/prisma/prisma-examples/blob/prisma2/deployment-platforms/netlify/prisma/schema.prisma#L9) an example of making Photon work with netlify. 

This is where you can learn more about binaries and platforms: https://github.com/prisma/specs/tree/master/binaries

Please let me know if this works for you. If yes, please feel free to ask further questions or close this issue :)

**Comment by s7au** [comment]
Thank you managed to get it working. Trying to get it working with typescript now and it seems to be more involved what with the file sourcing but will bang my head against it some more.

**Comment by s7au** [comment]
Decided to reopen this issue instead of creating a new one. Please advise if this is appropriate.
I took the deployment/platform starter code and:
- renamed the index.js file to index.ts
- added the relevant typescript dependencies to package.json
- modified the netlify.toml file to get functions from "lambda/"
- added a "build:lambda": "netlify-lambda build functions" to the package.json scripts
When I try to run this time I still get the following error:

```
Request from ::1: GET /.netlify/functions/index
Response with status 500 in 85 ms.
◈ Error during invocation:  Error: Error in Photon: 
Error: Photon binary for current platform darwin could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
  platforms = ["native", "linux-glibc-libssl1.0.2", "darwin"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `darwin`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at NodeEngine.getPrismaPath (/Users/s7au/prisma-examples/deployment-platforms/netlify/lambda/index.js:1:136638)
    at o.<anonymous> (/Users/s7au/prisma-examples/deployment-platforms/netlify/lambda/index.js:1:2370)
    at Generator.throw (<anonymous>)
    at o (/Users/s7au/prisma-examples/deployment-platforms/netlify/lambda/index.js:1:1573)
```

Is this a bug or am I doing something incorrectly?

**Comment by janpio** [comment]
Create a new one please - much easier to keep stuff independent. Thanks.

**Comment by s7au** [comment]
Moved new question two #625
