### ISSUE TITLE
Bring your own ID fails

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#62]
Creates the data in mutation but fails afterwards

Reproduction
https://github.com/divyenduz/p2-byoi

**Comment by divyenduz** [comment]
Notes: The [error log](https://github.com/divyenduz/p2-byoi/blob/master/error.log) shows that mutation is run twice, and the record in indeed created. This might be a Photon issue.

**Comment by mavilein** [comment]
Fixed in latest `alpha`.
