### ISSUE TITLE
Increase heap size of the generate compilation process

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#621]
Alternate continuation of https://github.com/prisma/prisma2/issues/254

The scope of the #611 (which was to be the next step in #254) is big enough that we want to tackle that after https://github.com/prisma/photonjs/issues/238

This issue offers an alternative short term solution to unblock people from #254 is to increase the heap size of the generate process that runs the TS compiler.

**Comment by williamluke4** [comment]
Will this make it in time for Preview 14?

**Comment by divyenduz** [comment]
It is targeted for Preview 14 yes but preview 14 lands on 10th October (because we are experimenting with 2 week sprints)

**Comment by timsuchanek** [comment]
Released in the latest preview. We increased the heap size to 2048 mb. Please let us know, if that already helps with your bigger schemas 🙏

**Comment by williamluke4** [comment]
Hi @timsuchanek, I just tried again using `Preview 14` but I'm still receiving the error `spawn E2BIG`.
The Schema that I'm trying to introspect is running on a Heroku Postgres DB (140 Tables, 8.34 MB)
```
ERROR  Introspection failed:
Error: Command failed with exit code 7 (E2BIG): /home/will/.nvm/versions/node/v1
1.15.0/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf_
to_dml 
```

**Comment by williamluke4** [comment]
Let me know if there is any additional info that I can provide

**Comment by williamluke4** [comment]
`Preview 14.1` Yields the same result.
After doing some digging through the output I have found various issues such as 
```
"documentation": "Field name normalization failed because of a conflicting field name."
```
```
"documentation": "Field name normalization failed because of a conflicting field name.\\nCould not auto-generate backwards relation field, field name would be ambiguous.\\nPlease specify the name of this field and the name of the relation manually.\\nIt references PropertyAccess.nearestInternationalAirport."
```
 I don't know if these are a symptom or a cause of the error?

**Comment by divyenduz** [comment]
We increased this further to 8096 here: https://github.com/prisma/prisma2/commit/e04d81be1b0a2495d33a80bec24177e80a310ec8

Closing this issue. Please ping me if you think that this issue should not be closed. 

Note that this is a temporary fix to unblock users, the proper fix is tracked here: https://github.com/prisma/prisma2/issues/611
