### ISSUE TITLE
[Mac] "Photon binary for current platform darwin could not be found" when calling typescript netlify function

### ISSUE THREAD

**Issue by s7au** [prisma/prisma2#625]
(Follow up to https://github.com/prisma/prisma2/issues/619)

I took the deployment/platform starter code and:

- renamed the index.js file to index.ts
- added the relevant typescript dependencies to package.json
- modified the netlify.toml file to get functions from "lambda/-"
- added a "build:lambda": "netlify-lambda build functions" to the package.json scripts (ran this manually for now to build lambda folder)
- When I try to hit the endpoint I get the following error:
```
Request from ::1: GET /.netlify/functions/index
Response with status 500 in 85 ms.
◈ Error during invocation:  Error: Error in Photon: 
Error: Photon binary for current platform darwin could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
  platforms = ["native", "linux-glibc-libssl1.0.2", "darwin"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `darwin`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at NodeEngine.getPrismaPath (/Users/s7au/prisma-examples/deployment-platforms/netlify/lambda/index.js:1:136638)
    at o.<anonymous> (/Users/s7au/prisma-examples/deployment-platforms/netlify/lambda/index.js:1:2370)
    at Generator.throw (<anonymous>)
    at o (/Users/s7au/prisma-examples/deployment-platforms/netlify/lambda/index.js:1:1573)
```
Is this a bug or am I doing something incorrectly?
EDIT: this isn't specific to typescript. The issue occurs even if it's index.js

**Comment by divyenduz** [comment]
@s7au Can you please share a GH repo that shows this behavior? I am unable to repro this following the steps you mentioned.

**Comment by s7au** [comment]
@divyenduz here you go:
https://github.com/s7au/prisma2-netlify-lambda-test

**Comment by divyenduz** [comment]
@s7au can you also please mention the steps I need to take to reproduce with this repo?

**Comment by s7au** [comment]
@divyenduz 
I think I set it up so all that's needed is to do an npm install and then npm run dev.
Then navigate to localhost:8888

**Comment by divyenduz** [comment]
Thanks for the detailed reproduction 🙏 

I am able to reproduce your repro with `npm install` and `npm run dev`. 

Observation, we only download 1 binary with this config, it should download `darwin`: 
<img width="1451" alt="CleanShot 2019-09-30 at 16 56 58@2x" src="https://user-images.githubusercontent.com/746482/65890650-7e522d80-e3a3-11e9-9ded-4caa2c6b92db.png">

This is a regression. I also reproduced this with preview 13 and the latest alpha.

**Comment by s7au** [comment]
@divyenduz as a side node, even making this modification to the schema.prisma file:
```
generator photon {
  provider  = "photonjs"
  platforms = ["native", "linux-glibc-libssl1.0.2", "darwin"]
}
```
The error persists.
I also see see this:
```
Generating Photon.js Client to /Users/s7au/prisma-examples/deployment-platforms/netlify/node_modules/@generated/photon
> Downloading linux-glibc-libssl1.0.2 and darwin and darwin binaries [====================] 100%
```

**Comment by s7au** [comment]
Replacing the alternative.js path in index.js gets it to work but it's not exactly a workaround.

**Comment by timsuchanek** [comment]
In `netlify dev` the reason that the binary can't be found, is that netlify creates a new file `./lambda/index.js`, without copying the assets, in our case the binary over.

That looks like a problem Netlify needs to fix in the dev command and which we don't have much control over.

**Comment by s7au** [comment]
@timsuchanek So actually it runs netlify-lambda which creates the .js file inside the lambda folder. Pathing for imports does not seem to break for other .ts files I have compiled with netlify-lambda so I am inclined to believe copying assets is not required. Also getPrismaPath assumes the binary files are in the '/' directory so not sure if copying assets would help either.

**Comment by peterp** [comment]
We're not using `netlify-lambda` in Hammerframework. From what I understand `netlify-lambda` uses webpack to bundle and package the JS files related to a lambda function.

I would be surprised if it was able to include the binary.

I think `zip-it-and-ship-it` was created as a way to circumvent the limitations of netlify-lambda.

**Comment by s7au** [comment]
Yup my workaround was to compile typescript separately and then place everything in a separate folder for `zip-it-and-ship-it`. Had to manually copy the generated folders over and fix some pathing issues in the index file. Not sure what can be done to make it more intuitive.

**Comment by s7au** [comment]
I'm going to close this as this ticket on its own is not really actionable.

**Comment by seawatts** [comment]
I am having the same issue in preview017. Which claims to fix the issue because of the facade pattern.

**Comment by pantharshit00** [comment]
@seawatts Can you please share your code? Binary names has changed so it might be possible that you schema still has the outdated names.

**Comment by seawatts** [comment]
Replied in #952
