### ISSUE TITLE
"Warning! Please try installing Prisma 2 CLI again with the `--unsafe-perm` option."

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#631]
Installing prisma2 on some Ubuntu systems (like the hosted agents from Azure Pipelines) gives you this output when using `npm install -g prisma2`:

```
/usr/local/bin/prisma2 -> /usr/local/lib/node_modules/prisma2/build/index.js

> prisma2@2.0.0-preview-13 install /usr/local/lib/node_modules/prisma2
> node download-build/index.js || echo ""

> Warning! Please try installing Prisma 2 CLI again with the `--unsafe-perm` option.
> Example: `npm i -g --unsafe-perm prisma2`
+ prisma2@2.0.0-preview-13
added 1 package from 1 contributor in 1.365s
prisma2@2.0.0-preview-13, binary version: 14576370b55d5152d9cb90f4f509bfa56760dbbd
```

Is this a prisma2 or npm thing?
Is this normal for users of Ubuntu?
What does it mean exactly? The process returned without an error, although it has this warning message.

**Comment by lboecker** [comment]
> Is this a prisma2 or npm thing?

It's an npm thing.

> Is this normal for users of Ubuntu?

Nope.

> What does it mean exactly.

When you `npm install` a package as root, npm switches to a user with lower privileges before executing the preinstall and postinstall scripts. When you install a package with `--unsafe-perm`, the scripts are executed with root privileges.

I think in this case it means that the postinstall script that downloads query-engine and migration-engine can't write the files to disk because the user npm switched to can't write to the global node_modules folder.

**Comment by janpio** [comment]
Thanks for the explanation @lboecker. 
Is there a way to handle this better than to have this pretty easy to miss warning by npm?

**Comment by lboecker** [comment]
I don't think there's a better way to handle this. If you want to install prisma2 globally you need the post-install script to have root privileges, and that's what `--unsafe-perm` is for.

I do agree with you though that the exit code should reflect that something went wrong. See https://github.com/prisma/photonjs/blob/master/packages/fetch-engine/src/download.ts#L127-L132

**Comment by janpio** [comment]
Ohhh, that _is_ coming from Prisma/Photon - I somehow couldn't find it using code search on Github.

Thanks - then this is a improvement request to make this fail properly with a matching exit code.

**Comment by divyenduz** [comment]
This is also our current recommendation in the upcoming errors spec: https://github.com/prisma/specs/tree/spec_errors/errors#common

Subjected to review but IMO this is a safe enough fallback when the `npm` permissions are messed up due to being `root` or if they are messed up in any other way.
