### ISSUE TITLE
How to resolve ambiguous relationship in prisma2 datamodel?

### ISSUE THREAD

**Issue by kingRayhan** [prisma/prisma2#633]
How to fix this ambiguous relationship in prisma2 datamodel?

![image](https://user-images.githubusercontent.com/7611746/65831937-77161b80-e2e0-11e9-9334-2521bd80ae70.png)

When I hover over on the red dotted error I got this
`Ambiguous relation detected and then Named relations require an opposite field errors get me here.`

**Comment by imVinayPandya** [comment]
i am having same issue

**Comment by divyenduz** [comment]
You need to disambiguate the relations with the `@relation` directive, it is documented here: https://github.com/prisma/prisma2/blob/master/docs/relations.md#the-relation-attribute

Please let me know if this solved the issue for you.

**Comment by imVinayPandya** [comment]
I got this error:

![prisma_error](https://user-images.githubusercontent.com/5011197/65936358-008d3100-e43a-11e9-8ebf-9e000ada1589.png)

**Comment by divyenduz** [comment]
@imVinayPandya @kingRayhan can you please share your whole schema file and does it face an error in vscode from the extension or with lift save or both?

**Comment by imVinayPandya** [comment]
@divyenduz  Here is my schema 
```

model User {
  id          String  @default(cuid()) @id @unique
  first_name  String
  last_name   String?
  password    String
  last_login  DateTime?
  created_by  User    @relation(name: "createdByUserId")
  updated_by  User    @relation(name: "updatedByUserId")
  family_head User    @relation(name: "familyHeadId")
  // society_id  Society

  is_active  Boolean? @default(true)
  is_deleted Boolean? @default(false)
  created_at DateTime @default(now())
  updated_at DateTime @default(now())
  
  contact_details ContactDetails[] @relation(name: "ContactDetailsByUser")
  // resources       Resources[] @relation(name: "ResourcesCreatedUpdatedById")
  // posts Post[]
}
```

**Prisma2 Version:**
prisma2@2.0.0-preview-13, binary version: 14576370b55d5152d9cb90f4f509bfa56760dbbd

and here is the screenshot of error, when i am running **prisma2 dev** command in terminal.

![Screenshot from 2019-10-09 12-30-33](https://user-images.githubusercontent.com/5011197/66458584-bc7cda80-ea90-11e9-9e2c-6269a65b2a86.png)

**Comment by divyenduz** [comment]
@imVinayPandya You need to provide the opposite field, like

```
model User {
  id          String  @default(cuid()) @id @unique
  first_name  String
  last_name   String?
  password    String
  last_login  DateTime?
  created User @relation(name: "createdByUserId")
  created_by  User    @relation(name: "createdByUserId")

  updated User @relation(name: "updatedByUserId")
  updated_by  User    @relation(name: "updatedByUserId")

  family_head_relation @relation(name: "familyHeadId")
  family_head User    @relation(name: "familyHeadId")
  // society_id  Society

  is_active  Boolean? @default(true)
  is_deleted Boolean? @default(false)
  created_at DateTime @default(now())
  updated_at DateTime @default(now())
  
  contact_details ContactDetails[] @relation(name: "ContactDetailsByUser")
  // resources       Resources[] @relation(name: "ResourcesCreatedUpdatedById")
  // posts Post[]
}
```

But right now it failed with https://github.com/prisma/lift/issues/164 for me. I marked it as a potential candidate for the next sprint.

**Comment by divyenduz** [comment]
Created a separate issue to track the DX of resolving relation ambiguity here: https://github.com/prisma/prisma2/issues/704

**Comment by divyenduz** [comment]
@imVinayPandya btw just curious, is that an actual schema that you use in an actual application? Looks really interesting, if possible, we would love to know more about the whole application/schema? Please join our slack at https://slack.prisma.io, my username there is `divyenduz`

**Comment by imVinayPandya** [comment]
Yes it is real word application, i can't share you the whole schema but may be i can give you enough fields in schema to replicate the issues. I have joined you slack team and sent you a message in person.

**Comment by deibeljc** [comment]
For others that might stumble into this and struggle to understand the solution like I did, here is a simple working solution of the originally stated problem. Link to slack thread: https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0/thread/CKQTGR6T0-1569769694.226900 

```
model User {
    id        String @default(cuid()) @id
    name      String
    posts     Post[] @relation(name: "UserPosts")
    bookmarks Post[] @relation(name: "UserBookmarks")
}

model Post {
    id     String @default(cuid()) @id
    title  String
    author User? @relation(name: "UserPosts")
    bookmarkedBy User? @relation(name: "UserBookmarks")
}
```

**Comment by lizkane222** [comment]
@deibeljc I'm struggling to open that Slack thread, but I'm running into the same issue.

`generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mongodb"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}


model profilephoto {
  id                      String              @id @default(auto()) @map("_id") @db.ObjectId
  v                       Int                 @map("__v")
  alt_description         String
  blur_hash               String
  color                   String
  height                  Int
  id_                     String              @map("id")
  links                   ProfilephotoLinks[]
  links_download          String
  links_download_location String
  links_html              String
  links_self              String
  urls                    ProfilephotoUrls[]
  urls_full               String
  urls_raw                String
  urls_regular            String
  urls_small              String
  urls_small_s3           String
  urls_thumb              String
  users                   user[]             @relation(name:"UserProfilePhotos")
  width                   Int
}

model segmenter {
  id            String      @id @default(auto()) @map("_id") @db.ObjectId
  v             Int         @map("__v")
  createdAt     DateTime    @db.Date
  userId        String      @map("id")
  firstName     String
  internalTeam  String
  jobRole       String?
  lastName      String
  myUsers       user[]      @relation(name:"segmenterusers")      
  profilephoto  String
  phoneNumber   String?
  pronouns      String?
  region        String?
  segmentEmail  String
  slackName     String
  team          String
  twilioEmail   String
  updatedAt     DateTime @db.Date
  workspaceId   String?
  workspaceSlug String
}


model user {
  id                        String        @id @default(auto()) @map("_id") @db.ObjectId
  v                         Int?          @map("__v")
  anonymousId               Json?
  createdAt                 DateTime?     @db.Date
  email                     String
  firstName                 String
  lastName                  String
  phoneNumber               String
  profilePhoto              user[]        @relation(name:"UserProfilePhotos")
  segmenters                segmenter[]   @relation(name:"segmenterusers")
  traits                    Json?
  updatedAt                 DateTime      @db.Date
  userId                    String        @unique @map("id")
  username                  String
}
`
![Screen Shot 2023-06-02 at 6 10 59 PM](https://github.com/prisma/prisma/assets/68755692/e8d5e2e7-9089-4c20-abf2-757d30a7388b)

**Comment by tylermcrobert** [comment]
> For others that might stumble into this and struggle to understand the solution like I did, here is a simple working solution of the originally stated problem. Link to slack thread: https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0/thread/CKQTGR6T0-1569769694.226900
> 
> ```
> model User {
>     id        String @default(cuid()) @id
>     name      String
>     posts     Post[] @relation(name: "UserPosts")
>     bookmarks Post[] @relation(name: "UserBookmarks")
> }
> 
> model Post {
>     id     String @default(cuid()) @id
>     title  String
>     author User? @relation(name: "UserPosts")
>     bookmarkedBy User? @relation(name: "UserBookmarks")
> }
> ```

I don't know what has changed since this is posted, but this now creates an error because it'll duplicate userID on autosave

```
model User {
  id        String @id @default(cuid())
  name      String
  posts     Post[] @relation(name: "UserPosts")
  bookmarks Post[] @relation(name: "UserBookmarks")
}

model Post {
  id           String  @id @default(cuid())
  title        String
  author       User?   @relation(name: "UserPosts", fields: [userId], references: [id])
  bookmarkedBy User?   @relation(name: "UserBookmarks", fields: [userId], references: [id])
  userId       String?
  userId       String?
}
```

With the error: `Field "userId" is already defined on model "Post".`

**Comment by janpio** [comment]
Yes, that is intentional. Both relations need a relation scalar field to hold the foreign key value - and Prisma can not decide on the names for you so just goes with an autogenerated one. Rename one of these (and the respective use in `fields`) and you should be good to go.
