### ISSUE TITLE
The postinstall command (prisma2 generate) fails on Windows, but works fine on Mac

### ISSUE THREAD

**Issue by JeremieLeblanc** [prisma/prisma2#64]
I installed the SQLite Graphql Boilerplate from the command line and everything works fine until I do the "npm install" which triggers the postinstall script "prisma2 generate".
On Mac I do the exact same with no issues but on Windows 10 I get this error:

Error: write EPIPE
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-graphql@1.0.0 postinstall: 'prisma2 generate'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-graphql@1.0.0 postinstall script.

**Comment by pantharshit00** [comment]
Closing as a duplicate of #4
