### ISSUE TITLE
`prisma2 init` shortly shows `yarn install` stuff

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#642]
![yarn_install](https://user-images.githubusercontent.com/183673/65871192-2b19b400-e37e-11e9-8555-1322b2628707.gif)

(Very possible this is a Windows only thing, ran this in `cmd.exe` - I have never seen this before preview-13 though)

`prisma2@2.0.0-preview-13.1, binary version: 14576370b55d5152d9cb90f4f509bfa56760dbbd`

**Comment by janpio** [comment]
Depending on selection during `init` also shows other stuff:

```
C:\Users\Jan\Documents\throwaway>prisma2 init hotfix4

Preparing your starter kit: GraphQL API (+ Auth)


Preparing your starter kit: GraphQL API (+ Auth)

  Downloading the starter kit from GitHub ...
  Extracting content to ./ ...
  Installing dependencies with: `npm install` ...
{
  command: '"C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\prisma2\\build\\index.js" tmp-prepare'
}
{
  command: '"C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\prisma2\\build\\index.js" tm
 SUCCESS  Prisma is connected to your database at file:dev.db
...
```

![image](https://user-images.githubusercontent.com/183673/65871353-7d5ad500-e37e-11e9-8494-db1e5270737b.png)

**Comment by divyenduz** [comment]
Just spoke to Tim about this, it is residue logging that would be removed.

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Can not reproduce any more in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`.
