### ISSUE TITLE
`prisma2 dev` stacktrace output detail

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#643]
Seems on crash the stacktrace output has `stack backtrace:` at the beginning and the end currently:

![image](https://user-images.githubusercontent.com/183673/65871602-0f62dd80-e37f-11e9-8c1f-93f42ec1337b.png)
![image](https://user-images.githubusercontent.com/183673/65871622-1ab60900-e37f-11e9-90b2-0206643ed1b1.png)

**Comment by nikolasburk** [comment]
I would also like to add additional new lines before and after the stack trace, wdyt?

**Comment by janpio** [comment]
Yes, that would probably make sense as well.

Note that on Linux and macOS the "Please help us improve ..." error reporting modal thing might look a lot different already and be better separated from the stracktrace.

**Comment by divyenduz** [comment]
@pantharshit00 Can you please reproduce this?

**Comment by pantharshit00** [comment]
Unable to reproduce now, it is hard for me to produce that big of a backtrace now as connection issues are handled by our error handling logic and invalid lift steps are also properly handled. 

If I encounter a larger stacktrace like that, I will reopen this.
