### ISSUE TITLE
`npm install` should exit with proper exit code when installation does not fully succeed

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#646]
`npm install` should emit proper exit code when its fails, for example, when it fails to download binaries because of permission issues (See https://github.com/prisma/prisma2/issues/631)

This is probably the related code: 
https://github.com/prisma/photonjs/blob/master/packages/fetch-engine/src/download.ts#L127-L132

**Comment by janpio** [comment]
Another thought here might be that `npm install` should not only fail, but also make sure that no broken `prisma2` stays on the system. Currently `prisma2 -v` works afterwards, but the engines are of course missing. (Maybe that is already solved by failing `npm install`)

**Comment by divyenduz** [comment]
This can be closed, via Tim
