### ISSUE TITLE
Prisma 2 CLI and exit code

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#647]
This issue tracks the exit codes returned by Prisma 2 CLI. For error conditions, it should return a non-zero exit code. 

Related issue: https://github.com/prisma/prisma2/issues/646

**Comment by divyenduz** [comment]
Internal note: Divy makes it actionable by trying it out and finding exact commands where error code doesn't match expectation.

**Comment by janpio** [comment]
Internal note: Failing download of binaries used to create an unexpected exit code.

**Comment by divyenduz** [comment]
Tested most (I think) commands and they seem to emit the proper exit code. Will re-open specific issues if I run into anything.
