### ISSUE TITLE
prisma2 init + Postgres without generating demo script fails

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#654]
Steps to reproduce:

`prisma2 init`, then make the following choices:

1. Blank Project
2. Postgres
3. postgresql://siddhant@localhost:5432/experiments?schema=public
4. Create Postgres schema `public`
5. Typescript
6. Just the Prisma Schema

The process never finishes (nothing is created in the folder either)

Note that on the last step, if you choose `Demo Script`, then everything works just fine.

**Comment by vladano** [comment]
>>Note that on the last step, if you choose Demo Script, then everything works just fine.
I try this on windows 10 x64 version 1803 and this doesen't work!
I got message:
'No example selected'

If I choose:
Blank Project > Postgres > postgresql://postgres:mali2%233.@localhost:5432/test1 > Use existing PostgreSQL schema > public > TypeScript > Just the Prisma schema

This is working.
C:\>prisma2 init

 SUCCESS  Prisma is connected to your database at localhost

┌─ Next steps ────────────────────────────────────────────────────┐
│                                                                                                                                                             │
│   Start Prisma's development mode to enable access to                                                                    │
│   Prisma Studio and watch schema.prisma for changes:                                                                     │
│   $ prisma2 dev                                                                                                                                   
│                                                                                                                                                             
│   Learn more about Prisma 2:                                                                                       
│   https://github.com/prisma/prisma2/                                                                               
│                                                                                                                    
│   If you encounter any issues, please report them here:                                                            
│   https://github.com/prisma/prisma2/issues/new                                                                     
│                                                                                                                    
└─────────────────────────────────────────────────────────────┘

**Comment by divyenduz** [comment]
@madebysid Spoke to Sid, he will check on the latest and try again.

**Comment by madebysid** [comment]
Just tested on `prisma2@2.0.0-alpha.224`, and this seems to be fixed there.

@vladano Perhaps try updating as well (`npm i -g prisma2@alpha`) :)
