### ISSUE TITLE
prisma2 bugs on windows 10 x64 platform

### ISSUE THREAD

**Issue by vladano** [prisma/prisma2#655]
Today I try following:
Uninstall old version:
npm uninstall -g prisma2 
Install new version:
npm install -g prisma2@2.0.0-preview-13.2

After that I tried the following cases:
1.
prisma2 init prisma-sqlite1 > Blank project > SQLite > Photon + Lift > JavaScript/TypeScript > Demo script -> No example selected - Not working
2.
prisma2 init prisma-sqlite1 > Blank project > SQLite > Photon + Lift > JavaScript/TypeScript > Prisma Schema -> OK
3.
prisma2 init prisma-sqlite2 > Blank project > PostgreSQL > URL: postgresql://postgres:mali2%233.@localhost:5432/test1 > Create new PostgreSQL schema  > Name: mydbschema > TypeScript > Demo script -> No example selected - Not working
4.
prisma2 init prisma-sqlite2 > Blank project > PostgreSQL > URL: postgresql://postgres:mali2%233.@localhost:5432/test1 > Use existing PostgreSQL schema > public > TypeScript > Just the Prisma schema -> OK

**Comment by janpio** [comment]
What exactly do you mean by `No example selected`? 
Can you post the error messages you are getting?

**Comment by vladano** [comment]
Hi,
I repeat case number 1.
This is output from cmd.exe command prompt on Windows
---------------------------------------------------------
C:\>prisma2 init prisma-sqlite1

No example selected
---------------------------------------------------------
node.exe process 
"C:\Users\vladan.obradovic\AppData\Roaming\npm\\node_modules\prisma2\build\index.js" init prisma-sqlite1
is waiting indefinitely, with output message "No example selected" on cmd.exe command prompt window.

**Comment by vladano** [comment]
Exact running process is (two '\\' sign between 'npm\\node_modules')
node 'C:\Users\vladan.obradovic\AppData\Roaming\npm\\node_modules\prisma2\build\index.js'

**Comment by janpio** [comment]
Oh wow, that is a new one as far as I know.

What is the last thing you see before "No example selected" appears?
How did you find out which file the node process is running? (just curious)

**Comment by vladano** [comment]
>>How did you find out which file the node process is running? (just curious)
Right click on taskbar > Task manager >Details > Command line (column)
If you don't see column "Command line", use right click on header on Details tab and choose "Select columns". Then you can select with check boxes, what columns you will see inside Details tab.  

For case number 3, this is output, screen by screen
C:\>prisma2 init prisma-sqlite1

  Get started with a blank project or a starter kit.
  Starter kits provide ready-made setups for various use cases.

┌─ Languages for starter kits ───────────────────────────────────────────┐
│                                                                                                                    
│ > Blank project  Supports introspecting your existing DB                                                           
│   Starter Kit    Sample setups for GraphQL, REST, gRPC, ...                                                        

┌─ Supported databases ──────────────────────────────────────────────┐
│                                                                                                                    
│   SQLite         Easiest to set up                                                                                 
│   MySQL          Requires running a MySQL database                                                                 
│ > PostgreSQL     Requires running a PostgreSQL database                                                            
│   MongoDB        (Coming soon)                                                                                     

┌─ PostgreSQL database credentials ───────────────────────────────────────┐
│                                                                                                                    
│   Host: localhost                                                                                                  
│   Port: 5432                                                                                                       
│   User: postgres                                                                                                   
│   Password: mali2%233.                                                                                             
│   Database: test1                                                                                                  
│   Schema (optional):                                                                                               
│   [ ] Use SSL                                                                                                      
│                                                                                                                    
├─ PostgreSQL database credentials ───────────────────────────────────────┤
│                                                                                                                    │
│ > URL: postgresql://postgres:mali2%233.@localhost:5432/test1                                                       
│
 SUCCESS  Connected to PostgreSQL database as postgres

Create a new PostgreSQL schema or use an existing one
A PostgreSQL database server can host multiple databases

┌─ Database options ───────────────────────────────────────────┐
│                                                                                                                    
│ > Create new PostgreSQL schema   Start from scratch                                                                
│   Use existing PostgreSQL schema Found 1 schema

┌─ PostgreSQL schema name ───────────────────────────────────┐
│                                                                                                                    │
│ > Name: mydbschema

─ Photon is available in these languages ──────────────────────────┐
│                                                                                                                    
│ > JavaScript                                                                                                       
│   TypeScript                                                                                                       
│   Go (Coming soon)                                                                                                 │

┌──────────────────────────────────────────────────────┐
│                                                                                                                    
│ > Demo script              Simple script with API examples                                                         
│   Just the Prisma schema   Most minimal setup                                                                      

No example selected

After output message "No example selected" node process is stuck.

**Comment by vladano** [comment]
NOTE:
I forgot to mention, all of this happened when I run these different cases from my computer through the corporate firewall / proxy.
When I try this case from my home computer (win 10 x64):
prisma2 init prisma-sqlite1 > Blank project > SQLite > Photon + Lift > JavaScript/TypeScript > Demo script >
I got following output message:

 **SUCCESS  The prisma-sqlite1 directory was created!
 SUCCESS  Prisma is connected to your database at file:dev.db**

┌─ Next steps ────────────────────────────────────────────────
│
│   Navigate into the project directory:
│   $ cd prisma-sqlite1
│
│   Start Prisma's development mode to enable access to
│   Prisma Studio and watch schema.prisma for changes:
│   $ prisma2 dev
│
│   Start the REST API server (in a new terminal window/tab):
│   $ npm start
│
│   Learn more about Prisma 2:
│   https://github.com/prisma/prisma2/
│
│   If you encounter any issues, please report them here:
│   https://github.com/prisma/prisma-examples/issues/new

It seems its working fine :)
Sorry, my mistake, but error when you behind corporate firewall / proxy is very strange :(

**Comment by janpio** [comment]
Oh, we are very interested in figuring this out as well! I reopened the issue, it would be super awesome if you could help us learn more here.

Can you uninstall and install `prisma2` again in that environment and paste the full install output? Also, can you maybe tell us a bit about the proxy setup and what does or does not work on there?
