### ISSUE TITLE
`prisma2 studio`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#657]
It would be nice to have a CLI command to start Studio out of the context of Watchmode (`prisma2 dev`), so without any possible side effects of migration, the `dev` UI complications and so on.

Possible output:
```
$ prisma2 studio
Prisma Studio is now available at http://localhost:5555/
Ctrl + C to exit

^C
$ 
```

Notes:
- If you want to get fancy, it could use https://www.npmjs.com/package/open to automatically open the URL in the default browser as well (as this command is explicitly about using Studio, so this matches the user's expectation).
- As this command is a first experiment, it should probably not yet be surfaced in any help commands, release notes or similar.

**Comment by madebysid** [comment]
This is now available with alpha.266

**Comment by tvvignesh** [comment]
@madebysid You may want to add this to the cli help as well - that is, when you type `prisma2` it does not show studio as a possible command. Just bumped into this issue to figure it out.

**Comment by pantharshit00** [comment]
@tvvignesh Can you please open an issue about this 🙏 ?
