### ISSUE TITLE
postgresql error for "record does not exist"

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma2#660]
Hi!.
When I execute the following query:
```graphql
query{
  user(
    id:"ck18xsqc00005v4wcjlwipch"
  ){
    id
    name
   }
}
```
If the data does not exist, I will always get an error:
```js
Record does not exist
```
Why ? It shouldn't be an error, it should return `null` or `undefined`.
My database is postgresql.

**Comment by malekjaroslav** [comment]
I think it was already discussed somewhere, nevertheless it makes sense for it to be an error. You are requesting an entity that does not exist and returning undefined would not match the return type (different with arrays where empty array can be returned). You can set how your client library (like Apollo) behaves when error is returned.

**Comment by pantharshit00** [comment]
Hi,

You point is valid but it is currently the indented behaviour which is being discussed here: https://github.com/prisma/photonjs/issues/89#issuecomment-512832211

Feel free to leave your comments there. 

I will be closing this as a duplicate.
