### ISSUE TITLE
Prisma Studio in a docker container creates non-fatal errors when starting up.

### ISSUE THREAD

**Issue by CaptainChemist** [prisma/prisma2#662]
When I run React Studio in a docker container, it all runs perfectly fine, but I get the following console logs in my docker-compose. It will repeat this error many many times when starting up. Any idea why this is occurring?

````
prisma      | React will try to recreate this component tree from scratch using the error boundary you provided, App.
prisma      | The above error occurred in the <DevComponent> component:
prisma      |     in DevComponent (created by Context.Consumer)
prisma      |     in Unknown
prisma      |     in App
````

A working demo of this is over at: https://github.com/CaptainChemist/blog-prisma2 . Just build and then start it up to see the errors. This isn't critical because I can still use the studio just fine, but I thought I'd put it here so you guys were aware.

**Comment by janpio** [comment]
@pantharshit00 Please reproduce this and make sure it is not a duplicate - I seem to remember a React error via Docker, but can't find it right now.

**Comment by pantharshit00** [comment]
I was able to reproduce this. This is related to the non TTY terminal issue: #554 

Without the `-it` flag docker runs the machine in a non-interactive terminal environment so our CLI would produce the same errors that produces in Git Bash.

So closing this as a duplication of #554 as fixing that would automatically fix this.

**Comment by codejamninja** [comment]
I made a docker image for introspecting a database and running the prisma2 studio.

https://github.com/codejamninja/docker-prisma-studio
https://hub.docker.com/r/codejamninja/prisma-studio

```sh
docker run -e POSTGRES_URL=postgresql://user:pass@localhost5432/data?schema=data codejamninja/prisma-studio
```
