### ISSUE TITLE
Generate `package.json` alongside Photon

### ISSUE THREAD

**Issue by peterp** [prisma/prisma2#664]
Netlify's zip-it-and-ship-it uses the `package.json`'s `main` and `files` keys to know what needs to be bundled during deployment.

I generate my prisma2 client into a **yarn workspace** with the following in my package.json:
```
{
  "name": "@generated/photon",
  "private": true,
  "version": "0.0.0-generated",
  "files": [
    "runtime/query-engine-linux-glibc-libssl1.0.2",
    "runtime/index.js"
  ],
  "types": "index.d.ts",
  "main": "index.js"
}
```

I then install this yarn workspace package as a dependency of my project which allows everything to bundle correctly.

I think that generating a `package.json` file, and adding the `@geneated/photon` package as a local `file://`-based dependency to a project might make the generated package a bit more standardised and easier to deal with odd edge cases.

- [ ] blocked by https://github.com/netlify/zip-it-and-ship-it/pull/49

**Comment by timsuchanek** [comment]
As we now have the facade package in place, this can be closed 🙂
