### ISSUE TITLE
Instructions in the CLI output should use `npm` not `yarn`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#67]
When providing instructions to the user such as running a npm script, these instructions should be given using `npm` instead of `yarn`. E.g. print `npm run seed` instead of `yarn seed`.

**Comment by divyenduz** [comment]
@nikolasburk Is this still an issue?

**Comment by pantharshit00** [comment]
This is no longer an issue:
![image](https://user-images.githubusercontent.com/22195362/72205674-07512880-34ac-11ea-9534-3739f6b2037a.png)
Closing
