### ISSUE TITLE
Getting error: no such file or directory, mkdir, since prisma2@2.0.0-preview-11

### ISSUE THREAD

**Issue by emolr** [prisma/prisma2#670]
My project is running perfectly with `prisma2@2.0.0-preview-11 dev`.

But when trying to use `prisma2@prisma2@2.0.0-preview-12 - 13.2 dev` the console outputs: 
```
(node:15733) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir
(node:15733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Should i add a folder manually? Run a command?

**Comment by janpio** [comment]
Both `preview-12` and `preview-13` had breaking changes:
https://github.com/prisma/prisma2/releases/tag/2.0.0-preview-12
https://github.com/prisma/prisma2/releases/tag/2.0.0-preview-13

But those should not lead to the error message you are getting - looking into these won't hurt though.

Can you share the full output you are getting (also maybe via a screenshot for context)?

**Comment by emolr** [comment]
Hi @janpio, sure :) 

<img width="759" alt="Screenshot 2019-10-07 at 14 17 00" src="https://user-images.githubusercontent.com/2789549/66310703-29676780-e90d-11e9-9543-65e249cbd6f8.png">

I saw that breaking changes meant that i will need to delete the `_migrations` table in my database. But the error message is very different :)

**Comment by pantharshit00** [comment]
@emolr 

Also, please share your operating system details 🙏 .

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/66311240-a1dd2100-e92b-11e9-8a8e-39babcd70b7f.png)

I am unable to reproduce this. 

Can you please try using a globally installed version?

**Comment by janpio** [comment]
Can you maybe also share your project?

**Comment by emolr** [comment]
Hi again, sorry for the delay. 

I was today able to get `prisma2@2.0.0-preview-13.2` installed and working. 
For some reason i had to install it using `sudo npm install -g --unsafe-perm prisma2@2.0.0-preview-13.2`.

This seems to have fixed this exact issue. 

I'm unsure whether it's a permission issue on my machine or how it's supposed to be installed. 
Tried removing everything node related on my machine, installed nvm and node, but the problem persisted until running with `sudo`.

Thanks for looking into this

**Comment by janpio** [comment]
Thanks, there are indeed permissions problems on some system we are currently still figuring out. Reports like your will help us do that. 

If you encounter this again, please let us know and we will again try to reproduce.

**Comment by emolr** [comment]
SOLVED - I'm just leaving this for others to find. 

This error came because of a hidden folder `.cache/prisma` in the Home directory in MacOS. 
I'm not sure why it was causing later versions of Prisma2 to fail installing, but after deleting it, i could successfully run  `npm i -g prisma2`again. 

But after inspecting the errors in the console, i figured it was missing a path somewhere, so i started looking for Prisma related directories on my system. I don't expect this error to come up again as it can be a relic from one of the very early versions of prisma2 that caused this mismatch.

Looking forward to play around with the latest prisma now!
