### ISSUE TITLE
`init` flow with SQLite is broken

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#673]
The CLI is hanging on the last screen at the `Preparing your database ...` step:

![image](https://user-images.githubusercontent.com/4058327/66296809-acc59080-e8ee-11e9-9e89-0b0d33d9c645.png)

To reproduce, use version `preview-13.2`:

```
prisma2 init graphql-demo
```

Then select:

1. Starter kit
1. TypeScript
1. GraphQL API
1. SQLite

**Comment by janpio** [comment]
Side effect of https://github.com/prisma/prisma2/issues/641

**Comment by nikolasburk** [comment]
This also affects Postgres in exactly the same way (trying to create a new schema through the `init` flow with a starter kit).

**Comment by janpio** [comment]
Turns out this is not reproducible.

**Comment by nikolasburk** [comment]
This was just fixed after I restarted my computer. The issue likely was that there wasn't a free port the CLI could use.

**Comment by janpio** [comment]
Should we create an issue for the "no free ports" thing so we don't forget?
