### ISSUE TITLE
Sometimes it doesn't quit even after pressing ⌃C multiple times

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#676]
I don't think it's my Mac's problem. Does anyone else face this issue? 🙋‍♂️

**Comment by madebysid** [comment]
Hey @deadcoder0904, I think this is a prisma2 CLI issue, so I'm moving it to that repo so that the right people can take a look!

**Comment by janpio** [comment]
What commands do you refer to here @deadcoder0904? I am aware of a few commands where this is actually a problem, but which ones are you talking about here?

**Comment by deadcoder0904** [comment]
I think it was the studio one so `prisma2 dev` I think

**Comment by janpio** [comment]
Ok, we are aware of that, probably because of running generation or similar things. @pantharshit00 will know if we have an existing issue for that.

**Comment by pantharshit00** [comment]
I am not aware of this issue. Can you provide a reproduction 🙂?

**Comment by deadcoder0904** [comment]
Idk how to provide a repro. Maybe ask @janpio @madebysid 

Or try doing `prisma2 dev` & when it's generating then try quitting. Also, it happens at random times, so don't know how I can repro.

**Comment by janpio** [comment]
@pantharshit00 This is one example: https://github.com/prisma/prisma2/issues/675

But I can confirm anecdotally that `prisma2 dev` also not always handles Ctrl+C as expected when regenerating.

**Comment by pantharshit00** [comment]
Marking this one as confirmed as we need to investigate the blocking process issue #675 anyways.

**Comment by divyenduz** [comment]
Also, closing this as a duplicate of https://github.com/prisma/prisma2/issues/650

@deadcoder0904 Please comment here and tag me if you disagree 🙏

**Comment by deadcoder0904** [comment]
Haha, both are opened by me. Idk man. Haven’t touched Prisma since Oct/Nov I think so I’ll let u know when I get back to it :)
