### ISSUE TITLE
`From scratch` TypeScript boilerplate doesn't install dev dependencies so initial seeding fails

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#68]
When running `prisma2 init` and choosing:
- SQLite
- Photon + Lift
- From scratch

The CLI prints:

```
  Here are the next steps to get you started:
    1. Run prisma2 lift save --name init to create a migration.
    2. Run prisma2 lift up to apply the migration.
    3. Run yarn seed to seed the database.
    4. Run yarn start (Runs the default script)
    5. That's it !
```

Step 3 (i.e. running `yarn seed`) fails with:

```
sh: ts-node: command not found
```

`ts-node` is listed in the `devDependencies` in package.json, but the these must still be installed using `npm install`.

**Comment by timsuchanek** [comment]
Fixed in latest version.
