### ISSUE TITLE
`npm install` for project with `prisma2` dependency is missing output on CI

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#680]
When running `npm install` for a project that has a `prisma2` dependency on CI, you do not see information about the binaries being downloaded:

https://janpio.visualstudio.com/prisma2-azureRepro/_build/results?buildId=751&view=logs&j=022b0a5d-2698-5f72-7610-a845972a8b4c&t=e3ad75ef-8c3f-5911-75e3-8878b91eb8ae&l=18

```
> prisma2@2.0.0-preview013.3 install D:\a\1\s\node_modules\prisma2
> node download-build/index.js || echo ""






> script@1.0.0 postinstall D:\a\1\s
> prisma2 generate

Generating Photon.js Client to D:\a\1\s\node_modules\@generated\photon
Done in 3.46s

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN script@1.0.0 No repository field.

added 1 package from 1 contributor and audited 1 package in 13.12s
found 0 vulnerabilities

```

![image](https://user-images.githubusercontent.com/183673/66333025-58de9a00-e936-11e9-8e34-073a86d9f5dc.png)

vs. how it is on a local machine:

![image](https://user-images.githubusercontent.com/183673/66332973-41071600-e936-11e9-9d22-d3a5c9d26fab.png)

This is most probably cause by the "animation" of the progress bar, maybe there is an option to not have that on outputs that do not support it.

**Comment by janpio** [comment]
The problem is also visible on Github Actions check output:
https://github.com/janpio/prisma2-azureRepro/pull/2/checks?check_run_id=250923225

![image](https://user-images.githubusercontent.com/183673/66333440-46b12b80-e937-11e9-87d0-07d51c949d05.png)

(The problem happens on all OS, not only Windows which I am only showing because I could show the local comparison for that easily.)

**Comment by divyenduz** [comment]
@janpio Is this still and issue?

**Comment by janpio** [comment]
Probably not.
