### ISSUE TITLE
`init` flow doesn't show instruction to navigate into new directory

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#684]
I'm on version `prisma2@2.0.0-preview013.3`. I run:

```
prisma2 init test
```

The new folder isn't displayed in the "loading messages"

```
~/Desktop $ prisma2 init test

Preparing your starter kit: GraphQL API

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to ./ ... 
✔  Installing dependencies with: `npm install` ...
✔  Preparing your database ...
```

The second line should be:

```
✔  Extracting content to ./test ... 
```

**Comment by janpio** [comment]
First part of this issue is a duplicate of https://github.com/prisma/prisma2/issues/640
The second one is a new one and valid.

**Comment by pantharshit00** [comment]
I wasn't aware of #640. Thanks!

**Comment by janpio** [comment]
You could edit this one to only contain the new problem and then hide our responses @pantharshit00

**Comment by timsuchanek** [comment]
Fixed in latest preview.

**Comment by janpio** [comment]
Can confirm this is fixed.
