### ISSUE TITLE
Support NO_COLOR env var to strip color from output

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#686]
> An increasing number of command-line software programs output text with ANSI color escape codes by default. While some developers and users obviously prefer seeing these colors, many users don’t. Unfortunately, every new piece of software seems to have a different way of disabling colored text output and some software has no way at all.

https://no-color.org/

**Comment by divyenduz** [comment]
Similar to: https://github.com/prisma/photonjs/issues/195
Specced via https://github.com/prisma/specs/pull/151 i.e. respect `NODE_ENV`

But we should also support `NO_COLOR`

**Comment by timsuchanek** [comment]
This has to be implemented across both in the CLI and in Photon.
The Photon implementation is done in this commit: https://github.com/prisma/photonjs/commit/d0c441db5294061c6e25ecbc414743de2b481491

**Comment by janpio** [comment]
Internal Note: Dropping from current sprint, and picking up later.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
