### ISSUE TITLE
Postgres: A database with that name doesn't exist at xx.xx.xx.xx using @2.0.0-preview013.3

### ISSUE THREAD

**Issue by emolr** [prisma/prisma2#694]
Trying to run `prisma2@2.0.0-preview013.3 dev`

It works fine with v2.0.0-preview-13.2, but when running with v2.0.0-preview013.3 i get this error in the terminal:

<img width="1250" alt="Screenshot 2019-10-09 at 07 48 10" src="https://user-images.githubusercontent.com/2789549/66454788-28e3e380-ea69-11e9-8518-8f43a55eb14e.png">

The dataabse `postgres` is available on the server, thus no problem using a previous version of prisma2.

Note! 
I'm running a postgres database on google cloud.
Running on MacOS latest

Thanks for the great work!

**Comment by janpio** [comment]
To confirm: The exact same setup (postgres on google cloud, running macOS latest) works with `2.0.0-preview-13.2` but not `2.0.0-preview013.3` when running `prisma dev`?

**Comment by christopher-schroer** [comment]
I'm running into the same issue running `prisma2 dev` on ubuntu 19.04 while using `prisma2@2.0.0-preview013.3` with a postgres database provided by Heroku. I was following the instructions on the tutorial linked in the README.md

**Comment by alexwine36** [comment]
Same issue on Windows 10 with `2.0.0-preview013.3`
Running `prisma2 lift save`

**Comment by janpio** [comment]
@christopher-schroer @alexwine36 So you both are experiencing a mistaken error message that a database with a name does not exist, although it does exist, correct?

**Comment by christopher-schroer** [comment]
@janpio yes

**Comment by emolr** [comment]
> To confirm: The exact same setup (postgres on google cloud, running macOS latest) works with `2.0.0-preview-13.2` but not `2.0.0-preview013.3` when running `prisma dev`?

yes, i can confirm this :)

**Comment by pantharshit00** [comment]
I can confirm this regression. I tested on a heroku postgres instance and as reported by @emolr version `2.0.0-preview-13.2` works but the latest version `2.0.0-preview-013.3` doesn't.

I also tested with the latest alpha(`prisma2@2.0.0-alpha.232, binary version: 19ed9db8b704a89eef6fe710fa52c2ad0493443f`) and it also fails

**Comment by divyenduz** [comment]
Internal note: Needs to be discussed from spec's perspective

**Comment by divyenduz** [comment]
The spec part of this issue is tracked here: https://github.com/prisma/specs/issues/244

**Comment by timsuchanek** [comment]
Thanks a lot for reporting. Fixed in latest preview.
