### ISSUE TITLE
prisma2 commands do not recognize environment variables. 

### ISSUE THREAD

**Issue by liamdanielduffy** [prisma/prisma2#70]
Hi,

I have a `project.prisma` file beginning with:

```
datasource db {
  provider = "postgres"
  url      = env("POSTGRES_URL")
}
```

However, when I run either:

`POSTGRES_URL=hello_world prisma2 generate`
or 
`export POSTGRES_URL=hello_world; prisma2 generate`

I get the following errors:
<img width="714" alt="Screen Shot 2019-07-02 at 3 44 27 PM" src="https://user-images.githubusercontent.com/7659261/60504952-4b36ca00-9ce0-11e9-8e75-9c8a241a05fa.png">

---

Additionally, running the commands:

`export POSTGRES_URL=hello_world prisma2 generate`
OR
`export POSTGRES_URL=hello_world prisma2 dev`

Both return with no console output.

**Comment by pantharshit00** [comment]
I can confirm this.

![image](https://user-images.githubusercontent.com/22195362/60507705-60aef280-9ce6-11e9-99e2-ab3a72e08f39.png)

**Comment by ChristianJacobsen** [comment]
I also tried this out with @liamdanielduffy through Slack, and can confirm that this is the case.
This works perfectly for `lift`, but the generator does not read the environment variables.

**Comment by liamdanielduffy** [comment]
In any case, wouldn't it make more sense for the missing environment variables to be a warning, rather than an error?

According to the docs (as of July 3 2019), the output from using the `env()` function in the `project.prisma` file is a photon JS client that references that environment variable in its code. 

From the docs: 

```
datasource pg {
  provider = "postgres"
  url      = env("POSTGRES_URL")
}
```

becomes

```
childProcess.spawn('./query_engine', {
  env: {
    url: process.env.POSTGRES_URL,
  },
})
```

This implies to me that the environment variable is not injected when the photon JS client is created. Rather, the environment variable with the same name must be present at runtime in the environment where the photon JS client is used.

Based on this, why would the lack of an environment variable at the time of photon client generation be a problem?

The environment variable shouldn't be expected in the environment where the photon JS client is being generated, but rather the runtime environment where photon JS client is being used later on.

**Comment by timsuchanek** [comment]
We implemented the first version of a fix in `prisma2@2.0.0-preview-1`.

Please note, that as of now the env vars are already interpolated in generation time, we'll fix that in the coming days.

**Comment by nickreynke** [comment]
I'd like to expand this issue by that the commands also do not recognise a `.env` file (or respectively any environment file that possibly could be used via an extra `--env=XXX.env` option appended to the current command).

I am doing the [tutorial](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#51-save-the-migration-on-the-file-system) and am stuck where I have to run `prisma2 lift save --name 'init'`.

I only have a `schema.prisma`:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}

model User {
  id    String  @id @default(cuid())
  name  String?
  email String  @unique
}
```

And a `.env` file containing `POSTGRES_URL="postgresql://prisma:prisma@localhost:5433/prisma?schema=hello-prisma2"`. (I have a Postgres server running on port `5433` via Docker Compose.)

This is my terminal output:

```shell
➜  prisma2 --version

prisma2@2.0.0-preview-1, binary version: 30a33bde5b1d9f79e0a48491749528da76002e24
```

```shell
➜  prisma2 lift save --name 'init'

Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'loading the connector failed.: DataModelErrors { code: 1001, errors: ["Environment variable not found: POSTGRES_URL."] }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: migration_core::migration_engine::MigrationEngine::init
  10: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  11: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  12: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  13: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: futures::task_impl::std::set
  17: std::thread::local::LocalKey<T>::with
  18: futures::future::Future::wait
  19: jsonrpc_core::io::IoHandler<M>::handle_request_sync
  20: migration_core::rpc_api::RpcApi::handle
  21: migration_engine::main
  22: std::rt::lang_start::{{closure}}
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
  25: std::rt::lang_start_internal
  26: main
```

**Comment by timsuchanek** [comment]
@nickreynke good point! Support for `.env` files has been added to `2.0.0-preview-2`.
We'll resolve this issue in `2.0.0-preview-3`.

**Comment by timsuchanek** [comment]
Update: The desired behavior here is very clear: Env vars should *not* be interpolated in generation time, but always just during runtime of Photon or when CLI commands as lift use it.

There is one exception where env vars are not allowed:
`provider` fields - they determine the output type of the generation and should not be configurable through env vars, as otherwise, these env vars could differ in runtime.

**Comment by timsuchanek** [comment]
A fix will be available on alpha in about 10min.

**Comment by mikaelrss** [comment]
Sorry if I am misunderstanding this but the desired behavior is to have a warning for this case with a `POSTGRES_URL` env var missing instead of an error  right? 

Well I am still getting errors when running `prisma2 generate` without providing the environmentvariable. I am using `prisma2@2.0.0-preview-11`, and my `schema.prisma` looks like this: 
`
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}

generator photonjs {
  provider = "photonjs"
}
`

Getting the following error: 
![image](https://user-images.githubusercontent.com/26043795/64920071-30d69d80-d7b3-11e9-9b99-ae1e2fd2332b.png)

**Comment by pantharshit00** [comment]
Yes, currently it is desired behaviour to throw an error on missing env variables.

We are going to add a default fallback field in the schema: https://github.com/prisma/prisma2/issues/222#issuecomment-518159331

**Comment by AryanJ-NYC** [comment]
I am very oddly getting this error when I try to run a GraphQL query from my frontend.

To recreate
1. go to https://ny-dev-jobs.aryanjabbari21.now.sh/register and try and register any email address (feel free to make it a dummy email address as this is in dev).
2. inspect the console and see:
```bash
fa56f042da5f7702be65db290bd6e047e932bb78.4010973f4a259965f526.js:1 Uncaught (in promise) Error: GraphQL error: 
Invalid `prisma.user.create()` invocation:

error: Environment variable not found: PRISMA_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("PRISMA_URL")
   | 
```
![Screen Shot 2020-03-15 at 2 17 17 AM](https://user-images.githubusercontent.com/8263430/76696547-206c8600-6663-11ea-8eb8-f216344dd1c4.png)

With respect to GraphQL releated packages, I am using:

```json
"dependencies": {
  "@apollo/react-hooks": "^3.1.3",
  "@apollo/react-ssr": "^3.1.3",
  "@prisma/client": "^2.0.0-preview024",
  "apollo-cache-inmemory": "^1.6.5",
  "apollo-client": "^2.6.8",
  "apollo-link-http": "^1.5.16",
  "graphql": "^14.6.0",
  "graphql-iso-date": "^3.6.1",
  "graphql-tag": "^2.10.3",
  "isomorphic-unfetch": "^3.0.0",
  "next": "^9.2.1",
  "nexus": "^0.12.0-rc.13",
  "nexus-prisma": "^0.11.1",
},
"devDependencies": {
  "prisma2": "^2.0.0-preview024",
  "ts-node": "^8.6.2",
},
```

**Comment by janpio** [comment]
Please open a new issue @AryanJ-NYC - we can not debug this here in a closed issue.

**Comment by AryanJ-NYC** [comment]
OK, great! Thanks @janpio!
