### ISSUE TITLE
force users to use node > 10

### ISSUE THREAD

**Issue by wardpeet** [prisma/prisma2#701]
Node 8 will be end of life at the end of 2019. Prisma 2 is still in beta which I suggest we should force prisma2 to be node 10 or higher. We might be even bold and move to node 12 right away depending on when prisma2 is production ready.

We can force this by adding an engine option to the package.json.

More information on Node releases can be found at https://nodejs.org/en/about/releases/

**Comment by timsuchanek** [comment]
We're doing this in the latest version :)
