### ISSUE TITLE
Telemetry: Error report ID

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#705]
After submitting an error report, it would be a nice addition to provide the user with an ID that they can use to communicate stack traces/reports on GH issues/other communication channels with us. 

![image](https://user-images.githubusercontent.com/746482/66490055-dd552800-eab0-11e9-89c9-edb39d92a81f.png)

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.

**Comment by janpio** [comment]
Unfortunately not testable on Windows with https://github.com/prisma/prisma2/issues/617
