### ISSUE TITLE
Schema converter

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#71]
Prisma 2 define a new [Prisma schema file](https://github.com/prisma/prisma2-docs/blob/master/prisma-schema-file.md) that is specifically designed to work with multiple data sources. 

With this change migration from `Graphcool` or `Prisma 1` requires migration of the datamodel file to the Prisma schema file. 

As a par of migration tooling, we should provide a schema converter tool that converts from older schema formats to Prisma schema file. 

This can be exposed via CLI, programmatically, and a side-by-side web UI.

**Comment by janpio** [comment]
We decided against this for now and expect people to be able to use Introspection to get the same or a better result.
