### ISSUE TITLE
I don't think it's a bug, but how can I deleteMany without error?

### ISSUE THREAD

**Issue by xero0001** [prisma/prisma2#714]
Hello. I really love prisma2 as a frontend developer, but I'm not very used to it.
I'm having trouble with deleting data with relations.

this is my model.
```
model Team {
  id    String   @default(cuid()) @id

  name        String
  founder     User?
  memberships Membership[]
}

model Membership {
  id    String   @default(cuid()) @id
  class    String

  owner User
  team  Team
}
```

and this is my Mutation. this deletes memberships related to team, and finally deletes team.

```
t.list.field("deleteTeam", {
  type: "Team",
  nullable: true,
  args: {
    teamid: idArg()
  },
  resolve: async (_, { teamid }, ctx) => {
    const { findMany, deleteMany } = ctx.photon.memberships;
    const results = await findMany({ where: { team: { id: teamid } } });

    if (results.length > 0) {
      const results2 = await deleteMany({
        where: {
          id: { in: results.map(({ id }) => id) }
        }
      });
      return ctx.photon.teams.delete({
        where: {
          id: teamid
        }
      });
    } else {
      return ctx.photon.teams.delete({
        where: {
          id: teamid
        }
      });
    }
  }
});
```

When I tried with this codes, it successfully deletes all related memberships and the team.

But an error comes out from "const results2 = await deleteMany(...)" line.
Error looks like this.

```
{
  "data": {
    "deleteTeam": null
  },
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field Mutation.deleteTeam.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "deleteTeam"
      ]
    }
  ]
}
```

I really couldn't find any method for resolving this.

**Comment by pantharshit00** [comment]
The problem here is that `delete` returns a single `Team` but your schema is expecting you to return a list of teams. That is what is meant by `expected iterable` but you didn't return an iterable(array). I would suggest you make the following change in order to solve this:

```diff
- t.list.field("deleteTeam", {
+ t.field("deleteTeam", {  
```

**Comment by pantharshit00** [comment]
I am going to close this issue. Feel free to comment here if this hasn't been properly addressed.

**Comment by xero0001** [comment]
OMG I was so dumb. Thank you so much!

**Comment by pantharshit00** [comment]
No problems at all! I have personally have done the same thing in past 😅
