### ISSUE TITLE
More inclusive language in docs

### ISSUE THREAD

**Issue by carolstran** [prisma/prisma2#722]
:wave: I noticed that there are a couple of instances of words like "simply" in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading (myself included, hence the issue) - especially if they are facing issues.

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing instances of "simply", "easy", "just", etc. I've been following you all since back in the Graphcool days, so I'm happy to help 😊  

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

**Comment by nikolasburk** [comment]
Hey Carolyn, great to see you here! 😄Thanks so much for pointing this out!

> If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing instances of "simply", "easy", "just", etc. 

Definitely, that would be more than welcome! Otherwise we'll try to incorporate this issue into our next sprint 🙂

**Comment by carolstran** [comment]
Hey @nikolasburk, I can do an initial PR because this is something I'm working on for Hacktoberfest 🎃 I'll try to send it over asap! Thank you for being so receptive 🙏
