### ISSUE TITLE
`init`: Back button is not working

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#723]
If you go through the following flow, the back button is not working.

`prisma2 init` > `Blank Project` > `SQLite` > `Prisma 2 Tools` > `Back`

![image](https://user-images.githubusercontent.com/22195362/66657199-0dd9c500-ec5d-11e9-8ee7-295a05d1c039.png)

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Still reproducible in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
