### ISSUE TITLE
`prisma2 generate` keeps downloading query engine (or at least tells me it does)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#725]
```
C:\Users\Jan\Documents\throwaway\timFriday2  (script@1.0.0)
λ prisma2 generate
> Downloading windows binary for query-engine [====================] 100%

Generating Photon.js to C:\Users\Jan\Documents\throwaway\timFriday2\node_modules\@generated\photon
Done in 2.11s


C:\Users\Jan\Documents\throwaway\timFriday2  (script@1.0.0)
λ prisma2 generate
> Downloading windows binary for query-engine [====================] 100%

Generating Photon.js to C:\Users\Jan\Documents\throwaway\timFriday2\node_modules\@generated\photon
Done in 2.10s


C:\Users\Jan\Documents\throwaway\timFriday2  (script@1.0.0)
λ prisma2 generate
> Downloading windows binary for query-engine [====================] 100%

Generating Photon.js to C:\Users\Jan\Documents\throwaway\timFriday2\node_modules\@generated\photon
Done in 2.17s

```

```
λ prisma2 -v
prisma2@2.0.0-alpha.236, binary version: 188a379c9b8c6650e5812f9bdb7407d7b197692f
```

Please double check this with the released preview @pantharshit00 and see if this also happens on other platforms.

**Comment by pantharshit00** [comment]
Sorry for the late reply, this went off my radar somehow.

I am able to reproduce this with `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483`

![image](https://user-images.githubusercontent.com/22195362/67009387-263c5a80-f109-11e9-8afc-198815bee398.png)

**Comment by rpateld** [comment]
look like similar to this [issues 834](https://github.com/prisma/prisma2/issues/834)

**Comment by divyenduz** [comment]
@janpio @pantharshit00 is this still an issue?

**Comment by divyenduz** [comment]
Yes it is, it is using cache but showing the download progress, maybe we should not show the progress when cache is being used. Marking this as a candidate.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
