### ISSUE TITLE
`init` flow only offers introspection option and terminates early when using a new PostgreSQL DB

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#73]
I want to use `prisma2 init` with a new and empty PostgreSQL database. After I selected `Postgres` in the first step of the flow, I enter the credentials:

<img width="941" alt="Screen Shot 2019-07-02 at 15 32 22" src="https://user-images.githubusercontent.com/4058327/60517023-36a60200-9cdf-11e9-9494-4cb0db1b2ad1.png">

Once connected to the database, the CLI says:

<img width="941" alt="Screen Shot 2019-07-02 at 15 34 58" src="https://user-images.githubusercontent.com/4058327/60517045-43c2f100-9cdf-11e9-923a-0215bf23bbde.png">

When creating a new schema as done in the screenshot, the button `Introspect` should say `Create schema`. 

When I click on `Introspect`, it terminates and creates a schema file that only has the `datasource` configured but it should proceed to the boilerplate selection.

**Comment by alexthegoodman** [comment]
Thank you

**Comment by ManAnRuck** [comment]
same issue

installed with `yarn global add prisma2`

```
prisma2@0.0.124, binary version: 987243ce27251e1c05e83b84363017054686fe17

System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 443.38 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
```

**Comment by ManAnRuck** [comment]
still in version `prisma2@2.0.0-preview-2, binary version: 4f33077038a490e4b2c1c260f109309e4a447181`

---

on `prisma2 lift save --name 'init'` I got this error (if it should somehow be related) https://github.com/prisma/lift/issues/10

**Comment by schickling** [comment]
Will be solved via https://github.com/prisma/prisma2/issues/278

**Comment by Andrew1325** [comment]
When I try `init` it connects to the database but hen just hangs on the introspection.
![Screen Shot 2019-08-19 at 8 32 40 pm](https://user-images.githubusercontent.com/38718635/63259023-af2d4600-c2c0-11e9-9b4b-48db68c477de.png)

It doesn't end, just sits like this until I ctrl-c to get out. Was going all night last night.

Am using a local postgres, new empty database that I can connect to and see in pgAdmin.

**Comment by janpio** [comment]
@Andrew1325 You should create a new issue for this separate problem, here it will be lost and ignored. Much better chance to someone look at it with its separate issue. Thanks.
