### ISSUE TITLE
Can't find database

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#730]
<img width="485" alt="Screen Shot 2019-10-12 at 8 20 15 PM" src="https://user-images.githubusercontent.com/7302317/66705976-c8d19380-ed2d-11e9-8754-d38fdc78ec49.png">

alpha 230 is working but not since alpha 231

**Comment by pantharshit00** [comment]
Hi,

Can you please try this again with the latest version? This issue is a duplicate of https://github.com/prisma/prisma2/issues/711 and it was already fixed. Please report here if this has been fixed for you in the latest alpha.

**Comment by yovanoc** [comment]
No, alpha 240 is not fixing

**Comment by pantharshit00** [comment]
Ah ok, the original screenshot is suggesting that it is related to a database which already exists not being identified by Prisma. 

Can you please provide some additional details like exact steps to reproduce this? That would help a ton!

**Comment by yovanoc** [comment]
Yes that's right, but in my project when i'm importing photon is it working, but i'm doing a `prisma2 dev` for quick editing data it tells me that it doesn't find my database

**Comment by malekjaroslav** [comment]
I happens to me as well. It is a remote DB an Lift does not recognise it...Migrations therefore stopped working :/

**Comment by pantharshit00** [comment]
I can confirm this with a remote digitalocean instance.

![image](https://user-images.githubusercontent.com/22195362/66854552-2a4c6900-ef9f-11e9-90b5-ea02fd624724.png)


Database postgres already exists on this server.

**Comment by divyenduz** [comment]
@pantharshit00 Can you still reproduce this?

**Comment by pantharshit00** [comment]
Unable to reproduce this now with `prisma2@2.0.0-alpha.520, binary version: 89e9a32e88c127726a79da89b638c4bab2840095`. 

Going to close this, please comment here if this is not fixed for you.
