### ISSUE TITLE
`init`, MySQL/Postgres: Does not recognize exiting database/schema, lets me select exact same database/schema

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#738]
Pasted existing connection string (with database).

After connection succeeded:

![image](https://user-images.githubusercontent.com/183673/66715221-d97f1980-edc0-11e9-855f-9b51230e59e8.png)

Select "Use existing ...": 

![image](https://user-images.githubusercontent.com/183673/66715228-f0257080-edc0-11e9-9fa2-9a2034d872f3.png)

Image 1 tells me the db does not exist, image 2 lets me select the exact same DB (which indeed does exist and is empty).

**Comment by janpio** [comment]
Same problem exists for PostgreSQL:

Manually input DB credentials:
![image](https://user-images.githubusercontent.com/183673/66723885-137f0880-ee1f-11e9-9154-fcc56811dade.png)

Existing schema was not recognized:
![image](https://user-images.githubusercontent.com/183673/66723892-25f94200-ee1f-11e9-9dda-3d7da622013d.png)

But then choosing "Use existing ..." I can select the one that it can't find before:
![image](https://user-images.githubusercontent.com/183673/66723901-40332000-ee1f-11e9-897f-632d9001bb53.png)

**Comment by tomhoule** [comment]
I just tried with the latest preview (`prisma2@2.0.0-preview014.1, binary version: 188a379c9b8c6650e5812f9bdb7407d7b197692f`) and wasn't able to reproduce the bug.

I thought it was assigned externally but I assigned this to myself apparently, since I was working on something that looked similar, so I'll unassign myself from this issue.

**Comment by pantharshit00** [comment]
This issue looks like a duplicate of https://github.com/prisma/prisma2/issues/730

@tomhoule I was able to reproduce this with a remote database.

**Comment by janpio** [comment]
In my testing: MySQL was remote, Postgres was not.

**Comment by janpio** [comment]
With `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483` and `prisma2@2.0.0-alpha.255, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe` I can reproduce this on Windows with a local MySQL 5.7 database. (Enter name of empty DB in credentials screen, directly get error message that it could not be found as seen in first screenshot)

![mysql_empty](https://user-images.githubusercontent.com/183673/67160113-b66ae180-f34d-11e9-8311-cb5e15f1019f.gif)

**Comment by tomhoule** [comment]
I looked into this and I think the database/schema selection is happening through the typescript introspection code - should I try and look into it @timsuchanek ?

**Comment by janpio** [comment]
No, knowing this is coming from Introspection means we will wait until the TS Introspection has been replaced.

**Comment by janpio** [comment]
New introspection has been added, but the problem still exists although the output is a bit different now:

```
C:\Users\Jan\scoop\apps\nvm\current\nodejs\nodejs
λ prisma2 init sdfsdf22df

 SUCCESS  Connected to MySQL database as iv28ppo5xzceyf14

Create a new MySQL database or use an existing one
A MySQL database server can host multiple databases

┌─ Database options ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                                      │
│ > Create new MySQL database      Start from scratch                                                                                                                                  │
│   Use existing MySQL database    Found 2 databases                                                                                                                                   │
│                                                                                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

< Back (Database credentials)
```

```
C:\Users\Jan\scoop\apps\nvm\current\nodejs\nodejs
λ prisma2 init sdfsdf22df

  Select a MySQL database.
  Found 1 empty database and 1 non-empty MySQL database

┌─ Empty databases (Start new project) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                                      │
│ > information_schema                                                                                                                                                                 │
│                                                                                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌─ Non-empty databases (Introspect existing schema) ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                                      │
│   ovoownk5hz1f55is               1 tables, 16 kB                                                                                                                                     │
│                                                                                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
< Back (Database options)
```

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
