### ISSUE TITLE
`init`: Input is not disabled while connecting to database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#739]
While `init` is connecting to a MySQL or Postgres database you can still input additional data (as you can start the connection attempt with [Enter] in any form field and input is still accepted) which is strange and unexcpected.

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Still a problem in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
