### ISSUE TITLE
`init` does not handle case where DB credentials can not create new databases

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#740]
If you try to create a new database when running `init` (for MySQL, might also apply to Postgres) it is possible that your credentials (user + password) can not be used to actually create a new database. This is currently not handled:

![image](https://user-images.githubusercontent.com/183673/66715928-47c7da00-edc9-11e9-956a-92b1c561d8e0.png)

```
C:\Users\Jan\Documents\throwaway>prisma2 init mysqlIntrospectionTest

  Enter the name for the new database
  The database will be created by: iv28ppo5xzceyf14

┌─ MySQL database name ──────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                    │
│ > Name: foo                                                                                                        │
│                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

  Create
 ERROR  Command failed: C:\ProgramData\nvm\v10.16.3\node_modules\prisma2\migration-engine.exe cli --datasource mysql://
iv28ppo5xzceyf14:...@...yhwsb.us-east-1.rds.amazonaws.com:3306/foo --create_database
[2019-10-13T12:51:34Z ERROR migration_engine] Access denied to database 'foo'


 FIX  Make sure you have the correct rights to create the database.
```

If this can be properly recognized, we could show a more explicit error message and suggest better solutions.

**Comment by pantharshit00** [comment]
I think the error spec should be covering this under CLI errors: https://github.com/prisma/specs/tree/master/errors#prisma-cli

**Comment by miyi** [comment]
I'm currently hosting a free-tier Heroku database and have the same issues. Are heroku free-tier postgres databases incompatible with prisma2 cli commands?

**Comment by pantharshit00** [comment]
@miyi This looks like a separate issue to me. Can you please open a new issue for that?

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
