### ISSUE TITLE
Introspection, MySQL: System databases

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#745]
When introspecting a MySQL server you also get the default system databases:

```
┌─ Non-empty databases (Introspect existing schema) ─────────────────────────────────────────────────────────────────┐
│                                                                                                                    │
│   mysql                          31 tables, 2.46 MB                                                                │
│   performance_schema             87 tables, 0kB                                                                    │
│   sys                            1  tables, 16 kB                                                                  │
│                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

![image](https://user-images.githubusercontent.com/183673/66722946-f4c74480-ee13-11e9-9089-449ad5c26ffb.png)

We might want to hide those or handle them differently.

**Comment by pantharshit00** [comment]
What if I actually want to query those? There are many use cases for that. 

I haven't find any database UI that hide those so in my opinion, we are fine showing them.

**Comment by janpio** [comment]
I suggest this is a way where could be better than existing tools, and treating these known tables differently. Maybe they just get a separate category next to empty/non-empty so they are visually separated.

**Comment by janpio** [comment]
Decision: Hide or at least separate them into their own section.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
