### ISSUE TITLE
Document native import/export workflows

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#746]
For all the data sources we support. As we don't have a feature to do export/import.

**Comment by chrisdrackett** [comment]
would this include support for import/export of `NDF`? https://www.prisma.io/docs/prisma-cli-and-configuration/data-import-and-export-jsw9/#normalized-data-format

**Comment by nikolasburk** [comment]
I've the docs for native imports/exports here: https://github.com/prisma/prisma2/tree/master/docs/import-and-export-data

@chrisdrackett For as long as we don't support NDF with the Prisma Framework, you can use the described workflows to import/export your data 🙌
