### ISSUE TITLE
Create architecture diagram for the Prisma Framework internals

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#747]
It's currently difficult to understand what's going on in the internals of the Prisma Framework beyond the API surface area. A few months ago we created a high-level architecture diagram for all the components in the core of the Prisma Framework:

![Prisma](https://user-images.githubusercontent.com/4058327/66741069-f412ca80-ee74-11e9-9b45-832cf0c849a5.png)

It would be great to have something similar again (that's primarily for internal use but also as as foundation for external resources such as docs).

**Comment by mavilein** [comment]
Here is an updated high level view:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/2470881/67669570-72da2e00-f972-11e9-868a-3c7e31d70980.png">

**Comment by mavilein** [comment]
Here is a general architecture diagram that we follow in each of the engines:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/2470881/67669622-94d3b080-f972-11e9-9c7c-5345a02eb9e7.png">

**Comment by janpio** [comment]
Where does this live now?
Is there a raw file that can be adapted?

**Comment by mavilein** [comment]
@janpio :
> Where does this live now?
Nowhere right now. @nikolasburk said he is happy with it. Happy to put it somewhere if we know a good place.

>  Is there a raw file that can be adapted?
I drew it with Monodraw and could share that file.
