### ISSUE TITLE
Docs link 404

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#748]
Probably a minor issue but here we go.

I forgot what it's called but visit https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md & try clicking on **Type definitions** & it won't jump down.

Basically, this URL → https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#type-definitions

I think it should be https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#types although not sure if you guys want a heading on top of it.

**Comment by pantharshit00** [comment]
@deadcoder0904 Would you like to make a PR for this?

**Comment by deadcoder0904** [comment]
Sure but what should I add?

There is another `#types` under `Fields` heading?

**Comment by pantharshit00** [comment]
Change it `Type definitions` to `Types`. Then link it to `https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#types`

**Comment by janpio** [comment]
It looks more like `Type Definitions` section got removed or similar, can you confirm @nikolasburk?

**Comment by deadcoder0904** [comment]
What @janpio said @pantharshit00, that's what I was thinking so wasn't sure what to change if you have a closer look

**Comment by janpio** [comment]
Let's wait what @nikolasburk makes of it - he is the master of our docs and will probably know ✍️

**Comment by nikolasburk** [comment]
Great catch @deadcoder0904 🙌 this was indeed just a leftover from a former section that was called "Type definitions". I actually just fixed it myself, thought that's quicker than going through a PR workflow for this now 🙂
