### ISSUE TITLE
Add a filter to the field of the query

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma2#755]
I want to know if a user is following me, so I do the following:

```js
query{
  post(
    id:"ck1ey7ce70009b7wcrfn8uzmp"
  ){
    id
    title
    author{
      id
      followings(
      	where:{
           id: "ck18xsqc00005v4wcjlwipcho"  // My ID
      	}
      ){
      	id
      	name
      }
    }
    
  }
}
```
It is work in v1, but I found that v2 does not support this.
I got an error:
```js
Unknown argument \"where\" on field \"followings\" of type \"User\".
```
I noticed that first, after, skip are supported, but where is not allowed.

I am looking forward to being able to restore this feature.

**Comment by pantharshit00** [comment]
You need to explicitly enable filtering in your mode. Here is an example:-

```js
const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      filtering: true,
    })
  },
})
```

Adding `filtering: true` to the posts fields in the model would enable relational filters.

If this doesn't help, please share code for your model and maybe your Prisma Schema as well.

**Comment by sessionboy** [comment]
Thank you for your answer and solved my problem.

**Comment by pantharshit00** [comment]
Awesome 🙂 . I am going to close this issue then.

You can open a new issue or comment here if this haven't been properly addressed in some way.
