### ISSUE TITLE
prisma2 convert error (ENAMETOOLONG)

### ISSUE THREAD

**Issue by outerlook** [prisma/prisma2#759]
Was getting the following error when using prisma2 convert in powershell

> Error: Error: Command failed with exit code 38 (ENAMETOOLONG)

for testing, used the following datamodel (prisma1)
```
type Aweoiqewjweojqwjeoijweqoijewiojqeoijeqoiwjeqwiojweqoijeqwoijomwem {
  id: ID! @id
  facebookId: String @unique
  createdAt: DateTime! @createdAt
  updatedAewmqewoiweoiewmoiewqmoiemoiqemoiewmioeqwjmoiwm3213omt: DateTime! @updatedAt
  email: String! @unique
  senha: String!
}
```

got no error, and I pasted this several times till I get this error. 

The error appears after  128 lines of this

**Comment by divyenduz** [comment]
The command prisma2 convert does not exist anymore, we recommend using prisma2 introspect in its place. 

Does this error still exist when using introspect to introspect an existing long model name?

**Comment by divyenduz** [comment]
I am closing this one, please reopen a new issue if the problem persists with introspect.
