### ISSUE TITLE
Querying with findOne on an empty table raises an error

### ISSUE THREAD

**Issue by webnoob** [prisma/prisma2#760]
Let's say I call this:

```ts
const user = await this.photonService
      .users
      .findOne({
        where: {
          username
        }
      })
```
I will get an error as a response:

```
Invalid `.findOne()` invocation in C:\SourceCode\e2e\api\dist\user\user.service.js:21:14

  17 }
  18 async findOne(username) {
  19     const user = await this.photonService
  20         .users
→ 21         .findOne(

Reason: Error in connector: Record does not exist.
 +6121ms
Error:
Invalid `.findOne()` invocation in C:\SourceCode\e2e\api\dist\user\user.service.js:21:14

  17 }
  18 async findOne(username) {
  19     const user = await this.photonService
  20         .users
→ 21         .findOne(

Reason: Error in connector: Record does not exist.
```
I understand it's telling me why it's not returning one but surely this should just return null?

If I use` findMany` instead, I get an empty array as a result which I can work with but throwing an exception doesn't seem right.

I'm on Preview13 with an SQLite DB and windows 10 and just for clarity, this is my schema for this part:

```
model User {
  id String @default(cuid()) @id @unique
  username String @unique
  emailAddress String @unique
  password String
}
```

**Comment by pantharshit00** [comment]
This is expected behaviour right now but we are in the process of changing this behaviour.

Please follow: https://github.com/prisma/photonjs/issues/245
