### ISSUE TITLE
[Platforms] Zeit changed their terminal to something that does not support Raw Mode.

### ISSUE THREAD

**Issue by harrisrobin** [prisma/prisma2#769]
Looks like zeit changed their terminal to something that doesn't support raw mode.

this is a total blocker for deploying prisma2 on Zeit.

![Redacted Image](https://user-images.githubusercontent.com/3880008/66938196-c8c3e300-f00e-11e9-9df1-d856d2eba04a.png)

**Comment by divyenduz** [comment]
@pantharshit00 Please test this one again

**Comment by pantharshit00** [comment]
Unable to reproduce now, I just did a zeit deploy
