### ISSUE TITLE
Can't paste the `Host` in the `init` command for Postgres

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#77]
I can't paste the **Host** when providing my DB credentials. When I paste in the URL from clipboard, it always enters it as a **Port**: https://www.loom.com/share/73eb13028c674da683f6547ebfa0631f

**Comment by pantharshit00** [comment]
I can reproduce this with 2.0.0-alpha.21. Maybe it is specific to your shell or terminal emulator. Which shell are you using?

I am using zsh

**Comment by nikolasburk** [comment]
I think my issue back then indeed was a trailing newline... 😑 I'l close this.
