### ISSUE TITLE
ER diagram from the schema

### ISSUE THREAD

**Issue by email2vimalraj** [prisma/prisma2#772]
Based on the schema file, if we can generate the ER diagram, that would be great value add to share with others.

**Comment by yovanoc** [comment]
Yeah could be very nice :)

**Comment by pantharshit00** [comment]
This was already asked here: https://github.com/prisma/studio/issues/198#issuecomment-517990387


We have plans for integrating not only a diagram but a full schema editor. This requires some effort and we need to figure out how we will handle large schemas so it would definitely take time.


Closing as a duplicate

**Comment by pyros2097** [comment]
There is one now looks interesting,
https://github.com/keonik/prisma-erd-generator
