### ISSUE TITLE
Support for more kinds of join tables

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#773]
From my limited understanding of the migration engine, I gather that we only support a very specific type of join table, where the columns & the table itself are named in a format we recognize. This leads to some popular sample DBs being unusable "out of the box". Examples: Chinook, IMDB.

It would be nice to go over some of these datasets and support more popular ways of managing join tables.

**Comment by pantharshit00** [comment]
We already mention this limitation in our [limitaion.md](https://github.com/prisma/prisma2/blob/master/docs/limitations.md) file. 

This is also somewhat related to https://github.com/prisma/prisma2/issues/175

I think having a dedicated issue is better :)

**Comment by schickling** [comment]
This is addressed via the following two issues:
- https://github.com/prisma/prisma-engine/issues/68
- https://github.com/prisma/prisma-engine/issues/60
