### ISSUE TITLE
`prisma2 dev`: You can still hit `d` to see a diff when you already crashed the migration engine

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#774]
Even after the migration engine crashed and gave a nice stack trace, you can hit `d` to see a diff (and use `d` or `b` go back to the pretty stacktrace):

![prisma2-dev-crash-diff](https://user-images.githubusercontent.com/183673/67039052-e5e8d680-f120-11e9-8d87-f3521595cf64.gif)

**Comment by pantharshit00** [comment]
I can reproduce this but do you think this is a problem.

Maybe seeing the crashing diff is useful in some ways.

**Comment by janpio** [comment]
I am not sure - someone has to take this into consideration and then make a decision. I feel that proper error handling should halt the execution of everything.

**Comment by pantharshit00** [comment]
Adding candidate label so that we can discuss on this

**Comment by janpio** [comment]
Internal note: Removing label because `dev` is currently not something we want to spent time on.

**Comment by timsuchanek** [comment]
As we removed the `prisma2 dev` command, I'm closing this.
