### ISSUE TITLE
`init`: Starter Kit flows only show empty databases

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#775]
By design the Starter Kit flows only show you empty databases to select from. Problem is that this is not clearly communicated and can lead to confusion (at least it did to me). 

It might make more sense to list the non-empty databases as well, but make it explicit that and why they can not be used.

**Comment by pantharshit00** [comment]
I can confirm and would consider this as a bug.

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Still present in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
