### ISSUE TITLE
[Windows] `init`: Shift + Tab does not work

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#776]
You can not use Shift + Tab to go to the _previous_ field, it goes to the _next_ field as if you were using only Tab.

Shift + Tab does work for the normal selection, but not for the form input you do to enter your database credentials for example.

(Tested with `prisma2@2.0.0-alpha.255, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe`)

**Comment by pantharshit00** [comment]
I am able to do `Shift + Tab` on a Mac. 

I can't say for sure on Windows as I don't trust RDP for keyboard input which we are using for windows testing. Mark this as a windows specific issue if you able to reproduce this with `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483` on windows

**Comment by janpio** [comment]
I clarified and edited the title and issue description. If you can reproduce on non-Windows, please remove the specification from the title again.

**Comment by janpio** [comment]
Still exists in
```
λ prisma2 -v
prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038
```

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
