### ISSUE TITLE
`init`, Introspection: Tells me that schema is not empty, does not even exist though

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#777]
When introspecting a Postgres DB for a "Starter Kit" `init` run, I entered database `postgres` and schema `my_db`. Something goes wrong, and the error message tells me that `schema 'postgres' is not empty`. Something is getting confused here.

![image](https://user-images.githubusercontent.com/183673/67051377-310fe300-f13b-11e9-8470-ed37b2164a57.png)

```
C:\Users\Jan\Documents\throwaway>prisma2 init dafasdf3422

 SUCCESS  Connected to PostgreSQL database as postgres

The PostgreSQL schema `postgres` is not empty.
When using a starter kit, you must provide an empty schema.
Create a new PostgreSQL schema or use an empty one.

┌─ Database options ──────────────────────────────────────────────────────┐
│                                                                         │
│ > Create new PostgreSQL schema   Start from scratch                     │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘

< Back (Database credentials)
```

**Comment by pantharshit00** [comment]
I am able to reproduce this.

This occurs when you put the schema in the `Schema(optional)` field in the database credentials form. It is not being used by the cli

**Comment by divyenduz** [comment]
@pantharshit00 can you please quickly re-triage this one?

**Comment by janpio** [comment]
This is currently not reproducible as the database/schema entered in the credentials form is completely ignored. Will have to be retested when this is fixed.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
