### ISSUE TITLE
Query engine: Replace HTTP server with another solution

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#782]
## Current problems

1. Severe Security problem: HTTP server is accessible from host machine and has privileged access to database 🚨 

2. Shows misleading port detection messages on Codesandbox
![image](https://user-images.githubusercontent.com/1567498/66747680-67243d00-ee85-11e9-8470-b8f455c270a4.png)

### Inherent solution

Get rid of HTTP server and come up with another solution (maybe similar to migration engine?).

### Temporary solution

Re 1) Secure HTTP endpoint with a auto-generated secret
Re 2) Use allowlist for HTTP ports on CSB

**Comment by matthewmueller** [comment]
internal note: Do the first 10% to setup the machinery. Create an issue to do the rest later

**Comment by matthewmueller** [comment]
Closing, tracked in other issues
