### ISSUE TITLE
Make it possible to "end to end" download binaries in debug mode 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#785]
For this use case https://github.com/prisma/prisma2/issues/783

Manually setting up debug binaries is very tedious for this. It would be awesome if we can with an environment variable configure CLI to download debug binaries instead of production binaries.

**Comment by janpio** [comment]
> with an environment variable configure CLI

Could you clarify that?

**Comment by divyenduz** [comment]
Internal note: Discuss with Dom and bring up in sprint planning meeting.

**Comment by matthewmueller** [comment]
internal note: Drop for this sprint. Doubles the number of binaries.

**Comment by dpetrick** [comment]
We won't do this. It does not add the benefit you're looking for. This will be achieved by better error handling and error communication, as defined by the errors spec, for example.
