### ISSUE TITLE
`prisma2 convert` adds `@unique` to `@id` fields

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#786]
While this isn't incorrect, this is redundant and shouldn't be a pattern that we should teach our users. Also see: https://github.com/prisma/prisma2/issues/426

**Example**

Prisma 1 datamodel:

```graphql
type User {
  id: ID! @id
  email: String! @unique
  name: String
  posts: [Post!]!
}

type Post {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  published: Boolean! @default(value: false)
  title: String!
  content: String
  author: User!
}
```

Run:

```
cat datamodel.prisma | prisma2 convert > schema.prisma
```

Prisma 2 schema output:

```prisma
model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User
}
```

**Comment by pantharshit00** [comment]
I can confirm this.

**Comment by divyenduz** [comment]
Thanks, we have removed the `prisma2 convert` command in the latest preview, please use the new introspection to work with existing databases. Here are the relevant release notes: https://github.com/prisma/prisma2/releases/tag/2.0.0-preview018
