### ISSUE TITLE
Changing the `datasource.provider` does not crash `prisma2 dev` if it is already running

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#787]
A good way to create a migration engine crash right now is to create an SQLite demo script project, then edit `schema.prisma` from `sqlite` to `postgres`. If you run `prisma2 dev` afterwards, it crashes consistently as it should.

But surprisingly a running `prisma2 dev` does not crash because of that but happily migrates and generates.

**Comment by timsuchanek** [comment]
As we removed the `prisma2 dev` command, I'm closing this.
