### ISSUE TITLE
[Windows] Telemetry prompt does not work in Cmder

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#792]
This is a follow up to https://github.com/prisma/prisma2/issues/617 which fixed the same problem for `cmd.exe` and Powershell already. Unfortunately Cmder did not get fixed.

For details start with this comment: https://github.com/prisma/prisma2/issues/617#issuecomment-543693892

**Comment by divyenduz** [comment]
@janpio Can you please try this again?

**Comment by janpio** [comment]
I can not reproduce this with the steps as described in https://github.com/prisma/prisma2/issues/617#issuecomment-536478218 as the `provider = "postgres"` with a sqlite file does not crash any more, opened https://github.com/prisma/prisma2/issues/1096

If you can provide me with another way to crash Lift migrations, I am happy to try that out @divyenduz

**Comment by divyenduz** [comment]
@janpio Create a successful migration, pollute your lift migration table by randomly removing some data from the migrations table (making its steps column an invalid JSON for example) and try to use lift again.

**Comment by janpio** [comment]
This seems to work now:

![image](https://user-images.githubusercontent.com/183673/70656664-cbcc0000-1c5a-11ea-804f-f09348e86172.png)

I did not understand your instructions really, but I somehow locked the database along the way. I would appreciate clearer instructions on how to induce a Migration Engine crash.
