### ISSUE TITLE
Introspection tells me `⠋ Introspecting MySQL schema  with 1  tables.` during introspection

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#794]
... but MySQL doesn't have schemas:

```
⠋ Introspecting MySQL schema  with 1  tables.
```

The spacing in the output also seems wonky in general.

(This appears only shortly while the introspection is running, after a connection was successfully made.)

**Comment by janpio** [comment]
For Postgres it says:

```
⠋ Introspecting PostgreSQL database foo with 1  tables.
```

🌀

**Comment by pantharshit00** [comment]
Can you please tell me the exact steps for this? I wasn't able to reproduce when I tried it.

**Comment by janpio** [comment]
Internal link https://github.com/prisma/prisma-cli-blackbox-tests/runs/267432579 can tell you the exact steps for Postgres for example: Click `Run node init-flow-test.js prisma2 blank_postgres_with_exists_notempty_ts_schema` and then scroll down to line 5221 to see it - go back up to see the steps (Blank, Postgres, Enter credentials with DB and Schema of a not empty schema, observe).

**Comment by janpio** [comment]
Strings for MySQL and Postgres seem to be switched here:
- MySQL says `schema` and can't show one, because MySQL does not have that
- Postgres says `database` and shows something, probably the `schema`

Also additional space after the number in both cases.

**Comment by pantharshit00** [comment]
> Internal link prisma/prisma-cli-blackbox-tests/runs/267432579 can tell you the exact steps for Postgres for example: Click Run node init-flow-test.js prisma2 blank_postgres_with_exists_notempty_ts_schema and then scroll down to line 5221 to see it - go back up to see the steps (Blank, Postgres, Enter credentials with DB and Schema of a not empty schema, observe).

The link is broken now :/

**Comment by janpio** [comment]
Added you as collaborator.

**Comment by pantharshit00** [comment]
Ok, I can also reproduce this now:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/22195362/71483336-61f05080-282d-11ea-8220-eb92d795ba2e.png">

**Comment by divyenduz** [comment]
@janpio @pantharshit00 does this still apply with the new introspection? If no, please close it. Thanks.

**Comment by pantharshit00** [comment]
Yes, this is still relevant:
![image](https://user-images.githubusercontent.com/22195362/72206689-d7f3e900-34b6-11ea-8435-09e0ef7ad671.png)


It is probably a printing issue in the CLI.

**Comment by janpio** [comment]
To recap:
- Database and schema are mixed up between MySQL and Postgres
- There was additional spacing after the number of tables sometimes

**Comment by Jolg42** [comment]
This is not applicable anymore, the screenshots show the old interactive CLI that was removed.
We do have this https://github.com/prisma/migrate/blob/master/src/utils/ensureDatabaseExists.tsx 
It will create a database (the term should be the same for all db here as it's a different scenario, ie: not creating schema/tables) if non existing when doing `migrate` `save` `down` or `up`.
