### ISSUE TITLE
GitHub syntax theme for .prisma files (via Linguist)

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#80]
Let's create a GitHub syntax theme for .prisma files via https://github.com/github/linguist

**Comment by rajinwonderland** [comment]
Hey @schickling started looking into adding prisma to linguist.  [Forked repo here](https://github.com/rajinwonderland/linguist)

## Details

> In order of these steps [provided by linguist's contributing guidelines] (https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)

- [x] Add prisma to `language.yml` – Here's what the snippet looks like:

```yaml
Prisma:
  type: data
  aliases:
  - prisma
  extensions:
  - ".prisma"
  tm_scope: source.prisma
  ace_mode: text
  language_id: 499933428
```
- [x] Add a syntax-highlighting grammar for `prisma` using:
```sh
script/add-grammar https://github.com/prisma/vscode-prisma/blob/master/syntaxes/prisma.tmLanguage.json
```

- [x] Add a `schema.prisma` into a new `samples/Prisma` directory – [_available here_](https://github.com/rajinwonderland/linguist/tree/master/samples/Prisma)
- [x] Generate a unique ID for prisma language by running `script/update-ids`.

- [ ] Open a pull request, linking to GitHub search results showing in-the-wild usage. 


## Open Items

You can find the [forked repo here](https://github.com/rajinwonderland/linguist) and we are almost ready to make a PR, but we just need a couple of things:

1. Noticed the new `embed`  types are not currently highlighting on vs-code (_see screenshot below_) It’d be best if we were to translate all the final changes from `prisma2` onto the [`prisma.tmLanguage.json`](https://github.com/prisma/vscode-prisma/blob/master/syntaxes/prisma.tmLanguage.json) prior to making the pull request

![image](https://user-images.githubusercontent.com/15880596/60687181-d1c6e500-9e61-11e9-9809-404d9bcde70c.png)

> It wouldn't be entirely difficult to update. See here for more [details on updating linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language)

2. **License needed** for the Prisma language. 

    - From [linguist's contributor guide](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language), prior to opening a PR, it states: 
      
      > Must state clearly the license covering the code in the samples. Link directly to the original source if possible.


Must be one of the following as stated in the [contributor guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language):
```yaml
whitelist:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - permissive
  - mit
  - isc
  - mpl-2.0
  - unlicense
  - wtfpl
 - zlib
```

**Comment by schickling** [comment]
Thanks a lot for tackling this @rajinwonderland 🙏 

Re 1: The syntax for `embed` is still not 100% finalized. I suggest to ignore this feature for now.
Re 2: `apache-2.0`

**Comment by rajinwonderland** [comment]
Great!



[Pull Request here](https://github.com/github/linguist/pull/4579)
[Syntax Highlighting Example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fprisma%2Fvscode-prisma%2Fblob%2Fmaster%2Fsyntaxes%2Fprisma.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fprisma%2Fphotonjs%2Fmaster%2Fexamples%2Ftypescript%2Fgraphql%2Fprisma%2Fschema.prisma&code=)

The only issue right now is on the ci/cd checks. The check fails because there is no attributed license file (i.e `LICENSE.md`)on the [vscode-prisma](https://github.com/prisma/vscode-prisma) repo. If we can add this, we should be able to pass the checks!

**Comment by kuldar** [comment]
> Tried adding the default prisma color #0C344B, but it's too close to DataWeave's color.

Could we maybe try the purple tone (`#9F6BF4`) we've been using more with Prisma 2 imagery? Not sure if it's close to anything else as well though.

**Comment by rajinwonderland** [comment]
Hey @kuldar sure I'll try that!

@schickling any updates regarding the license for vscode-prisma?


_Sent from my Pixel 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schickling** [comment]
@rajinwonderland thanks a lot for pushing this forward. We've added a `LICENSE` file to the vscode-prisma repo!

**Comment by Weakky** [comment]
New PR up: https://github.com/github/linguist/pull/4668

**Comment by janpio** [comment]
Got merged and now works! 🚀
