### ISSUE TITLE
Do not require environment variables for `generate`

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#800]
This CLI should fail on environment on a must-have basis. For example, 

1. For `prisma introspect` and `prisma lift <command>`, the database URL is a must have: https://github.com/prisma/specs/tree/master/schema#introspect-behavior
2. While, `prisma generate` can proceed without fulfilling the environment variables: https://github.com/prisma/prisma2/issues/593

**Comment by janpio** [comment]
> 1. For `prisma introspect` and `prisma lift <command>`, the database URL is a must have: [prisma/specs:schema@`master`#introspect-behavior](https://github.com/prisma/specs/tree/master/schema#introspect-behavior)

This is not really how `prisma2 introspect` works, and if it would be I would definitely ask for this to be revised. I am confused why normal parameters should not work there.

**Comment by divyenduz** [comment]
@janpio Normal parameters should work, this is the scenario where `prisma introspect` is called without parameters and schema file contains an env var for DB URL. In this case, to resolve the DB path, the environment variable should be available as a concrete value.

**Comment by janpio** [comment]
(We need a spec for the actual Introspection command, this is only slightly to not at all connected to the schema)

**Comment by divyenduz** [comment]
`prisma2 generate` fails if the DB variable is not fulfilled, hence, keeping this issue open and marking it as a candidate for quick discussion

```
prismprisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7
divyendusingh [next-prisma2]$ prisma2 generate
Error: Schema parsing
error: Environment variable not found: PG_URL.
  -->  schema.prisma:7
   |
 6 |   provider = "postgresql"
 7 |   url      = env("PG_URL")
 8 | }
   |
```

**Comment by divyenduz** [comment]
Currently, `prisma2 generate` fails in now build as it requires a special `-b` flag to have the env vars there
![image](https://user-images.githubusercontent.com/746482/70998399-92bae200-20d7-11ea-9595-968e1b6d6d4d.png)

**Comment by alechp** [comment]
@pantharshit00 https://github.com/prisma/photonjs/issues/326 was closed prematurely.

* The error isn't a result of a missing environment variable
* POSTGRES_URL _does_ exist in a .env file 
* prisma _does_ recognize it when you run `prisma2 generate`

The `postinstall` command - which automatically runs when you run npm install - is the cause of the error. The original log provided here by @ctrlplusb illustrates that: https://github.com/prisma/photonjs/issues/326#issue-537085896

And the screenshot I provided [here](https://github.com/prisma/photonjs/issues/326#issuecomment-565237999) shows how `prisma2 generate` works as expected despite previously being told that an environment variable missing while `postinstall` calls `node scripts/generate.js`

**Comment by janpio** [comment]
You should post that in the closed issue then.

**Comment by janpio** [comment]
Internal Note: Dropping from current sprint, and picking up later.

**Comment by narciero** [comment]
what is the recommended workaround for this? I'm trying to build a Docker image using prisma2 and I can't find a way to run `prisma2 generate` without hardcoding the environment variables for my production environment (which is obviously not what I want to do)

**Comment by akoufatzis** [comment]
@narciero I think for the moment defining something like `ENV DB_URL ""` in your Dockerfile so that `prisma2 generate` runs should be fine.

**Comment by narciero** [comment]
@akoufatzis yea I ended up putting `RUN export POSTGRES_URL= && prisma2 generate`

**Comment by janpio** [comment]
Also requested by users: 
https://github.com/prisma/prisma2/issues/1679
https://github.com/prisma/prisma2/issues/1716#issue-571482205

**Comment by mavilein** [comment]
done in: https://github.com/prisma/prisma-engines/pull/541
