### ISSUE TITLE
Explicit many to many relationships with/without extra columns

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#816]
Tracks implementation of https://github.com/prisma/specs/tree/master/schema#explicit-many-to-many-mn-relationships-with-or-without-extra-columns

Many-to-many relation with/without extra columns.

**Comment by nikolasburk** [comment]
There's also a related discussion here: https://github.com/prisma/specs/issues/264

**Comment by ifndefdeadmau5** [comment]
Here I update temporary workaround by @matthewmueller (in slack channel) that possibly can be migrate into official implementation in future

```
model Blog {
  id       Int       @id
  authors  Writer[]
}
model Writer {
  id      Int     @id
  blogs   Blog[]
}
// many to many
model BlogsWriters {
  id        Int      @id
  blog      Blog
  author    Writer
  is_owner  Boolean
}
```

**Comment by scriptcoded** [comment]
@ifndefdeadmau5 This won't actually work as of right now. The following schema has been tested and works :)

```prisma
model Blog {
  id      Int          @id
  authors BlogWriter[]
}
model Writer {
  id    Int          @id
  blogs BlogWriter[]
}
// many to many
model BlogWriter {
  id       Int     @id
  blog     Blog
  author   Writer
  is_owner Boolean
}
```

**Comment by narciero** [comment]
what is the status of prisma supporting extra data fields with M-N relation?

**Comment by janpio** [comment]
This is now implemented 🚀
