### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Photon binary for current platform linux-glibc-libssl1.1.0 could not be found.

### ISSUE THREAD

**Issue by grjzwaan** [prisma/prisma2#818]
I'm getting `UnhandledPromiseRejectionWarning: Error: Photon binary for current platform linux-glibc-libssl1.1.0 could not be found.` errors when running the generated code.

Any idea how I can fix this? When I checked similar issues they seemed to be fixed and closed, so I reported this one.

## Reproduction:

1. Install Prisma2 `npm install -g prisma2`, results in version `2.0.0-preview014.2`
2. Run `prisma2 init` and pick sqlite, blank project and Javascript
3. Make a sample schema
4. run `prisma2 generate`
```
> Sockify@0.0.1 prisma2 /home/ruben/Datasprong/sokken/sockpreview/sockify
> prisma2 "generate"

> Downloading linux-glibc-libssl1.1.0 binary for query-engine [====================] 100%

Generating Photon.js to /home/ruben/Datasprong/sokken/sockpreview/sockify/node_modules/@generated/photon
Done in 2.05s
```
5. Run my code (simply connects via Photon to the database)
```
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
12961:         }
12962:         this.platform = this.platform || platform;
12963:         const fileName = eval(`require('path').basename(__filename)`);
                                ^
12964:         if (fileName === 'NodeEngine.js') {
12965:             return this.getQueryEnginePath(this.platform, path_1.default.resolve(__dirname, `..`));

(node:16314) UnhandledPromiseRejectionWarning: Error: Photon binary for current platform linux-glibc-libssl1.1.0 could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider      = "photonjs"
  binaryTargets = ["native"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `linux-glibc-libssl1.1.0`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at NodeEngine.getPrismaPath (/home/ruben/Datasprong/sokken/sockpreview/sockify/__sapper__/dev/server/server.js:17081:23)
(node:16314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
6. Following the sugestion to add `'native'` does not help.

**Comment by pantharshit00** [comment]
Hi @grjzwaan 

Can you please tell me which OS you are using and output of `uname -a` would also be useful if you are on a unix based system.

**Comment by grjzwaan** [comment]
```
Linux saturnus 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by soullivaneuh** [comment]
Same issue for me.

Host:

```
Linux sweethome 4.19.79-1-MANJARO #1 SMP PREEMPT Fri Oct 11 19:57:09 UTC 2019 x86_64 GNU/Linux
```

Version of prisma2: `2.0.0-preview015`

**Comment by soullivaneuh** [comment]
It looks to be a bit tricky. If I use `node src/seed.js` from the Prisma2 starter kit, it works, but if I call Photon from my sapper `server.js` file:

```javascript
import { Photon } from '@generated/photon';

const photon = new Photon();
photon.connect()
```

It fails.

Note that [Sapper]() has a special dev mode, re-compiling the server js file to use it.

It may be related, but I don't know how. Any idea?

**Comment by soullivaneuh** [comment]
Maybe related to https://github.com/prisma/photonjs/issues/119.

@grjzwaan Do you have a similar setup?

**Comment by grjzwaan** [comment]
Actually, yes, I also wanted to run it together with Sapper.  I also tried it without Sapper, but _with_ bundler. Then the error makes sense, since it's probably not moved by the bundler...

It would be helpful if the error would include the search path. It would have alerted me to the fact that Photon looks in a different spot than the bundle, and that I overlooked that fact.
`
UnhandledPromiseRejectionWarning: Error: Photon binary for current platform linux-glibc-libssl1.1.0 could not be found **at '/home/kitten/project/node_modules/@generated/photon/'**
`

**Comment by soullivaneuh** [comment]
> It would be helpful if the error would include the search path.

I agree. So far I did try to manually copy the generated directory on some place of the `__sapper__` directory without success.

Did you find a workaround?

**Comment by soullivaneuh** [comment]
It may be a Sapper issue, see: https://github.com/sveltejs/sapper/issues/959

**Comment by grjzwaan** [comment]
My conclusion is that it seems a general issue and not directly related to Photon/Prisma2. 

However, for a different project with binaries I've found a solution. I guess the solution below should also work, but then by replacing the generated module by Photon. 

## The 'solution'
For another NodeJS project with Rollup as a bundler I also needed a binary. I did the following things by looking at [this Rollup issue](https://github.com/rollup/rollup-plugin-commonjs/issues/101) and inferring some steps.

### Tell Rollup to not process these binaries
Add the `paths` parameter to Rollup. This states that imports of 'sharp' should not be included/processed, but rather be looked for in the output directory.

Add in `rollup.config.js`:
```javascript
    paths: {
        'sharp': './vendor/sharp'
    }
```

### Copy node_module
Copy the node module with a a prehook and place it where you promised Rollup it would be. Otherwise it'll be sad.

Add in `package.json`:
```js
    "prebuild": "rm -rf ./build/vendor/* && cp -r ./node_modules/sharp ./build/vendor/sharp",
```

**Comment by alexthegoodman** [comment]
I am also experiencing this issue.

**Comment by soullivaneuh** [comment]
@grjzwaan What would be the copy path for the `__sapper__` build directory?

**Comment by grjzwaan** [comment]
@soullivaneuh I didn't try it myself in combination with Sapper (both from Prisma and Sapper). I gave up on the combination, so below is only speculation :man_shrugging:

## Workaround in Sapper
It's a bit tricky because in the default Sapper project configuration `output.paths` uses a config function  and `export` is set with another piece of code. Both of which are not transparent to me.

The directory you should copy is `@generated` in `node_modules`, and it should end up in `__sapper__/[dev | build]/server`, and then in in the location you promised in setting the `paths`.

## Workaround in Prisma2?
Perhaps it's possible to pass the path to the binary as an option when you do `new Photon()`. In the generated code I can see that you can pass `PhotonOptions`:
```javascript
export interface PhotonOptions {
    datasources?: Datasources;
    debug?: boolean | {
        engine?: boolean;
        library?: boolean;
    };
    /**
     * You probably don't want to use this. `__internal` is used by internal tooling.
     */
    __internal?: {
        hooks?: Hooks;
        engine?: {
            cwd?: string;
            binaryPath?: string;
        };
    };
}
```

Perhaps one of the developers can comment on this.

**Comment by alexthegoodman** [comment]
Turns out, my Webpack was sending a compiled bundle to a `/dist/` folder. And there is a path.join in the Photon code. This leads it to search for the binary in the `/dist/` folder, rather than the original Photon folder, where the binary is actually located.

The simple solution was to copy the binaries into the location that it is searching for, which for me was that `/dist/` folder. :)

**Comment by divyenduz** [comment]
> And there is a path.join in the Photon code.

That is intentional, tools like zeit's now also move project files around and this allows their tooling to determine the dependencies and copy them over. 

Photon relies on binaries and they should be treated as static assets, which means any bundlers like webpack, parcel must copy the binaries over.

We should document this behavior. 

This is our current take on this, please let us know what you think about it?

**Comment by divyenduz** [comment]
Created this issue https://github.com/prisma/specs/issues/336 in our specs repo to acknowledge this. Please share your valuable feedback there. 

Assuming that this issue has a resolution via the manual copy workaround. I will close it, please write a comment and tag me if you think that closing this one is not correct. Thanks.
