### ISSUE TITLE
Back button does not work on init flow with SQLite selected

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#819]
Steps to reproduce:

1. prisma2 init
2. Select Blank Project > SQLite
3. Try to go back using the Back button

<img width="675" alt="Screenshot 2019-10-22 at 15 39 59" src="https://user-images.githubusercontent.com/7689783/67291703-39bd3c00-f4e2-11e9-9cf7-5262aedf9d9f.png">

**Comment by pantharshit00** [comment]
I can confirm this bug.

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by janpio** [comment]
Still exists in `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
