### ISSUE TITLE
Relations Foreign Key Reference

### ISSUE THREAD

**Issue by skyflyer55** [prisma/prisma2#82]
Using the following model:
```
model User {
  id        String    @default(cuid()) @id @unique
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  email     String    @unique
  name      String?
  slack     Provider? @relation(onDelete: CASCADE)
}

model Provider {
  id           String  @default(cuid()) @id @unique
  userId       String  @unique
  accessToken  String  @unique
  refreshToken String? @unique
  user         User?   @relation(onDelete: CASCADE)
}
```
Reading the docs... "`For 1:1 relationships, it doesn't matter on which side you store the foreign key. Prisma has a convention that the foreign key is added to the model which appears first alphanumerically in your data model`".

But running `SELECT * FROM sqlite_master;` shows me differently

```
CREATE TABLE "Provider"("id" TEXT NOT NULL  ,"userId" TEXT NOT NULL DEFAULT '' ,"accessToken" TEXT NOT NULL DEFAULT '' ,"refreshToken" TEXT   ,PRIMARY KEY ("id"))
```
```
CREATE TABLE "User"("id" TEXT NOT NULL  ,"createdAt" DATE NOT NULL  ,"updatedAt" DATE NOT NULL DEFAULT '1970-01-01 00:00:00' ,"email" TEXT NOT NULL DEFAULT '' ,"name" TEXT   ,"slack" TEXT NOT NULL  REFERENCES Provider(id),PRIMARY KEY ("id"))
```

**Comment by pantharshit00** [comment]
I can confirm this.

Right now we are creating the foreign key on the model which appears first in the project.prisma file. But it should be in accordance with lexicographical precedence.

Also, onDelete: CASCADE is yet to be implemented.

**Comment by skyflyer55** [comment]
After some testing, it seems the foreign key is determined by which referenced field on the two referencing models comes with lexicographical precedence.

**Example 1** - _userRef > userReff_
Model
```
model User2 {
  id      String @default(cuid()) @id @unique
  userRef User3
}

model User3 {
  id      String @default(cuid()) @id @unique
  userReff User2
}
```
Creates
```sql
CREATE TABLE "file:dev"."User2"("id" TEXT NOT NULL  ,"userRef" TEXT NOT NULL  REFERENCES User3(id),PRIMARY KEY ("id"));

CREATE TABLE "file:dev"."User3"("id" TEXT NOT NULL  ,PRIMARY KEY ("id"));
```

**Example 2** - _userRef < userRe_
Model
```
model User2 {
  id      String @default(cuid()) @id @unique
  userRef User3
}

model User3 {
  id      String @default(cuid()) @id @unique
  userRe User2
}
```
Creates
```sql
CREATE TABLE "file:dev"."User2"("id" TEXT NOT NULL  ,PRIMARY KEY ("id"));

CREATE TABLE "file:dev"."User3"("id" TEXT NOT NULL  ,"userRe" TEXT NOT NULL  REFERENCES User2(id),PRIMARY KEY ("id"));
```

**Comment by pantharshit00** [comment]
One more thing we want to keep in mind is creating a foreign key for an optional relation defined in the datamodel. 

For example:
```groovy
model User {
  id         String        @default(cuid()) @id @unique
  email      String        @unique
  staff      Staff?
}

model Staff {
  id        String   @default(cuid()) @id @unique
  user      User
  active    Boolean?
}
```

If we create the database schema for the above datamodel using Lift, it will create a foreign key on the User field. But in the datamodel, `Staff` on a `User` is optional but a `User` is required on the `Staff`.

So when we try to create a User:
```ts
const user: User = await photon.users.create({
	data:{
		email: "pant@prisma.io"
	}
});
```

It will throw a Null Constraint violation exception as shown below:
```json
"error": "ConnectorError(NullConstraintViolation { field_name: \"User.staff\" })"
```

This shouldn't be the case. This is also easily fixable by creating the foreign key on staff rather than on the user.

```groovy
model Staff {
  id     String   @default(cuid()) @id @unique
  user   User     @relation(references: [id])
  active Boolean?
}

model User {
  id    String @default(cuid()) @id @unique
  email String @unique
  staff Staff?
}
```

**Comment by mavilein** [comment]
This is fixed. It will ship with `preview4`.

**Comment by tomitrescak** [comment]
Hi, the CASCADE does not work though ;(

**Comment by janpio** [comment]
Can you please open a new issue about this @tomitrescak? We will then look into it with the necessary information you provide about the problem. Thanks.
