### ISSUE TITLE
prisma2 dev stuck at "Waiting for migrations"

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#821]
```
$ prisma2 -v
prisma2@2.0.0-alpha.268, binary version: cdf5c04cbfa7228f05eadb07656db1781b9d5b85
```

To reproduce: 

1. `prisma2 init <folder>`
1. `Blank project` 
1. `MySQL`
1. `New database`
1. `Typescript`
1. `Just the prisma schema`
1. `cd <folder>`
1. `prisma2 dev`

GIF: https://divyendu.s3-eu-west-1.amazonaws.com/prisma2-821.gif

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.
