### ISSUE TITLE
unexpected db schema created with name 'lift'

### ISSUE THREAD

**Issue by insanebaba** [prisma/prisma2#827]
When I'm creating migrations for my model(_schema.prisma)_ :

```
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  enabled  = true
}

model User {
  id        Int      @id
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  posts     Post[]
  profile   Profile?
}
```

I get this sql as the migration script 
```
CREATE TABLE "lift"."User" (
  "createdAt" DATE NOT NULL DEFAULT '1970-01-01 00:00:00'  ,
  "email" TEXT NOT NULL DEFAULT ''  ,
  "id" INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT ,
  "name" TEXT    ,
  "role" TEXT NOT NULL DEFAULT 'USER'  
);
```
Here, _lift_ schema is created in my database which is unexpected. Is there a way to avoid this, or configure it?

**Comment by janpio** [comment]
Ok, I managed to reproduce this:
1. Create a new folder as the project
2. Create `prisma/schema.prisma` inside with content:
	```
	datasource db {
	  provider = "sqlite"
	  url      = "file:dev.db"
	  enabled  = true
	}
	
	model User {
	  id        Int      @id
	  createdAt DateTime @default(now())
	  email     String   @unique
	  name      String?
	}
	```
3. Run `prisma2 lift up`
4. Look at `README.md` in the migration folder that was created

If you run `prisma2 lift up` with the generated mirgation, it just creates the `User` table as it should - so I think this is a display problem in the `README.md`.

Does this match your observations @insanebaba?

**Comment by insanebaba** [comment]
Yes, That's right. Thank you
