### ISSUE TITLE
Adding the possibility to access the foreign key

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma2#829]
Hi, it would be fantastic if we had a possibility to access the foreign key, so that we do not need to do joins. Example

```
model Person {
   id Int @id
   posts Posts[]
}

model Post {
  owner: Person
  title: String
}
```

Photon currently will generate something similar to following for `Post`.

```ts
type Post {
  title: String
}
```

it would be great if we also had the key there

```ts
type Post {
  title: String
  owner_key: Int
}
```

This may not seem ovious, but often all we need is that `id` or we want to filter by that id. Having it there would be possible to omit many joins if I have Id ready

```js
posts.findMany({ where: { owner_key: 1 }}) // no join

// instead of 

posts.findMany({ where: { owner: { key: 1 } }})
```

also obtaining that id would not require any join

```js
posts.findMany({}) // no join

// instead of 

posts.findMany({ include: { owner } }})
```

**Comment by mavilein** [comment]
My 2 cents: 
I think we should not introduce special syntax for this. The query `posts.findMany({ where: { owner: { key: 1 } }})` should be handled in such a way that no unnecessary join happens. The owner key is stored within a Post. So we could apply an optimization here.

**Comment by schickling** [comment]
I suggest to go with @mavilein’s proposal for now and revisit this later as we’re seeing more demand/feedback for this feature/use case from a DX perspective. 

This is also related to https://github.com/prisma/photonjs/issues/188

**Comment by tomitrescak** [comment]
Guys, but how do I access that key? the key is not generated and returned.

**Comment by mavilein** [comment]
@tomitrescak : You need to include it in the selected fields. Check out the [docs](https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#field-selection).

**Comment by pantharshit00** [comment]
> Guys, but how do I access that key? the key is not generated and returned.

For now, you can use `prisma.raw` if you have to do that. Otherwise we plan to revisit this as already mentioned.

**Comment by tomitrescak** [comment]
@mavilein what do you mean? How do I access the the foreign key? This is automatically generated by Prisma. @pantharshit00 same thing, are there any docs on prisma.raw?

Example:

```
type User {
  id: String @id
}

type Post {
   id: String @id
   user: User
}
```

How do I access the `userId` of the post without doing the "join" ?

**Comment by pantharshit00** [comment]
You can the following workaround for now: 
```js
const result = await prisma.raw`select user from Post where Post.id = "something"`;
```

As already mentioned by @schickling above, we plan to revisit this issue and include it in our API.

**Comment by mavilein** [comment]
This might get adressed with https://github.com/prisma/prisma2/issues/1606

**Comment by Sytten** [comment]
I also very much need that for some of my GraphQL resolvers. Since we receive the parent object in the field resolver and I need to fetch again the database to get this ID.

**Comment by mavilein** [comment]
This was implemented in https://github.com/prisma/prisma-engines/pull/621
The plain value for a foreign key is accesible through a new scalar field

**Comment by tomitrescak** [comment]
Amazing, thanks! Are there any docs for this? I tried to go through the PR but it is huge!

**Comment by janpio** [comment]
If you use `prisma2 introspect` to get a schema of your existing database, generate a client with `prisma2 generate` and use any `find` method to any of your models, they will just be present.

**Comment by MichalLytek** [comment]
@janpio 
So to sum up:

The example from release notes:
```prisma
model Movie {
  director Director @map(["directorFirstName", "directorLastName"])
  title    String

  @@id([director, title])
}
```

Should now be written explicitly as:
```prisma
model Movie {
  directorFirstName String
  directorLastName  String
  director          Director @relation(fields: [directorFirstName, directorLastName], references: [firstName, lastName])
  title             String

  @@id([directorFirstName, directorLastName, title])
}
```

Or is there a faster syntax? As `alpha.980` throws now `Error validating model "Movie": The id definition refers to the relation fields director. Id definitions must reference only scalar fields.` 😕

**Comment by janpio** [comment]
> Should now be written explicitly as:

Yes, that would be my understanding.

> Or is there a faster syntax?

Not right now, we are starting with a bit more verbose syntax and will later introduce optimizations again if possible.

> As `alpha.980` throws now `Error validating model "Movie": The id definition refers to the relation fields director. Id definitions must reference only scalar fields.` 😕

Uh, that would be unexpected I would say. Can you please create a new issue? What command throws this error exactly? In quick testing I could not reproduce the error.

**Comment by MichalLytek** [comment]
@janpio the error is for using alpha 980 with the old schema - the new one works correctly, don't worry :wink: 

But one thing is also missing for me - some info in dmmf about to which relation does the id keys refers to, in order to directly fetch the relation by foreign key, not by `findOne().relation()` :thinking:

**Comment by janpio** [comment]
Ah sorry, I misunderstood - that is indeed correct.

> But one thing is also missing for me - some info in dmmf about to which relation does the id keys refers to, in order to directly fetch the relation by foreign key, not by `findOne().relation()` 🤔

I think you know my answer already... issue pls :)
