### ISSUE TITLE
Generation and `node_modules`

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#83]
`prisma2 generate` acts on the [generators](https://github.com/prisma/prisma2-docs/blob/master/prisma-schema-file.md#generators-optional) from Prisma schema file and generates the respective packages on the respective output path. 

The default for most of the generators (Photon, Nexus) in at `node_modules/@generated/<generator-provider>`

Some of the advantages of doing this are
1. Easier imports like `import Photon from '@generated/photon'`
2. Keeping the binary (in case of `Photon`) from version control without having additional configuration in user land like an additional `.gitignore` entry to ignore the binary.

However, package managers like `yarn`, `npm` want to maintain the integrity of `node_modules` and they remove any additional folders that are not specified by the respective `.lock` file on operations like `install`, `add` etc. 

To get around this, we need to provide a `postinstall` hook to run `prisma2 generate` command. 

This might be an issue with developer experience if the `postinstall` hook is not set initially. We also need to make users aware about adding it.

Additionally, we can make this more prominent in the ecosystem by talking to package manager maintainers regarding exception in folders that stay across integrity cleanups.

**Comment by notrab** [comment]
@divyenduz What's the main benefit of adding it to the `node_modules` folder? I've not been following the development all that much but when I showed Photon to a friend, the import from `@generated/photon` confused the hell out of them instead of being a relative import.

I guess by providing `output` you could specify a relative path to import from but this I'm guessing would have an impact on the type defs?

**Comment by schickling** [comment]
This is also related to https://github.com/prisma/photonjs/issues/88

**Comment by nikolasburk** [comment]
I've added a docs page with more content around this here: https://github.com/prisma/prisma2/blob/master/docs/photon/codegen-and-node-setup.md
