### ISSUE TITLE
Schema does not get loaded using preview015 when deploying server as lambda function

### ISSUE THREAD

**Issue by s7au** [prisma/prisma2#837]
#625 isn't related but provides context as to what I am trying to do.
I managed to get prisma2 working with netlify as of 13.3 by putting the generated packages into the same folder as the server code.
preview015 introduces nexus-prisma which resulted in some tinkering to get things working again. Had to add:
```
  plugins: [nexusPrismaPlugin({
    inputs: {
      photon: require.resolve('./generated/photon')
    }
  })],
```
... to make sure the nexus-prisma library knew where the generated photon file was. Everything successfully built and ran but when I hit the endpoint I get this error: 
```
Function invocation failed: Error: It seems like you have applied rules to Mutation types but Shield cannot find them in your schema.
```
I try removing the middleware and realize none of my queries can be made through the graphql ui.

Any ideas why?

Edit:
Possibly related but I found weird behaviour when I hit the endpoint the `@types/nexus-typegen/index.d.ts`. The file gets overwritten to something that would indicate there is no loaded schema.

**Comment by s7au** [comment]
Weird behaviour in that when I hit the endpoint the '@types/nexus-typegen/index.d.ts' file gets overwritten to something that would indicate there is no schema.

**Comment by ajmcclary** [comment]
I think they may have changed the location of where "prisma2 generate" is run post install, because I got breaking changes in this release too. 

I keep getting an error "Cannot find prisma.schema", which must be a typo in the error message, because the filename is supposed to be "schema.prisma".

**Comment by s7au** [comment]
I went back to javascript and it works so might leave it as is until there's another update. So pretty sure there must be some weird issue with the schema file.
Here is my `schema.ts`:
```
import { nexusPrismaPlugin } from 'nexus-prisma'
import { makeSchema } from 'nexus'
import * as types from './types'
import { Context } from './context';

export const schema = makeSchema({
  types,
  plugins: [nexusPrismaPlugin({
    photon: (ctx: Context) => ctx.photon,
    inputs: {
      photon: require.resolve('./generated/photon')
    }
  })],
  // plugins: [nexusPrismaPlugin()],
  typegenAutoConfig: {
    sources: [
      {
        source: require.resolve('./generated/photon/index.d.ts'),
        alias: 'photon',
      },
      {
        source: require.resolve('./context.ts'),
        alias: 'Context',
      },
    ],
    contextType: 'Context.Context',
  },
})
```
I needed to append `.ts` as after compilation to js `require.resolve` looks for `.js` files and errors. This also means manually copying the `context.ts` into the compiled folder.

**Comment by pantharshit00** [comment]
Can you please create a minimal reproduction in a git repository? I wasn't able to reproduce this but I am sure I have missed something.

**Comment by divyenduz** [comment]
@s7au I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
