### ISSUE TITLE
Syntax error : "(" unexpected on "npm install"

### ISSUE THREAD

**Issue by NeOMakinG** [prisma/prisma2#845]
I've got the following error : 

Error: Get config /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2-ubuntu1604: 2: /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2-ubuntu1604: Syntax error: "(" unexpected

While trying to prisma2 generate, and 

Error: Schema parsing /home/spliziws/webservices/splizi/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2-ubuntu1604: 2: /home/spliziws/webservices/splizi/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2-ubuntu1604: Syntax error: "(" unexpected

when trying to npm install

It works perfectly locally on my Windows 10 computer, but these errors happens on my linux server !

**Comment by pantharshit00** [comment]
Hi,

I just testing this on a Ubuntu 16.04 Digitalocean instance and I was unable to reproduce the issue.

The output of `uname -a` of the machine that I used:
```
Linux ubuntu-s-1vcpu-1gb-fra1-01 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

The version of Prisma 2 that I used: `prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe`


Can you please make sure that you are using the latest version of prisma2 and also please make sure that you install the prisma2 binary using the `--unsafe-perm` flag.
```
npm install -g --unsafe-perm prisma2
```

**Comment by NeOMakinG** [comment]
Hey

The uname -a : 

Linux dev 4.4.127-mainline-rev1 #1 SMP Sun Apr 8 10:33:17 UTC 2018 armv7l armv7l armv7l GNU/Linux

The actual version of Prisma 2 on the server :

prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe

I've got the same error after reinstalling it with the --unsafe-perm flag :

```
Error: Schema parsing /home/webservices/splizi/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2-ubuntu1604: 2: /home/webservices/splizi/node_modules/prisma2/query-engine-linux-glibc-libssl1.0.2-ubuntu1604: Syntax error: "(" unexpected
```

**Comment by pantharshit00** [comment]
Looks like you are using Prisma on ARM. We currently do not compile Prisma for ARM.

**Comment by pantharshit00** [comment]
If that is the case, please feel free to close this as a duplicate of : https://github.com/prisma/prisma2/issues/132

**Comment by NeOMakinG** [comment]
Oh ok, thanks then ;)

**Comment by janpio** [comment]
@pantharshit00 Please create an actual issue "Compile for ARM" if this is the actual wanted change here instead of keeping these bug issues around. Thanks.

**Comment by pantharshit00** [comment]
#132 which I mentioned here is the issue tracking this and it has more context as well.

I will update the title of #132

**Comment by janpio** [comment]
A bug is not a feature request. Updating the title of a bug issue does not make it a feature request. Please take the time to create a new issue that is clear and summarizes the problem and ask.
