### ISSUE TITLE
Specify `schema.prisma` as CLI configuration path

### ISSUE THREAD

**Issue by peterp** [prisma/prisma2#849]
Due to the way I've organised my project I would love to have the ability to specify the path to the schema.

Something along the lines of:
`prisma2 dev --schema ./path/to/schema.prisma`

**Comment by pantharshit00** [comment]
Hi @peterp,

Looks like you have already opened an issue for this: https://github.com/prisma/prisma2/issues/225

I will need to close this one as a duplicate but I have added the candidate label on the other issue so that we can discuss it internally in the next planning meeting.

**Comment by peterp** [comment]
@pantharshit00 Whoops! Sorry!
