### ISSUE TITLE
Documentation to be added for using Array of primitives

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma2#853]
This is in relation to the comment made in this issue: https://github.com/prisma/prisma2/issues/169#issuecomment-546783146

Documentation would need to be added on how to set data for an array of Primitives.

I got the array of primitives working by using the set keyword after digging through the prisma generated source code and found that it was declared as 
```
export declare type TheClassName = {
    set?: Enumerable<string> | null;
}
```

So, I tried this and it worked. This may need to be documented if not done already.

```
const notification1 = await photon.notifications.create({
        data: {
            mode: "email",
            deliveryDate: new Date(),
            destinationUserIDList: {
                set: ["123", "456"]
            },
            status: "pending",
            payload: '{"hello":"world"}'
        }
    });
```

Thanks.

_Originally posted by @tvvignesh in https://github.com/prisma/prisma2/issues/169#issuecomment-546783146_

**Comment by nikolasburk** [comment]
Thanks a lot for raising this @tvvignesh 🙌 you can find the documentation for `set` here: https://github.com/prisma/prisma2/blob/master/docs/photon/api.md#scalar-lists
