### ISSUE TITLE
prisma2 cli command failed --create_database

### ISSUE THREAD

**Issue by miyi** [prisma/prisma2#859]
I'm going through the tutorial trying to host a free-tier postgres sever through Heroku, but I'm unable to create the database.

error message:
`
Command Failed: <file_location> cli --datasource <heroku-db-uri> -- create_database ConnectorError(QueryError(QueryError(QueryError(Error { kind: Tls, cause: Some(Error { code: -67843, message: "The certificate was not trusted." }) }`

`FIX  Make sure you have the correct rights to create the database.`

I shouldn't have an ssl certification issue since heroku apps ship with automated ssl certs, and it seems like the default role is the only credential free-tier allows. Are free-tier accounts incompatible with prisma2?

**Comment by pantharshit00** [comment]
I am unable to reproduce this issue. Can you please make sure that `sslmode=prefer` is added to your URL?

If you can still reproduce this, please tell me the exact steps to reproduce this problem.

**Comment by miyi** [comment]
@janpio I did provide the username and password as well as the database name. I perhaps misrepresented the issue. The error occurs after the credential step where the cli attemps to create a new schema. There is step where the prompt asks if I want to create a new schema or use an existing one. 

When I input prisma2 dev into the commandline, should I not create a new database?

**Comment by janpio** [comment]
> The error occurs after the credential step where the cli attemps to create a new schema. There is step where the prompt asks if I want to create a new schema or use an existing one.

Then the same I wrote before maybe applies for schemas? (In as: You can not create database and schemas manually on Heroku Postgres - but get a database and schema name provided in the web UI and can only use those). Could this be the case?

---

> I'm running into further problems. [...]

Can you please create a separate issue for your second problem? Best with a reproduction path that does not include the first problem you are hitting, so probably with both existing database and schema being provided to the introspection/DB connection step of `init`.

**Comment by janpio** [comment]
Was the first part of your question actually solved? How?

**Comment by miyi** [comment]
I can no longer reproduce the error even though I struggled with it over the past few days. I'm not sure what fixed it.

**Comment by pantharshit00** [comment]
That's good to hear @miyi 

If it occurs again, feel free to comment here or open a new issue.
