### ISSUE TITLE
Error Running Prisma2 dev

### ISSUE THREAD

**Issue by garyro** [prisma/prisma2#865]
I am lost what this error means while attempting to run tutorial?

```
Error: Get config Error: Command failed with exit code 2 (ENOENT): /usr/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --get_config {"datamodel":"generator photon {\n  provider = \"photonjs\"\n}\n\ndatasource db {\n  provider = \"mysql\"\n  url      = \"mysql://root@localhost:3306/test\"\n}\n\nmodel User {\n  id    String  @default(cuid()) @id\n  email String  @unique\n  name  String?\n  posts Post[]\n}\n\nmodel Post {\n  id        String   @default(cuid()) @id\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  published Boolean  @default(true)\n  title     String\n  content   String?\n  author    User?\n}"}

**Comment by pantharshit00** [comment]
Try installing `prisma2` with the unsafe perm.

```
npm install -g --unsafe-perm prisma2
```

**Comment by andreasanta** [comment]
I had a similar issue on MacOS 10.15 and it was fixed by running the following:

`
sudo npm install -g --unsafe-perm prisma2
sudo prisma2 init hello-prisma
`

@pantharshit00 Maybe the docs should be updated for MacOS?

**Comment by pantharshit00** [comment]
We personally haven't encountered such issue on macOS.

But I do think this is related to running the install command with administrator permissions in unix like OS. I have opened a new docs issue for this here: https://github.com/prisma/prisma2/issues/931

**Comment by divyenduz** [comment]
The unsafe-perm issue was fixed, @andreasanta does this problem still exist for you?

**Comment by andreasanta** [comment]
Yes, the issue still exists, but the CLI is suggesting to re-install it with --unsafe-perm so it can be worked around easily. Thank you!

**Comment by divyenduz** [comment]
Thanks, I am closing this one then.
