### ISSUE TITLE
Migration engine gets killed when running `prisma2 dev`

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma2#867]
Running `prisma2 dev` in preview 15 returns following error. I tried to remove `node_modules` and reinstall, but it did not help

```
Error: Command failed: /Users/**/Sites/**/**/backend/node_modules/prisma2/migration-engine cli --datasource postgresql://**:**@localhost/** --can_connect_to_database
```

**Comment by janpio** [comment]
How did you create your project?
Can you share your `schema.prisma` or the relevant parts of it?

**Comment by malekjaroslav** [comment]
I updated from Prisma preview 14.2, it is a project in development since preview 8. This is the schema.prisma config

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://usr:pass@localhost:5433/db"
}

generator photon {
  provider = "photonjs"
}
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this.


Can you please tell me the details about your operating system?

**Comment by malekjaroslav** [comment]
I run macOS Catalina 10.15 Beta

**Comment by malekjaroslav** [comment]
I no longer have that issue running Prisma preview-016
