### ISSUE TITLE
Test Prisma with Google Cloud Functions

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#87]
Placeholder. Reminder to test photon with Google Cloud Functions

**Comment by matthewmueller** [comment]
Google cloud functions support the following runtimes:

- nodejs8
- nodejs10
- python37
- go111
- nodejs6 (deprecated)

We should test each of the node versions to figure out what libssl version work.

**Comment by divyenduz** [comment]
We have an example for GCF now https://github.com/prisma/photonjs/tree/master/examples/deployment-platforms/google-cloud-functions

Closing this one, please reopen a new issue if there are issues with this deployment.
