### ISSUE TITLE
Ambiguous relations detected

### ISSUE THREAD

**Issue by miyi** [prisma/prisma2#870]
<img width="446" alt="Screen Shot 2019-10-30 at 3 03 04 PM" src="https://user-images.githubusercontent.com/6610928/67902607-ca20ff80-fb26-11e9-8701-8266757207a2.png">

Is this considered a poor model design? If so whats are some common patterns I can use to resolve it?

There could be other similar data model relationships. For example, a chat group can have many owners and many members, all of whom are also chat-users.

**Comment by AbdusamadTurdiev** [comment]
@miyi you can use the `@relation` directive to separate the logic

https://github.com/prisma/prisma2/blob/master/docs/relations.md#the-relation-attribute

**Comment by pantharshit00** [comment]
Yes, you will need to use the `@relation` directive like so:
```prisma
model User {
  id              String  @default(cuid()) @id @unique
  email           String  @unique
  name            String?
  groupMembership Group[] @relation(name: "GroupMembership")
  groupOwnership  Group[] @relation(name: "GroupOwnership")
}

model Group {
  id   String @default(cuid()) @id @unique
  name String
  userMembership User[] @relation(name: "GroupMembership")
  userOwnership  User[] @relation(name: "GroupOwnership") 
}
```

**Comment by miyi** [comment]
thanks guys
