### ISSUE TITLE
Restore Prisma2 structure in a DB after Resetting it

### ISSUE THREAD

**Issue by ScottAgirs** [prisma/prisma2#873]
After Resetting Database on Heroku
![image](https://user-images.githubusercontent.com/11737572/67999045-135d7600-fc31-11e9-9d13-93fb51c8dbb3.png)

I get the following error, when trying to `npm run seed`
![image](https://user-images.githubusercontent.com/11737572/67999073-2b34fa00-fc31-11e9-8a9e-5e6eed8b6cc0.png)

is there currently a way to rehydrate the database from CLI for Prisma2?

**Comment by ScottAgirs** [comment]
Whoah, 14-hour workday does its magic - it's time to go to sleep.

The solution is `prisma2 lift save` and `prisma2 lift up` - dahh.

**Comment by janpio** [comment]
We've all been there @ScottAgirs - great that the existing tools worked out for you <3
