### ISSUE TITLE
Projecting external fields/object of data to GraphQL API, similar to schema file in Prisma V1

### ISSUE THREAD

**Issue by ScottAgirs** [prisma/prisma2#874]
In Prisma V1 it was possible to define custom fields that would allow to make an API call from within a resolver and pass the data to the client, the data which doesn't live inside the database of the app and/or isn't part of the datamodel itself.

Consider the following:
### Prisma 1
- in datamodel.prisma: 
```
type User {
  id: ID! @id @unique
  email: String! @unique
  firstName: String!
  stripeCusId: String
}
```
- in schema.graphql
```
type Query {
  users: [User]
  currentUser: UserInfo
}

// Here creating a new object (not in datamodel.prisma) which will enable to merge data from 
// ctx.query() and from a stripe.api.call() inside a resolver and pass it to client as one
type UserInfo {
  id: ID!
  email: String!
  firstName: String!
  stripeCusId: String
  stripeCus: StripeCus
}

// "Fake" type not existing in datamodel - how to replicate this?
type StripeCus {
  id: String!
  default_source: String
  sources: UserStripeCusSources
  ..
}

type UserStripeCusSources {
  data: [UserStripeCusSourcesData]
  ..
}
```

Not sure if this is nexus or prisma2 issue, but since it was possible in Prisma V1 would be great to have an alternative or pointers to potential workarounds, if this is not supported out of the box

**Comment by jasonkuhrt** [comment]
Migrated to nexus-prisma repo https://github.com/prisma-labs/nexus-prisma/issues/515
