### ISSUE TITLE
Prisma 2 pagination. Small help needed :-). 

### ISSUE THREAD

**Issue by SvitlanaShepitsena** [prisma/prisma2#883]
Dear pro, 
First of all, I am so sorry if I am asking to the wrong channel. I had a pretty big Prisma 1, react, apollo, nextjs app with relay-type pagination. It took me a while but I finally switched to Prisma 2. First of all, I like very much error handling and code-first approach and also switched to typescript :-). 

My question that I already have a relay-type pagination with entityConnections - HOWEVER my website is not facebook, so there is no need in cursor pagination. My questions are:
- What is the "default" pagination approach for Prisma2
- What would you use for pagination skip/after or cursor type for something like https://www.impressivebathandkitchen.com/blog
- I saw something like this approach - what is your opinion

type PaginatedPosts {
  nodes: [Post!]!
  meta: PaginationMeta!
}

type PaginationMeta {
  nodeCount: Int!
  pageCount: Int!
  pageCurrent: Int!
  nodesPerPage: Int!
}

I would appreciate at least very brief answers with direction and I will continue my research and will figure out details, but I did not find it in documentation, so I would like to get a direction from developers. 

P.S. FINALLY, THANK YOU GUYS - YOU REALLY MADE MY DEV LIFE MUCH, MUCH EASIER. Writting resolvers was real torture for me -  I was thinking that some of my friends switched to WordPress and they are millioners, some switched to Jumla and they make 400k, some work in Angular and are pretty reach and I always kepts going to the right but hard path and now in order to have a simple form - I need to spend 4 hours. 

Jesus, why I did not switch to WordPress - maybe I should throw everything and there is this new hot thing WIX.... however, PRISMA changed everything. It's a game-changer, THANK YOU FOR YOUR HARD WORK!

**Comment by pantharshit00** [comment]
Hi @SvitlanaShepitsena 

Thanks for the kind words 🙌 

Right now we provide properties from which you can implement both cursor or offset based pagination:
![image](https://user-images.githubusercontent.com/22195362/68453920-f3bfe200-021c-11ea-9ec7-3aec88e483ba.png)

So using `before` or `after` you can implement cursor-based pagination and using `first` or `last` and `skip` you can implement offset based pagination.

Right now we don't include any pagination metadata which you are expecting but we might implement something like that in the coming weeks as it is in the current spec of photonjs here: https://github.com/prisma/specs/tree/master/photonjs#experimental-meta-response

**Comment by SvitlanaShepitsena** [comment]
Thank you !

**Comment by SvitlanaShepitsena** [comment]
Thank you, pantharshit00.  Looking forward for PageInfo meta-data.... I will try to implement in myself, though I will have to do it for each type  but in my case it's so many. And if you have generic implementations then I can easily switch. 

If you implement metadata and do not forget let me know please as I am eagerly waiting for:-)! THANK YOU GUYS!

**Comment by marcjulian** [comment]
Are you still planing on implementing pagination metadata?

**Comment by janpio** [comment]
Best create a new issue @marcjulian to get this properly looked into.
