### ISSUE TITLE
Error: The certificate was not trusted

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#884]
Hello, I've got this error today with latest alpha:

`prisma2@2.0.0-alpha.281, binary version: c55e482a7a27ec30ea41b074ffb3de8a1a40c36e`

![image](https://user-images.githubusercontent.com/7302317/68206990-4eafca00-ffce-11e9-9e55-077ac97b5a9a.png)

PS: I'm with sslmode=prefer and report id 457

**Comment by pantharshit00** [comment]
Can you please tell me where your database is hosted?

**Comment by yovanoc** [comment]
On a random Vultr server

**Comment by pantharshit00** [comment]
You are trying to access the postgres instance over localhost on the vultr instance or you are using that vultr instance locally on your machine?

**Comment by yovanoc** [comment]
I'm not sure to understand the question. All was working before but I think I'm using this db locally. I just put in the datasource url my db connection string and use this with a local server

**Comment by pantharshit00** [comment]
I am trying to ask are you trying to connect to your vultr server where postgres is hosted from your development machine or you are running you prisma2 application on the same vultr box in which your database is hosted?

**Comment by yovanoc** [comment]
Oh no the database is in the vultr server, and i'm locally trying to use this database

**Comment by iherger** [comment]
I am having the same problem.

- prisma2@2.0.0-alpha.282, binary version: 4d50094c10949656143dbc604bc13c784954c990
- database hosted on DigitalOcean, graphql/prisma2 dev server hosted locally

**Comment by williamluke4** [comment]
Currently receiving the same error
-  Database is hosted on Heroku/AWS
- prisma2@2.0.0-preview016, binary version: 377e2db71bae5da19d0090558c8819ff57dfdfc6

**Comment by williamluke4** [comment]
@iherger  Preview 15 fails for me,
prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe

**Comment by janpio** [comment]
@iherger @williamluke4 Can you please make sure all the information about what you are actually doing is provided in your comment - so it is easy and straightforward for @pantharshit00 to try to reproduce the problem.

**Comment by iherger** [comment]
@janpio , @pantharshit00 

1. new project, no previous database migrations
2. postgresql database hosted on DigitalOcean (connection string works fine)
3. running `prisma2 lift save` produces the error above 

The same three steps with a local postgresql database work fine.

**Comment by pantharshit00** [comment]
I can confirm this bug in `prisma2@2.0.0-preview016, binary version: 377e2db71bae5da19d0090558c8819ff57dfdfc6`

![image](https://user-images.githubusercontent.com/22195362/68452847-bdcd2e80-0219-11ea-8e8d-26e342b9b59a.png)


Thanks for the reproduction steps @iherger :)

**Comment by williamluke4** [comment]
Adding `sslaccept=accept_invalid_certs` to your datasource url should work for now

**Comment by iherger** [comment]
@williamluke4 , thanks, that works indeed for now.

**Comment by tomhoule** [comment]
I can confirm the discrepancy between lift and the `psql` CLI connecting to the same database with the same SSL settings, we're investigating.

In the meantime for setups that are not security sensitive, @williamluke4 's workaround works :)

**Comment by tomhoule** [comment]
I spent a lot of time investigating this, and the conclusion is that what we are doing is not buggy, but much stricter than most other postgres clients. We will relax the current behaviour a bit (otherwise you would have to pass certificate files to the postgres connection in nearly every scenario). I will keep this issue up to date.

**Comment by williamluke4** [comment]
@tomhoule Why is it that this only cropped recently? Was the code change recently to make the certificate file required by default?

**Comment by tomhoule** [comment]
Yes, we implemented passing custom certificates for postgres connections a few weeks ago and I think that's when the decision was made.

**Comment by jwld** [comment]
Encountering the same issue with a postgres database hosted on heroku

**Comment by BiscuiTech** [comment]
I have a few issues currently with the Prisma2 platform and I think it all stems from this issue (unless majorly mistaken). 

I have tried all the params above without success, on both localhost and hosted on DO. The same error seems to show up on a variety of steps. Sometimes on prisma2 lift up, lift save, dev. Sometimes not at all, but later on during prisma2 dev. 

I have created this #999 which seems to be the same error on #919. 

I'd really grateful if someone had a temporary workaround while the devs iron this out.

**Comment by tomhoule** [comment]
This is fixed upstream, the change should make it in preview 18 :) More context in https://github.com/prisma/specs/issues/325

**Comment by BiscuiTech** [comment]
> This is fixed upstream, the change should make it in preview 18 :) More context in [prisma/specs#325](https://github.com/prisma/specs/issues/325)

Has this been fixed in 18? Because the notes do not mention this issue.

**Comment by dizzyn** [comment]
I have 2.0.0-preview018.2 and the problem is still there

**Comment by BiscuiTech** [comment]
> I have 2.0.0-preview018.2 and the problem is still there

The devs haven't replied, but I am pretty sure it's fixed. I haven't had the issue ever since I updated. Now it's mostly the lift engine panicking at every turn.

Can you make sure you have prisma 18.2 throughout your stack? Your global pckg, your local file and your server, if any?

**Comment by dizzyn** [comment]
I have just tried this approach:
1. Setup local environment with a Prisma schema pointed to the local DB and run the `prisma2 generate` -- works without problem
2. Prepare new postgress on Heroku and change the link in the local schema to the remote one and call again the  `prisma2 generate` -- seen the error
3. Fixed the postgress URL by the parameter: `sslaccept=accept_invalid_certs` annd clall the command again -- now it works fine, the remote database were generated.

So IMHO the problem is still there

**Comment by BiscuiTech** [comment]
@janpio 
Could we get a clarification on this?

**Comment by dizzyn** [comment]
--- NO LONGER VALID ---

I have tried to replicate that again to provide more details with the 2.0.0-preview018.2 and it works FINE. So the error was on my side somewhere, probably by using the npx that uses 017 version. 

Sorry for that and thank you for the good work.

**Comment by janpio** [comment]
By my knowledge this should work as expected, sorry I did not get to confirm this earlier - but happy you figured it out yourself.
