### ISSUE TITLE
Connecting to AWS Aurora Serverless?

### ISSUE THREAD

**Issue by tibotiber** [prisma/prisma2#885]
Hi, 

The points on serverless deployments found [here](https://github.com/prisma/prisma2/blob/master/docs/photon/deployment.md#photon-in-faas-environment-eg-aws-lambda-netlify) as well as the comment by @sorenbs [here](https://github.com/prisma/prisma2/issues/276#issuecomment-516782498) are great. 

I was wondering if anyone has tried connecting prisma (1 or 2) to a Aurora (Serverless)? Is that supported? Would I have an issue being on a different VPC?

Thanks

**Comment by pantharshit00** [comment]
Yes, it is supported as it is MySQL/Postgres compatible.

**Comment by pantharshit00** [comment]
If you getting any issues while using it, feel free to open an issue about it.

**Comment by tibotiber** [comment]
Thanks. Feel free to close this.

**Comment by mruzekw** [comment]
Is it possible to connect via the Aurora Data API? (Basically an HTTP API without a database connection in the lambda.)

**Comment by pantharshit00** [comment]
@mruzekw We currently don't support that but in the future, it would be possible to write a connector for that. But that is a bit far on the roadmap, current goal is to stabilize Prisma 2.

**Comment by mruzekw** [comment]
Thanks, @pantharshit00. What is the best way right now to connect to a DB in a serverless environment like AWS Lambda? Are you aware of the mysql-serverless connector? https://github.com/samdei/mysql-serverless Would this work?

Would appreciate your guidance. Thanks.

**Comment by janpio** [comment]
Please open a new issue about this @mruzekw.
