### ISSUE TITLE
Create "Is Prisma 2 ready yet?" resource

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#89]
I think we should create a document called: “Is Prisma 2 ready yet?” which gives people a more “casual” answer and links to the roadmap + current limitations. This is a lot more approachable for people to come back to and check the process than parsing a list of limitations etc. Ideally we’d even come up with a way how people could “subscribe” to this?

Similar: http://isfiberreadyyet.com/

**Comment by FrankSandqvist** [comment]
I'd love to be notified whenever I can start thinking about migrating without worrying about breaking changes.

**Comment by ScottAgirs** [comment]
Even a rough roadmap/timeline would be go a long way!

**Comment by ScottAgirs** [comment]
Even just a rough roadmap/timeline would go a long way

**Comment by helsont** [comment]
https://www.isprisma2ready.com
