### ISSUE TITLE
@prisma/sdk postinstall

### ISSUE THREAD

**Issue by iherger** [prisma/prisma2#891]
`@prisma/sdk` has a postinstall script that assumes `yarn` is installed. This can break deployments on e.g. Heroku. 

Therefore it might be better to use `node scripts/download.js` instead of `yarn download` as the postinstall script.

**Comment by timsuchanek** [comment]
Thanks @iherger ! Just fixed it in the latest version `@prisma/sdk@0.0.22`.
It will also soon not be necessary anymore to have that dependency installed.
