### ISSUE TITLE
how list work ?

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#892]
in schema.prisma

model User {
  id       String  @default(cuid()) @id
  email    String  @unique
  password String
  posts    Post[]
  name     String?
}

the type Post[] , how does it work ? since when i migrate this schema to postgresql using Lift, there is no column posts inside the table User at all .  so how exactly type list work ?

**Comment by justicejoe** [comment]
wrong

**Comment by matthewmueller** [comment]
Hi @justicejoe 👋

`Post[]` actually has no column in the database, the column is on the other side `Post.user`.

It's like this:

```groovy
model User {
  id      Int     @id
  blogs   Blog[]
}

model Post {
  id      Int     @id
  user  User
}
```

Results in:

```sql
create table User (
  id integer primary key
);

create table Post (
  id integer primary key,
  user integer not null references User(id)
);
```

Does that make sense?
