### ISSUE TITLE
Docs for the `postinstall` script of the `prisma2` npm package

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#895]
We should document what the `postinstall` script does when people run `npm i -g prisma2` and why it's necessary.

Some context from the public Prisma [Slack](https://slack.prisma.io):

![image](https://user-images.githubusercontent.com/4058327/68378162-ea1a7980-014b-11ea-95d7-74716ed976c0.png)

**Comment by steebchen** [comment]
@timsuchanek Why do we need to fetch the prisma binaries at install time? Isn't it fetched when running commands such as `prisma2 dev` or `prisma2 generate` anyway?

**Comment by nikolasburk** [comment]
I've added the docs here: https://github.com/prisma/prisma2/blob/master/docs/prisma2-cli.md#the-postinstall-hook
![image](https://user-images.githubusercontent.com/4058327/68695208-e5562b00-057a-11ea-8978-0527fb39e066.png)
