### ISSUE TITLE
how to implement m:n relation in the schema.prisma

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#897]
when something like this occur

```
model Post {
  id         Int        @id
  categories Category[]
}

model Category {
  id    Int    @id
  posts Post[]
}
```

how to implement many to many relation from schema like this after migrate to postgres using photon (reference to from https://github.com/prisma/prisma2/blob/master/docs/relations.md) since there is not much example about this case.

**Comment by pantharshit00** [comment]
I am not sure what exactly you are asking here. The schema you have provided will create a Many to Many(m:n) relation between Post and Category tables in postgres using a join table(which will be automatically created)
