### ISSUE TITLE
prisma2 init flow is throwing "File name too long" 

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#904]
After installing preview 16, after following the following init flow:
1. prisma2 init
2. Blank project
3. SQLite
4. Selecting both Photon and Lift > Confirm
5. Typescript
6. Demo script

It is throwing the this Rust panic:
![image](https://user-images.githubusercontent.com/22195362/68454812-cfb1d000-021f-11ea-87fb-aa5d0fb6a881.png)

My suspicion is that this is caused by https://github.com/prisma/prisma2/pull/841 so I am going to classify this as a regression. I use that init flow a lot to reproduce issues, so I will appreciate this being fixed relatively quickly.

**Comment by pantharshit00** [comment]
Version: `prisma2@2.0.0-preview016, binary version: 377e2db71bae5da19d0090558c8819ff57dfdfc6`

**Comment by homoky** [comment]
Same here.

**Comment by janpio** [comment]
We are looking into this right now and working on finding a fix.

**Comment by timsuchanek** [comment]
Thanks for reporting! We just released a patch release to hot fix this!
https://github.com/prisma/prisma2/releases/tag/2.0.0-preview016.1
