### ISSUE TITLE
Can't run prisma init with existing MySQL db

### ISSUE THREAD

**Issue by PeterDraex** [prisma/prisma2#909]
Steps to reproduce:
1. Run `prisma2 init eshop-test`
2. Select *Blank project*
3. Select *MySQL*
4. Enter database details
Host: localhost
Port: 3306
Username: root
Password: (left empty)
Database name: (provided)
5. Error is shown:
```
⠦ Introspecting MySQL schema  with 62  tables.
 ERROR  Introspection failed:
Error: Command failed with exit code 38 (ENAMETOOLONG): C:\Users\HP\AppData\Roaming\npm\node_modules\prisma2\query-engi
ne-windows.exe cli --dmmf_to_dml {"con................... very loooong JSON ........

```

**Comment by PeterDraex** [comment]
I've also tested doing this through WSL (Ubuntu on Windows), that gave me another error.
```
⠋ Introspecting MySQL schema  with 61  tables.
 ERROR  Introspection failed:
Error: Command failed with exit code 2 (ENOENT): /mnt/c/Users/HP/AppData/Roaming/npm/node_modules/prisma2/query-engine-l
inux-glibc-libssl1.1.0 cli --dmmf_to_dml {"config":{"datasources....... very loooong JSON .....
```

**Comment by pantharshit00** [comment]
This should be fixed with Preview 16.1. See https://github.com/prisma/prisma2/issues/904

So can you please try this again and report back as I was unable to reproduce this with `prisma2@2.0.0-preview016.1, binary version: 54c4d8ce690254b5d0c77a21361896a6ca3fc4b7`

**Comment by PeterDraex** [comment]
I've tried this with `prisma2@2.0.0-preview016.2`. I got a little further. Now it's failing when creating demo script:

```
PS F:\PrismaTesting> prisma2 init eshop-test

Preparing your demo script (TypeScript) ...

✔  Downloading the demo script from GitHub ...
⠙  Extracting content to eshop-test ...
3  Installing dependencies with: `npm install` ...
4  Preparing your database ...
 ERROR  Error during command execution

Schema parsing error: Unexpected token. Expected one of: End of block ("}"), enum field declaration.
  -->  schema.prisma:680
   |
679 | enum OrderMessagesAuthorTypeEnum {
680 |   admin-action
   |        ^ Unexpected token.
681 |   admin-message
   |
```

**Comment by pantharshit00** [comment]
Looks like you are introspecting a database instead of starting from scratch and looks like an enum in your database has `-` in it. I think this is a bug in our introspection logic and it might be automatically get fixed once we start using the introspection engine written in rust instead of current typescript one.

cc @do4gr maybe this might interest you.

Marking this as a confirmed bug.

**Comment by divyenduz** [comment]
We [rewrote introspection](https://github.com/prisma/prisma2/releases) recently. Can you please see if this issue still exists in the latest alpha or preview?

**Comment by PeterDraex** [comment]
This is fixed in Rust introspection
