### ISSUE TITLE
Embeds are not working with prisma2

### ISSUE THREAD

**Issue by kartikthapar** [prisma/prisma2#91]
Using the existing example:

```
embed Address {
  street: String
  zipCode: String
}
```

The error is here: https://gist.github.com/kartikthapar/0a0f71bc5faa6e9d1cbf8965d9072f88.

Probably a bug.

**Comment by pantharshit00** [comment]
These haven't been implemented yet.

I think this issue is duplicate of https://github.com/prisma/lift/issues/43

**Comment by kartikthapar** [comment]
Sounds good. Closing this in favor of prisma/lift#43.
