### ISSUE TITLE
debug mode docs don't match types

### ISSUE THREAD

**Issue by chrisdrackett** [prisma/prisma2#911]
in the docs here:

https://github.com/prisma/prisma2/blob/master/docs/photon/api.md#debugging

it mentions debug mode can be used with `const photon = new Photon({ debug: true })` however this raises an error in practice:

`Argument of type '{ debug: boolean; }' is not assignable to parameter of type 'PhotonOptions'.`

It seems `log` is available and `__internal: { debug: true }` not sure if either or both of these is equivalent.

**Comment by pantharshit00** [comment]
Yes, it is indeed a typing. If you will execute it in JS, it logs the debug output.

Thanks for catching this!

**Comment by nikolasburk** [comment]
Hey @chrisdrackett, thanks a lot for opening this issue! I couldn't reproduce the error `Argument of type '{ debug: boolean; }' is not assignable to parameter of type 'PhotonOptions'.` that you shared, can you confirm that this actually works in the latest release?

I did update the docs though to also document the `log` option and the different log levels that can be provided: https://github.com/prisma/prisma2/blob/master/docs/photon/api.md#debugging

Let me know if that addresses your issues! 🙂
