### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by SvitlanaShepitsena** [prisma/prisma2#913]
Hi @SvitlanaShepitsena 

Thanks for the kind words 🙌 

Right now we provide properties from which you can implement both cursor or offset based pagination:
![image](https://user-images.githubusercontent.com/22195362/68453920-f3bfe200-021c-11ea-9ec7-3aec88e483ba.png)

So using `before` or `after` you can implement cursor-based pagination and using `first` or `last` and `skip` you can implement offset based pagination.

Right now we don't include any pagination metadata which you are expecting but we might implement something like that in the coming weeks as it is in the current spec of photonjs here: https://github.com/prisma/specs/tree/master/photonjs#experimental-meta-response

_Originally posted by @pantharshit00 in https://github.com/prisma/prisma2/issues/883#issuecomment-551400895_

**Comment by SvitlanaShepitsena** [comment]
I am sorry @pantharshit00 

I decided to implement cursor-based pagination. So in my nexus model I had 

    ` t.crud.posts({
            type: 'Post',
            ordering: true,
            filtering: true,
            pagination: true,
        })`

However, when I went to apollo gql first, skip works perfectly.

` query posts(
    $orderBy: PostOrderByInput
    $first: Int
    $where: PostWhereInput
    $skip: Int
  ) {
    posts(orderBy: $orderBy, first: $first, skip: $skip, where: $where) {
      ...PostFragment
    }
  }
  ${Fragment.fragments.post}
`
But first after gives me a strange error, 
![Selection_240](https://user-images.githubusercontent.com/5209402/68535680-c30aa600-030b-11ea-99d6-cbaa31287181.png)

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma-labs/nexus-prisma/issues/530 as this looks like a nexus prisma issue to me.
