### ISSUE TITLE
Prisma2 install fails in corporate proxy / firewall

### ISSUE THREAD

**Issue by prisma2user** [prisma/prisma2#916]
Left a message over in the Prisma slack channel, but didn't get reply likely due to most people not using Prisma2 behind corporate proxy / firewalls, so posting an issue here

Recently discovered Prisma / Prisma2 and was looking to test it out for a project at work, but ran into an issue with running `npm install -g prisma2` since it looks like there is a call out to an s3 bucket to download a binary which in our environment we don't have access to directly proxy out to get this.

In our environment, npm packages are proxied through an artifact repository / proxy like Artifactory or Nexus, which allows us to centralize management and security around what npm packages get pulled into the environment which then can act as a local cache of any artifacts we pull in. This allows us to also retain better security controls since we don't allow opening up corporate wide proxy holes to allow things to connect out to the internet directly.

This works well for most npm packages and ensures that when a npm package (or any other third party code) attempts to connect out to the internet it will fail (for security reasons). In this case, it looks like prisma2 is attempting to download a binary after it detects what kind of system its being installed on and attempting to download this from an S3 bucket.

We have ran into similar packages that require downloading a binary as part of the installation process, but most of the ones we have ran across attempt to download these release binary artifacts from their own GitHub project. 

For instance, node-sass will download its binary from a URL like https://github.com/sass/node-sass/releases/download/v4.13.0/linux-x64-79_binding.node which you can review all the binaries they produce for various relaeases on their GitHub releases page https://github.com/sass/node-sass/releases. They also provide a few different ways to override the download url so that within a corporate proxy / firewall enviroment the user can specify where to download this from (see https://github.com/sass/node-sass#binary-configuration-parameters).

This is great for us because we can configure an environment variable to have the package download its binary from our artifact repository which can then call out to the upstream GitHub releases to pull it into the environment if we don't already have it and we can setup access control policies to whitelist only specific GitHub url paths to only allow proxying in the exact resources we will allow to be pulled into the environment to maintain strict security.

It would be great if a similar type of release artifact binary download could be provided for prisma2 as well,  but I wanted to provide my use case an open a dialog on this topic to get some feedback and hopefully work towards a solution to accommodate this type of environment for installing prisma2.

**Comment by pantharshit00** [comment]
We actually do provide proxy option so that you can use Prisma 2 behind a corporate proxy: https://github.com/prisma/prisma2/blob/dbb9ed844c10728b45ef450d5c85969a3b4b694d/docs/prisma2-cli.md#using-a-http-proxy-for-the-cli

Also, you can find a list of our binaries here: https://github.com/prisma/prisma2/blob/66049c779613f30c5e762ff14b1a2bcd3834c653/docs/core/generators/photonjs.md#available-binaries. Please let me know if this resolves the issue for you

**Comment by prisma2user** [comment]
@pantharshit00, thanks for your reply to point out where these binaries are located since it seems to be part of photonjs instead of primsa itself, however, I feel our use case here is a bit different than those previously stated so I will elaborate a bit more.

In regard to configuring `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` will not work in our environment because the network we leverage is very secure and no outbound internet network connections can be made directly from a machine by providing these environment variables because we do not allow any machine to proxy their connection to the internet directly.

Unlike most corporate networks, you can almost think of this network to being closer to an air-apped network, but instead of having literally no connection to the internet the control flows to connect / pull in third party libraries are heavily restricted and must be made to an internal server where this server is then configured to inspect requested objects / urls and only permit specific network requests to proxy only those exact objects that are permitted to their upstream / actual network location. But within the network, any machine, user or script would only be able to download these objects from this internal server.

I've done a bit more digging into photonjs source and found the a few places where the url appears to be crafted to the s3 bucket, but will provide one for reference and talk more about this.

https://github.com/prisma/photonjs/blob/90a5fc5b24fa8be7f6dd67c95a85628cab338597/packages/fetch-engine/src/util.ts#L59

```
export function getDownloadUrl(channel: string, version: string, platform: string, binaryName: BinaryKind) {
  const extension = platform === 'windows' ? '.exe.gz' : '.gz'
  return `https://s3-eu-west-1.amazonaws.com/prisma-native/${channel}/${version}/${platform}/${rewriteKind(
    binaryName,
  )}${extension}`
}
```

So basically what happens here is that when we install prisma, photonjs jets installed and at some point it woudl seem that photonjs is attempting to install the binary engine for our platform and this crafted S3 url is returned and then our local machine where we are installing primsa then attempts to connect out to S3 to get this but fails due to network restrictions.

What I'm asking for in this ticket is that rather than hard coding this S3 URL, check to see if a user has provided an environment URL (e.g. PHOTONJS_CDNURL) to partially override the url for example:

```
user@server: ~$ export PHOTONJS_CDNURL=https://artifact-server.internal-domain.com/proxy-prisma-binary
user@server: ~$ npm install -g primsa2
```

Then photonjs can request to download its engine binary from https://artifact-server.internal-domain.com/proxy-prisma-binary/prisma-native/path/to/binary where then our artifact server can determine what proxy url is being requested, check to see if we have already pulled the binary into our environment and return the binary or if we don't have it we check to ensure the path requested is legitimate and then connect to the configured proxy upstream url (i.e. S3) and download and cache it.

One last piece I will share doesn't change the overall workflow described here, but just from how we have noticed various repositories manage / distribute these binaries is that if you leverage GitHub itself we already have proxy endpoints to permit access to GitHub and whitelist connections to specific projects to permit only those binaries from being downloaded. So from our end can have a single proxy configuration where we can group / managed binaries downloaded from GitHub projects which makes it easy. Since in this case we have to connect to a different location (your S3 bucket), we will just have to set up a new repository on our end so that we can configure new upstream proxy so that when requests come in to our new internal repository they can be correctly routed out to your s3 bucket, but if it were possible to host these from GitHub itself it would be nice, but I understand if there are other use cases on your end for why you are hosting them there.

**Comment by pantharshit00** [comment]
Thanks for sharing your thoughts. Marking this as a candidate for next sprint.

**Comment by prisma2user** [comment]
Did want to follow up one more time since it dawned on me that the hard coded link is specific to s3-eu-west-1 and may also make sense to leverage a default domain being https://prisma-native.s3.amazonaws.com/ so that its not specific to any particular region.

Just providing for additional reference, but I was also looking for additional projects that host binaries on GitHub and did see that Prisma's GraphQL Playground binaries are hosted in GitHub under the project releases (e.g. https://github.com/prisma-labs/graphql-playground/releases/download/v1.8.10/graphql-playground-electron-setup-1.8.10.exe).

**Comment by silemelon** [comment]
Same here,I'm in china,npm install -g prisma2 can't work but can wget gz package through environment variable.

**Comment by matthewmueller** [comment]
internal note: drop for this sprint

**Comment by divyenduz** [comment]
Thanks for a great discussion everyone, closing this in favor of https://github.com/prisma/prisma2/issues/1333 feature request which pin points the problem.
