### ISSUE TITLE
Create database from init flow when it doesn't exists

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#921]
![image](https://user-images.githubusercontent.com/22195362/68661594-36f1bc00-0561-11ea-88bc-e2411032d0b5.png)

Right now if the database doesn't exist in the database server, we are unable to proceed through the init flow and we need to manually create the database. What I would like is an option similar to that in lift(screenshot below) that will allow us to create this database within the init flow.

![image](https://user-images.githubusercontent.com/22195362/68663407-98fff080-0564-11ea-98e0-2d1a1f413572.png)

**Comment by janpio** [comment]
This option now exists @pantharshit00. Unfortunately it is _always_ triggered as the database/schemas you entered is ignored, so we will have to retest this after the other bug is fixed to see if the behavior is as expected/wanted.

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
