### ISSUE TITLE
How Prisma2 RealTime compares to Prisma1 and Apollo Server

### ISSUE THREAD

**Issue by AlexandruSerban142** [prisma/prisma2#929]
Hello,

I am new to graphql so I have a question to ask related to real time. We are in the process of developing an app that will need some Real Time Updates & Push notifications on the mobile side. I am really interested to know what I can do with prisma1 real time vs prisma2 (I know that the real time feature is not build in yet) vs Apollo Server subscription. From what I can tell with what I know, with apollo I can do all I need, like when a user mutates some data, that data to be updated on all clients. Right now basically I don't understand the role of the prisma, and what it is adding over the apollo server features in terms of real time updates. 

Also great work with the prisma project and keep up with prisma2!

**Comment by pantharshit00** [comment]
Hi,

First of all, we don't have dedicated subscription support right now in Prisma 2(please see #298). So right now we can't really compare Prisma 1 vs Prisma 2 in terms of subscription.

Now Apollo Server subscription, you need something there to access data from the database, you can use Prisma 2 for that. So you would use Prisma 2 with apollo server to implement subscriptions. Prisma will act as a data access layer there.

**Comment by andreasanta** [comment]
@pantharshit00 Do you have an example of Prisma2 as ORM with Apollo Server as GraphQL server?

**Comment by pantharshit00** [comment]
Yes, please have a look here: https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-apollo-server

**Comment by andreasanta** [comment]
Thank you, I see the example uses Nexus. Do you have an example with typedefs and resolvers passed in to Apollo Server, without using Nexus for schema generation, but just prisma.schema? Thanks!

**Comment by pantharshit00** [comment]
@andreasanta Can you please open a new issue about that? We will add it to the docs after it is tracked by an issue

**Comment by andreasanta** [comment]
@pantharshit00 Created issue #1281 thank you.

**Comment by divyenduz** [comment]
Thanks @andreasanta for creating the issue. Since, that concern is already track and general subscription support is being tracked here: https://github.com/prisma/prisma2/issues/298

I think we can close this one?

**Comment by andreasanta** [comment]
@divyenduz Yes thank you, but I believe we should ask @AlexandruSerban142 which reported the issue initially :)

**Comment by divyenduz** [comment]
@AlexandruSerban142 oops, my bad, thanks for asking this question. I believe that it is answered and I will close this issue. Please feel free to comment on the issue and tag me if you do not agree. Thanks 🙏
