### ISSUE TITLE
Fetch the correct binary for EC2 started with Amazon Linux 2 + x86

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#93]
Current binary resolution gets a binary that fails with this error (for `migration-engine`): 

```
  LiftEngine:stderr /home/ec2-user/.nvm/versions/node/v10.4.0/lib/node_modules/prisma2/migration-engine: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
  LiftEngine:stderr  +0ms
Error: Error: Error in lift engine for rpc listMigrations:
  /home/ec2-user/.nvm/versions/node/v10.4.0/lib/node_modules/prisma2/migration-engine: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by divyenduz** [comment]
Further learnings: 

![image](https://user-images.githubusercontent.com/746482/60656415-ac30e000-9e4f-11e9-8054-37d87b9b6b9f.png)

This AMI does not have `openssl` installed. In its current state, we need to manually install `openssl` and if required, fetch the correct binary. In this case the lambda binary works.

**Comment by timsuchanek** [comment]
This sounds like a documentation issue, as we can only detect the libssl version if it's installed.
We would have to add a guide how to handle this specific AMI image with Photon.

**Comment by divyenduz** [comment]
This issue is not reproducible anymore. I am closing this, please feel free to reopen if the problem persists for anyone.
