### ISSUE TITLE
Hanging on "Preparing your database ..." during tutorial

### ISSUE THREAD

**Issue by darrylyoung** [prisma/prisma2#932]
Hi,

I'm currently going through [this](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md) tutorial. I created a MySQL 5.7 database on RDS. It was going fine until it seemed to hang on _"Preparing your database ..."_.

See the screenshot below (note: I hid the app name; that was showing as expected):

![prisma](https://user-images.githubusercontent.com/1460800/68780036-e8fab800-0635-11ea-95f1-cf9872be1cf5.png)

As of now, it's been over 30 minutes like this so it seems like there's definitely an issue somewhere. I'm running macOS `10.15.1`, if that matters, and using Prisma 2 `2.0.0-preview016.2`.

Let me know if you'd like any more information. Thanks.

_Update: note that I cancelled the hanging process and the `schema.prisma` seemed to have been created successfully anyway, complete with the correct `datasource` `url`._

**Comment by pantharshit00** [comment]
Hi,

Can you please try running `prisma2 lift save` and `prisma2 lift up`. If you encounter `certificate not trusted` error, this might be a consequence of #884

**Comment by janpio** [comment]
Hey @darrylyoung, did you see the message from @pantharshit00? Would be great if you could have a look, it would help us reproduce and later fix this problem.

**Comment by darrylyoung** [comment]
Hi, guys. Apologies for the delay in coming back to this thread. Unfortunately, once I was hit by that issue I decided to run a local MySQL database for my Prisma project so ended up dropping the one in RDS. Thanks for the help, though. I really appreciate it.
