### ISSUE TITLE
`prisma2 dev` fails with `ETIMEDOUT`

### ISSUE THREAD

**Issue by phil-r** [prisma/prisma2#933]
At first it does nothing for some time and then fails with `ETIMEDOUT`

Worked fine earlier today 

Full error:
```
Error: request to https://s3-eu-west-1.amazonaws.com/prisma-native/master/54c4d8ce690254b5d0c77a21361896a6ca3fc4b7/darwin/prisma.gz failed, reason: connect ETIMEDOUT 52.218.106.139:443
```

**Comment by pantharshit00** [comment]
Hi,

I was successfully able to download the binary using that URL. Can you please try again?

**Comment by phil-r** [comment]
Looks like it was some connectivity issue between my isp and s3, worked with vpn and works fine now.
