### ISSUE TITLE
`prisma2 lift save` creates two new `.db` files for SQLite

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#936]
I have this Prisma schema in a new project:

```prisma
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
}
```

This is the file structure:

```
$ tree .
.
├── README.md
└── prisma
    └── schema.prisma

1 directory, 2 files
```

When I run `prisma lift save` from the project root dir, two `.db` files are being created, one in the project root dir, the other one inside the `prisma` dir:

```
$ tree .
.
├── README.md
├── dev.db
└── prisma
    ├── dev.db
    ├── migrations
    │   ├── 20191114112229-init
    │   │   ├── README.md
    │   │   ├── schema.prisma
    │   │   └── steps.json
    │   └── lift.lock
    └── schema.prisma

3 directories, 8 files
```

I'm on:

```
prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0
```

**Comment by pantharshit00** [comment]
I can also confirm this bug.

![image](https://user-images.githubusercontent.com/22195362/68859576-97256100-070d-11ea-8bbd-c62dc8c21a0f.png)

**Comment by madebysid** [comment]
I'm also seeing this for `prisma2 init` with `Blank Project` > `SQLite` > `JavaScript`, `Demo Script`.
One DB file is in the project root (0KB in size) and the other one is in the `prisma` directory.

Quite possibly the same issue.

**Comment by tomhoule** [comment]
We reproduced the bug and found where it comes from, but there is no spec regarding on the right thing to do. Issue: https://github.com/prisma/specs/issues/329

**Comment by frntmp** [comment]
I think we found a related issue: 

When the url to the sqlite-db contains `..`, i.e. something like `url: "file:../../<some_folder>/data.db"`, the process hangs after selecting `Yes            Create new Sqlite database <some_folder>/data.db`.

Let me know if this is unrelated and I should create a separate issue.

**Comment by pantharshit00** [comment]
Can you please check if there is any error thrown when tracing is on @frntmp 

To enable tracing, run `export DEBUG=*` or run `set DEBUG=*` if you are on windows.

**Comment by pantharshit00** [comment]
@frntmp looks like someone else also reported the same, I can confirm this bug.

It is being tracked here: https://github.com/prisma/lift/issues/219

**Comment by timsuchanek** [comment]
Thanks for reporting! A fix is available on the latest prisma2 alpha.
You can try it out with `npm i -g prisma2@alpha`.
