### ISSUE TITLE
JSON Object as property

### ISSUE THREAD

**Issue by AlexandruSerban142** [prisma/prisma2#941]
Hello Guys,

How should I declare a JSON object into a prisma2 model?

**Comment by pantharshit00** [comment]
Hello

In the current state, you can't natively store JSON with prisma2. You will need to store it as a string and you will need to serialise and deserialize them manually. and  But in the coming when type system is implemented(see spec here: https://github.com/prisma/specs/tree/master/schema#type-definitions-provided-by-connectors), you will be able to use the native JSON type in postgres and all other types provided by your database.

**Comment by pantharshit00** [comment]
Closing this as a duplicate of https://github.com/prisma/prisma2/issues/186
