### ISSUE TITLE
Document Connection Management for Lambda

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#942]
We've decided that rather than provide a fancy solution for doing connection management in Lambda, we'll instead document how to optimally configure Photon based on the memory size of your Lambda and the size of your RDS instance

**Update** [See below](https://github.com/prisma/prisma2/issues/942#issuecomment-557168564) for details

**Comment by saturday-scott** [comment]
> We've decided that rather than provide a fancy solution for doing connection management in Lambda, we'll instead document how to optimally configure Photon based on the memory size of your Lambda and the size of your RDS instance
> 
> More Details: https://www.notion.so/prismaio/Connection-Management-18600641ee8a4f7b9c40652214be1be6
> 
> Next Steps:
> 
> * [ ]  Engineering: Map out the number of CPUs you get based on the memory you select in Lambda
> * [ ]  Content Team: Explain how you should set your lambda concurrency limits in the docs, maybe provide an interactive calculator

Hey excited about the update! Is this is a temporary solution or something that is planned as part of Prisma Framework setup? Also sadly to view the content in the link it appears that one needs to be part of Prisma team

![image](https://user-images.githubusercontent.com/57911125/69354629-69c93d80-0c4e-11ea-9077-c90048b0b562.png)

**Comment by matthewmueller** [comment]
@saturday-scott sorry for plopping an internal link in a public issue! We're still researching the details, but here's the outline. We'd love if you wanted to make headway on this research for your own work!


## Lambda CPU Cores by Memory

| Memory (MB) | CPU (Cores) | Pool Size (`= 2 * CPU + 1`) |
| :---------: | :---------: | --------------------------- |
|     128     |      ?      | ?                           |
|     256     |      ?      | ?                           |
|     512     |      ?      | ?                           |
|    1024     |      ?      | ?                           |
|    2048     |      ?      | ?                           |
|    3008     |      ?      | ?                           |

From AWS:

> Lambda allocates CPU power linearly in proportion to the amount of memory configured. At 1,792 MB, a function has the equivalent of 1 full vCPU (one vCPU-second of credits per second).

We'll need to deploy a function that checks the number of CPU cores and then change the various memory limits and redeploy.



## Postgres RDS Connection Limits

| Instance Size | `max_connections` limit |
| :-----------: | :---------------------: |
|   t2.micro    |            ?            |
|   t2.small    |            ?            |
|   m3.medium   |            ?            |
|      ...      |            ?            |

Need to pull this information from [DB Parameter Groups](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html#USER_ParamValuesRef).

## Final Formula

```
Lambda Concurrency Limit = Math.floor(max_connections / Pool Size)
```

https://docs.aws.amazon.com/lambda/latest/dg/per-function-concurrency.html

**Comment by pimeys** [comment]
Results.

I used a small Rust app in lambda to display the number of cpus. Code is [here](https://github.com/pimeys/lambda-cpus).

| Memory (MB) | CPU (Cores) | Default Pool Size (`= 2 * CPU + 1`) |
| :---------: | :---------: | --------------------------- |
|     128     |      2      | 5                           |
|     256     |      2      | 5                           |
|     512     |      2      | 5                           |
|    1024     |      2      | 5                           |
|    2048     |      2      | 5                           |
|    3008     |      2      | 5                           |

So now I just changed the memory setting, but the reported cpu value is always the same, meaning we'll give 2 IO threads per lambda and 5 connections.

**Comment by pimeys** [comment]
WIP, updating while I find more data.

| Instance Size | used_at_start | max_conn | res_for_super | res_for_normal |
| :-----------: | :---------------------: | :---------------------: | :---------------------: | :--------------------: |
|   t2.micro    | 7 |            87          | 3                         | 77                       |
|   t2.small    | 7 |           198        | 3                         | 188 |

**Comment by matthewmueller** [comment]
Thanks @pimeys! @nikolasburk do you mind documenting this? Let me know if you need any input.

**Comment by idan** [comment]
![](https://media.giphy.com/media/l3q2LH45XElELRzRm/giphy.gif)

**Comment by matthewmueller** [comment]
@pimeys noted that since each Lambda is only servicing 1 request at a time, perhaps we should rather document the usage of `?connection_limit=1` and adjust the formulas above accordingly.

**Comment by nikolasburk** [comment]
Documented via https://github.com/prisma/prisma2/pull/1189. Thanks a lot for explaining everything @matthewmueller 🙏
