### ISSUE TITLE
Improve install behavior on linux

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma2#944]
When installing prisma2 in an ordinary Ubuntu docker image, you'll get an error, that you have to install prisma2 with `--unsafe-perm`.
We should come up with a better solution here instead of letting the user figure the situation out.

**Comment by LongLiveCHIEF** [comment]
@timsuchanek this is being tracked in #938. would you mind closing this in favor of that?

**Comment by timsuchanek** [comment]
@LongLiveCHIEF this is just mentioning the `--unsafe-perm` aspect of your issue. In your issue you also mention GPG and proxies. In order to have a separate working item we can plan, I created this issue.

**Comment by divyenduz** [comment]
`npm` also has docs to fix this behavior: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Irrespective of Prisma, if this is not addressed on linux, users need to use sudo with `npm`.

**Comment by pantharshit00** [comment]
> Irrespective of Prisma, if this is not addressed on linux, users need to use sudo with npm.

Yes, but sadly most of the online tutorials encourage the use of `sudo` for installing global packages in Linux. Also, people want to install the CLI in docker to run the migrations and it is tedious to fix permissions there.

**Comment by LongLiveCHIEF** [comment]
As far as a docker image goes, I'd rather have a `prisma2` image as a base, which already has the binaries installed globally, as opposed to starting with the base node image myself and having to figure out how to install everything.

Providing a ready made cli docker image means I only have to worry about pulling that single image, and not making sure I have connections for all the binary dependencies.

**Comment by janpio** [comment]
Please open a new issue for this request @LongLiveCHIEF. It is not related to the original problem and task that is being tracked here from @timsuchanek. Thanks.

**Comment by dodas** [comment]
@LongLiveCHIEF I don't agree with your opinion.
I, in most cases, don't want to decide about docker image based on one particular library I am going to use inside it. I will much rather have some light base and then cherry-pick software I need.

Hopefully prisma can be improved to work seamlessly in either scenario.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
