### ISSUE TITLE
Is there a way to view the generated photon API?

### ISSUE THREAD

**Issue by jwld** [prisma/prisma2#946]
With prisma 1 you could go to the url of your hosted prisma server and view the generated API in full there. This made it really easy to work out how to sort / filter etc.

Is there a way to do this with Prisma 2? I'm trying to work out how to filter by a many-to-many connection, and getting stuck because there's no way to reference what's been generated.

**Comment by pantharshit00** [comment]
Hi,

Prisma 2 doesn't really provide a GraphQL API like Prisma 1. Its architecture is a bit different. For such visibility, you can use Prisma Studio(which you can access in `prisma2 dev` now. It lists the photon query it is running on the top and you can also use autocompletion in there.

**Comment by BiscuiTech** [comment]
Just to add to the previous answer:
You can leverage TypeScript and intellisense to get nice autocompletion on `ctx.photon.[model].[action]()`.
You can also right-click and sift through the TypeScript declarations on the model. Generally, that's all I need to build my function. 

Hope this helps.

**Comment by jwld** [comment]
Thanks, both valid options

**Comment by pantharshit00** [comment]
Going to close this now, feel free to open a new issue if you have any other questions.
