### ISSUE TITLE
How do i run raw GraphQL

### ISSUE THREAD

**Issue by emahuni** [prisma/prisma2#95]
Can we query GraphQL in Prisma 2? and how?

**Comment by pantharshit00** [comment]
Hi,

I am assuming that you are referring to the GraphQL API which was exposed by Prisma 1. 

We are not exposing GraphQL API this time as it is an implementation detail. It is used as a wire protocol in Prisma 1 and we have removed it Prisma 2 and have adopted a newer wire protocol(which still currently uses GraphQL internally but we may switch it in the future with something like gRPC) between Photon and query engine.

Photon is meant to be used as ORM. You can build a GraphQL API using it. Here is an example: https://github.com/prisma/photonjs/tree/master/examples/typescript/graphql

We have also written a blog post to clear this confusion out: https://www.prisma.io/blog/prisma-and-graphql-mfl5y2r7t49c/

**Comment by emahuni** [comment]
Ok. Thank you for the clarification

**Comment by divyenduz** [comment]
We are closing this issue, please feel free to re-open a new issue if you think that the concern was not addressed.

**Comment by softmarshmallow** [comment]
link is dead. can you update it for future readers?
https://github.com/prisma/photonjs/tree/master/examples/typescript/graphql

**Comment by divyenduz** [comment]
@softmarshmallow The link has moved to https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql
