### ISSUE TITLE
how to do basic operation in photon ?

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#954]
for example if I want to query something that come before 2019-11-20 and come after  2019-11-12 and how to sort the output out of this query ? is there any document available for this kind of thing ?

**Comment by THPubs** [comment]
Earlier we could use the GraphQL Playground exposed by prisma to build our queries. But looks like prisma2 does not have a playground. Would be nice if we had a way to build our queries or a documentation. @justicejoe For now you can refer to this: https://www.prisma.io/docs/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2/ to see how to fetch filtered data. It's basically a GraphQL query. Example:

```javascript
  const users = await photon.users({
    where: {
      id: 'id',
    },
  });
```

**Comment by justicejoe** [comment]
> Earlier we could use the GraphQL Playground exposed by prisma to build our queries. But looks like prisma2 does not have a playground. Would be nice if we had a way to build our queries or a documentation. @justicejoe For now you can refer to this: https://www.prisma.io/docs/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2/ to see how to fetch filtered data. It's basically a GraphQL query. Example:
> 
> ```js
>   const users = await photon.users({
>     where: {
>       id: 'id',
>     },
>   });
> ```

So you mean that instead of the word 'prisma', I can use word 'photon' instead and it can do the same operation as in the prisma client one that you refer to ?

**Comment by pantharshit00** [comment]
Actually no. The API is a bit different.

For filtering you would do the following:
```
const users = await photon.users.findMany({
    where: {
      id: 'id',
    },
  });
```

Please read the photonjs docs: https://github.com/prisma/prisma2/blob/master/docs/photon/api.md#crud

Also, please check out examples: https://github.com/prisma/prisma-examples
