### ISSUE TITLE
Prisma2 Introspect script

### ISSUE THREAD

**Issue by shah05** [prisma/prisma2#958]
Hi,

I am trying out the Prisma2 introspect service. But when I pass all the CLI flags based on my local mysql db credential, it always prompt me to provide a database name. Can please help to check ?

![image](https://user-images.githubusercontent.com/20430495/69151091-ee17a580-0b14-11ea-9e1c-15efdc599069.png)

**Comment by shah05** [comment]
let schema: string | undefined
    if (credentialsByFlag.type === DatabaseType.mysql) {
      schema = credentialsByFlag.database
    }

I think just need to replace the return code below from schema -> database. To match the above attribute call. Please reconfirm

 if (mysqlFlags.length >= requiredMysqlFlags.length) {
      return {
        host: args['--mysql-host'],
        port: parseInt(args['--mysql-port']!, 10),
        user: args['--mysql-user'],
        password: args['--mysql-password'],
        schema: args['--mysql-db'],
        type: DatabaseType.mysql,
      }

**Comment by pantharshit00** [comment]
Can you please tell me which MySQL version you are using?

There is a similar issue regarding introspection: https://github.com/prisma/prisma2/issues/862

So this one might also get fixed automatically once we use the rust implementation of introspection instead of typescript one.

**Comment by shah05** [comment]
Hi, 

I am using MySQL 5.7.  I haven't tried for PostGres and Mongo DB yet if similar issue is found.

So means I need to wait for the rust implementation which will be in the next version is it ?

Thanks,

**Comment by pantharshit00** [comment]
Yes, introspection will be more streamlined then and we are not fixing current issues because most of them will automatically get fixed. 

I can't give you a timeline on when it will get released.

**Comment by divyenduz** [comment]
We [rewrote introspection](https://github.com/prisma/prisma2/releases) recently. Can you please see if this issue still exists in the latest alpha or preview?

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
