### ISSUE TITLE
How do querys return the count records to be used in pagination?

### ISSUE THREAD

**Issue by alaxfilho** [prisma/prisma2#959]

**Comment by pantharshit00** [comment]
Hello,

We currently do provide a count query(https://github.com/prisma/photonjs/issues/202)

Example usage:
```ts
const count = await photon.users.count()
```

It is not documented yet and its functionality is limited right now(see https://github.com/prisma/photonjs/issues/252). We are currently specing out and implementing all sorts of aggregation that you can use(https://github.com/prisma/specs/tree/master/photonjs#aggregations)

I create this issue regarding documentation of count query: https://github.com/prisma/photonjs/issues/252
