### ISSUE TITLE
Defaults for DateTime

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/prisma2#96]
If I define a Prisma2 model like this:

```
model Event {
  name String
  date DateTime @default(now())
  description String @default("")
}
```

I expect Prisma2 to consider all values with defaults as optional. While it properly works for String values, DataTime values are still required. I.e., if I create an event using this data:

```
{
  name: ""
}
```

I expect, that date and description will get defaults. But it isn't so for date. I get the error:

> Argument date for data.date is missing.

**Comment by timsuchanek** [comment]
Fixed in the latest version.
