### ISSUE TITLE
mongodb problem

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#963]
I've this error with all prisma2 command even to get the version, but it's the latest alpha now, 325 I think

PS: I only use postgres and never put "mongo" somewhere

![image](https://user-images.githubusercontent.com/7302317/69223173-2520a200-0b7b-11ea-8ba9-7f85220e1a43.png)

**Comment by timsuchanek** [comment]
Thanks for reporting @yovanoc ! We're working on it and will in a few hours have it fixed.

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
