### ISSUE TITLE
Query engine: default values should be settable

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#964]
Fields marked with the `@updatedAt` or `@default(...)` directives are currently ignored when running a `CreateOne` mutation. 

```prisma
model User {
	id        String   @id @default(cuid())
	createdAt DateTime @default(now())
	updatedAt DateTime @updatedAt
	str       String
	int       Int
	float     Float
	bool      Boolean
	date      DateTime
}
```

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/5013932/69239682-14802400-0b9b-11ea-8cdd-7100e141da60.png">

First, I think it’s a bit inconsistent, as `@id` is also a `@default` but can also be overridden. Also, just by definition, default values provide `defaults`; they shouldn't prevent you from setting them.

Second, I think settings these values should be allowed for testing applications. Currently, my use-case is testing generators (Photon Go), as I can just compare the full result of any query. This requires me to set `createdAt` and `updatedAt` to default values like `2000-01-01T00:00:00Z`, otherwise they get set to the current time which is not good for testing.

I think this should be possible just for the sake of testing. End-users may also write tests, in which case they would have the same problem if it’s not possible to set these values.

I also think there’s a good chance that users may want to set `createdAt` in some cases for whatever reasons; maybe they have some special use case where they need to set it to an earlier date.

**Comment by olup** [comment]
I spent a bit of time trying to set my dates values that have a `default` at `now`. Was wondering what I was doing wrong, but I guess I am just going to +1 this bug (yes, default are supposed to be settable, this is indeed a bug)

**Comment by steebchen** [comment]
@olup Do you use `@default(now())` in your prisma schema? Then prisma handles it for you and you don't have to set these values manually. What's your reason to set this manually? Mine is just for testing purposes as I said.

**Comment by olup** [comment]
I do use @default(now()). And i dont set my timestamps manually when I want
them to default to the said default.

However, if I do pass on a value, I would expect this value to be used, and
not the default.

For example the date and time for an event. If not set, it's now() but if I
want to set the time, earlier or later, for it, i should be able to.

I believe it works like this when setting defaults in postgres.

Or maybe i am understanding this all wrong ?

Le jeu. 21 nov. 2019 à 21:58, Luca Steeb <notifications@github.com> a
écrit :

**Comment by garyro** [comment]
I just wanted to add as I think this is part of this issue. I have 6 models in my test db. In all of them I use createdAt DateTime @default(now()).
In all but one everything works as expected. In the one model when using create the createdAt field is always set to 1970-01-01 00:00:00.000 and also returns an error of:
 Error in connector: Error querying the database: Server error: `ERROR 42000 (1065): Query was empty'
using the following mutation:
mutation {
  addUser(newUserData:{name:"test" email:"test@somewhere.com"}) {
    id
    createdAt
  }
}
If I omit the createdAt in the mutation that date is still incorrect but there is no error and the db is updated. 
Let me know if you need further info

**Comment by pantharshit00** [comment]
Hi @garyro 

`Query was empty` is a different issue(#902)


Also, you other issue is also known(https://github.com/prisma/prisma2/issues/457). It is related to having two fields with `@default(now())` in the model and engine is not working properly in that case.

**Comment by matthewmueller** [comment]
Just to clarify the expected solution: 

- `@id` works as expected. You can bring your own id
- `createdAt` should be editable, currently you cannot bring your own DateTime
- `updatedAt` should be editable, currently you cannot bring your own DateTime

**Comment by olup** [comment]
Exactly. Basicaly, any fields with a default property should be editable, but insert the default on creation if no data is passed for it.

If new datas are passed on update, it should use them.

`CreatedAt` and `updatedAt` ignore passed values as it is now, and only insert the default.

**Comment by dpetrick** [comment]
The fix will be available in Preview-18.
