### ISSUE TITLE
Error with prisma2 generate command.

### ISSUE THREAD

**Issue by SvitlanaShepitsena** [prisma/prisma2#966]
`
"Error: Error: ETXTBSY: text file is busy, copyfile '/root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/prisma2/build/query-engine-linux-glibc-libssl1.1.0' -> '/root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/@generated/photon/runtime/query-engine-linux-glibc-libssl1.1.0'", "error Command failed with exit code 1."], "stdout": "yarn install v1.19.1\n[1/4] Resolving packages...\nsuccess Already up-to-date.\n$ yarn -s generate\n\n\nGenerating Photon.js to /root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/@generated/photon\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.", "stdout_lines": ["yarn install v1.19.1", "[1/4] Resolving packages...", "success Already up-to-date.", "$ yarn -s generate", "", "", "Generating Photon.js to /root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/@generated/photon", "info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command."]}
`

I got this error when I try to run prisma2 generate or just yarn and via scripts it runs prisma2 generate. I got this error on my development machine Ubuntu 19.10 and also on my production workstation with Ubuntu 16.04. 

The solution is to purge node_modules and install it again - then everything works fine. 
Thank you

**Comment by SvitlanaShepitsena** [comment]
`"Error: Error: ETXTBSY: text file is busy, copyfile '/root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/prisma2/build/query-engine-linux-glibc-libssl1.1.0' -> '/root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/@generated/photon/runtime/query-engine-linux-glibc-libssl1.1.0'", "error Command failed with exit code 1."], "stdout": "yarn install v1.19.1\n[1/4] Resolving packages...\nsuccess Already up-to-date.\n$ yarn -s generate\n\n\nGenerating Photon.js to /root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/@generated/photon\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.", "stdout_lines": ["yarn install v1.19.1", "[1/4] Resolving packages...", "success Already up-to-date.", "$ yarn -s generate", "", "", "Generating Photon.js to /root/go/src/github.com/SvitlanaShepitsena/matevaman/nexus/node_modules/@generated/photon", "info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command."]}`

I got this error when I try to run prisma2 generate or just yarn and via scripts it runs prisma2 generate. I got this error on my development machine Ubuntu 19.10 and also on my production workstation with Ubuntu 16.04. 

The solution is to purge node_modules and install it again - then everything works fine. 
Thank you

**Comment by pantharshit00** [comment]
@SvitlanaShepitsena 

Can you please share the version of Prisma 2 that you are using? Also, can you list out exact steps to reproduce this? Also, please share your datamodel if possible :)

**Comment by tvvignesh** [comment]
@pantharshit00 Facing the same issue on my end as well. Run `prisma2 dev` and then save the `schema.prisma` file with/without making any change and my cli throws this error. Have to run `prisma2 dev` again after this.

![Screenshot from 2019-12-16 11-07-41](https://user-images.githubusercontent.com/1165845/70882080-975a9a00-1ff4-11ea-925b-aaf69d606eb7.png)

Version of Prisma2: `prisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7`

Data model:
```
// datasource sqlite {
//     provider = "sqlite"
//     url      = "file:dev.db"
//     default  = true
// }

datasource postgres {
    provider = "postgres"
    url      = "postgresql://user:pwd@localhost:54320/mydb"
    default  = true
}

generator photon {
    provider = "photonjs"
}

model UserAuthentication {
    id          String   @default(cuid()) @id
    emails      String[]
    local       String
    facebook    String
    google      String
    github      String
    microsoft   String
    amazon      String
    status      String
    metadata    String
    tagIDList   String[]
    createdDate DateTime @default(now())
    updatedDate DateTime @updatedAt
}
```

**Comment by tvvignesh** [comment]
This got resolved for me by doing an `npm install -g prisma2` as suggested by @divyenduz in this thread: https://prisma.slack.com/archives/CKQTGR6T0/p1576488933027800

**Comment by pantharshit00** [comment]
Continuing discussion on #1157
