### ISSUE TITLE
Is there some kind of graphql compose or something that work with prisma2 postgres ?

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#967]
Now, when I need to query something using graphql, I always need to adjust the query filter at the photon directly in backend. So ,I'm wondering  that is there any kind of graphql compose that let me adjust the filter parameter from the client only , then the backend will remain unchanged.

**Comment by pantharshit00** [comment]
@justicejoe Your use case is interesting but this is probably not for photon as it is like an ORM and exactly adhered to your schema. Maybe we can make something like this in nexus though. cc @jasonkuhrt @Weakky

**Comment by jasonkuhrt** [comment]
@justicejoe This might already be possible. Can you share what an ideal client query to the graphql api would look like in your opinion?

**Comment by justicejoe** [comment]
> @justicejoe Your use case is interesting but this is probably not for photon as it is like an ORM and not exactly adhered to your graphql schema(but rather to your database schema). Maybe we can make something like this in nexus though. cc @jasonkuhrt @Weakky

Ok, now I found what I expected in nexus-prisma but I have some problem with query of many to many relationship

**Comment by jasonkuhrt** [comment]
@justicejoe feel free to open a new issue on nexus-prisma. A code example will probably help us give you feedback on your case. Since this doesn't seem to be a Prisma 2 issue, I will close here. 🙏
