### ISSUE TITLE
Delivering the proper Prisma 2 Binaries

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#97]
This issue is a TODO list for our [binary workflow spec](https://github.com/prisma/specs/tree/master/binary-workflows).

- [ ] `prisma generate` should optionally pull a binary from the target:

```groovy
generator photon {
  provider = "photonjs"
  target = "linux_musl_libssl1.0.1"
}
```

- [ ] Update the new targets in S3

https://github.com/prisma/specs/tree/master/binary-workflows#platforms-and-their-urls

- [ ] Update the download engine package

https://github.com/prisma/photonjs/blob/b53e9895c5ebd9e31194854a1eda484ae50cdfe3/packages/fetch-engine/src/download.ts#L306

**Comment by timsuchanek** [comment]
Fixed in latest release.
You can read more [here](https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md#specifying-the-right-platform-for-photon-js) about how to use it.
