### ISSUE TITLE
query engine instances

### ISSUE THREAD

**Issue by garyro** [prisma/prisma2#978]
I assume having an instance of the query engine per model is correct? If so is this documented? also in my schema I have a couple of models that are accessed rarely is there any way to remove the instance of that model. Is there more docs on exactly how this query engine is working. I apologize if this is more of question than an issue

**Comment by nikolasburk** [comment]
Hey @garyro 👋 thanks a lot for your question!

> I assume having an instance of the query engine per model is correct?

That's not quite correct. There's one instance of the query engine _per Photon.js generator_ in your Prisma schema, and this is almost always exactly one! So, you're very likely to have exactly one instance of the query engine in your application.

> If so is this documented?

Unfortunately, we don't have official documentation of the query engine yet but this will come soon! You can find a high-level overview of the Prisma Framework internals [here](https://github.com/prisma/prisma2/issues/747#issuecomment-546875704). 

Please let me know if you have any further questions! It would also definitely be helpful if you share any more questions you might have around the query engine topic, that way we can make sure to answer them when we're writing the docs!

**Comment by garyro** [comment]
Thanks for the answer and a link to the diagram (very helpful). Still I am clearly getting one query instance created for every model I do a query on. Currently in my test scenario I have 5 models if I run a query on each one I will have 5 instances of the query engine running. Tell me what info I can send to you. I am running prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0 on Fedora 30.

**Comment by pantharshit00** [comment]
If that is happening, it is clearly a bug. Please open a new issue about it with screenshots and possibly a reproduction.

**Comment by garyro** [comment]
I wanted to close this out with my apologies my own code was causing this issue. This does work exactly as described by nikolasburk.

**Comment by crstn210** [comment]
Hello @garyro sorry for reopen the issue, I'm having the same problem, could you share your solution please?
