### ISSUE TITLE
[2.0.0-preview017] Error: Get config SyntaxError: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by kripod** [prisma/prisma2#985]
While executing `npx prisma2 lift save` on a clean [repo](https://github.com/kripod/exigo) after upgrading the Prisma framework, I encountered the error message as described in the title:

![image](https://user-images.githubusercontent.com/14854048/69555921-336c2500-0fa4-11ea-97d4-31df91427058.png)

**Comment by kripod** [comment]
Also, while executing `prisma2 generate`, the following error message came along:

```
Error: Problem while parsing the query engine response at C:\Development\Projects\exigo\node_modules\prisma2\query-engine-windows.exe. Please wait until the 'prisma query-engine' download completes!
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Development\Projects\exigo\node_modules\prisma2\build\index.js:109803:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Development\Projects\exigo\node_modules\prisma2\build\index.js:109753:58)
```

**Comment by pantharshit00** [comment]
I am able to confirm this bug on windows. I am unable to reproduce this on MacOS though.

![image](https://user-images.githubusercontent.com/22195362/69557752-21eb4300-0fcd-11ea-8672-a5eab6d5c653.png)

**Comment by smartnet-club** [comment]
The content of query-engine-windows.exe after npm install:

#!/usr/bin/env node
console.log("Please wait until the 'prisma query-engine' download completes!")

**Comment by timsuchanek** [comment]
Thanks a lot for reporting!
We just fixed this in the latest patch https://github.com/prisma/prisma2/releases/tag/2.0.0-preview017.1

**Comment by suevalov** [comment]
@timsuchanek I'm experiencing the same issue with latest `preview18.2`. Rollback to `preview17.2` fixes the issue.

**Comment by janpio** [comment]
Can you please open a new issue @suevalov? Provide some information that might help us reproduce it.

**Comment by jlarmstrongiv** [comment]
I have been debugging this all night.  The issue cannot be reproduced on mac.  However, it causes errors on windows and unix (vscode online).  

Here's a sample repo:
https://github.com/jlarmstrongiv/temp-prisma-template

Steps:
- cd temp-prisma-template
- yarn install
- npx prisma2 dev
- yarn generate
- yarn dev:nexus

**Comment by jlarmstrongiv** [comment]
Downgrading to 17.2 did not fix the issue for me

**Comment by zw-slime** [comment]
> Downgrading to 17.2 did not fix the issue for me
+1

**Comment by janpio** [comment]
Same for you @jlarmstrongiv, please open a new issue and and provide all the necessary information including the error message you are getting. Here this is quite confusing. Thanks.

**Comment by tobkle** [comment]
Same problem with 
```
prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038
```

**Comment by YannSuissa** [comment]
Same here downgrade to : 
`npm i prisma2@2.0.0-preview017.2`
fixed the bug

**Comment by dizzyn** [comment]
Have the same issue with 2.0.0-preview019 on Heroku

**Comment by pantharshit00** [comment]
Can you all please try reinstalling photon? This might be related to https://github.com/prisma/prisma2/issues/1232#issuecomment-569090211

Otherwise please open a new issue with a proper reproduction.

**Comment by dizzyn** [comment]
Thank you, now i see that the problem was in my case caused by the situation that I haven't have the folder migration in the proper state. So it can be fixed by removing the folder and renew them by prisma2 dev.


Thank you for the help.

**Comment by janpio** [comment]
Please open a new issue if you have this problem and provide more information. All the "same here" comments do not help us recreate the problem unfortunately, so we have no way to understand the problem.
