### ISSUE TITLE
[Feature Request] Default to public schema when using postgresql

### ISSUE THREAD

**Issue by jgoux** [prisma/prisma2#986]
Hello, 👋 

I was surprised that we have to set the schema explicitly when using postgresql in the database url (example : `postgres://user:password@localhost:5432/myawesomedatabase`)

This raises the error `Please provide a database name` which is confusing because the database name is set, but not the schema. Something like `Please provide a schema name` would be better.

Also as `public` is the default schema for postgresql, it would be great to have it set by default.

**Comment by divyenduz** [comment]
Candidate because a common trap that users fall into :)

**Comment by janpio** [comment]
> This raises the error `Please provide a database name` which is confusing because the database name is set, but not the schema.

That is indeed just a bug and should not happen. Can you please create a new issue for this?

> Also as `public` is the default schema for postgresql, it would be great to have it set by default.

That is a great idea and we will see if and how we can incorporate that.

**Comment by timsuchanek** [comment]
Thanks @jgoux for reporting! In which exact situation are you facing this problem?
When using `prisma2 init`? There we, for example, show a dialog that asks you if you want to reuse a schema or create a new one.

I searched through the code and can't find `Please provide a database name`, so I'm not sure where this comes from.

**Comment by pantharshit00** [comment]
@timsuchanek I think the error is coming from the engine when you specify the URI manually with specifying the schema(you assume it will default to public). I think this belongs to Rust land

**Comment by mavilein** [comment]
We had a look at this from the Rust side and we are having the proper default as far as we can tell.

**Comment by nikolasburk** [comment]
This should be avaialble, the docs for PostgreSQL connection strings mention that `public` is the default: https://github.com/prisma/prisma2/blob/master/docs/core/connectors/postgresql.md#configuration-options
