### ISSUE TITLE
Automatically clean prisma2 binary cache

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#988]
Right now there is no way to clean the prisma2 binary cache. So cache folder is getting quite big in size.

![image](https://user-images.githubusercontent.com/22195362/69560497-dc7d4480-0fd1-11ea-959f-0ec6114320de.png)

So we need a way to clean the cache

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
