### ISSUE TITLE
Issues with @relation arguments

### ISSUE THREAD

**Issue by reinvanimschoot** [prisma/prisma2#99]
When I try to add `onDelete` as an argument to the @relation attribute, I get back
a strange error in VS Code (with the Prisma plugin).

<img width="706" alt="Screenshot 2019-07-05 at 10 41 14" src="https://user-images.githubusercontent.com/35171567/60719534-49f7de00-9f28-11e9-827c-feb6b1b2fbcd.png">

**Comment by pantharshit00** [comment]
It has been renamed to `NONE`.

**Comment by pantharshit00** [comment]
More context: https://github.com/prisma/prisma2/issues/129
