### ISSUE TITLE
Preview017 error on "prisma2 dev" or "generate" - 'C:/Program' not a windows command

### ISSUE THREAD

**Issue by outerlook** [prisma/prisma2#992]
Hi! I got this error while running Preview017 on windows.

```
C:\projetob\quoro\backend>prisma2 generate
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error:
    Error: Generator at C:/projetob/quoro/backend/node_modules/@prisma/photon/generator-build/index.js could not start:
    'C:/Program' is not recognized as an internal or external command,
    operable program or batch file.
        at Timeout.setTimeout [as _onTimeout] (C:/Users/RaffaelCampos/AppData/Roaming/npm/node_modules/prisma2/build/index.js:231413:28)
```

My node_modules global folder isn't on Programs and files folder. 
I also tested the @alpha.353 release, same error

**Comment by smartnet-club** [comment]
and also prisma2\query-engine-windows.exe is not compatible with current version of Windows

**Comment by pantharshit00** [comment]
Might be related to https://github.com/prisma/prisma2/issues/985

I can confirm this.

**Comment by timsuchanek** [comment]
Thanks for reporting! Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.
