### ISSUE TITLE
Error: datasource must not use the env() function

### ISSUE THREAD

**Issue by himerus** [prisma/prisma2#998]
According to [prisma-schema-file.md](https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#switching-data-sources-based-on-environments), it should be possible to do the following:

> As a workaround you can provide environment variables for both url and provider options.

```
datasource db {
    provider = env("DB_PROVIDER")
    url           = env("PRISMA_DATA_SOURCE")
}
```

However, with the above, I get the following:

```
Error: Get config error: A datasource must not use the env() function in the provider argument.
  -->  schema.prisma:5
    |
 4 |
 5 | datasource db {
 6 |     provider = env("DB_PROVIDER")
```
If I set the provider manually to "mysql" in my case, it seems to work fine. 

```
datasource db {
    provider = "mysql"
    url           = env("PRISMA_DATA_SOURCE")
}
```

**Comment by pantharshit00** [comment]
I think this is expected by design. If you want to add additional datasources just  define them separately like so:
```groovy
datasource mysql {
  provider = "mysql"
  url = env("PRISMA_MYSQL_URL")
  enabled = true
}

datasource postgres {
  provider = "postgresql"
  url = env("PRISMA_POSTGRES_URL")
}
```

You can use the enabled flag to toggle them. In the future you can use multiple datasources in conjunction.

So please the spec for datasources here: https://github.com/prisma/specs/tree/master/schema#datasource-block

**Comment by divyenduz** [comment]
A related issue that might change this behavior in future is https://github.com/prisma/photonjs/issues/184

**Comment by nikolasburk** [comment]
Hey @himerus 👋 the docs were indeed incorrect here, I just updated them: https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#using-environment-variables

**Comment by wolszczak96** [comment]
> this is expected by design
why so? Doesn't it feel natural that you may use SQLite for development, and some mysql for production? How should we handle it then, if not by environment variables?

**Comment by wolszczak96** [comment]
> this is expected by design

why so? Doesn't it feel natural that you may use SQLite for development, and some mysql for production? How should we handle it then, if not by environment variables?

**Comment by pantharshit00** [comment]
> this is expected by design

It followed the spec we defined for the schema: https://github.com/prisma/specs/tree/master/schema

We plan to improve this, please have a look here: https://github.com/prisma/prisma2/issues/1487

**Comment by nemanjam** [comment]
Are you saying that I cant toggle datasource provider with env variable??? And it has to be hardcoded in schema???

**Comment by pantharshit00** [comment]
@nemanjam Yes, we have tried to make that dynamic in the past but that has caused various problems in the past as not every datasource support all the features. All that also makes migrations tricky as every database source use slight variation in the SQL they expect.

**Comment by emrahaydemir** [comment]
I just wanted to use SQLite in the development environment and PostgreSQL in the production environment....
